local L = AceLibrary("AceLocale-2.0"):new("QuestsFu")

L:RegisterTranslations("enUS", function() return {
	QUEST_DONE = "(done)",
	QUEST_FAILED = "(failed)",
	
	ELITE = "Elite",
	DUNGEON = "Dungeon",
	RAID = "Raid",
	PVP = "PvP",
	
	TAG_ELITE = "+",
	TAG_DUNGEON = "d",
	TAG_RAID = "r",
	TAG_PVP = "p",
	
	ARGUMENT_SHOWLEVELS = "levels",
	ARGUMENT_SHOWDIFFICULTY = "difficulty",
	ARGUMENT_SHOWIMPOSSIBLE = "impossible",
	ARGUMENT_SHOWAREA = "area",
	ARGUMENT_SHOWCLASSANYWAY = "classanyway",
	ARGUMENT_SHOWCURRENTAREAONLY = "currentareaonly",
	ARGUMENT_SHOWDESCRIPTION = "description",
	ARGUMENT_COLOROBJECTIVES = "colorobjectives",
	ARGUMENT_COMPLETEDOBJECTIVES = "completedobjectives",
	ARGUMENT_CURRENTAREADESCRIPTIONONLY = "currentareadescriptiononly",
	ARGUMENT_SHOWINITEMTOOLTIP = "initemtooltip",
	ARGUMENT_SHOWTEXT = "paneltextis",
	ARGUMENT_UPDATE = "update",
	
	MENU_SHOW_LEVELS = "Show quest levels",
	MENU_SHOW_DIFFICULTY = "Show quest difficulty colors",
	MENU_SHOW_IMPOSSIBLE = "Show impossible (red) quests",
	MENU_SHOW_AREA = "Show quest areas",
	MENU_SHOW_CLASS_ANYWAY = "Always show class quests",
	MENU_SHOW_CURRENT_AREA_ONLY = "Show current area quests only",
	MENU_SHOW_DESCRIPTION = "Show quest descriptions",
	MENU_COLOR_OBJECTIVES = "Color objectives completion status",
	MENU_SHOW_COMPLETED_OBJECTIVES = "Show completed objectives",
	MENU_SHOW_CURRENT_AREA_DESCRIPTION_ONLY = "Show descriptions for current area quests only",
	MENU_SHOW_IN_ITEM_TOOLTIP = "Show quest objectives in item/mob tooltips",
	MENU_SHOW_TEXT = "Show text",
	MENU_SHOW_TEXT_COMPLETE = "Show quests complete",
	MENU_SHOW_TEXT_CURRENT = "Show current # of quests",
	MENU_SHOW_TEXT_TOTAL = "Show total possible quests",
	MENU_SHOW_TEXT_LASTMESSAGE = "Show last quest status message",
	
	TEXT_SCANNING = "Scanning...",
	TEXT_LOADING = "Loading",
	
	TOOLTIP_HINT = "Click to open the quest log",
	OPT_show = "Show",
	OPT_show_d = "Choose what information to display",
	OPT_text = "Text",
	OPT_text_d = "Toolbar text",
	OPT_current = "Current",
	OPT_current_d = "Show current # of quests",
	OPT_complete = "Completed",
	OPT_complete_d = "Show # of quests completed",
	OPT_total = "Total",
	OPT_total_d = "Show total possible quests",
	OPT_lastmessage = "Last message",
	OPT_lastmessage_d = "Show last quest status message",
	OPT_levels = "Levels",
	OPT_levels_d = "Show quest levels",
	OPT_levels_game = "In Game",
	OPT_levels_game_d = "Show quest levels in the quest log and NPC dialogs",
	OPT_levels_tablet = "In QuestsFu",
	OPT_levels_tablet_d = "Show quest levels in the QuestsFu tooltip",
	OPT_levels_zone = "Zones",
	OPT_levels_zone_d = "Show zone levels in the QuestsFu tooltip",
	OPT_diff = "Difficulty colors",
	OPT_diff_d = "Show quest difficulty colors",
	OPT_impossible = "Impossible quests",
	OPT_impossible_d = "Show impossible (red) quests",
	OPT_area = "Areas",
	OPT_area_d = "Show quest areas",
	OPT_caonly = "Current area only",
	OPT_caonly_d = "Show current area quests only",
	OPT_classanyway = "Class quests always",
	OPT_classanyway_d = "Always show class quests",
	OPT_description = "Description",
	OPT_description_d = "Show quest descriptions",
	OPT_cadonly = "Current area descriptions only",
	OPT_cadonly_d = "Show current area quests only",
	OPT_completed = "Completed objectives",
	OPT_completed_d = "Show completed objectives",
	OPT_tooltip = "Objectives in tooltip",
	OPT_tooltip_d = "Show quest objectives in item/mob tooltips",
	OPT_colorobj = "Color objectives",
	OPT_colorobj_d = "Color objectives completion status",
	OPT_wrap = "Wrap quests",
	OPT_wrap_d = "Wrap long quest titles"
} end)
