
-- Settingnames
if not DHUD_Layouts then DHUD_Layouts = {} end;
DHUD_Layouts.DHUD_Standard_Layout = { 
    ["name"] = "Default Layout",
    ["DHUD_textures"] = {
        ["DHUD_PlayerHealth_Bar"] = { "Interface\\AddOns\\DHUD\\layout\\1"      , 0 , 1 , 0 , 1 },
        ["DHUD_PlayerMana_Bar"]   = { "Interface\\AddOns\\DHUD\\layout\\1"      , 1 , 0 , 0 , 1 },
        ["DHUD_TargetHealth_Bar"] = { "Interface\\AddOns\\DHUD\\layout\\2"      , 0 , 1 , 0 , 1 },
        ["DHUD_TargetMana_Bar"]   = { "Interface\\AddOns\\DHUD\\layout\\2"      , 1 , 0 , 0 , 1 },
        ["DHUD_PetHealth_Bar"]    = { "Interface\\AddOns\\DHUD\\layout\\p1"     , 0 , 1 , 0 , 1 },
        ["DHUD_PetMana_Bar"]      = { "Interface\\AddOns\\DHUD\\layout\\p1"     , 1 , 0 , 0 , 1 },
        ["DHUD_Casting_Bar"]      = { "Interface\\AddOns\\DHUD\\layout\\cb"     , 1 , 0 , 0 , 1 },
        ["DHUD_Flash_Bar"]        = { "Interface\\AddOns\\DHUD\\layout\\cbh"    , 1 , 0 , 0 , 1 },
        ["DHUD_Combo1"]           = { "Interface\\AddOns\\DHUD\\layout\\c1"     , 0 , 1 , 0 , 1 },
        ["DHUD_Combo2"]           = { "Interface\\AddOns\\DHUD\\layout\\c2"     , 0 , 1 , 0 , 1 },
        ["DHUD_Combo3"]           = { "Interface\\AddOns\\DHUD\\layout\\c3"     , 0 , 1 , 0 , 1 },
        ["DHUD_Combo4"]           = { "Interface\\AddOns\\DHUD\\layout\\c4"     , 0 , 1 , 0 , 1 },
        ["DHUD_Combo5"]           = { "Interface\\AddOns\\DHUD\\layout\\c5"     , 0 , 1 , 0 , 1 },
        
        ["l_ph_pm"]               = { "Interface\\AddOns\\DHUD\\layout\\bg_1"    , 0 , 1 , 0 , 1 },
        ["r_ph_pm"]               = { "Interface\\AddOns\\DHUD\\layout\\bg_1"    , 1 , 0 , 0 , 1 },
        
        ["l_ph_pm_em"]            = { "Interface\\AddOns\\DHUD\\layout\\bg_1"    , 0 , 1 , 0 , 1 },        
        ["r_ph_pm_em"]            = { "Interface\\AddOns\\DHUD\\layout\\bg_1p"   , 1 , 0 , 0 , 1 },
        
        ["l_ph_pm_eh_em"]         = { "Interface\\AddOns\\DHUD\\layout\\bg_1p"   , 0 , 1 , 0 , 1 },        
        ["r_ph_pm_eh_em"]         = { "Interface\\AddOns\\DHUD\\layout\\bg_1p"   , 1 , 0 , 0 , 1 },

        ["l_ph_pm_eh"]            = { "Interface\\AddOns\\DHUD\\layout\\bg_1p"   , 0 , 1 , 0 , 1 },        
        ["r_ph_pm_eh"]            = { "Interface\\AddOns\\DHUD\\layout\\bg_1"    , 1 , 0 , 0 , 1 },
                
        ["l_ph_pm_th"]            = { "Interface\\AddOns\\DHUD\\layout\\bg_21"   , 0 , 1 , 0 , 1 },
        ["r_ph_pm_th"]            = { "Interface\\AddOns\\DHUD\\layout\\bg_1"    , 1 , 0 , 0 , 1 },
        
        ["l_ph_pm_em_th"]         = { "Interface\\AddOns\\DHUD\\layout\\bg_21"   , 0 , 1 , 0 , 1 },
        ["r_ph_pm_em_th"]         = { "Interface\\AddOns\\DHUD\\layout\\bg_1p"   , 1 , 0 , 0 , 1 },

        ["l_ph_pm_eh_th"]         = { "Interface\\AddOns\\DHUD\\layout\\bg_21"   , 0 , 1 , 0 , 1 },
        ["r_ph_pm_eh_th"]         = { "Interface\\AddOns\\DHUD\\layout\\bg_1p"   , 1 , 0 , 0 , 1 },

        ["l_ph_pm_th_tm"]         = { "Interface\\AddOns\\DHUD\\layout\\bg_21"   , 0 , 1 , 0 , 1 },
        ["r_ph_pm_th_tm"]         = { "Interface\\AddOns\\DHUD\\layout\\bg_21"   , 1 , 0 , 0 , 1 },
                        
        ["l_ph_pm_eh_th"]         = { "Interface\\AddOns\\DHUD\\layout\\bg_21p"  , 0 , 1 , 0 , 1 },
        ["r_ph_pm_eh_th"]         = { "Interface\\AddOns\\DHUD\\layout\\bg_1"    , 1 , 0 , 0 , 1 },
        
        ["l_ph_pm_em_th_tm"]      = { "Interface\\AddOns\\DHUD\\layout\\bg_21"   , 0 , 1 , 0 , 1 },
        ["r_ph_pm_em_th_tm"]      = { "Interface\\AddOns\\DHUD\\layout\\bg_21p"  , 1 , 0 , 0 , 1 },

        ["l_ph_pm_eh_em_th"]      = { "Interface\\AddOns\\DHUD\\layout\\bg_21p"  , 0 , 1 , 0 , 1 },
        ["r_ph_pm_eh_em_th"]      = { "Interface\\AddOns\\DHUD\\layout\\bg_1p"   , 1 , 0 , 0 , 1 },
                
        ["l_ph_pm_eh_em_th_tm"]   = { "Interface\\AddOns\\DHUD\\layout\\bg_21p"  , 0 , 1 , 0 , 1 },
        ["r_ph_pm_eh_em_th_tm"]   = { "Interface\\AddOns\\DHUD\\layout\\bg_21p"  , 1 , 0 , 0 , 1 },
                
        ["DHUD_LeftFrame"]        = { "Interface\\AddOns\\DHUD\\layout\\bg_21p"  , 0 , 1 , 0 , 1 },
        ["DHUD_RightFrame"]       = { "Interface\\AddOns\\DHUD\\layout\\bg_21p"  , 1 , 0 , 0 , 1 },
        
        ["DHUD_PlayerResting"]    = { "Interface\\CharacterFrame\\UI-StateIcon"             , 0.0625 , 0.4475 , 0.0625 , 0.4375 },
        ["DHUD_PlayerLeader"]     = { "Interface\\GroupFrame\\UI-Group-LeaderIcon"          , 0 , 1 , 0 , 1 },
        ["DHUD_PlayerLooter"]     = { "Interface\\GroupFrame\\UI-Group-MasterLooter"        , 0 , 1 , 0 , 1 },
        ["DHUD_PetHappy"]         = { "Interface\\PetPaperDollFrame\\UI-PetHappiness"       , 0     , 0.1875 , 0 , 0.359375 },
        ["DHUD_PetNormal"]        = { "Interface\\PetPaperDollFrame\\UI-PetHappiness"       , 0.1875, 0.375  , 0 , 0.359375 },
        ["DHUD_PetUnhappy"]       = { "Interface\\PetPaperDollFrame\\UI-PetHappiness"       , 0.375 , 0.5625 , 0 , 0.359375 },
        ["DHUD_TargetPvP"]        = { "Interface\\TargetingFrame\\UI-PVP-Horde"             , 0.6 , 0   , 0 , 0.6 },
        ["DHUD_PlayerPvP"]        = { "Interface\\TargetingFrame\\UI-PVP-Alliance"          , 0   , 0.6 , 0 , 0.6 }, 
        ["DHUD_FreePvP"]          = { "Interface\\TargetingFrame\\UI-PVP-FFA"               , 0   , 0.6 , 0 , 0.6 },    
        ["DHUD_TargetElite"]      = { "Interface\\AddOns\\DHUD\\layout\\elite"              , 0   , 1 , 0 , 1 },   
        ["DHUD_TargetRare"]       = { "Interface\\AddOns\\DHUD\\layout\\rare"               , 0   , 1 , 0 , 1 }, 
    },
    ["DHUD_frames"] = {
        ["DHUD_Main"]              = { "Frame"   , "CENTER" , "UIParent"          , "CENTER"  , 0    , 0    , 512 , 256 },
        ["DHUD_LeftFrame"]         = { "Texture" , "LEFT"   , "DHUD_Main"         , "LEFT"    , 0    , 0    , 128 , 256 },
        ["DHUD_RightFrame"]        = { "Texture" , "RIGHT"  , "DHUD_Main"         , "RIGHT"   , 0    , 0    , 128 , 256 },
        ["DHUD_PlayerHealth_Bar"]  = { "Bar"     , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , 0    , 0    , 128 , 256 },
        ["DHUD_PlayerMana_Bar"]    = { "Bar"     , "BOTTOM" , "DHUD_RightFrame"   , "BOTTOM"  , 0    , 0    , 128 , 256 },
        ["DHUD_TargetHealth_Bar"]  = { "Bar"     , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , 0    , 0    , 128 , 256 },
        ["DHUD_TargetMana_Bar"]    = { "Bar"     , "BOTTOM" , "DHUD_RightFrame"   , "BOTTOM"  , 0    , 0    , 128 , 256 },
        ["DHUD_PetHealth_Bar"]     = { "Bar"     , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , 0    , 0    , 128 , 256 },
        ["DHUD_PetMana_Bar"]       = { "Bar"     , "BOTTOM" , "DHUD_RightFrame"   , "BOTTOM"  , 0    , 0    , 128 , 256 },
        ["DHUD_Casting_Bar"]       = { "Bar"     , "BOTTOM" , "DHUD_RightFrame"   , "BOTTOM"  , 0    , 0    , 128 , 256 },
        ["DHUD_Flash_Bar"]         = { "Bar"     , "BOTTOM" , "DHUD_RightFrame"   , "BOTTOM"  , 0    , 0    , 128 , 256 },    
        ["DHUD_Combo1"]            = { "Texture" , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , 6    , 0    , 20  , 20 },
        ["DHUD_Combo2"]            = { "Texture" , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , -1   , 20   , 20  , 20 },
        ["DHUD_Combo3"]            = { "Texture" , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , -7   , 40   , 20  , 20 },
        ["DHUD_Combo4"]            = { "Texture" , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , -11  , 60   , 20  , 20 },
        ["DHUD_Combo5"]            = { "Texture" , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , -13  , 80   , 20  , 20 },
        ["DHUD_Target_Text"]       = { "Text"    , "BOTTOM" , "DHUD_Main"         , "BOTTOM"  , 0    , -45  , 200 , 14 },
        
        ["DHUD_PlayerHealth_Text"] = { "Text"    , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , 95   , 2    , 200 , 14 },
        ["DHUD_PlayerMana_Text"]   = { "Text"    , "BOTTOM" , "DHUD_RightFrame"   , "BOTTOM"  , -95  , 2    , 200 , 14 },
        
        ["DHUD_TargetHealth_Text"] = { "Text"    , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , 80   , -16  , 200 , 14 },
        ["DHUD_TargetMana_Text"]   = { "Text"    , "BOTTOM" , "DHUD_RightFrame"   , "BOTTOM"  , -80  , -16  , 200 , 14 },
        
        ["DHUD_PetHealth_Text"]    = { "Text"    , "BOTTOM" , "DHUD_LeftFrame"    , "BOTTOM"  , 110  , 19   , 200 , 14 },
        ["DHUD_PetMana_Text"]      = { "Text"    , "BOTTOM" , "DHUD_RightFrame"   , "BOTTOM"  , -110 , 19   , 200 , 14 }, 
        
        ["DHUD_Casttime_Text"]     = { "Text"    , "TOPRIGHT", "DHUD_RightFrame"   , "TOPRIGHT" , -88  , 5    , 100 , 14 },
        ["DHUD_Castdelay_Text"]    = { "Text"    , "TOPRIGHT", "DHUD_RightFrame"   , "TOPRIGHT" , -88  , 19   , 100 , 14 }, 
        
        ["DHUD_Buff1"]             = { "Buff"    , "RIGHT"  , "DHUD_Target_Text"  , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff2"]             = { "Buff"    , "RIGHT"  , "DHUD_Buff1"        , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff3"]             = { "Buff"    , "RIGHT"  , "DHUD_Buff2"        , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff4"]             = { "Buff"    , "RIGHT"  , "DHUD_Buff3"        , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff5"]             = { "Buff"    , "RIGHT"  , "DHUD_Buff4"        , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff6"]             = { "Buff"    , "RIGHT"  , "DHUD_Buff5"        , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff7"]             = { "Buff"    , "RIGHT"  , "DHUD_Buff6"        , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff8"]             = { "Buff"    , "RIGHT"  , "DHUD_Buff7"        , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff9"]             = { "Buff"    , "RIGHT"  , "DHUD_Buff1"        , "LEFT"    , 20   , -21  , 20  , 20 },
        ["DHUD_Buff10"]            = { "Buff"    , "RIGHT"  , "DHUD_Buff9"        , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff11"]            = { "Buff"    , "RIGHT"  , "DHUD_Buff10"       , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff12"]            = { "Buff"    , "RIGHT"  , "DHUD_Buff11"       , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff13"]            = { "Buff"    , "RIGHT"  , "DHUD_Buff12"       , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff14"]            = { "Buff"    , "RIGHT"  , "DHUD_Buff13"       , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff15"]            = { "Buff"    , "RIGHT"  , "DHUD_Buff14"       , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_Buff16"]            = { "Buff"    , "RIGHT"  , "DHUD_Buff15"       , "LEFT"    , -1   , 0    , 20  , 20 },
        ["DHUD_DeBuff1"]           = { "Buff"    , "LEFT"   , "DHUD_Target_Text"  , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff2"]           = { "Buff"    , "LEFT"   , "DHUD_DeBuff1"      , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff3"]           = { "Buff"    , "LEFT"   , "DHUD_DeBuff2"      , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff4"]           = { "Buff"    , "LEFT"   , "DHUD_DeBuff3"      , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff5"]           = { "Buff"    , "LEFT"   , "DHUD_DeBuff4"      , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff6"]           = { "Buff"    , "LEFT"   , "DHUD_DeBuff5"      , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff7"]           = { "Buff"    , "LEFT"   , "DHUD_DeBuff6"      , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff8"]           = { "Buff"    , "LEFT"   , "DHUD_DeBuff7"      , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff9"]           = { "Buff"    , "LEFT"   , "DHUD_DeBuff1"      , "RIGHT"   , -20  , -21  , 20  , 20 },
        ["DHUD_DeBuff10"]          = { "Buff"    , "LEFT"   , "DHUD_DeBuff9"      , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff11"]          = { "Buff"    , "LEFT"   , "DHUD_DeBuff10"     , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff12"]          = { "Buff"    , "LEFT"   , "DHUD_DeBuff11"     , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff13"]          = { "Buff"    , "LEFT"   , "DHUD_DeBuff12"     , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff14"]          = { "Buff"    , "LEFT"   , "DHUD_DeBuff13"     , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff15"]          = { "Buff"    , "LEFT"   , "DHUD_DeBuff14"     , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_DeBuff16"]          = { "Buff"    , "LEFT"   , "DHUD_DeBuff15"     , "RIGHT"   , 1    , 0    , 20  , 20 },
        ["DHUD_PlayerResting"]     = { "Texture" , "TOP"    , "DHUD_LeftFrame"    , "TOP"     , 42   , 12    , 25  , 25 },
        ["DHUD_PlayerLeader"]      = { "Texture" , "TOP"    , "DHUD_LeftFrame"    , "TOP"     , 48   , -20  , 20  , 20 },
        ["DHUD_PlayerLooter"]      = { "Texture" , "TOP"    , "DHUD_LeftFrame"    , "TOP"     , 43   , -40  , 18  , 18 },
        ["DHUD_PlayerPvP"]         = { "Texture" , "TOP"    , "DHUD_LeftFrame"    , "TOP"     , 50   , -15  , 25  , 25 },
        ["DHUD_PetHappy"]          = { "Texture" , "TOP"    , "DHUD_LeftFrame"    , "TOP"     , 32   , -107 , 20  , 20 },
        ["DHUD_TargetPvP"]         = { "Texture" , "BOTTOM" , "DHUD_Target_Text"  , "TOP"     , 0    , 0    , 25  , 25 },
        ["DHUD_TargetElite"]       = { "Texture" , "TOP"    , "DHUD_LeftFrame"    , "TOP"     , 18   , 20   , 64  , 64 },
        
    },
    ["DHUD_textures_clip"] = {
        ["Interface\\AddOns\\DHUD\\layout\\1"]   = { 256, 11  , 11 },
        ["Interface\\AddOns\\DHUD\\layout\\2"]   = { 256, 5   , 5  },
        ["Interface\\AddOns\\DHUD\\layout\\p1"]  = { 256, 128 , 20 },
        ["Interface\\AddOns\\DHUD\\layout\\p2"]  = { 256, 128 , 20 },	
        ["Interface\\AddOns\\DHUD\\layout\\cb"]  = { 256, 11  , 11 }, 	
        ["Interface\\AddOns\\DHUD\\layout\\cbh"] = { 256, 11  , 11 },
    },
    ["defaultfont"]     = "Fonts/FRIZQT__.TTF",  
    ["defaultfont_num"] = "Interface\\AddOns\\DHUD\\layout\\Number.TTF", 
    ["DHUD_names"] = { 
        "DHUD_Main", 
        "DHUD_LeftFrame",
        "DHUD_RightFrame",
        "DHUD_PlayerHealth_Bar",
        "DHUD_PlayerMana_Bar",
        "DHUD_TargetHealth_Bar",
        "DHUD_TargetMana_Bar",
        "DHUD_PetHealth_Bar",
        "DHUD_PetMana_Bar",
        "DHUD_Combo1",
        "DHUD_Combo2",
        "DHUD_Combo3",
        "DHUD_Combo4",
        "DHUD_Combo5",
        "DHUD_Target_Text",
        "DHUD_PlayerHealth_Text",
        "DHUD_PlayerMana_Text",
        "DHUD_TargetHealth_Text",
        "DHUD_TargetMana_Text",
        "DHUD_PetHealth_Text",
        "DHUD_PetMana_Text",
        "DHUD_Casttime_Text",
        "DHUD_Castdelay_Text",
        "DHUD_Buff1",
        "DHUD_Buff2",
        "DHUD_Buff3",
        "DHUD_Buff4",
        "DHUD_Buff5",
        "DHUD_Buff6",
        "DHUD_Buff7",
        "DHUD_Buff8",
        "DHUD_Buff9",
        "DHUD_Buff10",
        "DHUD_Buff11",
        "DHUD_Buff12",
        "DHUD_Buff13",
        "DHUD_Buff14",
        "DHUD_Buff15",
        "DHUD_Buff16",
        "DHUD_DeBuff1",
        "DHUD_DeBuff2",
        "DHUD_DeBuff3",
        "DHUD_DeBuff4",
        "DHUD_DeBuff5",
        "DHUD_DeBuff6",
        "DHUD_DeBuff7",
        "DHUD_DeBuff8",
        "DHUD_DeBuff9",
        "DHUD_DeBuff10",
        "DHUD_DeBuff11",
        "DHUD_DeBuff12",
        "DHUD_DeBuff13",
        "DHUD_DeBuff14",
        "DHUD_DeBuff15",
        "DHUD_DeBuff16",  
        "DHUD_Casting_Bar",
        "DHUD_Flash_Bar",
        "DHUD_PlayerResting",
        --"DHUD_PlayerLeader",
        --"DHUD_PlayerLooter",
        "DHUD_PlayerPvP",
        "DHUD_PetHappy",
        "DHUD_TargetPvP",
        "DHUD_TargetElite",
    },
}
