local L = AceLibrary("AceLocale-2.0"):new("ag_UnitFrames")

L:RegisterTranslations("enUS", function()
    return {
		["Fonts\\FRIZQT__.TTF"]	= true,
		["Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf"] = true,
		
		["addonname"]			= "ag_UnitFrames",	
		
		["config"]				= "Configure",	
		["configdesc"]			= "Opens the configuration menu",	

		["reset"]				= "Reset",	
		["resetdesc"]			= "Resets the current profile",	
		
		["player"]				= "Player",
		["pet"]					= "Player's Pet",
		["party"]				= "Party",
		["partypet"]			= "Party Pets",
		["target"]				= "Target",
		["targettarget"]		= "Target's Target",
		["raid"]				= "Raid",
		["raidpet"]				= "Raid Pets",
		
		["dead"] 				= "DEAD",
		["ghost"] 				= "GHOST",
		["disc"] 				= "OFFLINE",
		
		["frame"] 				= "Frame",
		["aurasettings"] 		= "Aura Settings",
		["layoutsettings"] 		= "Layout Settings",
		["unitsettings"] 		= "Frame Settings",
		
		["units"] 				= "Unit Frames",
		["borders"] 			= "Borders",
		["barstyle"] 			= "Bar Style",
		["highlightselected"]	= "Hightlight Selected",
		["targetshowhostile"]	= "Hostility Coloring",
		["pvpicon"]				= "Show PvP Icons",
		["groupicon"]			= "Show Group Icons",
		["lock"]				= "Lock Frames",
		
		["framestyle"]			= "Frame Layout",
		["widthadjust"]			= "Frame Width",
		["aurastyle"]			= "Aura Style",
		["aurapos"]				= "Aura Position",
		["statustext"]			= "Statusbar Text",
		["scale"]				= "Scale",
		["longbars"]			= "Extend Statusbars",
		["classcolorbar"]		= "Color Health by Class",
		["raidcolorname"]		= "Color Name by Class",
		["showcombat"]			= "Display Combat Text",
		["aurafilter"]			= "Filter Auras",
		["debuffcoloring"]		= "Debuff Highlighting",
		["hidemana"]			= "Hide Mana Bar",
		["hideframe"]			= "Hide Frames",
		["showincombat"] 		= "Show Status Icon",
--		["showresting"] 		= "Show Resting Icon",
		["showraidicon"] 		= "Show Raid Target Icon",
		["showxp"]				= "Show Experience Bar",
		["raidhideparty"]		= "Hide Frames in Raid",
		["raidgrouping"]		= "Group Raid By",
		
		["bysubgroup"]			= "Raid Subgroups",
		["byclass"]				= "Classes",
		["byrole"]				= "Healer/Tank/DPS",
		["onebiggroup"]			= "All Together",
		["nogroup"]				= "Don't Group",

		["partygrouping"]		= "Group Party",
		["petgrouping"]			= "Group Pets",

		["withplayer"]			= "With Player",
		["withoutplayer"]		= "Without Player",		
		
		["oneline"]				= "One Line",
		["twolines"]			= "Two Lines",	
		["hide"]				= "Hidden",	

		["health"] 				= "Health",	
		["mana"] 				= "Mana",	
		["rage"] 				= "Rage",	
		["petfocus"] 			= "Pet Focus",	
		["barcolors"] 			= "Bar Colors",	
		["energy"] 				= "Energy",	

		["healthDesc"] 			= "Set the health color",	
		["manaDesc"] 			= "Set the mana color",	
		["rageDesc"] 			= "Set the rage color",	
		["petfocusDesc"] 		= "Set the pet focus color",	
		["energyDesc"] 			= "Set the energy color",	
		["barcolorsDesc"] 		= "Set power colors for all units",			
        ["UnitDesc"]			= "Individual frame configuration",
        ["BordersDesc"]			= "Set frame borders",
        ["BarStyleDesc"]		= "Set bar textures",
        ["HighlightSelectedDesc"]	= "Check to show selection highlight on frames",
        ["ShowPVPIconDesc"]		= "Check to show pvp icons",
        ["ShowGroupIconsDesc"]	= "Check to show group leader icon",
        ["LockedDesc"]		    = "Lock the frames",
        ["FrameStyleDesc"]		= "Set the frame style",
        ["StatusTextDesc"]		= "Set what information is shown on health and mana bars",
        ["ScaleDesc"]		    = "Set the frame scale",
        ["widthadjustDesc"]		= "Set the frame width",
        ["ClassColorBarsDesc"]	= "Check to color health bars by class type",
        ["RaidColorNameDesc"]	= "Check to color unit names by class type",
        ["ShowCombatDesc"]		= "Check to show combat text in the frame",
        ["LongBarsDesc"]		= "Check to extend health and mana bars over the entire frame",
        ["HideManaDesc"]		= "Check to hide the mana bar",
        ["HideFrameDesc"]		= "Check to hide the entire frame",
        ["AuraStyleDesc"]		= "Set the aura style",
        ["AuraPosDesc"] 		= "Set the aura position",
        ["DebuffColoringDesc"]	= "Check to color the frame by debuff type",
        ["AuraFilterDesc"]		= "Check to only show auras you can cast or cure",
		["ShowInCombatDesc"] = "Check to show status icon",
		["ShowRaidIconDesc"] = "Check to show raid target icon",
--		["ShowRestingDesc"] = "Check to show resting icon",
        ["ShowXPDesc"]		    = "Check to show an experience bar",
        ["PetGroupingDesc"]		= "Set pet grouping",
        ["TargetHostileDesc"]	= "Check to color health bars by hostility",
        ["RaidHidePartyDesc"]	= "Check to hide party frames in raid",
        ["PartyGroupingDesc"]	= "Set party grouping",
        ["RaidGroupingDesc"]	= "Set raid grouping",
		["targetbg"]			= "Target Background",
		["targetbgdesc"]		= "Target frame background color",
		["partybg"]				= "Party Background",
		["partybgdesc"]			= "Party frame background color",
		["bordercolor"]			= "Border Color",
		["bordercolordesc"]		= "Frame border color",
		["framecolors"]			= "Frame Colors",
		["framecolorsdesc"]		= "Frame background and border color",
    }
end)
