
DAB_CUSTOM_SETTINGS = {
	["defaultFont"] = "Interface\\AddOns\\DiscordActionBars\\CustomFonts\\",
	["EventMacros"] = {
	},
	["FrameLocs"] = {
	},
	["optionsScale"] = 100,
	["ControlBox"] = {
		[1] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["mbordcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["Scripts"] = {
			},
			["b3width"] = 1,
			["b1width"] = 1,
			["onclick"] = 1,
			["b3texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["b1texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["text"] = "Control Box 1",
			["font"] = "Fonts\\FRIZQT__.TTF",
			["bordalpha"] = 1,
			["height"] = 25,
			["malpha"] = 1,
			["group"] = 1,
			["justifyV"] = "CENTER",
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["justifyH"] = "CENTER",
			["Anchor"] = {
				["y"] = -40,
				["x"] = 100,
				["point"] = "TOPLEFT",
				["frame"] = "UIParent",
				["to"] = "TOPLEFT",
			},
			["b4width"] = 1,
			["mbgalpha"] = 1,
			["hide"] = true,
			["b2texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bordcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["frameStrata"] = "LOW",
			["alpha"] = 1,
			["b4texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["fontsize"] = 14,
			["TextAnchor"] = {
				["y"] = 0,
				["x"] = 0,
				["point"] = "CENTER",
				["to"] = "CENTER",
			},
			["mbgcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["mbordalpha"] = 1,
			["mcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["width"] = 120,
			["delay"] = 0.5,
			["b2width"] = 1,
		},
		[2] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["mbordcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["Scripts"] = {
			},
			["b3width"] = 1,
			["b1width"] = 1,
			["onclick"] = 1,
			["b3texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["b1texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["text"] = "Control Box 2",
			["font"] = "Fonts\\FRIZQT__.TTF",
			["bordalpha"] = 1,
			["height"] = 25,
			["malpha"] = 1,
			["group"] = 2,
			["justifyV"] = "CENTER",
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["justifyH"] = "CENTER",
			["Anchor"] = {
				["y"] = -80,
				["x"] = 100,
				["point"] = "TOPLEFT",
				["frame"] = "UIParent",
				["to"] = "TOPLEFT",
			},
			["b4width"] = 1,
			["mbgalpha"] = 1,
			["hide"] = true,
			["b2texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bordcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["frameStrata"] = "LOW",
			["alpha"] = 1,
			["b4texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["fontsize"] = 14,
			["TextAnchor"] = {
				["y"] = 0,
				["x"] = 0,
				["point"] = "CENTER",
				["to"] = "CENTER",
			},
			["mbgcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["mbordalpha"] = 1,
			["mcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["width"] = 120,
			["delay"] = 0.5,
			["b2width"] = 1,
		},
		[3] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["mbordcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["Scripts"] = {
			},
			["b3width"] = 1,
			["b1width"] = 1,
			["onclick"] = 1,
			["b3texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["b1texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["text"] = "Control Box 3",
			["font"] = "Fonts\\FRIZQT__.TTF",
			["bordalpha"] = 1,
			["height"] = 25,
			["malpha"] = 1,
			["group"] = 3,
			["justifyV"] = "CENTER",
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["justifyH"] = "CENTER",
			["Anchor"] = {
				["y"] = -120,
				["x"] = 100,
				["point"] = "TOPLEFT",
				["frame"] = "UIParent",
				["to"] = "TOPLEFT",
			},
			["b4width"] = 1,
			["mbgalpha"] = 1,
			["hide"] = true,
			["b2texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bordcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["frameStrata"] = "LOW",
			["alpha"] = 1,
			["b4texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["fontsize"] = 14,
			["TextAnchor"] = {
				["y"] = 0,
				["x"] = 0,
				["point"] = "CENTER",
				["to"] = "CENTER",
			},
			["mbgcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["mbordalpha"] = 1,
			["mcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["width"] = 120,
			["delay"] = 0.5,
			["b2width"] = 1,
		},
		[4] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["mbordcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["Scripts"] = {
			},
			["b3width"] = 1,
			["b1width"] = 1,
			["onclick"] = 1,
			["b3texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["b1texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["text"] = "Control Box 4",
			["font"] = "Fonts\\FRIZQT__.TTF",
			["bordalpha"] = 1,
			["height"] = 25,
			["malpha"] = 1,
			["group"] = 4,
			["justifyV"] = "CENTER",
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["justifyH"] = "CENTER",
			["Anchor"] = {
				["y"] = -160,
				["x"] = 100,
				["point"] = "TOPLEFT",
				["frame"] = "UIParent",
				["to"] = "TOPLEFT",
			},
			["b4width"] = 1,
			["mbgalpha"] = 1,
			["hide"] = true,
			["b2texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bordcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["frameStrata"] = "LOW",
			["alpha"] = 1,
			["b4texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["fontsize"] = 14,
			["TextAnchor"] = {
				["y"] = 0,
				["x"] = 0,
				["point"] = "CENTER",
				["to"] = "CENTER",
			},
			["mbgcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["mbordalpha"] = 1,
			["mcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["width"] = 120,
			["delay"] = 0.5,
			["b2width"] = 1,
		},
		[5] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["mbordcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["Scripts"] = {
			},
			["b3width"] = 1,
			["b1width"] = 1,
			["onclick"] = 1,
			["b3texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["b1texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["text"] = "Control Box 5",
			["font"] = "Fonts\\FRIZQT__.TTF",
			["bordalpha"] = 1,
			["height"] = 25,
			["malpha"] = 1,
			["group"] = 5,
			["justifyV"] = "CENTER",
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["justifyH"] = "CENTER",
			["Anchor"] = {
				["y"] = -200,
				["x"] = 100,
				["point"] = "TOPLEFT",
				["frame"] = "UIParent",
				["to"] = "TOPLEFT",
			},
			["b4width"] = 1,
			["mbgalpha"] = 1,
			["hide"] = true,
			["b2texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bordcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["frameStrata"] = "LOW",
			["alpha"] = 1,
			["b4texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["fontsize"] = 14,
			["TextAnchor"] = {
				["y"] = 0,
				["x"] = 0,
				["point"] = "CENTER",
				["to"] = "CENTER",
			},
			["mbgcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["mbordalpha"] = 1,
			["mcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["width"] = 120,
			["delay"] = 0.5,
			["b2width"] = 1,
		},
		[6] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["mbordcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["Scripts"] = {
			},
			["b3width"] = 1,
			["b1width"] = 1,
			["onclick"] = 1,
			["b3texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["b1texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["text"] = "Control Box 6",
			["font"] = "Fonts\\FRIZQT__.TTF",
			["bordalpha"] = 1,
			["height"] = 25,
			["malpha"] = 1,
			["group"] = 6,
			["justifyV"] = "CENTER",
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["justifyH"] = "CENTER",
			["Anchor"] = {
				["y"] = -240,
				["x"] = 100,
				["point"] = "TOPLEFT",
				["frame"] = "UIParent",
				["to"] = "TOPLEFT",
			},
			["b4width"] = 1,
			["mbgalpha"] = 1,
			["hide"] = true,
			["b2texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bordcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["frameStrata"] = "LOW",
			["alpha"] = 1,
			["b4texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["fontsize"] = 14,
			["TextAnchor"] = {
				["y"] = 0,
				["x"] = 0,
				["point"] = "CENTER",
				["to"] = "CENTER",
			},
			["mbgcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["mbordalpha"] = 1,
			["mcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["width"] = 120,
			["delay"] = 0.5,
			["b2width"] = 1,
		},
		[7] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["mbordcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["Scripts"] = {
			},
			["b3width"] = 1,
			["b1width"] = 1,
			["onclick"] = 1,
			["b3texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["b1texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["text"] = "Control Box 7",
			["font"] = "Fonts\\FRIZQT__.TTF",
			["bordalpha"] = 1,
			["height"] = 25,
			["malpha"] = 1,
			["group"] = 7,
			["justifyV"] = "CENTER",
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["justifyH"] = "CENTER",
			["Anchor"] = {
				["y"] = -280,
				["x"] = 100,
				["point"] = "TOPLEFT",
				["frame"] = "UIParent",
				["to"] = "TOPLEFT",
			},
			["b4width"] = 1,
			["mbgalpha"] = 1,
			["hide"] = true,
			["b2texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bordcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["frameStrata"] = "LOW",
			["alpha"] = 1,
			["b4texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["fontsize"] = 14,
			["TextAnchor"] = {
				["y"] = 0,
				["x"] = 0,
				["point"] = "CENTER",
				["to"] = "CENTER",
			},
			["mbgcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["mbordalpha"] = 1,
			["mcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["width"] = 120,
			["delay"] = 0.5,
			["b2width"] = 1,
		},
		[8] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["mbordcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["Scripts"] = {
			},
			["b3width"] = 1,
			["b1width"] = 1,
			["onclick"] = 1,
			["b3texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["b1texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["text"] = "Control Box 8",
			["font"] = "Fonts\\FRIZQT__.TTF",
			["bordalpha"] = 1,
			["height"] = 25,
			["malpha"] = 1,
			["group"] = 8,
			["justifyV"] = "CENTER",
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["justifyH"] = "CENTER",
			["Anchor"] = {
				["y"] = -320,
				["x"] = 100,
				["point"] = "TOPLEFT",
				["frame"] = "UIParent",
				["to"] = "TOPLEFT",
			},
			["b4width"] = 1,
			["mbgalpha"] = 1,
			["hide"] = true,
			["b2texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bordcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["frameStrata"] = "LOW",
			["alpha"] = 1,
			["b4texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["fontsize"] = 14,
			["TextAnchor"] = {
				["y"] = 0,
				["x"] = 0,
				["point"] = "CENTER",
				["to"] = "CENTER",
			},
			["mbgcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["mbordalpha"] = 1,
			["mcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["width"] = 120,
			["delay"] = 0.5,
			["b2width"] = 1,
		},
		[9] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["mbordcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["Scripts"] = {
			},
			["b3width"] = 1,
			["b1width"] = 1,
			["onclick"] = 1,
			["b3texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["b1texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["text"] = "Control Box 9",
			["font"] = "Fonts\\FRIZQT__.TTF",
			["bordalpha"] = 1,
			["height"] = 25,
			["malpha"] = 1,
			["group"] = 9,
			["justifyV"] = "CENTER",
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["justifyH"] = "CENTER",
			["Anchor"] = {
				["y"] = -360,
				["x"] = 100,
				["point"] = "TOPLEFT",
				["frame"] = "UIParent",
				["to"] = "TOPLEFT",
			},
			["b4width"] = 1,
			["mbgalpha"] = 1,
			["hide"] = true,
			["b2texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bordcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["frameStrata"] = "LOW",
			["alpha"] = 1,
			["b4texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["fontsize"] = 14,
			["TextAnchor"] = {
				["y"] = 0,
				["x"] = 0,
				["point"] = "CENTER",
				["to"] = "CENTER",
			},
			["mbgcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["mbordalpha"] = 1,
			["mcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["width"] = 120,
			["delay"] = 0.5,
			["b2width"] = 1,
		},
		[10] = {
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["mbordcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["Scripts"] = {
			},
			["b3width"] = 1,
			["b1width"] = 1,
			["onclick"] = 1,
			["b3texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["b1texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["text"] = "Control Box 10",
			["font"] = "Fonts\\FRIZQT__.TTF",
			["bordalpha"] = 1,
			["height"] = 25,
			["malpha"] = 1,
			["group"] = 10,
			["justifyV"] = "CENTER",
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["justifyH"] = "CENTER",
			["Anchor"] = {
				["y"] = -400,
				["x"] = 100,
				["point"] = "TOPLEFT",
				["frame"] = "UIParent",
				["to"] = "TOPLEFT",
			},
			["b4width"] = 1,
			["mbgalpha"] = 1,
			["hide"] = true,
			["b2texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["bordcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["frameStrata"] = "LOW",
			["alpha"] = 1,
			["b4texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["fontsize"] = 14,
			["TextAnchor"] = {
				["y"] = 0,
				["x"] = 0,
				["point"] = "CENTER",
				["to"] = "CENTER",
			},
			["mbgcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["mbordalpha"] = 1,
			["mcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["width"] = 120,
			["delay"] = 0.5,
			["b2width"] = 1,
		},
	},
	["Floaters"] = {
	},
	["MainMenuBar"] = {
		["xpscale"] = 0.9375,
		["xpcolor"] = {
			["b"] = 0.55,
			["g"] = 0,
			["r"] = 0.58,
		},
		["xpbcolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["xpalpha"] = 1,
		["latencyscale"] = 0.9375,
	},
	["OtherBar"] = {
		[12] = {
			["scale"] = 1,
			["layout"] = 1,
			["frameStrata"] = "HIGH",
			["alpha"] = 1,
			["Anchor"] = {
				["y"] = -3,
				["x"] = 37,
				["to"] = "TOPLEFT",
				["frame"] = "MainMenuBar",
				["point"] = "BOTTOMLEFT",
			},
			["Background"] = {
				["leftpadding"] = 5,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 5,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["hide"] = 1,
				["bottompadding"] = 5,
				["tileSize"] = 1,
				["rightpadding"] = 5,
				["balpha"] = 1,
			},
			["vspacing"] = 0,
			["hspacing"] = 6,
		},
		[14] = {
			["scale"] = 1,
			["layout"] = 1,
			["frameStrata"] = "HIGH",
			["alpha"] = 1,
			["Anchor"] = {
				["y"] = -3,
				["x"] = 34,
				["to"] = "BOTTOM",
				["frame"] = "MainMenuBar",
				["point"] = "BOTTOMLEFT",
			},
			["Background"] = {
				["leftpadding"] = 5,
				["color"] = {
					["r"] = 1,
					["g"] = 0.03137254901960784,
					["b"] = 0,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["tileSize"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["rightpadding"] = 5,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["toppadding"] = 5,
				["bottompadding"] = 5,
				["edgeSize"] = 1,
				["balpha"] = 1,
				["hide"] = 1,
			},
			["vspacing"] = 0,
			["hspacing"] = -3,
		},
		[11] = {
			["scale"] = 1,
			["layout"] = 1,
			["frameStrata"] = "HIGH",
			["alpha"] = 1,
			["Anchor"] = {
				["y"] = -1,
				["x"] = 68,
				["to"] = "TOPLEFT",
				["frame"] = "MainMenuBar",
				["point"] = "BOTTOMLEFT",
			},
			["Background"] = {
				["leftpadding"] = 5,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 5,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["tileSize"] = 1,
				["bottompadding"] = 5,
				["rightpadding"] = 5,
				["balpha"] = 1,
				["hide"] = 1,
			},
			["vspacing"] = 0,
			["hspacing"] = 7.5,
		},
		[13] = {
			["scale"] = 1,
			["layout"] = 1,
			["frameStrata"] = "HIGH",
			["alpha"] = 1,
			["Anchor"] = {
				["y"] = -2,
				["x"] = -2,
				["to"] = "BOTTOMRIGHT",
				["frame"] = "MainMenuBar",
				["point"] = "BOTTOMRIGHT",
			},
			["Background"] = {
				["leftpadding"] = 5,
				["color"] = {
					["r"] = 1,
					["g"] = 0.0392156862745098,
					["b"] = 0,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 5,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["rightpadding"] = 5,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["tileSize"] = 1,
				["bottompadding"] = 5,
				["edgeSize"] = 1,
				["balpha"] = 1,
				["hide"] = 1,
			},
			["vspacing"] = 0,
			["hspacing"] = 5,
		},
	},
	["Keybindings"] = {
		[1] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[2] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[3] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[4] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[5] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 5,
			["down"] = 1,
		},
		[6] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 6,
			["down"] = 1,
		},
		[7] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 7,
			["down"] = 1,
		},
		[8] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 8,
			["down"] = 1,
		},
		[9] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 9,
			["down"] = 1,
		},
		[10] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 10,
			["down"] = 1,
		},
		[11] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 11,
			["down"] = 1,
		},
		[12] = {
			["suboption"] = 1,
			["option"] = 1,
			["suboption2"] = 12,
			["down"] = 1,
		},
		[13] = {
			["suboption"] = 2,
			["option"] = 1,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[14] = {
			["suboption"] = 2,
			["option"] = 1,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[15] = {
			["suboption"] = 2,
			["option"] = 1,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[16] = {
			["suboption"] = 2,
			["option"] = 1,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[17] = {
			["suboption"] = 3,
			["option"] = 1,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[18] = {
			["suboption"] = 3,
			["option"] = 1,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[19] = {
			["suboption"] = 3,
			["option"] = 1,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[20] = {
			["suboption"] = 3,
			["option"] = 1,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[21] = {
			["suboption"] = 4,
			["option"] = 1,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[22] = {
			["suboption"] = 4,
			["option"] = 1,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[23] = {
			["suboption"] = 4,
			["option"] = 1,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[24] = {
			["suboption"] = 4,
			["option"] = 1,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[25] = {
			["suboption"] = 5,
			["option"] = 1,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[26] = {
			["suboption"] = 5,
			["option"] = 1,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[27] = {
			["suboption"] = 5,
			["option"] = 1,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[28] = {
			["suboption"] = 5,
			["option"] = 1,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[29] = {
			["suboption"] = 6,
			["option"] = 1,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[30] = {
			["suboption"] = 6,
			["option"] = 1,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[31] = {
			["suboption"] = 6,
			["option"] = 1,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[32] = {
			["suboption"] = 6,
			["option"] = 1,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[33] = {
			["suboption"] = 7,
			["option"] = 1,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[34] = {
			["suboption"] = 7,
			["option"] = 1,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[35] = {
			["suboption"] = 7,
			["option"] = 1,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[36] = {
			["suboption"] = 7,
			["option"] = 1,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[37] = {
			["suboption"] = 8,
			["option"] = 1,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[38] = {
			["suboption"] = 8,
			["option"] = 1,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[39] = {
			["suboption"] = 8,
			["option"] = 1,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[40] = {
			["suboption"] = 8,
			["option"] = 1,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[41] = {
			["suboption"] = 9,
			["option"] = 1,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[42] = {
			["suboption"] = 9,
			["option"] = 1,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[43] = {
			["suboption"] = 9,
			["option"] = 1,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[44] = {
			["suboption"] = 9,
			["option"] = 1,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[45] = {
			["suboption"] = 10,
			["option"] = 1,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[46] = {
			["suboption"] = 10,
			["option"] = 1,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[47] = {
			["suboption"] = 10,
			["option"] = 1,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[48] = {
			["suboption"] = 10,
			["option"] = 1,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[49] = {
			["suboption"] = 1,
			["down"] = 1,
			["option"] = 4,
		},
		[50] = {
			["suboption"] = 2,
			["down"] = 1,
			["option"] = 4,
		},
		[51] = {
			["suboption"] = 3,
			["down"] = 1,
			["option"] = 4,
		},
		[52] = {
			["suboption"] = 4,
			["down"] = 1,
			["option"] = 4,
		},
		[53] = {
			["suboption"] = 5,
			["down"] = 1,
			["option"] = 4,
		},
		[54] = {
			["suboption"] = 6,
			["down"] = 1,
			["option"] = 4,
		},
		[55] = {
			["suboption"] = 7,
			["down"] = 1,
			["option"] = 4,
		},
		[56] = {
			["suboption"] = 8,
			["down"] = 1,
			["option"] = 4,
		},
		[57] = {
			["suboption"] = 9,
			["down"] = 1,
			["option"] = 4,
		},
		[58] = {
			["suboption"] = 10,
			["down"] = 1,
			["option"] = 4,
		},
		[59] = {
			["suboption"] = 1,
			["down"] = 1,
			["option"] = 7,
		},
		[60] = {
			["suboption"] = 1,
			["down"] = 1,
			["option"] = 8,
		},
		[61] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[62] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[63] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[64] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[65] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 5,
			["down"] = 1,
		},
		[66] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 6,
			["down"] = 1,
		},
		[67] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 7,
			["down"] = 1,
		},
		[68] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 8,
			["down"] = 1,
		},
		[69] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 9,
			["down"] = 1,
		},
		[70] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 10,
			["down"] = 1,
		},
		[71] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 11,
			["down"] = 1,
		},
		[72] = {
			["suboption"] = 1,
			["option"] = 2,
			["suboption2"] = 12,
			["down"] = 1,
		},
		[73] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 1,
			["down"] = 1,
		},
		[74] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 2,
			["down"] = 1,
		},
		[75] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 3,
			["down"] = 1,
		},
		[76] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 4,
			["down"] = 1,
		},
		[77] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 5,
			["down"] = 1,
		},
		[78] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 6,
			["down"] = 1,
		},
		[79] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 7,
			["down"] = 1,
		},
		[80] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 8,
			["down"] = 1,
		},
		[81] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 9,
			["down"] = 1,
		},
		[82] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 10,
			["down"] = 1,
		},
		[83] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 11,
			["down"] = 1,
		},
		[84] = {
			["suboption"] = 2,
			["option"] = 2,
			["suboption2"] = 12,
			["down"] = 1,
		},
		[85] = {
			["option"] = 0,
			["down"] = 1,
		},
		[86] = {
			["option"] = 0,
			["down"] = 1,
		},
		[87] = {
			["option"] = 0,
			["down"] = 1,
		},
		[88] = {
			["option"] = 0,
			["down"] = 1,
		},
		[89] = {
			["option"] = 0,
			["down"] = 1,
		},
		[90] = {
			["option"] = 0,
			["down"] = 1,
		},
		[91] = {
			["option"] = 0,
			["down"] = 1,
		},
		[92] = {
			["option"] = 0,
			["down"] = 1,
		},
		[93] = {
			["option"] = 0,
			["down"] = 1,
		},
		[94] = {
			["option"] = 0,
			["down"] = 1,
		},
		[95] = {
			["option"] = 0,
			["down"] = 1,
		},
		[96] = {
			["option"] = 0,
			["down"] = 1,
		},
		[97] = {
			["option"] = 0,
			["down"] = 1,
		},
		[98] = {
			["option"] = 0,
			["down"] = 1,
		},
		[99] = {
			["option"] = 0,
			["down"] = 1,
		},
		[100] = {
			["option"] = 0,
			["down"] = 1,
		},
		[101] = {
			["option"] = 0,
			["down"] = 1,
		},
		[102] = {
			["option"] = 0,
			["down"] = 1,
		},
		[103] = {
			["option"] = 0,
			["down"] = 1,
		},
		[104] = {
			["option"] = 0,
			["down"] = 1,
		},
		[105] = {
			["option"] = 0,
			["down"] = 1,
		},
		[106] = {
			["option"] = 0,
			["down"] = 1,
		},
		[107] = {
			["option"] = 0,
			["down"] = 1,
		},
		[108] = {
			["option"] = 0,
			["down"] = 1,
		},
		[109] = {
			["option"] = 0,
			["down"] = 1,
		},
		[110] = {
			["option"] = 0,
			["down"] = 1,
		},
		[111] = {
			["option"] = 0,
			["down"] = 1,
		},
		[112] = {
			["option"] = 0,
			["down"] = 1,
		},
		[113] = {
			["option"] = 0,
			["down"] = 1,
		},
		[114] = {
			["option"] = 0,
			["down"] = 1,
		},
		[115] = {
			["option"] = 0,
			["down"] = 1,
		},
		[116] = {
			["option"] = 0,
			["down"] = 1,
		},
		[117] = {
			["option"] = 0,
			["down"] = 1,
		},
		[118] = {
			["option"] = 0,
			["down"] = 1,
		},
		[119] = {
			["option"] = 0,
			["down"] = 1,
		},
		[120] = {
			["option"] = 0,
			["down"] = 1,
		},
	},
	["defaultTexture"] = "Interface\\AddOns\\DiscordActionBars\\CustomTextures\\",
	["Buttons"] = {
		[1] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[2] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[3] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[4] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[5] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[6] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[7] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[8] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[9] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[10] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[11] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[12] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 1,
		},
		[13] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[14] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[15] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[16] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[17] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[18] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[19] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[20] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[21] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[22] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[23] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[24] = {
			["Conditions"] = {
			},
			["Bar2"] = 2,
			["Bar"] = 1,
		},
		[25] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[26] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[27] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[28] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[29] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[30] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[31] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[32] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[33] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[34] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[35] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[36] = {
			["Conditions"] = {
			},
			["Bar2"] = 3,
			["Bar"] = 1,
		},
		[37] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[38] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[39] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[40] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[41] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[42] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[43] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[44] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[45] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[46] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[47] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[48] = {
			["Conditions"] = {
			},
			["Bar2"] = 4,
			["Bar"] = 1,
		},
		[49] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[50] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[51] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[52] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[53] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[54] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[55] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[56] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[57] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[58] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[59] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[60] = {
			["Conditions"] = {
			},
			["Bar2"] = 5,
			["Bar"] = 1,
		},
		[61] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[62] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[63] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[64] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[65] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[66] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[67] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[68] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[69] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[70] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[71] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[72] = {
			["Conditions"] = {
			},
			["Bar2"] = 6,
			["Bar"] = 1,
		},
		[73] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[74] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[75] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[76] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[77] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[78] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[79] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[80] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[81] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[82] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[83] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[84] = {
			["Conditions"] = {
			},
			["Bar2"] = 7,
			["Bar"] = 1,
		},
		[85] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 2,
		},
		[86] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 2,
		},
		[87] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 2,
		},
		[88] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 2,
		},
		[89] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 3,
		},
		[90] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 3,
		},
		[91] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 3,
		},
		[92] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 3,
		},
		[93] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 4,
		},
		[94] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 4,
		},
		[95] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 4,
		},
		[96] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 4,
		},
		[97] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 5,
		},
		[98] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 5,
		},
		[99] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 5,
		},
		[100] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 5,
		},
		[101] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 6,
		},
		[102] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 6,
		},
		[103] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 6,
		},
		[104] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 6,
		},
		[105] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 7,
		},
		[106] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 7,
		},
		[107] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 7,
		},
		[108] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 7,
		},
		[109] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 8,
		},
		[110] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 8,
		},
		[111] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 8,
		},
		[112] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 8,
		},
		[113] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 9,
		},
		[114] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 9,
		},
		[115] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 9,
		},
		[116] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 9,
		},
		[117] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 10,
		},
		[118] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 10,
		},
		[119] = {
			["Conditions"] = {
			},
			["Bar2"] = 1,
			["Bar"] = 10,
		},
		[120] = {
			["Conditions"] = {
			},
			["Bar"] = 10,
			["Bar2"] = 1,
		},
	},
	["FreeButtons"] = {
	},
	["CustomEvents"] = {
	},
	["KBGroups"] = {
	},
	["UpdateSpeed"] = 10,
	["Bar"] = {
		[1] = {
			["unusablerecolor"] = 1,
			["checked"] = "Interface\\Buttons\\CheckButtonHilight",
			["Keybinding"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["checkedcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["unusablecolor"] = {
				["b"] = 0.6,
				["g"] = 0.6,
				["r"] = 0.6,
			},
			["buttonbg"] = "",
			["size"] = 36,
			["rightClick"] = 1,
			["buttonbgcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Cooldown"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 16,
			},
			["hspacing"] = 3.5,
			["ButtonBorder"] = {
				["rightpadding"] = 13,
				["leftpadding"] = 12,
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["ecolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 0,
				},
				["bottompadding"] = 13,
				["toppadding"] = 12,
				["etexture"] = "Interface\\Buttons\\ButtonHilight-Square",
				["texture"] = "Interface\\Buttons\\UI-Quickslot2",
			},
			["highlight"] = "Interface\\Buttons\\ButtonHilight-Square",
			["numBars"] = 7,
			["rows"] = 1,
			["cbgroup"] = 1,
			["Anchor"] = {
				["y"] = 1,
				["x"] = -4,
				["point"] = "BOTTOMRIGHT",
				["frame"] = "MainMenuBar",
				["to"] = "BOTTOM",
			},
			["vspacing"] = 0,
			["expandHidden"] = 1,
			["Background"] = {
				["leftpadding"] = 1,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["rightpadding"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["tileSize"] = 1,
				["bottompadding"] = 1,
				["edgeSize"] = 1,
				["balpha"] = 1,
				["hide"] = 1,
			},
			["Scripts"] = {
			},
			["manacolor"] = {
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.2,
			},
			["Label"] = {
				["bgcolor"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["attachpoint"] = "BOTTOM",
				["justifyV"] = "CENTER",
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["justifyH"] = "CENTER",
				["attachto"] = "TOP",
				["right"] = 1,
				["left"] = 1,
				["hide"] = 1,
				["bgalpha"] = 1,
				["bordcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["edgeSize"] = 1,
				["bottom"] = 1,
				["x"] = 0,
				["text"] = "MAIN",
				["alpha"] = 1,
				["width"] = 100,
				["y"] = 10,
				["font"] = "Fonts\\FRIZQT__.TTF",
				["bordalpha"] = 1,
				["top"] = 1,
				["height"] = 20,
				["tileSize"] = 1,
				["fontsize"] = 15,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			},
			["Macro"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["rangerecolor"] = 1,
			["frameStrata"] = "DIALOG",
			["middleClick"] = 1,
			["rangecolor"] = {
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			},
			["manarecolor"] = 1,
			["Count"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["Conditions"] = {
				[1] = {
					["overrides"] = {
					},
					["page"] = 1,
					["form"] = 0,
					["condition"] = 22,
					["response"] = 1,
				},
				[2] = {
					["overrides"] = {
					},
					["page"] = 7,
					["form"] = 1,
					["condition"] = 22,
					["response"] = 1,
				},
			},
			["numButtons"] = 12,
			["page"] = 1,
			["highlightcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 1,
		},
		[2] = {
			["middleClick"] = 2,
			["checked"] = "Interface\\Buttons\\CheckButtonHilight",
			["Keybinding"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["checkedcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["unusablecolor"] = {
				["b"] = 0.6,
				["g"] = 0.6,
				["r"] = 0.6,
			},
			["buttonbg"] = "Interface\\AddOns\\DiscordLibrary\\EmptyButton",
			["size"] = 50,
			["rightClick"] = 2,
			["buttonbgcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Cooldown"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 16,
			},
			["hspacing"] = 0,
			["ButtonBorder"] = {
				["rightpadding"] = 13,
				["leftpadding"] = 12,
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["ecolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 0,
				},
				["bottompadding"] = 13,
				["toppadding"] = 12,
				["etexture"] = "Interface\\Buttons\\ButtonHilight-Square",
				["texture"] = "Interface\\Buttons\\UI-Quickslot2",
			},
			["highlight"] = "Interface\\Buttons\\ButtonHilight-Square",
			["numBars"] = 1,
			["rows"] = 2,
			["cbgroup"] = 2,
			["Anchor"] = {
				["y"] = -80,
				["x"] = 0,
				["point"] = "TOP",
				["frame"] = "UIParent",
				["to"] = "TOP",
			},
			["Background"] = {
				["leftpadding"] = 1,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["bottompadding"] = 1,
				["tileSize"] = 1,
				["rightpadding"] = 1,
				["balpha"] = 1,
			},
			["numButtons"] = 4,
			["hide"] = 1,
			["Label"] = {
				["bgcolor"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["attachpoint"] = "BOTTOM",
				["justifyV"] = "CENTER",
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["justifyH"] = "CENTER",
				["attachto"] = "TOP",
				["right"] = 1,
				["left"] = 1,
				["hide"] = true,
				["bgalpha"] = 1,
				["bordcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["edgeSize"] = 1,
				["bottom"] = 1,
				["x"] = 0,
				["text"] = "Bar 2",
				["alpha"] = 1,
				["width"] = 100,
				["y"] = 10,
				["font"] = "Fonts\\FRIZQT__.TTF",
				["bordalpha"] = 1,
				["top"] = 1,
				["height"] = 20,
				["tileSize"] = 1,
				["fontsize"] = 15,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			},
			["manacolor"] = {
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.2,
			},
			["vspacing"] = 0,
			["Macro"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["rangerecolor"] = 1,
			["alpha"] = 1,
			["Scripts"] = {
			},
			["rangecolor"] = {
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			},
			["manarecolor"] = 1,
			["Count"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["unusablerecolor"] = 1,
			["Conditions"] = {
			},
			["page"] = 1,
			["frameStrata"] = "LOW",
			["highlightcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
		[3] = {
			["middleClick"] = 3,
			["checked"] = "Interface\\Buttons\\CheckButtonHilight",
			["Keybinding"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["checkedcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["unusablecolor"] = {
				["b"] = 0.6,
				["g"] = 0.6,
				["r"] = 0.6,
			},
			["buttonbg"] = "Interface\\AddOns\\DiscordLibrary\\EmptyButton",
			["size"] = 50,
			["rightClick"] = 3,
			["buttonbgcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Cooldown"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 16,
			},
			["hspacing"] = 0,
			["ButtonBorder"] = {
				["rightpadding"] = 13,
				["leftpadding"] = 12,
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["ecolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 0,
				},
				["bottompadding"] = 13,
				["toppadding"] = 12,
				["etexture"] = "Interface\\Buttons\\ButtonHilight-Square",
				["texture"] = "Interface\\Buttons\\UI-Quickslot2",
			},
			["highlight"] = "Interface\\Buttons\\ButtonHilight-Square",
			["numBars"] = 1,
			["rows"] = 2,
			["cbgroup"] = 3,
			["Anchor"] = {
				["y"] = -120,
				["x"] = 0,
				["point"] = "TOP",
				["frame"] = "UIParent",
				["to"] = "TOP",
			},
			["Background"] = {
				["leftpadding"] = 1,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["bottompadding"] = 1,
				["tileSize"] = 1,
				["rightpadding"] = 1,
				["balpha"] = 1,
			},
			["numButtons"] = 4,
			["hide"] = 1,
			["Label"] = {
				["bgcolor"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["attachpoint"] = "BOTTOM",
				["justifyV"] = "CENTER",
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["justifyH"] = "CENTER",
				["attachto"] = "TOP",
				["right"] = 1,
				["left"] = 1,
				["hide"] = true,
				["bgalpha"] = 1,
				["bordcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["edgeSize"] = 1,
				["bottom"] = 1,
				["x"] = 0,
				["text"] = "Bar 3",
				["alpha"] = 1,
				["width"] = 100,
				["y"] = 10,
				["font"] = "Fonts\\FRIZQT__.TTF",
				["bordalpha"] = 1,
				["top"] = 1,
				["height"] = 20,
				["tileSize"] = 1,
				["fontsize"] = 15,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			},
			["manacolor"] = {
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.2,
			},
			["vspacing"] = 0,
			["Macro"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["rangerecolor"] = 1,
			["alpha"] = 1,
			["Scripts"] = {
			},
			["rangecolor"] = {
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			},
			["manarecolor"] = 1,
			["Count"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["unusablerecolor"] = 1,
			["Conditions"] = {
			},
			["page"] = 1,
			["frameStrata"] = "LOW",
			["highlightcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
		[4] = {
			["middleClick"] = 4,
			["checked"] = "Interface\\Buttons\\CheckButtonHilight",
			["Keybinding"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["checkedcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["unusablecolor"] = {
				["b"] = 0.6,
				["g"] = 0.6,
				["r"] = 0.6,
			},
			["buttonbg"] = "Interface\\AddOns\\DiscordLibrary\\EmptyButton",
			["size"] = 50,
			["rightClick"] = 4,
			["buttonbgcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Cooldown"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 16,
			},
			["hspacing"] = 0,
			["ButtonBorder"] = {
				["rightpadding"] = 13,
				["leftpadding"] = 12,
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["ecolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 0,
				},
				["bottompadding"] = 13,
				["toppadding"] = 12,
				["etexture"] = "Interface\\Buttons\\ButtonHilight-Square",
				["texture"] = "Interface\\Buttons\\UI-Quickslot2",
			},
			["highlight"] = "Interface\\Buttons\\ButtonHilight-Square",
			["numBars"] = 1,
			["rows"] = 2,
			["cbgroup"] = 4,
			["Anchor"] = {
				["y"] = -160,
				["x"] = 0,
				["point"] = "TOP",
				["frame"] = "UIParent",
				["to"] = "TOP",
			},
			["Background"] = {
				["leftpadding"] = 1,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["bottompadding"] = 1,
				["tileSize"] = 1,
				["rightpadding"] = 1,
				["balpha"] = 1,
			},
			["numButtons"] = 4,
			["hide"] = 1,
			["Label"] = {
				["bgcolor"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["attachpoint"] = "BOTTOM",
				["justifyV"] = "CENTER",
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["justifyH"] = "CENTER",
				["attachto"] = "TOP",
				["right"] = 1,
				["left"] = 1,
				["hide"] = true,
				["bgalpha"] = 1,
				["bordcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["edgeSize"] = 1,
				["bottom"] = 1,
				["x"] = 0,
				["text"] = "Bar 4",
				["alpha"] = 1,
				["width"] = 100,
				["y"] = 10,
				["font"] = "Fonts\\FRIZQT__.TTF",
				["bordalpha"] = 1,
				["top"] = 1,
				["height"] = 20,
				["tileSize"] = 1,
				["fontsize"] = 15,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			},
			["manacolor"] = {
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.2,
			},
			["vspacing"] = 0,
			["Macro"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["rangerecolor"] = 1,
			["alpha"] = 1,
			["Scripts"] = {
			},
			["rangecolor"] = {
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			},
			["manarecolor"] = 1,
			["Count"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["unusablerecolor"] = 1,
			["Conditions"] = {
			},
			["page"] = 1,
			["frameStrata"] = "LOW",
			["highlightcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
		[5] = {
			["middleClick"] = 5,
			["checked"] = "Interface\\Buttons\\CheckButtonHilight",
			["Keybinding"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["checkedcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["unusablecolor"] = {
				["b"] = 0.6,
				["g"] = 0.6,
				["r"] = 0.6,
			},
			["buttonbg"] = "Interface\\AddOns\\DiscordLibrary\\EmptyButton",
			["size"] = 50,
			["rightClick"] = 5,
			["buttonbgcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Cooldown"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 16,
			},
			["hspacing"] = 0,
			["ButtonBorder"] = {
				["rightpadding"] = 13,
				["leftpadding"] = 12,
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["ecolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 0,
				},
				["bottompadding"] = 13,
				["toppadding"] = 12,
				["etexture"] = "Interface\\Buttons\\ButtonHilight-Square",
				["texture"] = "Interface\\Buttons\\UI-Quickslot2",
			},
			["highlight"] = "Interface\\Buttons\\ButtonHilight-Square",
			["numBars"] = 1,
			["rows"] = 2,
			["cbgroup"] = 5,
			["Anchor"] = {
				["y"] = -200,
				["x"] = 0,
				["point"] = "TOP",
				["frame"] = "UIParent",
				["to"] = "TOP",
			},
			["Background"] = {
				["leftpadding"] = 1,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["bottompadding"] = 1,
				["tileSize"] = 1,
				["rightpadding"] = 1,
				["balpha"] = 1,
			},
			["numButtons"] = 4,
			["hide"] = 1,
			["Label"] = {
				["bgcolor"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["attachpoint"] = "BOTTOM",
				["justifyV"] = "CENTER",
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["justifyH"] = "CENTER",
				["attachto"] = "TOP",
				["right"] = 1,
				["left"] = 1,
				["hide"] = true,
				["bgalpha"] = 1,
				["bordcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["edgeSize"] = 1,
				["bottom"] = 1,
				["x"] = 0,
				["text"] = "Bar 5",
				["alpha"] = 1,
				["width"] = 100,
				["y"] = 10,
				["font"] = "Fonts\\FRIZQT__.TTF",
				["bordalpha"] = 1,
				["top"] = 1,
				["height"] = 20,
				["tileSize"] = 1,
				["fontsize"] = 15,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			},
			["manacolor"] = {
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.2,
			},
			["vspacing"] = 0,
			["Macro"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["rangerecolor"] = 1,
			["alpha"] = 1,
			["Scripts"] = {
			},
			["rangecolor"] = {
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			},
			["manarecolor"] = 1,
			["Count"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["unusablerecolor"] = 1,
			["Conditions"] = {
			},
			["page"] = 1,
			["frameStrata"] = "LOW",
			["highlightcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
		[6] = {
			["middleClick"] = 6,
			["checked"] = "Interface\\Buttons\\CheckButtonHilight",
			["Keybinding"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["checkedcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["unusablecolor"] = {
				["b"] = 0.6,
				["g"] = 0.6,
				["r"] = 0.6,
			},
			["buttonbg"] = "Interface\\AddOns\\DiscordLibrary\\EmptyButton",
			["size"] = 50,
			["rightClick"] = 6,
			["buttonbgcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Cooldown"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 16,
			},
			["hspacing"] = 0,
			["ButtonBorder"] = {
				["rightpadding"] = 13,
				["leftpadding"] = 12,
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["ecolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 0,
				},
				["bottompadding"] = 13,
				["toppadding"] = 12,
				["etexture"] = "Interface\\Buttons\\ButtonHilight-Square",
				["texture"] = "Interface\\Buttons\\UI-Quickslot2",
			},
			["highlight"] = "Interface\\Buttons\\ButtonHilight-Square",
			["numBars"] = 1,
			["rows"] = 2,
			["cbgroup"] = 6,
			["Anchor"] = {
				["y"] = -240,
				["x"] = 0,
				["point"] = "TOP",
				["frame"] = "UIParent",
				["to"] = "TOP",
			},
			["Background"] = {
				["leftpadding"] = 1,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["bottompadding"] = 1,
				["tileSize"] = 1,
				["rightpadding"] = 1,
				["balpha"] = 1,
			},
			["numButtons"] = 4,
			["hide"] = 1,
			["Label"] = {
				["bgcolor"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["attachpoint"] = "BOTTOM",
				["justifyV"] = "CENTER",
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["justifyH"] = "CENTER",
				["attachto"] = "TOP",
				["right"] = 1,
				["left"] = 1,
				["hide"] = true,
				["bgalpha"] = 1,
				["bordcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["edgeSize"] = 1,
				["bottom"] = 1,
				["x"] = 0,
				["text"] = "Bar 6",
				["alpha"] = 1,
				["width"] = 100,
				["y"] = 10,
				["font"] = "Fonts\\FRIZQT__.TTF",
				["bordalpha"] = 1,
				["top"] = 1,
				["height"] = 20,
				["tileSize"] = 1,
				["fontsize"] = 15,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			},
			["manacolor"] = {
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.2,
			},
			["vspacing"] = 0,
			["Macro"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["rangerecolor"] = 1,
			["alpha"] = 1,
			["Scripts"] = {
			},
			["rangecolor"] = {
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			},
			["manarecolor"] = 1,
			["Count"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["unusablerecolor"] = 1,
			["Conditions"] = {
			},
			["page"] = 1,
			["frameStrata"] = "LOW",
			["highlightcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
		[7] = {
			["middleClick"] = 7,
			["checked"] = "Interface\\Buttons\\CheckButtonHilight",
			["Keybinding"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["checkedcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["unusablecolor"] = {
				["b"] = 0.6,
				["g"] = 0.6,
				["r"] = 0.6,
			},
			["buttonbg"] = "Interface\\AddOns\\DiscordLibrary\\EmptyButton",
			["size"] = 50,
			["rightClick"] = 7,
			["buttonbgcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Cooldown"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 16,
			},
			["hspacing"] = 0,
			["ButtonBorder"] = {
				["rightpadding"] = 13,
				["leftpadding"] = 12,
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["ecolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 0,
				},
				["bottompadding"] = 13,
				["toppadding"] = 12,
				["etexture"] = "Interface\\Buttons\\ButtonHilight-Square",
				["texture"] = "Interface\\Buttons\\UI-Quickslot2",
			},
			["highlight"] = "Interface\\Buttons\\ButtonHilight-Square",
			["numBars"] = 1,
			["rows"] = 2,
			["cbgroup"] = 7,
			["Anchor"] = {
				["y"] = -280,
				["x"] = 0,
				["point"] = "TOP",
				["frame"] = "UIParent",
				["to"] = "TOP",
			},
			["Background"] = {
				["leftpadding"] = 1,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["bottompadding"] = 1,
				["tileSize"] = 1,
				["rightpadding"] = 1,
				["balpha"] = 1,
			},
			["numButtons"] = 4,
			["hide"] = 1,
			["Label"] = {
				["bgcolor"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["attachpoint"] = "BOTTOM",
				["justifyV"] = "CENTER",
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["justifyH"] = "CENTER",
				["attachto"] = "TOP",
				["right"] = 1,
				["left"] = 1,
				["hide"] = true,
				["bgalpha"] = 1,
				["bordcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["edgeSize"] = 1,
				["bottom"] = 1,
				["x"] = 0,
				["text"] = "Bar 7",
				["alpha"] = 1,
				["width"] = 100,
				["y"] = 10,
				["font"] = "Fonts\\FRIZQT__.TTF",
				["bordalpha"] = 1,
				["top"] = 1,
				["height"] = 20,
				["tileSize"] = 1,
				["fontsize"] = 15,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			},
			["manacolor"] = {
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.2,
			},
			["vspacing"] = 0,
			["Macro"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["rangerecolor"] = 1,
			["alpha"] = 1,
			["Scripts"] = {
			},
			["rangecolor"] = {
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			},
			["manarecolor"] = 1,
			["Count"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["unusablerecolor"] = 1,
			["Conditions"] = {
			},
			["page"] = 1,
			["frameStrata"] = "LOW",
			["highlightcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
		[8] = {
			["middleClick"] = 8,
			["checked"] = "Interface\\Buttons\\CheckButtonHilight",
			["Keybinding"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["checkedcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["unusablecolor"] = {
				["b"] = 0.6,
				["g"] = 0.6,
				["r"] = 0.6,
			},
			["buttonbg"] = "Interface\\AddOns\\DiscordLibrary\\EmptyButton",
			["size"] = 50,
			["rightClick"] = 8,
			["buttonbgcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Cooldown"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 16,
			},
			["hspacing"] = 0,
			["ButtonBorder"] = {
				["rightpadding"] = 13,
				["leftpadding"] = 12,
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["ecolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 0,
				},
				["bottompadding"] = 13,
				["toppadding"] = 12,
				["etexture"] = "Interface\\Buttons\\ButtonHilight-Square",
				["texture"] = "Interface\\Buttons\\UI-Quickslot2",
			},
			["highlight"] = "Interface\\Buttons\\ButtonHilight-Square",
			["numBars"] = 1,
			["rows"] = 2,
			["cbgroup"] = 8,
			["Anchor"] = {
				["y"] = -320,
				["x"] = 0,
				["point"] = "TOP",
				["frame"] = "UIParent",
				["to"] = "TOP",
			},
			["Background"] = {
				["leftpadding"] = 1,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["bottompadding"] = 1,
				["tileSize"] = 1,
				["rightpadding"] = 1,
				["balpha"] = 1,
			},
			["numButtons"] = 4,
			["hide"] = 1,
			["Label"] = {
				["bgcolor"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["attachpoint"] = "BOTTOM",
				["justifyV"] = "CENTER",
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["justifyH"] = "CENTER",
				["attachto"] = "TOP",
				["right"] = 1,
				["left"] = 1,
				["hide"] = true,
				["bgalpha"] = 1,
				["bordcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["edgeSize"] = 1,
				["bottom"] = 1,
				["x"] = 0,
				["text"] = "Bar 8",
				["alpha"] = 1,
				["width"] = 100,
				["y"] = 10,
				["font"] = "Fonts\\FRIZQT__.TTF",
				["bordalpha"] = 1,
				["top"] = 1,
				["height"] = 20,
				["tileSize"] = 1,
				["fontsize"] = 15,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			},
			["manacolor"] = {
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.2,
			},
			["vspacing"] = 0,
			["Macro"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["rangerecolor"] = 1,
			["alpha"] = 1,
			["Scripts"] = {
			},
			["rangecolor"] = {
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			},
			["manarecolor"] = 1,
			["Count"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["unusablerecolor"] = 1,
			["Conditions"] = {
			},
			["page"] = 1,
			["frameStrata"] = "LOW",
			["highlightcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
		[9] = {
			["middleClick"] = 9,
			["checked"] = "Interface\\Buttons\\CheckButtonHilight",
			["Keybinding"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["checkedcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["unusablecolor"] = {
				["b"] = 0.6,
				["g"] = 0.6,
				["r"] = 0.6,
			},
			["buttonbg"] = "Interface\\AddOns\\DiscordLibrary\\EmptyButton",
			["size"] = 50,
			["rightClick"] = 9,
			["buttonbgcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Cooldown"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 16,
			},
			["hspacing"] = 0,
			["ButtonBorder"] = {
				["rightpadding"] = 13,
				["leftpadding"] = 12,
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["ecolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 0,
				},
				["bottompadding"] = 13,
				["toppadding"] = 12,
				["etexture"] = "Interface\\Buttons\\ButtonHilight-Square",
				["texture"] = "Interface\\Buttons\\UI-Quickslot2",
			},
			["highlight"] = "Interface\\Buttons\\ButtonHilight-Square",
			["numBars"] = 1,
			["rows"] = 2,
			["cbgroup"] = 9,
			["Anchor"] = {
				["y"] = -360,
				["x"] = 0,
				["point"] = "TOP",
				["frame"] = "UIParent",
				["to"] = "TOP",
			},
			["Background"] = {
				["leftpadding"] = 1,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["bottompadding"] = 1,
				["tileSize"] = 1,
				["rightpadding"] = 1,
				["balpha"] = 1,
			},
			["numButtons"] = 4,
			["hide"] = 1,
			["Label"] = {
				["bgcolor"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["attachpoint"] = "BOTTOM",
				["justifyV"] = "CENTER",
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["justifyH"] = "CENTER",
				["attachto"] = "TOP",
				["right"] = 1,
				["left"] = 1,
				["hide"] = true,
				["bgalpha"] = 1,
				["bordcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["edgeSize"] = 1,
				["bottom"] = 1,
				["x"] = 0,
				["text"] = "Bar 9",
				["alpha"] = 1,
				["width"] = 100,
				["y"] = 10,
				["font"] = "Fonts\\FRIZQT__.TTF",
				["bordalpha"] = 1,
				["top"] = 1,
				["height"] = 20,
				["tileSize"] = 1,
				["fontsize"] = 15,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			},
			["manacolor"] = {
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.2,
			},
			["vspacing"] = 0,
			["Macro"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["rangerecolor"] = 1,
			["alpha"] = 1,
			["Scripts"] = {
			},
			["rangecolor"] = {
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			},
			["manarecolor"] = 1,
			["Count"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["unusablerecolor"] = 1,
			["Conditions"] = {
			},
			["page"] = 1,
			["frameStrata"] = "LOW",
			["highlightcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
		[10] = {
			["middleClick"] = 10,
			["checked"] = "Interface\\Buttons\\CheckButtonHilight",
			["Keybinding"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["checkedcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["unusablecolor"] = {
				["b"] = 0.6,
				["g"] = 0.6,
				["r"] = 0.6,
			},
			["buttonbg"] = "Interface\\AddOns\\DiscordLibrary\\EmptyButton",
			["size"] = 50,
			["rightClick"] = 10,
			["buttonbgcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Cooldown"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 16,
			},
			["hspacing"] = 0,
			["ButtonBorder"] = {
				["rightpadding"] = 13,
				["leftpadding"] = 12,
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["ecolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 0,
				},
				["bottompadding"] = 13,
				["toppadding"] = 12,
				["etexture"] = "Interface\\Buttons\\ButtonHilight-Square",
				["texture"] = "Interface\\Buttons\\UI-Quickslot2",
			},
			["highlight"] = "Interface\\Buttons\\ButtonHilight-Square",
			["numBars"] = 1,
			["rows"] = 2,
			["cbgroup"] = 10,
			["Anchor"] = {
				["y"] = -400,
				["x"] = 0,
				["point"] = "TOP",
				["frame"] = "UIParent",
				["to"] = "TOP",
			},
			["Background"] = {
				["leftpadding"] = 1,
				["color"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["right"] = 1,
				["left"] = 1,
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["toppadding"] = 1,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["edgeSize"] = 1,
				["bottom"] = 1,
				["bcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["alpha"] = 1,
				["top"] = 1,
				["bottompadding"] = 1,
				["tileSize"] = 1,
				["rightpadding"] = 1,
				["balpha"] = 1,
			},
			["numButtons"] = 4,
			["hide"] = 1,
			["Label"] = {
				["bgcolor"] = {
					["b"] = 0,
					["g"] = 0,
					["r"] = 1,
				},
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["attachpoint"] = "BOTTOM",
				["justifyV"] = "CENTER",
				["btexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
				["justifyH"] = "CENTER",
				["attachto"] = "TOP",
				["right"] = 1,
				["left"] = 1,
				["hide"] = true,
				["bgalpha"] = 1,
				["bordcolor"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["edgeSize"] = 1,
				["bottom"] = 1,
				["x"] = 0,
				["text"] = "Bar 10",
				["alpha"] = 1,
				["width"] = 100,
				["y"] = 10,
				["font"] = "Fonts\\FRIZQT__.TTF",
				["bordalpha"] = 1,
				["top"] = 1,
				["height"] = 20,
				["tileSize"] = 1,
				["fontsize"] = 15,
				["texture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			},
			["manacolor"] = {
				["b"] = 1,
				["g"] = 0.2,
				["r"] = 0.2,
			},
			["vspacing"] = 0,
			["Macro"] = {
				["color"] = {
					["b"] = 0,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["rangerecolor"] = 1,
			["alpha"] = 1,
			["Scripts"] = {
			},
			["rangecolor"] = {
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 1,
			},
			["manarecolor"] = 1,
			["Count"] = {
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["font"] = "Fonts\\FRIZQT__.TTF",
				["size"] = 10,
			},
			["unusablerecolor"] = 1,
			["Conditions"] = {
			},
			["page"] = 1,
			["frameStrata"] = "LOW",
			["highlightcolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
		},
	},
}