
function DAB_Options_LoadCustomSettings()
	DAB_Settings[DAB_INDEX] = {};


	DAB_Settings[DAB_INDEX] = {
	["BagOffsetX"] = 0,
	["EventMacros"] = {
	},
	["BagOffsetY"] = 0,
	["DynamicKeybindingBar"] = 1,
	["MinCooldownCount"] = 0,
	["ShowCooldownCount"] = true,
	["Button"] = {
		[1] = 1,
		[2] = 1,
		[3] = 1,
		[4] = 1,
		[5] = 1,
		[6] = 1,
		[7] = 1,
		[8] = 1,
		[9] = 1,
		[10] = 1,
		[11] = 1,
		[12] = 1,
		[13] = 2,
		[14] = 2,
		[15] = 2,
		[16] = 2,
		[17] = 2,
		[18] = 2,
		[19] = 2,
		[20] = 2,
		[21] = 2,
		[22] = 2,
		[23] = 2,
		[24] = 2,
		[25] = 3,
		[26] = 3,
		[27] = 3,
		[28] = 3,
		[29] = 3,
		[30] = 3,
		[31] = 3,
		[32] = 3,
		[33] = 3,
		[34] = 3,
		[35] = 3,
		[36] = 3,
		[37] = 4,
		[38] = 4,
		[39] = 4,
		[40] = 4,
		[41] = 4,
		[42] = 4,
		[43] = 4,
		[44] = 4,
		[45] = 4,
		[46] = 4,
		[47] = 4,
		[48] = 4,
		[49] = 5,
		[50] = 5,
		[51] = 5,
		[52] = 5,
		[53] = 5,
		[54] = 5,
		[61] = 6,
		[62] = 6,
		[63] = 6,
		[64] = 6,
		[65] = 6,
		[66] = 6,
		[67] = 6,
		[68] = 6,
		[69] = 6,
		[70] = 6,
		[71] = 6,
		[72] = 6,
		[73] = 7,
		[74] = 7,
		[75] = 7,
		[76] = 7,
		[77] = 7,
		[78] = 7,
		[79] = 7,
		[80] = 7,
		[81] = 7,
		[82] = 7,
		[83] = 7,
		[84] = 7,
		[85] = 8,
		[86] = 8,
		[87] = 8,
		[88] = 8,
		[89] = 8,
		[90] = 8,
		[91] = 8,
		[92] = 8,
		[93] = 8,
		[94] = 8,
		[95] = 8,
		[96] = 8,
		[97] = 9,
		[98] = 9,
		[99] = 9,
		[100] = 9,
		[101] = 9,
		[102] = 9,
		[103] = 9,
		[104] = 9,
		[105] = 9,
		[106] = 9,
		[107] = 9,
		[108] = 9,
		[109] = 10,
		[110] = 10,
		[111] = 10,
		[112] = 10,
		[113] = 10,
		[114] = 10,
		[115] = 10,
		[116] = 10,
		[117] = 10,
		[118] = 10,
		[119] = 10,
		[120] = 10,
	},
	["INITIALIZED2.2"] = true,
	["Timeout"] = 0.5,
	["INITIALIZED2.3"] = true,
	["OutOfRangeColor"] = {
		["r"] = 1,
		["g"] = 0.1,
		["b"] = 0.1,
	},
	["OutOfManaColor"] = {
		["r"] = 0.5,
		["g"] = 0.5,
		["b"] = 1,
	},
	["MainBar"] = 1,
	["OtherBar"] = {
		[12] = {
			["attachoffsety"] = 0,
			["spacingv"] = 0,
			["attachpoint"] = "TOPLEFT",
			["alpha"] = 1,
			["attachoffsetx"] = 0,
			["size"] = 30,
			["spacingh"] = 0,
			["padding"] = 10,
			["attachto"] = "TOPLEFT",
			["layout"] = 1,
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["alpha"] = 0,
			},
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Shapeshift Bar",
				["textsize"] = 12,
			},
			["hide"] = true,
		},
		[14] = {
			["attachoffsety"] = 0,
			["spacingv"] = 0,
			["attachpoint"] = "TOPLEFT",
			["alpha"] = 1,
			["attachoffsetx"] = 0,
			["hidelabel"] = true,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Menu Bar",
				["textsize"] = 12,
			},
			["padding"] = 10,
			["attachto"] = "TOPLEFT",
			["spacingh"] = -3,
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["alpha"] = 0,
			},
			["layout"] = 1,
			["size"] = 18,
		},
		[11] = {
			["attachoffsety"] = 0,
			["spacingv"] = 0,
			["attachpoint"] = "TOPLEFT",
			["alpha"] = 1,
			["attachoffsetx"] = 0,
			["hide"] = true,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Pet Action Bar",
				["textsize"] = 12,
			},
			["padding"] = 10,
			["attachto"] = "TOPLEFT",
			["spacingh"] = 0,
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["alpha"] = 0,
			},
			["layout"] = 1,
			["size"] = 30,
		},
		[13] = {
			["attachoffsety"] = 0,
			["spacingv"] = 0,
			["attachpoint"] = "TOPLEFT",
			["alpha"] = 1,
			["attachoffsetx"] = 0,
			["size"] = 25,
			["spacingh"] = 0,
			["padding"] = 10,
			["attachto"] = "TOPLEFT",
			["layout"] = 3,
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["alpha"] = 0,
			},
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bag Bar",
				["textsize"] = 12,
			},
			["hidelabel"] = true,
		},
	},
	["INITIALIZED2.1"] = true,
	["OptionsScale"] = 100,
	["UnusableColor"] = {
		["r"] = 0.4,
		["g"] = 0.4,
		["b"] = 0.4,
	},
	["Floaters"] = {
	},
	["FrameLocation"] = {
		["DAB_ControlBox_1"] = {
			["y"] = -50,
			["x"] = 150,
		},
		["DAB_ActionButton_91"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ActionBar_9"] = {
			["y"] = -412.5000086635897,
			["x"] = 62.10939007183146,
		},
		["DAB_OtherBar_Menu"] = {
			["y"] = 11.09431916588324,
			["x"] = 1360.75047235647,
		},
		["DAB_ActionButton_60"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ControlBox_10"] = {
			["y"] = -500,
			["x"] = 150,
		},
		["DAB_ActionButton_58"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_Options"] = {
			["y"] = -154.1404394615445,
			["x"] = 683.9843408095915,
		},
		["DAB_OtherBar_Form"] = {
			["y"] = -600,
			["x"] = 300,
		},
		["DAB_OtherBar_Bag"] = {
			["y"] = -1041.078027495257,
			["x"] = 1230.780771868599,
		},
		["DAB_ActionButton_96"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ActionButton_95"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ActionButton_59"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ActionBar_2"] = {
			["y"] = -1129.562720993099,
			["x"] = 250.0936011184046,
		},
		["DAB_ControlBox_6"] = {
			["y"] = -300,
			["x"] = 150,
		},
		["DAB_ActionBar_1"] = {
			["y"] = -1093.453086890462,
			["x"] = 250.1251012437785,
		},
		["DAB_ActionButton_57"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ActionBar_3"] = {
			["y"] = -1093.187379935813,
			["x"] = 807.422066048613,
		},
		["DAB_ActionButton_92"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ActionBar_7"] = {
			["y"] = -366.4062695383985,
			["x"] = 71.48436939562112,
		},
		["DAB_ActionButton_93"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ControlBox_8"] = {
			["y"] = -400,
			["x"] = 150,
		},
		["DAB_ControlBox_3"] = {
			["y"] = -150,
			["x"] = 150,
		},
		["DAB_ControlBox_4"] = {
			["y"] = -200,
			["x"] = 150,
		},
		["DAB_ActionBar_8"] = {
			["y"] = -878.1253707692008,
			["x"] = 302.3437829965411,
		},
		["DAB_ActionBar_5"] = {
			["y"] = -1059.421169462487,
			["x"] = 672.4839641533479,
		},
		["DAB_ControlBox_2"] = {
			["y"] = -100,
			["x"] = 150,
		},
		["DAB_ControlBox_7"] = {
			["y"] = -350,
			["x"] = 150,
		},
		["DAB_ActionBar_6"] = {
			["y"] = -877.7340665707184,
			["x"] = 740.7968443923866,
		},
		["DAB_ControlBox_9"] = {
			["y"] = -450,
			["x"] = 150,
		},
		["DAB_ActionBar_10"] = {
			["y"] = -492.9687224563681,
			["x"] = 71.48439382160105,
		},
		["DAB_ControlBox_5"] = {
			["y"] = -250,
			["x"] = 150,
		},
		["DAB_ActionButton_94"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ActionBar_4"] = {
			["y"] = -1129.296867482571,
			["x"] = 807.4526278347017,
		},
		["DAB_OtherBar_Pet"] = {
			["y"] = -550,
			["x"] = 300,
		},
		["DAB_ActionButton_90"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ActionButton_89"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ActionButton_56"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
		["DAB_ActionButton_55"] = {
			["y"] = -1399.999993282856,
			["x"] = 732.5000428599617,
		},
	},
	["Bar"] = {
		[1] = {
			["ccfontsize"] = 16,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bar 1",
				["textsize"] = 12,
			},
			["rightclick"] = 1,
			["rows"] = 1,
			["buttonborderalpha"] = 1,
			["attachoffsetx"] = 0,
			["middleclick"] = 1,
			["attachto"] = "TOPLEFT",
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 0.5019607843137255,
					["g"] = 0.3843137254901961,
					["b"] = 0.1294117647058823,
				},
				["alpha"] = 0,
			},
			["buttonbordercolor"] = {
				["r"] = 0.5019607843137255,
				["g"] = 0.3843137254901961,
				["b"] = 0.1294117647058823,
			},
			["hidelabel"] = true,
			["attachoffsety"] = 0,
			["controlbox"] = {
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["fontheight"] = 12,
				["textmouseovercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["left"] = true,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["mouseovercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["hide"] = true,
				["attachoffsety"] = 0,
				["textcolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "TOPLEFT",
				["bottom"] = true,
				["bgalpha"] = 1,
				["text"] = "Cbox Bar 1",
				["alpha"] = 1,
				["width"] = 100,
				["top"] = true,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["recolor"] = true,
				["height"] = 26,
				["baronclick"] = true,
				["textrecolor"] = true,
				["right"] = true,
			},
			["numbuttons"] = 12,
			["alpha"] = 1,
			["keybindings"] = {
				[1] = {
				},
				[2] = {
				},
				[3] = {
				},
				[4] = {
				},
				[5] = {
				},
				[6] = {
				},
				[7] = {
				},
				[8] = {
				},
				[9] = {
				},
				[10] = {
				},
				[11] = {
				},
				[12] = {
				},
			},
			["size"] = 35,
			["buttonborderpadding"] = 0,
			["spacingh"] = 0,
			["padding"] = 10,
			["spacingv"] = 0,
			["attachpoint"] = "TOPLEFT",
		},
		[2] = {
			["ccfontsize"] = 16,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bar 2",
				["textsize"] = 12,
			},
			["rightclick"] = 2,
			["rows"] = 1,
			["buttonborderalpha"] = 1,
			["attachoffsetx"] = 0,
			["middleclick"] = 2,
			["attachto"] = "TOPLEFT",
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 0.5019607843137255,
					["g"] = 0.3843137254901961,
					["b"] = 0.1294117647058823,
				},
				["alpha"] = 0,
			},
			["buttonbordercolor"] = {
				["r"] = 0.5019607843137255,
				["g"] = 0.3843137254901961,
				["b"] = 0.1294117647058823,
			},
			["hidelabel"] = true,
			["attachoffsety"] = 0,
			["controlbox"] = {
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["fontheight"] = 12,
				["textmouseovercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["left"] = true,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["mouseovercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["hide"] = true,
				["attachoffsety"] = 0,
				["textcolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "TOPLEFT",
				["bottom"] = true,
				["bgalpha"] = 1,
				["text"] = "Cbox Bar 2",
				["alpha"] = 1,
				["width"] = 100,
				["top"] = true,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["recolor"] = true,
				["height"] = 26,
				["baronclick"] = true,
				["textrecolor"] = true,
				["right"] = true,
			},
			["numbuttons"] = 12,
			["alpha"] = 1,
			["keybindings"] = {
				[1] = {
				},
				[2] = {
				},
				[3] = {
				},
				[4] = {
				},
				[5] = {
				},
				[6] = {
				},
				[7] = {
				},
				[8] = {
				},
				[9] = {
				},
				[10] = {
				},
				[11] = {
				},
				[12] = {
				},
			},
			["size"] = 35,
			["buttonborderpadding"] = 0,
			["spacingh"] = 0,
			["padding"] = 10,
			["spacingv"] = 0,
			["attachpoint"] = "TOPLEFT",
		},
		[3] = {
			["ccfontsize"] = 16,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bar 3",
				["textsize"] = 12,
			},
			["rightclick"] = 3,
			["rows"] = 1,
			["buttonborderalpha"] = 1,
			["attachoffsetx"] = 0,
			["middleclick"] = 3,
			["attachto"] = "TOPLEFT",
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 0.5019607843137255,
					["g"] = 0.3843137254901961,
					["b"] = 0.1294117647058823,
				},
				["alpha"] = 0,
			},
			["buttonbordercolor"] = {
				["r"] = 0.5019607843137255,
				["g"] = 0.3843137254901961,
				["b"] = 0.1294117647058823,
			},
			["hidelabel"] = true,
			["attachoffsety"] = 0,
			["controlbox"] = {
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["fontheight"] = 12,
				["textmouseovercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["left"] = true,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["mouseovercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["hide"] = true,
				["attachoffsety"] = 0,
				["textcolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "TOPLEFT",
				["bottom"] = true,
				["bgalpha"] = 1,
				["text"] = "Cbox Bar 3",
				["alpha"] = 1,
				["width"] = 100,
				["top"] = true,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["recolor"] = true,
				["height"] = 26,
				["baronclick"] = true,
				["textrecolor"] = true,
				["right"] = true,
			},
			["numbuttons"] = 12,
			["alpha"] = 1,
			["keybindings"] = {
				[1] = {
				},
				[2] = {
				},
				[3] = {
				},
				[4] = {
				},
				[5] = {
				},
				[6] = {
				},
				[7] = {
				},
				[8] = {
				},
				[9] = {
				},
				[10] = {
				},
				[11] = {
				},
				[12] = {
				},
			},
			["size"] = 35,
			["buttonborderpadding"] = 0,
			["spacingh"] = 0,
			["padding"] = 10,
			["spacingv"] = 0,
			["attachpoint"] = "TOPLEFT",
		},
		[4] = {
			["ccfontsize"] = 16,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bar 4",
				["textsize"] = 12,
			},
			["rightclick"] = 4,
			["rows"] = 1,
			["buttonborderalpha"] = 1,
			["attachoffsetx"] = 0,
			["middleclick"] = 4,
			["attachto"] = "TOPLEFT",
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 0.5019607843137255,
					["g"] = 0.3843137254901961,
					["b"] = 0.1294117647058823,
				},
				["alpha"] = 0,
			},
			["buttonbordercolor"] = {
				["r"] = 0.5019607843137255,
				["g"] = 0.3843137254901961,
				["b"] = 0.1294117647058823,
			},
			["hidelabel"] = true,
			["attachoffsety"] = 0,
			["controlbox"] = {
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["fontheight"] = 12,
				["textmouseovercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["left"] = true,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["mouseovercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["hide"] = true,
				["attachoffsety"] = 0,
				["textcolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "TOPLEFT",
				["bottom"] = true,
				["bgalpha"] = 1,
				["text"] = "Cbox Bar 4",
				["alpha"] = 1,
				["width"] = 100,
				["top"] = true,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["recolor"] = true,
				["height"] = 26,
				["baronclick"] = true,
				["textrecolor"] = true,
				["right"] = true,
			},
			["numbuttons"] = 12,
			["alpha"] = 1,
			["keybindings"] = {
				[1] = {
					["key1"] = "ALT-5",
				},
				[2] = {
				},
				[3] = {
				},
				[4] = {
				},
				[5] = {
				},
				[6] = {
				},
				[7] = {
				},
				[8] = {
				},
				[9] = {
				},
				[10] = {
				},
				[11] = {
				},
				[12] = {
				},
			},
			["size"] = 35,
			["buttonborderpadding"] = 0,
			["spacingh"] = 0,
			["padding"] = 10,
			["spacingv"] = 0,
			["attachpoint"] = "TOPLEFT",
		},
		[5] = {
			["ccfontsize"] = 16,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bar 5",
				["textsize"] = 12,
			},
			["rightclick"] = 5,
			["rows"] = 3,
			["buttonborderalpha"] = 1,
			["attachoffsetx"] = 0,
			["middleclick"] = 5,
			["attachto"] = "TOPLEFT",
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 0.5019607843137255,
					["g"] = 0.3843137254901961,
					["b"] = 0.1294117647058823,
				},
				["alpha"] = 0,
			},
			["buttonbordercolor"] = {
				["r"] = 0.5019607843137255,
				["g"] = 0.3843137254901961,
				["b"] = 0.1294117647058823,
			},
			["hidelabel"] = true,
			["attachoffsety"] = 0,
			["controlbox"] = {
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["fontheight"] = 12,
				["textmouseovercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["left"] = true,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["mouseovercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["hide"] = true,
				["attachoffsety"] = 0,
				["textcolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "TOPLEFT",
				["bottom"] = true,
				["bgalpha"] = 1,
				["text"] = "Cbox Bar 5",
				["alpha"] = 1,
				["width"] = 100,
				["top"] = true,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["recolor"] = true,
				["height"] = 26,
				["baronclick"] = true,
				["textrecolor"] = true,
				["right"] = true,
			},
			["numbuttons"] = 6,
			["alpha"] = 1,
			["keybindings"] = {
				[1] = {
				},
				[2] = {
				},
				[3] = {
				},
				[4] = {
				},
				[5] = {
				},
				[6] = {
				},
				[7] = {
				},
				[8] = {
				},
				[9] = {
				},
				[10] = {
				},
				[11] = {
				},
				[12] = {
				},
			},
			["size"] = 35,
			["buttonborderpadding"] = 0,
			["spacingh"] = 63,
			["padding"] = 10,
			["spacingv"] = 0,
			["attachpoint"] = "TOPLEFT",
		},
		[6] = {
			["ccfontsize"] = 16,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bar 6",
				["textsize"] = 12,
			},
			["rightclick"] = 6,
			["rows"] = 1,
			["buttonborderalpha"] = 1,
			["attachoffsetx"] = 0,
			["middleclick"] = 6,
			["mouseoverbar"] = true,
			["attachto"] = "TOPLEFT",
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["alpha"] = 0,
			},
			["buttonbordercolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["hidelabel"] = true,
			["attachoffsety"] = 0,
			["controlbox"] = {
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["fontheight"] = 12,
				["textmouseovercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["left"] = true,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["mouseovercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["hide"] = true,
				["attachoffsety"] = 0,
				["textcolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "TOPLEFT",
				["bottom"] = true,
				["bgalpha"] = 1,
				["text"] = "Cbox Bar 6",
				["alpha"] = 1,
				["width"] = 100,
				["top"] = true,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["recolor"] = true,
				["height"] = 26,
				["baronclick"] = true,
				["textrecolor"] = true,
				["right"] = true,
			},
			["numbuttons"] = 12,
			["alpha"] = 1,
			["size"] = 35,
			["keybindings"] = {
				[1] = {
					["key1"] = "ALT-3",
				},
				[2] = {
					["key1"] = "ALT-4",
				},
				[3] = {
				},
				[4] = {
				},
				[5] = {
				},
				[6] = {
				},
				[7] = {
				},
				[8] = {
				},
				[9] = {
				},
				[10] = {
				},
				[11] = {
				},
				[12] = {
				},
			},
			["attachpoint"] = "TOPLEFT",
			["spacingh"] = 1,
			["buttonborderpadding"] = 0,
			["spacingv"] = 0,
			["padding"] = 10,
			["hide"] = true,
			["hideempty"] = true,
		},
		[7] = {
			["ccfontsize"] = 16,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bar 7",
				["textsize"] = 12,
			},
			["rightclick"] = 7,
			["rows"] = 1,
			["buttonborderalpha"] = 1,
			["attachoffsetx"] = 0,
			["middleclick"] = 7,
			["attachto"] = "TOPLEFT",
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["alpha"] = 0,
			},
			["buttonbordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["hidelabel"] = true,
			["attachoffsety"] = 0,
			["controlbox"] = {
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["fontheight"] = 12,
				["textmouseovercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["left"] = true,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["mouseovercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["hide"] = true,
				["attachoffsety"] = 0,
				["textcolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "TOPLEFT",
				["bottom"] = true,
				["bgalpha"] = 1,
				["text"] = "Cbox Bar 7",
				["alpha"] = 1,
				["width"] = 100,
				["top"] = true,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["recolor"] = true,
				["height"] = 26,
				["baronclick"] = true,
				["textrecolor"] = true,
				["right"] = true,
			},
			["numbuttons"] = 12,
			["form"] = 3,
			["alpha"] = 1,
			["size"] = 35,
			["keybindings"] = {
				[1] = {
				},
				[2] = {
				},
				[3] = {
				},
				[4] = {
				},
				[5] = {
				},
				[6] = {
				},
				[7] = {
				},
				[8] = {
				},
				[9] = {
				},
				[10] = {
				},
				[11] = {
				},
				[12] = {
				},
			},
			["formmethod"] = 3,
			["buttonborderpadding"] = 0,
			["spacingh"] = 0,
			["spacingv"] = 0,
			["padding"] = 10,
			["attachpoint"] = "TOPLEFT",
			["hide"] = true,
		},
		[8] = {
			["hideempty"] = true,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bar 8",
				["textsize"] = 12,
			},
			["rightclick"] = 8,
			["rows"] = 1,
			["buttonborderalpha"] = 1,
			["attachoffsetx"] = 0,
			["middleclick"] = 8,
			["mouseoverbar"] = true,
			["attachto"] = "TOPLEFT",
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["alpha"] = 0,
			},
			["buttonbordercolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["hidelabel"] = true,
			["attachoffsety"] = 0,
			["controlbox"] = {
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["fontheight"] = 12,
				["textmouseovercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["left"] = true,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["mouseovercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["hide"] = true,
				["attachoffsety"] = 0,
				["textcolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "TOPLEFT",
				["bottom"] = true,
				["bgalpha"] = 1,
				["text"] = "Cbox Bar 8",
				["alpha"] = 1,
				["width"] = 100,
				["top"] = true,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["recolor"] = true,
				["height"] = 26,
				["baronclick"] = true,
				["textrecolor"] = true,
				["right"] = true,
			},
			["numbuttons"] = 12,
			["size"] = 35,
			["alpha"] = 1,
			["attachpoint"] = "TOPLEFT",
			["keybindings"] = {
				[1] = {
				},
				[2] = {
				},
				[3] = {
				},
				[4] = {
				},
				[5] = {
				},
				[6] = {
				},
				[7] = {
				},
				[8] = {
				},
				[9] = {
				},
				[10] = {
				},
				[11] = {
					["key1"] = "ALT-1",
				},
				[12] = {
					["key1"] = "ALT-2",
				},
			},
			["formmethod"] = 3,
			["spacingh"] = 1,
			["buttonborderpadding"] = 0,
			["spacingv"] = 0,
			["padding"] = 10,
			["ccfontsize"] = 16,
			["hide"] = true,
		},
		[9] = {
			["ccfontsize"] = 16,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bar 9",
				["textsize"] = 12,
			},
			["rightclick"] = 9,
			["rows"] = 1,
			["buttonborderalpha"] = 1,
			["attachoffsetx"] = 0,
			["middleclick"] = 9,
			["attachto"] = "TOPLEFT",
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["alpha"] = 0,
			},
			["buttonbordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["hidelabel"] = true,
			["attachoffsety"] = 0,
			["controlbox"] = {
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["fontheight"] = 12,
				["textmouseovercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["left"] = true,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["mouseovercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["hide"] = true,
				["attachoffsety"] = 0,
				["textcolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "TOPLEFT",
				["bottom"] = true,
				["bgalpha"] = 1,
				["text"] = "Cbox Bar 9",
				["alpha"] = 1,
				["width"] = 100,
				["top"] = true,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["recolor"] = true,
				["height"] = 26,
				["baronclick"] = true,
				["textrecolor"] = true,
				["right"] = true,
			},
			["numbuttons"] = 12,
			["form"] = 1,
			["alpha"] = 1,
			["size"] = 35,
			["keybindings"] = {
				[1] = {
				},
				[2] = {
				},
				[3] = {
				},
				[4] = {
				},
				[5] = {
				},
				[6] = {
				},
				[7] = {
				},
				[8] = {
				},
				[9] = {
				},
				[10] = {
				},
				[11] = {
				},
				[12] = {
				},
			},
			["formmethod"] = 3,
			["buttonborderpadding"] = 0,
			["spacingh"] = 0,
			["spacingv"] = 0,
			["padding"] = 10,
			["attachpoint"] = "TOPLEFT",
			["hide"] = true,
		},
		[10] = {
			["ccfontsize"] = 16,
			["label"] = {
				["attachoffsety"] = 0,
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "BOTTOMLEFT",
				["alpha"] = 1,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["bgalpha"] = 1,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["text"] = "Bar 10",
				["textsize"] = 12,
			},
			["rightclick"] = 10,
			["rows"] = 1,
			["buttonborderalpha"] = 1,
			["attachoffsetx"] = 0,
			["middleclick"] = 10,
			["attachto"] = "TOPLEFT",
			["background"] = {
				["style"] = 1,
				["borderalpha"] = 0,
				["color"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["bordercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["alpha"] = 0,
			},
			["buttonbordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["hidelabel"] = true,
			["attachoffsety"] = 0,
			["controlbox"] = {
				["bgcolor"] = {
					["r"] = 0.7,
					["g"] = 0,
					["b"] = 0,
				},
				["fontheight"] = 12,
				["textmouseovercolor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["left"] = true,
				["attachoffsetx"] = 0,
				["attachto"] = "TOPLEFT",
				["mouseovercolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["hide"] = true,
				["attachoffsety"] = 0,
				["textcolor"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 0,
				},
				["attachpoint"] = "TOPLEFT",
				["bottom"] = true,
				["bgalpha"] = 1,
				["text"] = "Cbox Bar 10",
				["alpha"] = 1,
				["width"] = 100,
				["top"] = true,
				["bordercolor"] = {
					["r"] = 0.7,
					["g"] = 0.7,
					["b"] = 0,
				},
				["borderalpha"] = 1,
				["recolor"] = true,
				["height"] = 26,
				["baronclick"] = true,
				["textrecolor"] = true,
				["right"] = true,
			},
			["numbuttons"] = 12,
			["alpha"] = 1,
			["size"] = 35,
			["keybindings"] = {
				[1] = {
				},
				[2] = {
				},
				[3] = {
				},
				[4] = {
				},
				[5] = {
				},
				[6] = {
				},
				[7] = {
				},
				[8] = {
				},
				[9] = {
				},
				[10] = {
				},
				[11] = {
				},
				[12] = {
				},
			},
			["formmethod"] = 3,
			["hide"] = true,
			["buttonborderpadding"] = 0,
			["spacingh"] = 0,
			["padding"] = 10,
			["spacingv"] = 0,
			["attachpoint"] = "TOPLEFT",
		},
	},
}
DAB_Initialize_AllSettings();
	DAB_Feedback(DAB_TEXT.SettingsLoaded);
end