if (not ExperienceFuLocals) then
    ExperienceFuLocals = AceLibrary("AceLocale-2.0"):new("ExperienceFu")
end

ExperienceFuLocals:RegisterTranslations("enUS", function() return {
    ["Current XP"] = true,
    ["Display Value as..."] = true,
    ["Display Values"] = true,
    ["Display various XP statistics"] = true,
    ["Gained"] = true,
    ["Hide Text at maximum level"] = true,
    ["Level"] = true,
    ["Pet XP"] = true,
    ["Remaining"] = true,
    ["Reset session"] = true,
    ["Rest XP"] = true,
    ["Show XP/hour"] = true,
    ["Show current XP percent"] = true,
    ["Show current XP until level"] = true,
    ["Show current XP value"] = true,
    ["Show current XP"] = true,
    ["Show in relation to level"] = true,
    ["Show percent"] = true,
    ["Show pet XP percent"] = true,
    ["Show pet XP until level"] = true,
    ["Show pet XP value"] = true,
    ["Show pet XP"] = true,
    ["Show rest XP percent"] = true,
    ["Show rest XP value"] = true,
    ["Show rest XP"] = true,
    ["Show time to level"] = true,
    ["Show value"] = true,
    ["Statistics"] = true,
    ["Time this level"] = true,
    ["Time this session"] = true,
    ["Time to level for this level"] = true,
    ["Time to level for this session"] = true,
    ["Toggle between showing experience as an absolute or in relation to time."] = true,
    ["Total XP this level"] = true,
    ["Total XP this session"] = true,
    ["Total time played"] = true,
    ["View as Remaining XP"] = true,
    ["XP/hour this level"] = true,
    ["XP/hour this session"] = true,
} end)

