AtlasLootWorldPvPItems = {
    
    HellHorde = {
        { 27833, "INV_Jewelry_Ring_36", "=q3=Band of the Victor", "=ds=#s13#" },
        { 27786, "INV_Misc_Gem_DeepPeridot_01", "=q3=Barbed Deep Peridot", "=ds=#e23#" },
        { 28360, "INV_Misc_Gem_Bloodstone_02", "=q3=Mighty Blood Garnet", "=ds=#e23#" },
        { 24522, "Racial_Orc_BerserkerStrength", "=q1=Thrallmar Favor", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 24581, "INV_Misc_Token_Thrallmar", "=q1=Mark of Thrallmar", "=ds=#e25#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 27830, "INV_Jewelry_Ring_36", "=q3=Circlet of the Victor", "=ds=#s13#" },
        { 27785, "INV_Misc_Gem_DeepPeridot_03", "=q3=Notched Deep Peridot", "=ds=#e23#" },
        { 27777, "INV_Misc_Gem_Bloodstone_02", "=q3=Stark Blood Garnet", "=ds=#e23#" },
    };
    
    HellAlliance = {
        { 27833, "INV_Jewelry_Ring_36", "=q3=Band of the Victor", "=ds=#s13#" },
        { 27786, "INV_Misc_Gem_DeepPeridot_01", "=q3=Barbed Deep Peridot", "=ds=#e23#" },
        { 28360, "INV_Misc_Gem_Bloodstone_02", "=q3=Mighty Blood Garnet", "=ds=#e23#" },
        { 24520, "INV_Banner_02", "=q1=Honor Hold Favor", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 24579, "INV_Misc_Token_HonorHold", "=q1=Mark of Honor Hold", "=ds=#e25#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 27830, "INV_Jewelry_Ring_36", "=q3=Circlet of the Victor", "=ds=#s13#" },
        { 27785, "INV_Misc_Gem_DeepPeridot_03", "=q3=Notched Deep Peridot", "=ds=#e23#" },
        { 27777, "INV_Misc_Gem_Bloodstone_02", "=q3=Stark Blood Garnet", "=ds=#e23#" },
    };
    
    Zangarmarsh = {
        { 27990, "INV_Relics_IdolofFerocity", "=q3=Idol of Savagery", "=ds=#e16#" },
        { 27983, "INV_Relics_LibramofTruth", "=q3=Libram of Zeal", "=ds=#e18#" },
        { 27922, "INV_Jewelry_Necklace_16", "=q3=Mark of Defiance", "=ds=#s14#" },
        { 27930, "INV_Weapon_Bow_04", "=q3=Splintermark", "=ds=#w2#" },
        { 27984, "Spell_Nature_SlowingTotem", "=q3=Totem of Impact", "=ds=#e17#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 24579, "INV_Misc_Token_HonorHold", "=q1=Mark of Honor Hold", "=ds=#e25#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 27939, "INV_Wand_11", "=q3=Incendic Rod", "=ds=#w12#" },
        { 27920, "INV_Misc_ArmorKit_12", "=q3=Mark of Conquest", "=ds=#s14#" },
        { 27927, "INV_QirajIdol_Sun", "=q3=Mark of Vindication", "=ds=#s14#" },
        { 27929, "INV_Axe_03", "=q3=Terminal Edge", "=ds=#w11#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 24581, "INV_Misc_Token_Thrallmar", "=q1=Mark of Thrallmar", "=ds=#e25#" },
    };
    
    Terokkar = {
        { 28553, "INV_Jewelry_Ring_60", "=q4=Band of the Exorcist", "=ds=#s13#" },
        { 28557, "INV_Misc_Gem_Diamond_07", "=q3=Swift Starfire Diamond", "=ds=#e23#" },
        { 28759, "INV_Helmet_30", "=q3=Exorcist's Dreadweave Hood", "=ds=#a1# #s1#" },
        { 28574, "INV_Helmet_30", "=q3=Exorcist's Dragonhide Helm", "=ds=#a2# #s1#" },
        { 28575, "INV_Helmet_30", "=q3=Exorcist's Wyrmhide Helm", "=ds=#a2# #s1#" },
        { 28577, "INV_Helmet_09", "=q3=Exorcist's Linked Helm", "=ds=#a3# #s1#" },
        { 28560, "INV_Helmet_22", "=q3=Exorcist's Lamellar Helm", "=ds=#a4# #s1#" },
        { 28761, "INV_Helmet_22", "=q3=Exorcist's Scaled Helm", "=ds=#a4# #s1#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 28558, "INV_Jewelry_FrostwolfTrinket_04", "=q1=Spirit Shard", "=ds=#e24#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 28555, "INV_Jewelry_Ring_60", "=q4=Seal of the Exorcist", "=ds=#s13#" },
        { 28556, "INV_Misc_Gem_Diamond_07", "=q3=Swift Windfire Diamond", "=ds=#e23#" },
        { 28760, "INV_Helmet_30", "=q3=Exorcist's Silk Hood", "=ds=#a1# #s1#" },
        { 28561, "INV_Helmet_30", "=q3=Exorcist's Leather Helm", "=ds=#a2# #s1#" },
        { 28576, "INV_Helmet_09", "=q3=Exorcist's Chain Helm", "=ds=#a3# #s1#" },
        { 28758, "INV_Helmet_09", "=q3=Exorcist's Mail Helm", "=ds=#a3# #s1#" },
        { 28559, "INV_Helmet_22", "=q3=Exorcist's Plate Helm", "=ds=#a4# #s1#" },
    };
    
    Nagrand = {
        { 27654, "INV_Pants_Plate_15", "=q3=Avenger's Legguards", "=ds=#a4# #s11#" },
        { 27648, "INV_Pants_07", "=q3=Dreamstalker Leggings", "=ds=#a2# #s12#" },
        { 27649, "INV_Pants_Cloth_05", "=q3=Hierophant's Leggings", "=ds=#a1# #s12#" },
        { 27647, "INV_Pants_Mail_04", "=q3=Marksman's Legguards", "=ds=#a3# #s12#" },
        { 27650, "INV_Pants_Leather_03", "=q3=Shadowstalker's Leggings", "=ds=#a2# #s12#" },
        { 27653, "INV_Pants_Plate_15", "=q3=Slayer's Legguards", "=ds=#a4# #s12#" },
        { 27652, "INV_Pants_Mail_12", "=q3=Stormbreaker's Leggings", "=ds=#a3# #s12#" },
        { 27680, "INV_Misc_Bag_17", "=q3=Halaani Bag", "=ds=#e10#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 26045, "INV_Misc_Rune_08", "=q2=Halaa Battle Token", "=ds=#e24#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 27644, "INV_Belt_14", "=q3=Avenger's Waistguard", "=ds=#a4# #s11#" },
        { 27645, "INV_Belt_17", "=q3=Dreamstalker Sash", "=ds=#a2# #s12#" },
        { 27638, "INV_Belt_17", "=q3=Hierophant's Sash", "=ds=#a1# #s12#" },
        { 27646, "INV_Belt_20", "=q3=Marksman's Belt", "=ds=#a3# #s12#" },
        { 27637, "INV_Belt_15", "=q3=Shadowstalker's Sash", "=ds=#a2# #s12#" },
        { 27639, "INV_Belt_14", "=q3=Slayer's Waistguard", "=ds=#a4# #s12#" },
        { 27643, "INV_Belt_20", "=q3=Stormbreaker's Girdle", "=ds=#a3# #s12#" },
        { 27679, "INV_Misc_Gem_Topaz_01", "=q4=Sublime Mystic Dawnstone", "=ds=#e23#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 26044, "INV_Misc_Rune_09", "=q2=Halaa Research Token", "=ds=#e24#" },
    };    
};