CastProgress.strings = {
	VERSION = "CastProgress |cff00ff00",
	OPTIONS = "CastProgress Options",
	UPDATE = "Updating to CastProgress ",
	NEW = "CastProgress new player: ",
	
	CASTTIME = "Show Progress as Time",
	UISCALE = "Use UI Scale",
	SAMESCALE = "Use One Scale",
	PROGRESS = "Hide Cast Progress",
	TITLE = "Hide Cast Title",
	CASTBAR = "Show Cast Bar",
	TITLESCALE = "Title Scale",
	PROGRESSSCALE = "Progress Scale",
	BARSCALE = "Casting Bar Scale",
	OPACITY = "Opacity",
	ADDONMENU = "Enable Addon Menu",
	ADDONMENU_DISABLE = "This change will take effect when the game is restarted (or /console reloadui)",
	JUSTIFY = "Title Justify",
	PJUSTIFY = "Progress Justify",
	STICKY = "Sticky Frames",
}