CCWATCH_VERSION = "10900.4"
CCWATCH_FULLVERSION = "CCWatch v"..CCWATCH_VERSION

-- EN

CCWATCH_DESCRIPTION = "Allow to monitor Crowd Control effects, for any class."

CCWATCH_PROFILE_TEXT = "Profile: "

CCWATCH_EFFECT = "Effect"
CCWATCH_NAME = "Name"
CCWATCH_DURATION = "Duration"
CCWATCH_RESET = "New"
CCWATCH_ADD = "Add"
CCWATCH_MODIFY = "Modify"
CCWATCH_EDIT = "Edit"
CCWATCH_DELETE = "Delete"
CCWATCH_LEARN_DELETE_PROMPT = "Are you sure you want to delete the effect "
CCWATCH_REMOVED_NOTICE = "Removed skill effect : "
CCWATCH_TYPE = "Type"
CCWATCH_GROUP = "Group"
CCWATCH_DR = "DR"
CCWATCH_MONITOR = "Monitor"
CCWATCH_WARN = "Warn"
CCWATCH_ADDEDMODIFIED = " added/modified."

CCWATCH_OPTIONS_BARS_TAB = "Bars"
CCWATCH_OPTIONS_EFFECTS_TAB = "Monitoring"
CCWATCH_OPTIONS_LEARN_TAB = "Skills"

CCWATCH_OPTIONS_TITLE = "CCWatch Options"
CCWATCH_OPTIONS_TRANS = "Transparency"
CCWATCH_OPTIONS_SCALE = "Scaling"
CCWATCH_OPTIONS_DONE = "Done"
CCWATCH_OPTIONS_UNLOCK = "Unlock"
CCWATCH_OPTIONS_WIDTH = "Width"
CCWATCH_OPTIONS_INVERT = "Invert"
CCWATCH_OPTIONS_LEADINGTIMER = "Leading Timer"
CCWATCH_OPTIONS_ARCANIST = "Arcanist' Set"

CCWATCH_OPTIONS_WARN_APPLIED = "Applied"
CCWATCH_OPTIONS_WARN_FADED = "Faded"
CCWATCH_OPTIONS_WARN_BROKEN = "Broken"
CCWATCH_OPTIONS_WARN_LOWTIME = "Low Time"

CCWATCH_OPTIONS_MAGE = "Mage"
CCWATCH_OPTIONS_PRIEST = "Priest"
CCWATCH_OPTIONS_DRUID = "Druid"
CCWATCH_OPTIONS_HUNTER = "Hunter"
CCWATCH_OPTIONS_PALADIN = "Paladin"
CCWATCH_OPTIONS_WARLOCK = "Warlock"
CCWATCH_OPTIONS_WARRIOR = "Warrior"
CCWATCH_OPTIONS_ROGUE = "Rogue"
CCWATCH_OPTIONS_SHAMAN = "Shaman"
CCWATCH_OPTIONS_MISC = "Other"

CCWATCH_OPTION_STYLE_CURRENT = "Current target"
CCWATCH_OPTION_STYLE_RECENT = "Recent targets"
CCWATCH_OPTION_STYLE_ALL = "Any Creature/Enemy"

CCWATCH_OPTION_GROWTH_OFF = "Growth Off"
CCWATCH_OPTION_GROWTH_UP = "Growth Down->Up"
CCWATCH_OPTION_GROWTH_DOWN = "Growth Up->Down"

CCWATCH_OPTION_TIMERS_OFF = "Timers Off"
CCWATCH_OPTION_TIMERS_ON = "Timers On"
CCWATCH_OPTION_TIMERS_REVERSE = "Rev. Timers"

CCWATCH_OPTION_DR_NEVER = "Never"
CCWATCH_OPTION_DR_MOBPLAYERS = "Mob+Players"
CCWATCH_OPTION_DR_PLAYERS = "Players"

CCWATCH_OPTIONS_MONITOR_CC = "Monitor CC"
CCWATCH_OPTIONS_MONITOR_DEBUFF = "Monitor Debuffs"
CCWATCH_OPTIONS_MONITOR_BUFF = "Monitor Buffs"

CCWATCH_OPTIONS_COLOROVERTIME = "Use coloration over time"
CCWATCH_OPTIONS_USECOLOR = "Specify color"

CCWATCH_WARN_EMOTE = "announces that ";
CCWATCH_WARN_LOWTIME = "[%s] will no more be afflicted by [%s] in %d seconds."
CCWATCH_WARN_APPLIED = "[%s] is now afflicted by [%s]."
CCWATCH_WARN_FADED = "[%s] is no more afflicted by [%s] (faded)."
CCWATCH_WARN_BROKEN = "[%s] is no more afflicted by [%s] (broken)."

-- Priest
CCWATCH_SHACKLE = "Shackle Undead"
CCWATCH_PSYCHICSCREAM = "Psychic Scream"
CCWATCH_BLACKOUT = "Blackout"
CCWATCH_SHADOWWORDPAIN = "Shadow Word: Pain"
CCWATCH_POWERWORDSHIELD = "Shadow Word: Shield"
CCWATCH_DEVOURINGPLAGUE = "Devouring Plague"
CCWATCH_WEAKENEDSOUL = "Weakened Soul"
CCWATCH_RENEW ="Renew"
CCWATCH_HOLYFIRE = "Holy Fire"
CCWATCH_POWERINFUSION = "Power Infusion"

-- Mage
CCWATCH_POLYMORPH = "Polymorph"
CCWATCH_FROSTNOVA = "Frost Nova"
CCWATCH_FROSTBITE = "Frostbite"
CCWATCH_ICEBLOCK = "Ice Block"
CCWATCH_FROSTBOLT = "Frostbolt"
CCWATCH_CONEOFCOLD = "Cone of cold"
CCWATCH_COUNTERSPELL = "Counterspell - Silenced"
CCWATCH_FIREBALL = "Fireball"
CCWATCH_PYROBLAST = "Pyroblast"
CCWATCH_IGNITE = "Ignite"
CCWATCH_FLAMESTRIKE = "Flamestrike"
CCWATCH_BLASTWAVE = "Blast Wave"
CCWATCH_FROSTARMOR = "Transi"
CCWATCH_DETECTMAGIC = "Detect Magic"
CCWATCH_EVOCATION = "Evocation"
CCWATCH_ARCANEPOWER = "Arcane Power"

-- Paladin
CCWATCH_HOJ = "Hammer of Justice"
CCWATCH_TURNUNDEAD = "Turn Undead"
CCWATCH_REPENTANCE = "Repentance"
CCWATCH_DIVINESHIELD = "Divine Shield"
CCWATCH_BOPROTECTION = "Blessing of Protection"
CCWATCH_BOFREEDOM = "Blessing of Freedom"

-- Warlock
CCWATCH_FEAR = "Fear"
CCWATCH_BANISH = "Banish"
CCWATCH_SEDUCE = "Seduction"
CCWATCH_HOWLOFTERROR = "Howl of Terror"
CCWATCH_DEATHCOIL = "Death Coil"
CCWATCH_IMMOLATE = "Immolate"
CCWATCH_CORRUPTION = "Corruption"
CCWATCH_CURSEOFRECKLESSNESS = "Curse of Recklessness"
CCWATCH_CURSEOFAGONY = "Curse of Agony"
CCWATCH_CURSEOFWEAKNESS = "Curse of Weakness"
CCWATCH_CURSEOFTONGUES = "Curse of Tongues"
CCWATCH_CURSEOFSHADOW = "Curse of Shadow"
CCWATCH_CURSEOFELEMENTS = "Curse of the Elements"
CCWATCH_CURSEOFEXHAUSTION = "Curse of Exhaustion"
CCWATCH_CURSEOFDOOM = "Curse of Doom"
CCWATCH_SIPHONLIFE = "Siphon Life"
CCWATCH_IMPROVEDSHADOWBOLT = "Improved Shadow Bolt"
CCWATCH_SACRIFICE = "Sacrifice"
CCWATCH_SPELLSTONE = "Spellstone"
CCWATCH_SPELLLOCK = "Spell Lock"


-- Druid
CCWATCH_HIBERNATE = "Hibernate"
CCWATCH_ROOTS = "Entangling Roots"
CCWATCH_POUNCE = "Pounce"
CCWATCH_BASH = "Bash"
CCWATCH_FERALCHARGE = "Feral Charge"
CCWATCH_IMPSTARFIRE = "Improved Starfire"
CCWATCH_MOONFIRE = "Moonfire"
CCWATCH_INSECTSWARM = "Insect Swarm"
CCWATCH_NATURESGRASP = "Nature's Grasp"
CCWATCH_REJUVENATION = "Rejuvenation"
CCWATCH_DASH = "Dash"
CCWATCH_FAERIEFIRE = "Faerie Fire"
CCWATCH_FAERIEFIREFERAL = "Faerie Fire (Feral)"
CCWATCH_INSECTSWARM = "Insect Swarm"
CCWATCH_INNERVATE = "Innervate"
CCWATCH_BARKSKIN = "Barkskin"
CCWATCH_REGROWTH = "Regrowth"
CCWATCH_FREGEN = "Frenzied Regeneration"


-- Hunter
CCWATCH_FREEZINGTRAP = "Freezing Trap Effect"
CCWATCH_FREEZINGTRAP_SPELL = "Freezing Trap"
CCWATCH_SCAREBEAST = "Scare Beast"
CCWATCH_IMPCS = "Improved Concussive Shot"
CCWATCH_SCATTERSHOT = "Scatter Shot"
CCWATCH_INTIMIDATION = "Intimidation"
CCWATCH_COUNTERATTACK = "Counterattack"
CCWATCH_WYVERNSTING = "Wyvernsting"
CCWATCH_IMPROVEDWINGCLIP = "Improved Wingclip"
CCWATCH_ENTRAPMENT = "Entrapment"
CCWATCH_SERPENTSTING = "Serpent Sting"
CCWATCH_DETERRENCE = "Deterrence"
CCWATCH_RAPIDFIRE = "Rapid Fire"

-- Warrior
CCWATCH_INTERCEPT = "Intercept Stun"
CCWATCH_MACESPE = "Mace Specialization"
CCWATCH_IMPHAMSTRING = "Improved Hamstring"
CCWATCH_INTIMIDATINGSHOUT = "Intimidating Shout"
CCWATCH_IMPREVENGE = "Revenge Stun"
CCWATCH_CONCUSSIONBLOW = "Concussion Blow"
CCWATCH_BERSERKERRAGE = "Berserker Rage"
CCWATCH_BLOODRAGE = "Bloodrage"
CCWATCH_REND = "Rend"
CCWATCH_DISARM = "Disarm"
CCWATCH_LASTSTAND = "Last Stand"
CCWATCH_RETALIATION = "Retaliation"
CCWATCH_SHIELDWALL = "Shield Wall"
CCWATCH_DEATHWISH = "Death Wish"
CCWATCH_IMPSHIELDBASH = "Shield Bash - Silenced"
CCWATCH_MORTALSTRIKE = "Mortal Strike"
CCWATCH_RECKLESSNESS = "Recklessness"
CCWATCH_HAMSTRING = "Hamstring"

--Rogue
CCWATCH_GOUGE = "Gouge"
CCWATCH_BLIND = "Blind"
CCWATCH_KS = "Kidney Shot"
CCWATCH_CS = "Cheap Shot"
CCWATCH_SAP = "Sap"
CCWATCH_RUPTURE = "Rupture"
CCWATCH_GAROTTE = "Garrote"
CCWATCH_RIPOSTE = "Riposte"
CCWATCH_IMPROVEDKICK = "Kick - Silenced"
CCWATCH_ADRENALINERUSH = "Adrenaline Rush"
CCWATCH_EVASION = "Evasion"
CCWATCH_ROGUESPRINT = "Sprint"
CCWATCH_BLADEFLURRY = "Blade Flurry"
CCWATCH_CRIPPLINGP = "Crippling Poison"
CCWATCH_DEADLYP = "Deadly Poison"

-- Shaman
CCWATCH_FROSTSHOCK = "Frost Shock"
CCWATCH_FLAMESHOCK = "Flame Shock"
CCWATCH_FROSTBRANDWEAPON = "Frostbrand Weapon"
CCWATCH_STORMSTRIKE = "Stormstrike"

-- Miscellaneous
CCWATCH_WARSTOMP = "War Stomp"
CCWATCH_SLEEP = "Sleep"
CCWATCH_NETOMATIC = "Net-o-Matic"
CCWATCH_ROCKETHELM = "Reckless Charge"

CCWATCH_WOTF = "Will of the Forsaken"
CCWATCH_PERCEPTION = "Perception"

CCWATCH_RANK = "rank"
CCWATCH_DETECTED = "detected"
CCWATCH_NOTDETECTED = "not detected"

CCWATCH_ENABLED = "CCWatch enabled"
CCWATCH_DISABLED = "CCWatch disabled"

CCWATCH_LOCKED = "CCWatch locked"
CCWATCH_UNLOCKED = "CCWatch unlocked"

CCWATCH_INVERSION_ON = "CCWatch inversion on"
CCWATCH_INVERSION_OFF = "CCWatch inversion off"

CCWATCH_STYLE_CURRENT = "Monitoring current target only"
CCWATCH_STYLE_RECENT = "Monitoring recent targets"
CCWATCH_STYLE_ALL = "Monitoring ALL TARGETS"

CCWATCH_GROW_OFF = "CCWatch bar growth off"
CCWATCH_GROW_UP = "CCWatch bar growth up"
CCWATCH_GROW_DOWN = "CCWatch bar growth down"

CCWATCH_TIMERS_OFF = "Timers off"
CCWATCH_TIMERS_ON = "Timers on"
CCWATCH_TIMERS_REVERSE = "Reversed Timers"

CCWATCH_ARCANIST_ON = "Arcanist' Set activated (+15 sec to "..CCWATCH_POLYMORPH.." spell)"
CCWATCH_ARCANIST_OFF = "Arcanist' Set off"

CCWATCH_COLOROVERTIME_ON = "Bar coloration over time enabled"
CCWATCH_COLOROVERTIME_OFF = "Bar coloration over time disabled"
CCWATCH_LEADINGTIMER_ON = "Timer position: leading"
CCWATCH_LEADINGTIMER_OFF = "Timer position: trailing"
CCWATCH_WARNCC_SETTO = "Warning output set to: "
CCWATCH_WARNCC_CUSTOM = "Custom cc used (standard cc are EMOTE, SAY, PARTY, RAID, YELL): "
CCWATCH_WARN_DISABLED = "Chat alerts disabled"
CCWATCH_WARN_ENABLED = "Chat alerts enabled"

CCWATCH_SCALE = "CCWatch Scale set to "

CCWATCH_WIDTH = "CCWatch Width set to "

CCWATCH_ALPHA = "CCWatch Alpha set to "

CCWATCH_LOADED = " Loaded - /ccw (c)Elwen&phoenixfire2001"

CCWATCH_HELP1  = " : Usage - /ccw option"
CCWATCH_HELP2  = "options:"
CCWATCH_HELP3  = " on     : Enables CCWatch"
CCWATCH_HELP4  = " off    : Disables CCWatch"
CCWATCH_HELP5  = " lock   : Locks CCWatch and enables"
CCWATCH_HELP6  = " unlock : Allows you to move CCWatch"
CCWATCH_HELP7  = " u      : Update improved skill ranks"
CCWATCH_HELP8  = " print  : Prints the current configuration"
CCWATCH_HELP9  = " invert : Invert progress bar direction"
CCWATCH_HELP10 = " scale  : Scale CCWatch, use 0.25 to 3.0"
CCWATCH_HELP11 = " width  : Set bar width, use 50 to 300"
CCWATCH_HELP12 = " alpha  : Set bar alpha, use 0 to 1"
CCWATCH_HELP13 = " grow   : Set bar growth up, down or off"
CCWATCH_HELP14 = " config : Show the configuration frame"
CCWATCH_HELP15 = " timers : Set timers display off, on or rev (countdown)"
CCWATCH_HELP16 = " warn   : enable/disable chat warning"
CCWATCH_HELP17 = " warncc : set which communication channel to use (EMOTE, SAY, PARTY, RAID, YELL or custom)"
