--SHT globals

SHT_NUM_BARS = 11;
SHT_NUM_TIMERS = 33;
SHT_NUM_OPTIONS = 11;
SHT_NUM_LABELS = 12;
SHT_NUM_SLIDERS = 7;

SHT_OPTIONS_TIMERS = {
	[1] = SHT_AUTO_SHOT,
	[2] = SHT_AIMED_SHOT,
	[3] = SHT_HUNTERS_MARK,
	[4] = SHT_FLARE,
	[5] = SHT_CONC_SHOT,
	[6] = SHT_SCATTER,
	[7] = SHT_INTIM,
	[8] = SHT_BW,
	[9] = SHT_FEAR_BEAST,
	[10] = SHT_WING_CLIP,
	[11] = SHT_COUNTER,
	[12] = SHT_DETERRENCE,
	[13] = SHT_SERPENT,
	[14] = SHT_VIPER,
	[15] = SHT_SCORPID,
	[16] = SHT_WYVERN,
	[17] = SHT_FREEZING_TRAP,
	[18] = SHT_FROST_TRAP,
	[19] = SHT_EXPL_TRAP,
	[20] = SHT_IMMO_TRAP,
	[21] = SHT_ENTRAPMENT,
	[22] = SHT_FRENZY,
	[23] = SHT_RAPID_FIRE,
	[24] = SHT_BERSERKING,
	[25] = SHT_QUICK_SHOTS,
	[26] = SHT_EXPOSE_WEAKNESS,
	[27] = SHT_PRIMAL_BLESSING,
	[28] = SHT_DEVILSAUR,
	[29] = SHT_ZHM,
	[30] = SHT_EARTHSTRIKE,
	[31] = SHT_SWARMGUARD,
	[32] = SHT_JOM_GABBAR,
	[33] = SHT_KISS_SPIDER
};

SHT_OPTIONS_BARS = {
	[1] = SHT_OPTIONS_LOCK,
	[2] = SHT_OPTIONS_COLOR_CHANGE,
	[3] = SHT_OPTIONS_SHOW_TEX,
	[4] = SHT_OPTIONS_LARGE_TEX,
	[5] = SHT_OPTIONS_HIDE_GAP,
	[6] = SHT_OPTIONS_APPEND,
	[7] = SHT_OPTIONS_HIDE_PADDING,
	[8] = SHT_OPTIONS_HIDE_TEXT,
	[9] = SHT_OPTIONS_HIDE_TIME,
	[10] = SHT_OPTIONS_STICKY,
	[11] = SHT_OPTIONS_DOWN
};

SHT_OPTIONS_LABELS = {
	[1] = SHT_OPTIONS_BARS_TEXT,
	[2] = SHT_OPTIONS_BORDER,
	[3] = SHT_OPTIONS_BARSTART,
	[4] = SHT_OPTIONS_TEXT_COLOR,
	[5] = SHT_OPTIONS_BACKDROP,
	[6] = SHT_OPTIONS_BAREND,
	[7] = SHT_OPTIONS_TIME_COLOR,
	[8] = SHT_OPTIONS_AIMED_DELAY,
	[9] = SHT_OPTIONS_MILI,
	[10] = SHT_OPTIONS_SHOT_DELAY,
	[11] = SHT_OPTIONS_MILI,
	[12] = SHT_OPTIONS_TARGET_COLOR
};

SHT_OPTIONS_SLIDER = {
	[1] = SHT_OPTIONS_BAR_DIST,
	[2] = SHT_OPTIONS_SCALE,
	[3] = SHT_OPTIONS_DECIMALS,
	[4] = SHT_OPTIONS_FLASH,
	[5] = SHT_OPTIONS_STEP,
	[6] = SHT_OPTIONS_OVERALL_OPACITY,
	[7] = SHT_OPTIONS_BAR_THICKNESS
};

SHT_OPTIONS_SLIDER_ENDS = {
	[1] = {
		[1] = "0",
		[2] = "10"
	},
	[2] = {
		[1] = "50%",
		[2] = "150%"
	},
	[3] = {
		[1] = SHT_OFF,
		[2] = "3"
	},
	[4] = {
		[1] = SHT_OFF,
		[2] = "10"
	},
	[5] = {
		[1] = "0.01",
		[2] = "0.05"
	},
	[6] = {
		[1] = "0%",
		[2] = "100%"
	},
	[7] = {
		[1] = "10",
		[2] = "32"
	}
};
