
DART_CUSTOM_SETTINGS = {
	[1] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 0.75,
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["highlightalpha"] = 0.3,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\UD_Left_Segment",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["hidebg"] = true,
		["height"] = 522,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["alpha"] = 1,
		["width"] = 522,
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["name"] = "Texture 3",
		["parent"] = "UIParent",
		["xoffset"] = {
			[1] = "-385",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["scripts"] = {
		},
		["yoffset"] = {
			[1] = "-473",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[2] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 0.75,
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["scripts"] = {
		},
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["hidebg"] = true,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\UD_Middle_Segment",
		["height"] = 522,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightalpha"] = 0.3,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["fontsize"] = 16,
			["justifyH"] = 5,
			["attachto"] = 2,
			["height"] = 20,
			["xoffset"] = 0,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["alpha"] = 1,
		["width"] = 266,
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["name"] = "Texture 3",
		["parent"] = "UIParent",
		["xoffset"] = {
			[1] = "-1",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["yoffset"] = {
			[1] = "-473",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[3] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["parent"] = "UIParent",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["bgalpha"] = 1,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\UD_Right_Segment",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["hidebg"] = true,
		["height"] = 522,
		["scale"] = 0.75,
		["highlightalpha"] = 0.3,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 522,
		["alpha"] = 1,
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["name"] = "Texture 3",
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["xoffset"] = {
			[1] = "383",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["scripts"] = {
			[2] = "",
			[14] = "",
		},
		["yoffset"] = {
			[1] = "-473",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[4] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["parent"] = "UIParent",
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = -7,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
			[2] = "if GetNumPartyMembers() > 0 then\
DART_Show(ti)\
else\
DART_Hide(ti)\
end",
			[14] = "this:RegisterEvent(\"PARTY_MEMBERS_CHANGED\");",
		},
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\UD_Party",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["height"] = 266,
		["hide"] = true,
		["scale"] = 0.69,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["fontsize"] = 16,
			["justifyH"] = 5,
			["attachto"] = 2,
			["height"] = 20,
			["xoffset"] = 0,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["alpha"] = 1,
		["width"] = 522,
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightalpha"] = 0.3,
		["name"] = "Texture 3",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["xoffset"] = {
			[1] = "-385",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hidebg"] = true,
		["yoffset"] = {
			[1] = "-348",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[5] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = -7,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
			[2] = "if GetNumPartyMembers() > 0 then\
DART_Show(ti)\
else\
DART_Hide(ti)\
end",
			[14] = "this:RegisterEvent(\"PARTY_MEMBERS_CHANGED\");",
		},
		["hidebg"] = true,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["height"] = 266,
		["hide"] = true,
		["parent"] = "UIParent",
		["scale"] = 0.69,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 522,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 5",
		["bgalpha"] = 1,
		["xoffset"] = {
			[1] = "391",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\UD_Party",
		["yoffset"] = {
			[1] = "-348",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[6] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
			[2] = "if UnitExists(\"target\") then\
DART_Show(ti)\
else\
DART_Hide(ti)\
end",
			[14] = "this:RegisterEvent(\"PLAYER_TARGET_CHANGED\");",
		},
		["hidebg"] = true,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["height"] = 266,
		["hide"] = true,
		["parent"] = "UIParent",
		["scale"] = 0.45,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 522,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 6",
		["bgalpha"] = 1,
		["xoffset"] = {
			[1] = "-4",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\UD_Target",
		["yoffset"] = {
			[1] = "-300",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[7] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["scripts"] = {
			[2] = "",
			[14] = "",
		},
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\UD_Titan1",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["hidebg"] = true,
		["height"] = 42,
		["bgalpha"] = 1,
		["highlightalpha"] = 0.3,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["alpha"] = 0.8,
		["width"] = 522,
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["name"] = "Texture 7",
		["scale"] = 0.72,
		["xoffset"] = {
			[1] = "-413",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["parent"] = "UIParent",
		["yoffset"] = {
			[1] = "525",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[8] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 0.72,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["scripts"] = {
		},
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\UD_Titan2",
		["bgalpha"] = 1,
		["hidebg"] = true,
		["height"] = 42,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightalpha"] = 0.3,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["alpha"] = 0.8,
		["width"] = 522,
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["name"] = "Texture 8",
		["parent"] = "UIParent",
		["xoffset"] = {
			[1] = "98",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["yoffset"] = {
			[1] = "525",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[9] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 0.72,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = -12,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["scripts"] = {
		},
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\UD_Titan1",
		["bgalpha"] = 1,
		["hidebg"] = 1,
		["height"] = 42,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["highlightalpha"] = 0.3,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["alpha"] = 0.8,
		["width"] = 522,
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["name"] = "Texture 9",
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["xoffset"] = {
			[1] = "609",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["parent"] = "UIParent",
		["yoffset"] = {
			[1] = "525",
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[10] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 0.45,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = -12,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
			[2] = "",
			[14] = "",
		},
		["hide"] = true,
		["bgalpha"] = 1,
		["height"] = 42,
		["hidebg"] = 1,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightalpha"] = 0.3,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["fontsize"] = 16,
			["justifyH"] = 5,
			["attachto"] = 2,
			["height"] = 20,
			["xoffset"] = 0,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 522,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["alpha"] = 1,
		["name"] = "Texture 9",
		["parent"] = "UIParent",
		["xoffset"] = {
			[1] = -271.5798326049866,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Longbarshort.tga",
		["yoffset"] = {
			[1] = -622.2969327501969,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[11] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["parent"] = "UIParent",
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = -3,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
			[1] = "",
			[2] = "",
			[3] = "",
			[4] = "",
			[14] = "",
		},
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\partyframe1.tga",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["height"] = 266,
		["hidebg"] = true,
		["scale"] = 0.7,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["alpha"] = 1,
		["width"] = 522,
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightalpha"] = 0.3,
		["name"] = "Texture 11",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["xoffset"] = {
			[1] = 388.6336855272512,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hide"] = true,
		["yoffset"] = {
			[1] = -345.6673087208154,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[12] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 0.7,
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = -3,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
			[2] = "",
			[14] = "",
		},
		["hidebg"] = true,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["height"] = 266,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\partyframe1.tga",
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["parent"] = "UIParent",
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["fontsize"] = 16,
			["justifyH"] = 5,
			["attachto"] = 2,
			["height"] = 20,
			["xoffset"] = 0,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["alpha"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["width"] = 522,
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["highlightalpha"] = 0.3,
		["name"] = "Texture 11",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["xoffset"] = {
			[1] = -386.0063144727488,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hide"] = true,
		["yoffset"] = {
			[1] = -345.6873087208154,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[13] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["hidebg"] = true,
		["scripts"] = {
			[2] = "",
			[14] = "",
		},
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["height"] = 266,
		["parent"] = "UIParent",
		["hide"] = true,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["alpha"] = 1,
		["width"] = 522,
		["highlightalpha"] = 0.3,
		["scale"] = 0.4,
		["name"] = "Texture 13",
		["disablemouse"] = 1,
		["xoffset"] = {
			[1] = -11.63351200992611,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\targetframe.tga",
		["yoffset"] = {
			[1] = -336.3627596078402,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[14] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["parent"] = "UIParent",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["scripts"] = {
			[2] = "",
		},
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["hidebg"] = true,
		["bgalpha"] = 1,
		["height"] = 266,
		["hide"] = true,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["alpha"] = 1,
		["width"] = 522,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightalpha"] = 0.3,
		["name"] = "Texture 14",
		["scale"] = 0.5,
		["xoffset"] = {
			[1] = -866.2528239130974,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Segment1",
		["yoffset"] = {
			[1] = -641.9742191302777,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[15] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hidebg"] = true,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["height"] = 50,
		["hide"] = true,
		["parent"] = "UIParent",
		["scale"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 15",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "",
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[16] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hidebg"] = true,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["height"] = 50,
		["hide"] = true,
		["parent"] = "UIParent",
		["scale"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 16",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "",
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[17] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hidebg"] = true,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["height"] = 50,
		["hide"] = true,
		["parent"] = "UIParent",
		["scale"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 17",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "",
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[18] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hidebg"] = true,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["height"] = 50,
		["hide"] = true,
		["parent"] = "UIParent",
		["scale"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 18",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "",
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[19] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hidebg"] = true,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["height"] = 50,
		["hide"] = true,
		["parent"] = "UIParent",
		["scale"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 19",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "",
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[20] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["framelevel"] = 0,
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hidebg"] = true,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["height"] = 50,
		["hide"] = true,
		["parent"] = "UIParent",
		["scale"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 20",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "",
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	["updatespeed"] = 30,
	["INITIALIZED1.1"] = true,
	["optionsscale"] = 0.8,
	["INITIALIZED1.0d"] = true,
}