-- Version : English - Isharra

MYEQUIPMENT_NAME = "MyEquipment"
MYEQUIPMENT_DESCRIPTION = "Equipped items display"

MYEQUIPMENTFRAME_TITLE = "Equipment"

-- SLASHCOMMANDS
-- /me already taken by emote commands
MYEQUIPMENT_COMMANDS    = {"/myequipment", "/myequip", "/mq"}
MYEQUIPMENT_CMD_OPTIONS = {
	MYBAGS_CMD_OPT_TOGGLE,
	MYBAGS_CMD_OPT_NOESC,
	MYBAGS_CMD_OPT_COLUMNS,
	MYBAGS_CMD_OPT_GRAPHICS,
	MYBAGS_CMD_OPT_LOCK,
	MYBAGS_CMD_OPT_TITLE,
	MYBAGS_CMD_OPT_CASH,
	MYBAGS_CMD_OPT_BUTTONS,
	MYBAGS_CMD_OPT_BORDER,
	MYBAGS_CMD_OPT_PLAYERSEL,
	MYBAGS_CMD_OPT_AIOI,
	MYBAGS_CMD_OPT_SCALE,
	MYBAGS_CMD_OPT_STRATA,
	MYBAGS_CMD_OPT_ANCHOR,
	MYBAGS_CMD_RESET,
	MYBAGS_CMD_OPT_SLOTCOLOR,
}