--MACROFRAME_CHAR_LIMIT = "%d/"..MACRO_MAX_LETTERS.." Characters Used";
SUPERMACROFRAME_EXTEND_CHAR_LIMIT = "%d/"..EXTEND_MAX_LETTERS.." Characters Used";
SUPERMACROFRAME_SUPER_CHAR_LIMIT = "%d/"..SUPER_MAX_LETTERS.." Characters Used";
REGULAR="Regular";
SUPER="Super";
SAVE_MACRO = "Save Macro";
ENTER_EXTEND_LABEL = "Enter Extended LUA code:";
SAVE_EXTEND = "Save Extend";
DELETE_EXTEND = "Delete Extend";
SAVE_SUPERMACRO = "Save Super";
NEW_SUPERMACRO = "New Super";
DELETE_SUPERMACRO = "Delete Super";
SUPERMACRO_TITLE = "SuperMacro";
SUPERMACRO_BUTTON = "S\nU\nP\nE\nR\n-\nM\nA\nC\nR\nO";
SUPERMACRO_OPTIONS = "SM Options";
SUPERMACRO_NEW_ACCOUNT = "New account macro";
SUPERMACRO_NEW_CHARACTER = "New character macro";
SUPERMACRO_OPTIONS_TITLE = "SuperMacro Options";
SUPERMACRO_MINIMAP = "Open SuperMacro frame";

SM_HIDE_ACTION = "Hide names on action bars";
SM_MACRO_TIP_1 = "Show tooltip about spell or item";
SM_MACRO_TIP_2 = "Show tooltip about macro's script";
SM_PRINT_COLOR = "Output color of SM_print() and /print";
SM_PRINT_COLOR_EXAMPLE_TEXT = "Ex: Can you see me now?";
SM_MINIMAP = "Show minimap button";
SM_REPLACE_ICON = "Auto-replace action icons";
SM_CHECK_COOLDOWN = "Auto-check cooldown for actions";

--SLASH

SLASH_SUPERMACRO1 = "/supermacro";
SUPERMACRO_HELP_LINE1 = "just /supermacro to show help"
SUPERMACRO_HELP_LINE2 = "/macro <macro_name> to run a macro by name"
SUPERMACRO_HELP_LINE3 = "/supermacro hideaction 1 or 0 to hide or show macro names on action buttons"
SUPERMACRO_HELP_LINE4 = "/supermacro printcolor <red> <green> <blue>, each from 0 to 1 to change color used in /print"
SUPERMACRO_HELP_LINE5 = "/supermacro macrotip 0-3, 1 default"
SUPERMACRO_HELP_LINE6 = "0 is normal, 1 show spells, 2 show macro code, 3 show  spell and/or code"

SLASH_SMUSE1 = "/use";
SLASH_SMUSE2 = "/smuse";
SLASH_SMEQUIP1 = "/equip";
SLASH_SMEQUIP2 = "/smequip";
SLASH_SMEQUIP3 = "/eq";
SLASH_SMEQUIP4 = "/smeq";
SLASH_SMEQUIPOFF1 = "/equipoff";
SLASH_SMEQUIPOFF2 = "/smequipoff";
SLASH_SMEQUIPOFF3 = "/eqoff";
SLASH_SMEQUIPOFF4 = "/smeqoff";
SLASH_SMUNEQUIP1 = "/unequip";
SLASH_SMUNEQUIP2 = "/smunequip";
SLASH_SMUNEQUIP3 = "/uneq";
SLASH_SMUNEQUIP4 = "/smuneq";
SLASH_SMPRINT1 = "/print";
SLASH_SMPRINT2 = "/smprint";
SLASH_SMPASS1 = "/pass";
SLASH_SMPASS2 = "/smpass";
SLASH_SMFAIL1 = "/fail";
SLASH_SMFAIL2 = "/smfail";
SLASH_SMDOORDER1 = "/order";
SLASH_SMDOORDER2 = "/smorder";
SLASH_SMCHANNEL1 = "/smchan";
SLASH_SMCHANNEL2 = "/smchannel";
SLASH_SMIN1 = "/in";
SLASH_SMIN2 = "/smin";
SLASH_SMSHIFT1 = "/shift";
SLASH_SMSHIFT2 = "/smshift";
SLASH_SMCRAFT1 = "/craft";
SLASH_SMCRAFT2 = "/smcraft";
SLASH_SMCRAFT1 = "/craft";
SLASH_SMCRAFT2 = "/smcraft";
SLASH_SMSAYRANDOM1 = "/sayrandom";
SLASH_SMSAYRANDOM2 = "/smsayrandom";
SLASH_SMCANCELBUFF1 = "/unbuff";
SLASH_SMCANCELBUFF2 = "/smunbuff";

--BINDINGS

BINDING_HEADER_SUPERMACROHEADER = "SuperMacro";
BINDING_NAME_TOGGLESUPERMACRO = "Toggle SuperMacro Frame";
BINDING_NAME_OPENCHATSCRIPT = "Open Chat /script";
BINDING_NAME_OPENCHATMACRO = "Open Chat /macro";
BINDING_NAME_SM_ATTACK = "Attack";
BINDING_NAME_SM_PETATTACK = "PetAttack";
BINDING_NAME_SM_MACRO1 = "Macro 1";
BINDING_NAME_SM_MACRO2 = "Macro 2";
BINDING_NAME_SM_MACRO3 = "Macro 3";
BINDING_NAME_SM_MACRO4 = "Macro 4";
BINDING_NAME_SM_MACRO5 = "Macro 5";
BINDING_NAME_SM_MACRO6 = "Macro 6";
BINDING_NAME_SM_MACRO7 = "Macro 7";
BINDING_NAME_SM_MACRO8 = "Macro 8";
BINDING_NAME_SM_MACRO9 = "Macro 9";
BINDING_NAME_SM_MACRO10 = "Macro 10";
BINDING_NAME_SM_MACRO11 = "Macro 11";
BINDING_NAME_SM_MACRO12 = "Macro 12";
BINDING_NAME_SM_MACRO13 = "Macro 13";
BINDING_NAME_SM_MACRO14 = "Macro 14";
BINDING_NAME_SM_MACRO15 = "Macro 15";
BINDING_NAME_SM_MACRO16 = "Macro 16";
BINDING_NAME_SM_MACRO17 = "Macro 17";
BINDING_NAME_SM_MACRO18 = "Macro 18";
BINDING_NAME_SM_MACRO19 = "Macro 19";
BINDING_NAME_SM_MACRO20 = "Macro 20";
BINDING_NAME_SM_MACRO21 = "Macro 21";
BINDING_NAME_SM_MACRO22 = "Macro 22";
BINDING_NAME_SM_MACRO23 = "Macro 23";
BINDING_NAME_SM_MACRO24 = "Macro 24";
BINDING_NAME_SM_MACRO25 = "Macro 25";
BINDING_NAME_SM_MACRO26 = "Macro 26";
BINDING_NAME_SM_MACRO27 = "Macro 27";
BINDING_NAME_SM_MACRO28 = "Macro 28";
BINDING_NAME_SM_MACRO29 = "Macro 29";
BINDING_NAME_SM_MACRO30 = "Macro 30";
BINDING_NAME_SM_MACRO31 = "Macro 31";
BINDING_NAME_SM_MACRO32 = "Macro 32";
BINDING_NAME_SM_MACRO33 = "Macro 33";
BINDING_NAME_SM_MACRO34 = "Macro 34";
BINDING_NAME_SM_MACRO35 = "Macro 35";
BINDING_NAME_SM_MACRO36 = "Macro 36";
BINDING_NAME_SM_SUPERMACRO1 = "SuperMacro 1";
BINDING_NAME_SM_SUPERMACRO2 = "SuperMacro 2";
BINDING_NAME_SM_SUPERMACRO3 = "SuperMacro 3";
BINDING_NAME_SM_SUPERMACRO4 = "SuperMacro 4";
BINDING_NAME_SM_SUPERMACRO5 = "SuperMacro 5";
BINDING_NAME_SM_SUPERMACRO6 = "SuperMacro 6";
BINDING_NAME_SM_SUPERMACRO7 = "SuperMacro 7";
BINDING_NAME_SM_SUPERMACRO8 = "SuperMacro 8";
BINDING_NAME_SM_SUPERMACRO9 = "SuperMacro 9";
BINDING_NAME_SM_SUPERMACRO10 = "SuperMacro 10";
