local L = AceLibrary("AceLocale-2.2"):new("XLoot")

L:RegisterTranslations("zhTW", function() 
	return {
		catSnap = "框架吸附設定",
		catLoot = "物品拾取設定",
		catFrame = "框架設定",
		catInfo = "拾取訊息",
		catGeneralAppearance = "一般表現",
		catFrameAppearance = "框架表現",
		catLootAppearance = "拾取物品表現",
		catExtras = "額外",
		
		optLock = "鎖定",
		optOptions = "設定界面",
		optBehavior = "行為設定",
		optCursor = "吸附滑鼠",
		optSmartsnap = "快速吸附",
		optSnapoffset = "吸附後滑鼠偏移坐標值",
		optCollapse = "Collapse loot buttons",
		optDragborder = "可移動邊框",
		optLootexpand = "以文字長度調整視窗長度",
		optAltoptions = "當Alt+RightClick顯示菜單",
		optSwiftloot = "當Shift-Cick時不顯示視窗",
		optQualitytext = "顯示物品品質",
		optInfotext = "顯示物品訊息",
		optLinkAll = "顯示所有的鏈接按鈕",
		optLinkAllVis = "可見: ",
		optLinkAllThreshold = "發佈高於定義等級的物品",
		optLinkAllChannels = "總是發佈物品到...",
		optAppearance = "外觀",
		optQualityborder = "邊框著色",
		optQualityframe = "背景著色",
		optLootqualityborder = "內邊框著色",
		optBgcolor = "整體背景著色",
		optBordercolor = "整體邊框著色",
		optTexColor = "物品圖標著色",
		optHighlightLoot = "高亮拾取",
		optHighlightThreshold = "高亮條件設定", 
		optLootbgcolor = "拾取框背景著色",
		optLootbordercolor = "拾取框邊框著色",
		optInfoColor = "訊息顏色",
		optScale = "縮放",
		optAdvanced = "高級選項",
		optDebug = "Debug 訊息",
		optDefaults = "恢復預設",
		
		descLock = "Makes loot frame unmoveable",
		descOptions = "Show the options dropdown",
		descBehavior = "Change how XLoot behaves",
		descCursor = "Snap the loot frame to the cursor whenever you loot something",
		descSmartsnap = "Snaps the loot frame only vertically to the cursor when the list shifts as you loot a item so it doesn't jump around",
		descSnapoffset = "Sets a distance from the middle of the first loot icon to snap to, horizontally",
		descCollapse = "Collapse looted (empty) buttons and place cursor over next frame if the Cursor option is enabled.",
		descDragborder = "Allows the loot window to be moved by dragging the frame's border, instead of just the buttons, which can otherwise be clicked through",
		descLootexpand = "Changes frame width to match loot names. Short names mean thin frames, long names make the frames widen",
		descAltoptions = "Allows you to Alt+RightClick on loot to bring up the XLoot menu. Can be disabled to not mess with other mods.",
		descSwiftloot = "Attempts to find out when loot is being shift-rightclick-looted, and never shows the frame if there is space for all items. Should reduce lag when shift-looting, disable if you run into problems.",
		descQualitytext = "Show a additional line above the item name with the item's Quality",
		descInfotext = "Show a addition line below the item name with the item's Information",
		descLinkAll = "The Link All button, a button that pops up a menu with all available channels, letting you send the current open loot to any of them.",
		descLinkAllVis = "When the Link All button should be visible",
		descLinkAllThreshold = "Only link items higher than the threshold.",
		descLinkAllChannels = "Always link to these channels when left-clicking Link All. |cFFFF0000If none are checked, left-clicking Link All will show the Link All menu.|r",
		descAppearance = "Coloring, scaling, and skin of XLootFrame and each individual loot button",
		descQualityborder = "Colors lootframe border by the highest quality item",
		descQualityframe = "Colors lootframe background by the highest quality item",
		descLootqualityborder = "Colors loot borders by quality",
		descHighlightLoot = "Highlights each loot frame by quality",
		descHighlightThreshold = "The minimum quality at which loot frames will be highlighted",
		descBgcolor = "Change the background color for the loot frame itself",
		descBordercolor = "Change the border color of the frame itself",
		descTexColor = "Color the border of the actual item icon/texture by quality",
		descLootbgcolor = "Change the background color for every loot item",
		descLootbordercolor = "Change the border color of every loot item",
		descInfoColor = "Change the color of the information text",
		descScale = "Scale of the loot frame",
		descAdvanced = "Options you may not want to mess with, but can anyway.",
		descDebug = "Show debug messages",
		descDefaults = "Reinstate the database that comes with XLoot and set all the options back to their defaults",
		
		qualityQuest = "任務物品",
		
		guiTitle = "XLoot設定",
		
		itemWeapon = "武器",
		
		evHerbs = "草藥採集",
		evOpenNT = "Opening - No Text",
		evOpen = "打開",
		
		linkallloot = "連結所有...",
		linkallchanneldesc = "當點選左鍵時，自動發佈所有物品到 %s",
		}
end)