BINDING_NAME_UBERQUEST_SHOWMINION_KEYBIND = "Show/Hide Questminion"

UBERQUEST_ABANDON		= "Abandon Quest"
UBERQUEST_SHARE			= "Share"
UBERQUEST_CONFIG		= "Config"
UBERQUEST_SUMMONMINION		= "Summon Minion"
UBERQUEST_DISMISSMINION		= "Dismiss Minion"
UBERQUEST_EXIT			= "Exit"

UBERQUEST_QLEVELS		= "Show Quest Levels"
UBERQUEST_QLEVELS_TOOLTIP	= "Show Quest Levels"
UBERQUEST_QMINION		= "Use Quest Minion"
UBERQUEST_QMINION_TOOLTIP	= "Use Quest Minion"
UBERQUEST_LMINION		= "Lock Minion"
UBERQUEST_LMINION_TOOLTIP	= "Locks the Minion so it is not movable and allows 'click-throughs'\nNote: This option is by character"
UBERQUEST_ADD_QMINION		= "Add new quests to Minion"
UBERQUEST_ADD_QMINION_TOOLTIP	= "Add new quests to Minion"
UBERQUEST_COL_MINION		= "Colorize Objectives in Minion"
UBERQUEST_COL_MINION_TOOLTIP	= "Colorize Objectives in Minion"
UBERQUEST_COQ_MINION		= "Clear Completed Quests"
UBERQUEST_COQ_MINION_TOOLTIP	= "Clears Completed Quests Automaticly"
UBERQUEST_COMO_MINION		= "Clears Completed Objectives"
UBERQUEST_COMO_MINION_TOOLTIP	= "Clears completed quest objectives in the minion"
UBERQUEST_NOTEXT		= "Don't Show Text in Empty Minion"
UBERQUEST_NOTEXT_TOOLTIP	= "Text is hidden when no quests are in the Minion\nUseful if you've set the Minion's transparency to zero"

UBERQUEST_QSPEED		= "Speed Quest text display"
UBERQUEST_QSPEED_TOOLTIP	= "Speed Quest text display"
UBERQUEST_BG_MINION		= "Select Background of Minion"
UBERQUEST_SAVE			= "Close and Save"
UBERQUEST_MINION_NOQUESTS	= "No selected quests"
UBERQUEST_QCOMPLETE		= "Complete"
UBERQUEST_LOADED		= "loaded"

UBERQUEST_MINIONSCALE		= "Scale of Minion"
UBERQUEST_MINIONSCALE_TOOLTIP	= "Scales the Questminion from 50 to 150 percent"
UBERQUEST_MINIONREST		= "Reset Minion"
