-- Originally based on the table at http://www.goodintentionsguild.info/hunters.html

FHH_BeastInfo = {
	
	["Agam'ar"] = { charge = 3, },
	["Aku'mai Fisher"] = { bite = 3, shell = 1, },
	["Aku'mai Snapjaw"] = { bite = 4, shell = 1, },
	["Angerclaw Mauler"] = { claw = 7, },
	["Arash-ethis"] = { dive = 2, lightning = 5, },
	["Ashenvale Bear"] = { claw = 3, },
	["Ashmane Boar"] = { charge = 5, },
	["Barbed Crustacean"] = { claw = 4, },
	["Barnabus"] = { bite = 6, },
	["Battleboar"] = { charge = 1, },
	["Bellygrub"] = { charge = 3, },
	["Besseleth"] = { bite = 3, },
	["Bhag'Thera"] = { dash = 2, },
	["Bjarn"] = { claw = 2, },
	["Black Bear Patriarch"] = { claw = 3, },
	["Black Ravager Mastiff"] = { howl = 2, bite = 4, },
	["Black Ravager"] = { bite = 4, },
	["Blackrock Worg"] = { dash = 3, },
	["Blind Hunter"] = { cower = 3, },
	["Blisterpaw Hyena"] = { dash = 2, },
	["Bloodaxe Worg"] = { bite = 8, howl = 4, dash = 3, },
	["Bloodsnout Worg"] = { bite = 3, },
	["Bonepaw Hyena"] = { dash = 1, },
	["Bristleback Battleboar"] = { charge = 1, },
	["Broken Tooth"] = { dash = 1, },
	["Carrion Vulture"] = { dive = 3, screech = 3, },
	["Clack the Reaver"] = { poison = 3, claw = 7, },
	["Clattering Crawler"] = { claw = 3, },
	["Cloud Serpent"] = { lightning = 3, },
	["Corrupted Mottled Boar"] = { charge = 1, },
	["Corrupted Scorpid"] = { poison = 1, },
	["Coyote Packleader"] = { howl = 1, bite = 2, },
	["Coyote"] = { bite = 2, },
	["Crag Boar"] = { charge = 1, },
	["Crag Coyote"] = { dash = 1, bite = 5, },
	["Crag Stalker"] = { cower = 3, },
	["Darkfang Creeper"] = { bite = 5, },
	["Darkfang Lurker"] = { bite = 5, },
	["Darkfang Spider"] = { bite = 5, },
	["Deadmire"] = { bite = 6, },
	["Deadly Cleft Scorpid"] = { poison = 3, },
	["Death Flayer"] = { poison = 1, claw = 2, },
	["Death Howl"] = { howl = 3, bite = 6, },
	["Deathlash Scorpid"] = { poison = 3, claw = 7, },
	["Deathstrike Tarantula"] = { bite = 6, },
	["Deepmoss Creeper"] = { bite = 3, },
	["Deepmoss Webspinner"] = { bite = 3, },
	["Den Mother"] = { claw = 3, },
	["Deviate Coiler"] = { lightning = 2, },
	["Deviate Crocolisk"] = { bite = 3, },
	["Deviate Dreadfang"] = { lightning = 2, },
	["Deviate Stinglash"] = { lightning = 2, },
	["Deviate Venomwing"] = { lightning = 2, },
	["Dire Mottled Boar"] = { charge = 1, },
	["Diseased Grizzly"] = { claw = 7, },
	["Diseased Wolf"] = { bite = 7, },
	["Dread Flyer"] = { dive = 1, },
	["Dread Ripper"] = { screech = 2, },
	["Dreadmaw Crocolisk"] = { bite = 1, },
	["Drywallow Crocolisk"] = { bite = 5, },
	["Drywallow Daggermaw"] = { bite = 6, },
	["Drywallow Snapper"] = { claw = 5, },
	["Durotar Tiger"] = { cower = 1, },
	["Elder Ashenvale Bear"] = { claw = 4, },
	["Elder Cloud Serpent"] = { lightning = 3, },
	["Elder Crag Boar"] = { charge = 1, },
	["Elder Crag Coyote"] = { howl = 2, dash = 1, },
	["Elder Mistvale Gorilla"] = { thunderstomp = 2, },
	["Elder Moss Creeper"] = { bite = 4, },
	["Elder Mottled Boar"] = { charge = 1, },
	["Elder Mountain Boar"] = { charge = 2, },
	["Elder Plainstrider"] = { cower = 1, },
	["Elder Shadowmaw Panther"] = { dash = 2, prowl = 2, },
	["Elder Shardtooth"] = { claw = 8, },
	["Encrusted Surf Crawler"] = { claw = 2, },
	["Felpaw Ravager"] = { bite = 7, },
	["Felpaw Wolf"] = { howl = 3, bite = 6, },
	["Feral Crag Coyote"] = { dash = 1, },
	["Feral Mountain Lion"] = { cower = 3, },
	["Ferocious Grizzled Bear"] = { claw = 2, },
	["Fire Roc"] = { dive = 2, },
	["Firetail Scorpid"] = { poison = 4, },
	["Flatland Cougar"] = { cower = 1, },
	["Fleeting Plainstrider"] = { cower = 1, },
	["Forest Lurker"] = { bite = 2, },
	["Forest Moss Creeper"] = { bite = 3, },
	["Forest Spider"] = { bite = 1, },
	["Foreststrider Fledgling"] = { cower = 1, },
	["Frostsaber Cub"] = { cower = 6, },
	["Frostsaber Huntress"] = { dash = 3, },
	["Frostsaber Stalker"] = { dash = 3, prowl = 3, },
	["Ghamoo-Ra"] = { bite = 4, shell = 1, },
	["Ghostpaw Alpha"] = { howl = 2, bite = 4, },
	["Ghostpaw Runner"] = { bite = 3, },
	["Giant Foreststrider"] = { cower = 2, },
	["Giant Moss Creeper"] = { bite = 4, },
	["Giant Plains Creeper"] = { bite = 5, },
	["Giant Surf Glider"] = { bite = 7, shell = 1, },
	["Giant Webwood Spider"] = { bite = 2, },
	["Giant Wetlands Crocolisk"] = { bite = 4, },
	["Githyiss the Vile"] = { bite = 1, },
	["Goretusk"] = { charge = 2, },
	["Gray Bear"] = { claw = 3, },
	["Gray Forest Wolf"] = { bite = 1, },
	["Great Goretusk"] = { charge = 2, },
	["Greater Duskbat"] = { cower = 1, },
	["Greater Fleshripper"] = { screech = 1, },
	["Greater Tarantula"] = { bite = 3, },
	["Greater Thunderhawk"] = { lightning = 2, },
	["Green Recluse"] = { bite = 3, },
	["Groddoc Thunderer"] = { thunderstomp = 2, },
	["Grunter"] = { dash = 2, },
	["Hakkari Frostwing"] = { dive = 3, lightning = 5, },
	["Hakkari Sapper"] = { dive = 3, lightning = 5, },
	["Hulking Mountain Lion"] = { prowl = 1, },
	["Ice Claw Bear"] = { claw = 1, },
	["Ironback"] = { bite = 7, shell = 1, },
	["Ironbeak Hunter"] = { dive = 3, claw = 7, },
	["Ironbeak Owl"] = { dive = 2, screech = 3, },
	["Ironbeak Screecher"] = { dive = 3, },
	["Ironfur Bear"] = { claw = 6, },
	["Ironfur Patriarch"] = { claw = 7, },
	["Jaguero Stalker"] = { cower = 5, prowl = 3, },
	["Jungle Thunderer"] = { thunderstomp = 1, },
	["Juvenile Snow Leopard"] = { cower = 1, },
	["King Bangalash"] = { dash = 2, claw = 6, },
	["Kraul Bat"] = { cower = 3, dive = 1, },
	["Krellack"] = { poison = 4, },
	["Kresh"] = { shell = 1, bite = 3 },
	["Kurzen War Tiger"] = { dash = 1, },
	["Lady Sathrah"] = { bite = 2, },
	["Large Crag Boar"] = { charge = 1, },
	["Loch Crocolisk"] = { bite = 2, },
	["Longsnout"] = { charge = 1, },
	["Longtooth Howler"] = { howl = 2, },
	["Longtooth Runner"] = { bite = 6, howl = 3, dash = 2, },
	["Lupos"] = { bite = 3, },
	["Magram Bonepaw"] = { dash = 1, },
	["Mangeclaw"] = { claw = 2, },
	["Mangy Mountain Boar"] = { charge = 2, },
	["Mangy Nightsaber"] = { cower = 1, },
	["Mazzranache"] = { cower = 1, },
	["Mesa Buzzard"] = { dive = 1, },
	["Mist Howler"] = { howl = 1, },
	["Mistvale Gorilla"] = { thunderstomp = 1, },
	["Monstrous Crawler"] = { claw = 6, },
	["Monstrous Plaguebat"] = { cower = 6, screech = 4, },
	["Moonstalker Runt"] = { cower = 1, },
	["Moonstalker Sire"] = { cower = 2, },
	["Mother Fang"] = { bite = 2, },
	["Mottled Boar"] = { charge = 1, },
	["Mottled Drywallow Crocolisk"] = { bite = 5, },
	["Mountain Boar"] = { charge = 1, },
	["Mountain Lion"] = { prowl = 1, },
	["Mudrock Snapjaw"] = { bite = 6, },
	["Mudrock Tortoise"] = { bite = 5, },
	["Naraxis"] = { bite = 4, },
	["Night Web Matriarch"] = { bite = 1, },
	["Night Web Spider"] = { bite = 1, },
	["Nightsaber"] = { cower = 1, },
	["Noxious Plaguebat"] = { cower = 5, },
	["Oasis Snapjaw"] = { bite = 2, },
	["Ol' Sooty"] = { claw = 3, },
	["Old Cliff Jumper"] = { dash = 2, bite = 6, },
	["Old Grizzlegut"] = { claw = 6, },
	["Olm the Wise"] = { dive = 3, screech = 3, claw = 7, },
	["Ornery Plainstrider"] = { cower = 2, },
	["Panther"] = { cower = 3, },
	["Plague Lurker"] = { bite = 7, },
	["Plaguebat"] = { cower = 5, dive = 3, },
	["Plagued Swine"] = { charge = 6, },
	["Plains Creeper"] = { bite = 5, },
	["Porcine Entourage"] = { charge = 1, },
	["Prairie Stalker"] = { bite = 1, },
	["Prairie Wolf Alpha"] = { howl = 1, bite = 2, },
	["Prairie Wolf"] = { bite = 1, },
	["Princess"] = { charge = 1, },
	["Prowler"] = { bite = 2, },
	["Pygmy Surf Crawler"] = { claw = 1, },
	["Rabid Blisterpaw"] = { dash = 2, },
	["Ragged Scavenger"] = { bite = 1, },
	["Raging Agam'ar"] = { charge = 3, },
	["Rak'shiri"] = { dash = 3, },
	["Ravage"] = { dash = 3, },
	["Rekk'tilac"] = { bite = 6, },
	["Ridge Huntress"] = { cower = 4, },
	["Ridge Stalker Patriarch"] = { dash = 2, prowl = 2, },
	["Ridge Stalker"] = { cower = 4, prowl = 1, },
	["Ripscale"] = { bite = 6, },
	["Roc"] = { dive = 2, },
	["Rockhide Boar"] = { charge = 1, },
	["Rogue Vale Screecher"] = { dive = 2, lightning = 4, },
	["Rotting Agam'ar"] = { charge = 3, },
	["Salt Flats Vulture"] = { screech = 2, },
	["Saltwater Snapjaw"] = { bite = 7, },
	["Sarkoth"] = { claw = 1, },
	["Savannah Patriarch"] = { cower = 2, },
	["Sawtooth Snapper"] = { bite = 6, },
	["Scarlet Tracking Hound"] = { dash = 1, },
	["Scarred Crag Boar"] = { charge = 1, },
	["Scorpashi Lasher"] = { poison = 2, claw = 5, },
	["Scorpashi Snapper"] = { poison = 2, claw = 4, },
	["Scorpashi Venomlash"] = { poison = 2, },
	["Scorpid Dunestalker"] = { poison = 3, },
	["Scorpid Hunter"] = { poison = 3, claw = 6, },
	["Scorpid Reaver"] = { poison = 2, claw = 4, },
	["Scorpid Tail Lasher"] = { poison = 3, },
	["Scorpid Terror"] = { poison = 2, },
	["Scorpid Worker"] = { claw = 1, },
	["Scorpok Stinger"] = { poison = 3, },
	["Sewer Beast"] = { bite = 7, },
	["Shadow Panther"] = { prowl = 1, },
	["Shanda the Spinner"] = { bite = 3, },
	["Shadowmaw Panther"] = { prowl = 1, },
	["Shardtooth Bear"] = { claw = 7, },
	["Shore Crawler"] = { claw = 3, },
	["Shrike Bat"] = { dive = 1, screech = 2, cower = 4, },
	["Silithid Creeper"] = { poison = 1, },
	["Silithid Swarmer"] = { poison = 1, },
	["Silt Crawler"] = { claw = 6, },
	["Silvermane Howler"] = { howl = 2, },
	["Silvermane Stalker"] = { dash = 2, },
	["Silvermane Wolf"] = { howl = 3, },
	["Sin'Dall"] = { dash = 1, },
	["Skittering Crustacean"] = { claw = 3, },
	["Small Crag Boar"] = { charge = 1, },
	["Snapjaw"] = { bite = 4, shell = 1, },
	["Snapping Crustacean"] = { claw = 3, },
	["Snarler"] = { howl = 3, bite = 6, },
	["Snow Tracker Wolf"] = { bite = 1, },
	["Son of Hakkar"] = { lightning = 6, },
	["Sparkleshell Snapper"] = { bite = 5, },
	["Spawn of Hakkar"] = { dive = 3, lightning = 5, },
	["Spiteflayer"] = { dive = 3, },
	["Sri'skulk"] = { bite = 1, },
	["Starving Blisterpaw"] = { dash = 2, },
	["Starving Mountain Lion"] = { cower = 2, },
	["Starving Winter Wolf"] = { bite = 2, },
	["Stonelash Flayer"] = { poison = 4, },
	["Stonelash Pincer"] = { poison = 4, },
	["Stonelash Scorpid"] = { poison = 3, },
	["Stonetusk Boar"] = { charge = 1, },
	["Stranglethorn Tiger"] = { dash = 1, },
	["Strigid Hunter"] = { claw = 2, },
	["Strigid Owl"] = { claw = 1, },
	["Swamp Jaguar"] = { dash = 1, },
	["Tarantula"] = { bite = 2, },
	["The Rake"] = { bite = 1, },
	["Thistle Bear"] = { claw = 2, },
	["Thistle Boar"] = { charge = 1, },
	["Thunderhawk Cloudscraper"] = { lightning = 2, },
	["Thunderhawk Hatchling"] = { lightning = 2, },
	["Tide Crawler"] = { claw = 2, },
	["Timber"] = { bite = 2, },
	["Timberweb Recluse"] = { bite = 6, },
	["Twilight Runner"] = { cower = 2, },
	["Uhk'loc"] = { bite = 7, },
	["U'cha"] = { thunderstomp = 3, },
	["Un'Goro Thunderer"] = { thunderstomp = 3, },
	["Vale Screecher"] = { dive = 2, lightning = 4, },
	["Venomous Cloud Serpent"] = { lightning = 3, },
	["Venomtail Scorpid"] = { poison = 1, claw = 2, },
	["Vicious Night Web Spider"] = { bite = 2, },
	["Vilebranch Raiding Wolf"] = { dash = 3, bite = 7, },
	["Vile Sting"] = { claw = 5, poison = 2, },
	["Washte Pawne"] = { lightning = 3, },
	["Webwood Silkspinner"] = { bite = 2, },
	["Webwood Venomfang"] = { bite = 1, },
	["Wildthorn Lurker"] = { bite = 4, },
	["Winter Wolf"] = { bite = 1, },
	["Winterspring Owl"] = { dive = 3, claw = 7, },
	["Winterspring Screecher"] = { dive = 3, screech = 4, claw = 8, },
	["Witherbark Broodguard"] = { bite = 6, },
	["Wood Lurker"] = { bite = 3, },
	["Worg"] = { howl = 1, bite = 2, },
	["Young Forest Bear"] = { claw = 2, },
	["Young Goretusk"] = { charge = 2, },
	["Young Mesa Buzzard"] = { dive = 1, },
	["Young Panther"] = { cower = 3, },
	["Young Stranglethorn Tiger"] = { cower = 3, },
	["Young Thistle Boar"] = { charge = 1, },
	["Zaricotl"] = { dive = 3, },

};
