FHH_BeastLevels = {
	["Agam'ar"] = { min=24, max=25, type="elite", },
	["Aku'mai Fisher"]				= { min=23, max=24, type="elite" },
	["Aku'mai Snapjaw"]				= { min=26, max=27, type="elite" },
	["Angerclaw Mauler"]			= { min=49, max=50, },
	["Arash-ethis"]					= { min=49, type="rare" },
	["Ashenvale Bear"]				= { min=21, max=22, },
	["Ashmane Boar"]				= { min=48, max=49, },
	["Barbed Crustacean"]			= { min=25, max=26, type="elite"},
	["Barnabus"]					= { min=38, },
	["Battleboar"] = { min=3, max=4, },
	["Bellygrub"] = { min=24, },
	["Besseleth"]					= { min=21, type="elite" },
	["Bhag'Thera"]					= { min=40, type="elite" },
	["Bjarn"]						= { min=12, type="rare" },
	["Black Bear Patriarch"]		= { min=16, max=17, },
	["Black Ravager Mastiff"]		= { min=25, max=26, },
	["Black Ravager"]				= { min=24, max=25, },
	["Blackrock Worg"]				= { min=54, max=55, },
	["Blind Hunter"]				= { min=32, type="elite" },
	["Blisterpaw Hyena"]			= { min=44, max=45, },
	["Bloodaxe Worg"]				= { min=56, max=57, },
	["Bloodsnout Worg"]				= { min=16, max=17, },
	["Bonepaw Hyena"]				= { min=33, max=35, },
	["Bristleback Battleboar"] = { min=4, max=5, },
	["Broken Tooth"]				= { min=37, type="rare" },
	["Carrion Vulture"]				= { min=50, max=52, },
	["Clack the Reaver"]			= { min=53, type="rare" },
	["Clattering Crawler"]			= { min=19, max=20, },
	["Cloud Serpent"]				= { min=25, max=26, },
	["Corrupted Mottled Boar"] = { min=10, max=11, },
	["Corrupted Scorpid"]			= { min=10, max=11, },
	["Coyote Packleader"]			= { min=11, max=12, },
	["Coyote"]						= { min=10, max=11, },
	["Crag Boar"] = { min=5, max=6, },
	["Crag Coyote"]					= { min=35, max=36, },
	["Crag Stalker"]				= { min=25, max=26, },
	["Darkfang Creeper"]			= { min=38, max=39, },
	["Darkfang Lurker"]				= { min=36, max=37, },
	["Darkfang Spider"]				= { min=35, max=36, },
	["Deadmire"]					= { min=45, },
	["Deadly Cleft Scorpid"] 		= { min=42, max=43, },
	["Death Flayer"]				= { min=11, type="rare" },
	["Death Howl"]				= { min=49, type="rare" },
	["Deathlash Scorpid"]			= { min=54, max=55, },
	["Deathstrike Tarantula"]		= { min=40, max=41, },
	["Deepmoss Creeper"]			= { min=16, max=17, },
	["Deepmoss Webspinner"]			= { min=19, max=21, },
	["Den Mother"]					= { min=19, },
	["Deviate Coiler"]				= { min=15, max=16, type="elite" },
	["Deviate Crocolisk"]			= { min=18, max=19, },
	["Deviate Dreadfang"]			= { min=20, max=21, type="elite" },
	["Deviate Stinglash"]			= { min=16, max=17, type="elite" },
	["Deviate Venomwing"]			= { min=20, max=21, type="elite" },
	["Dire Mottled Boar"] = { min=6, max=7, },
	["Diseased Grizzly"]			= { min=55, max=56, },
	["Diseased Wolf"]				= { min=53, max=54, },
	["Dread Flyer"]					= { min=36, max=37, },
	["Dread Ripper"]				= { min=39, max=40, },
	["Dreadmaw Crocolisk"]			= { min=9, max=11, },
	["Drywallow Crocolisk"]			= { min=35, max=36, },
	["Drywallow Daggermaw"]			= { min=40, max=41, type="elite"},
	["Drywallow Snapper"]			= { min=37, max=38, },
	["Durotar Tiger"]				= { min=4, max=9, },
	["Elder Ashenvale Bear"]		= { min=25, max=26, },
	["Elder Cloud Serpent"]			= { min=27, max=29, },
	["Elder Crag Boar"] = { min=7, max=8, },
	["Elder Crag Coyote"]			= { min=39, max=40, },
	["Elder Mistvale Gorilla"] = { min=40, max=41, },
	["Elder Moss Creeper"]			= { min=26, max=27, },
	["Elder Mottled Boar"] = { min=8, max=9, },
	["Elder Mountain Boar"] = { min=16, max=17, },
	["Elder Plainstrider"]			= { min=8, max=9, },
	["Elder Shadowmaw Panther"]		= { min=42, max=43, },
	["Elder Shardtooth"]			= { min=57, max=58, },
	["Encrusted Surf Crawler"]		= { min=9, max=10, },
	["Felpaw Ravager"]				= { min=51, max=52, },
	["Felpaw Wolf"]					= { min=47, max=48, },
	["Feral Crag Coyote"]			= { min=37, max=38, },
	["Feral Mountain Lion"]			= { min=27, max=28, },
	["Ferocious Grizzled Bear"]		= { min=11, max=12, },
	["Fire Roc"]					= { min=43, max=45, },
	["Firetail Scorpid"]			= { min=56, max=57, },
	["Flatland Cougar"]				= { min=7, max=8, },
	["Fleeting Plainstrider"]		= { min=12, max=13, },
	["Forest Lurker"]				= { min=10, max=11, },
	["Forest Moss Creeper"]			= { min=20, max=21, },
	["Forest Spider"]				= { min=5, max=6, },
	["Foreststrider Fledgling"]		= { min=11, max=13, },
	["Frostsaber Cub"]				= { min=55, max=56, },
	["Frostsaber Huntress"]			= { min=58, max=59, },
	["Frostsaber Stalker"]			= { min=59, max=60, },
	["Ghamoo-Ra"]					= { min=25, type="elite" },
	["Ghostpaw Alpha"]				= { min=27, max=28, },
	["Ghostpaw Runner"]				= { min=19, max=20, },
	["Giant Foreststrider"]			= { min=17, max=19, },
	["Giant Moss Creeper"]			= { min=24, max=25, },
	["Giant Plains Creeper"]		= { min=35, max=36, },
	["Giant Surf Glider"]			= { min=48, max=50, type="elite" },
	["Giant Webwood Spider"]		= { min=10, max=11, },
	["Giant Wetlands Crocolisk"]	= { min=25, max=26, },
	["Githyiss the Vile"]			= { min=5, },
	["Goretusk"] = { min=14, max=15, },
	["Gray Bear"]					= { min=21, max=22, },
	["Gray Forest Wolf"]			= { min=7, max=8, },
	["Great Goretusk"] = { min=16, max=17, },
	["Greater Duskbat"]				= { min=6, max=7, },
	["Greater Fleshripper"]			= { min=16, max=17, },
	["Greater Tarantula"]			= { min=19, max=20, },
	["Greater Thunderhawk"]			= { min=23, max=24, },
	["Green Recluse"]				= { min=21, max=22, },
	["Groddoc Thunderer"] = { min=49, max=50, },
	["Grunter"]						= { min=50, type="rare" },
	["Hakkari Frostwing"]			= { min=48, max=50, type="elite" },
	["Hakkari Sapper"]				= { min=48, max=50, type="elite" },
	["Hulking Mountain Lion"]		= { min=33, max=34, },
	["Ice Claw Bear"]				= { min=7, max=8, },
	["Ironback"]					= { min=51, type="rare"},
	["Ironbeak Hunter"]				= { min=50, max=51, },
	["Ironbeak Owl"]				= { min=48, max=49, },
	["Ironbeak Screecher"]			= { min=52, max=53, },
	["Ironfur Bear"]				= { min=41, max=42, },
	["Ironfur Patriarch"]			= { min=48, max=49, },
	["Jaguero Stalker"]				= { min=50, },
	["Jungle Thunderer"] = { min=37, max=38, },
	["Juvenile Snow Leopard"]		= { min=5, max=6, },
	["King Bangalash"]				= { min=43, type="elite" },
	["Kraul Bat"]					= { min=30, max=31, type="elite" },
	["Krellack"]					= { min=56, type="rare" },
	["Kresh"] = { min=20, type="elite", },
	["Kurzen War Tiger"]			= { min=32, max=33, },
	["Lady Sathrah"]				= { min=12, },
	["Large Crag Boar"] = { min=6, max=7, },
	["Loch Crocolisk"]				= { min=14, max=15, },
	["Longsnout"] = { min=10, max=11, },
	["Longtooth Howler"]			= { min=43, max=44, },
	["Longtooth Runner"]			= { min=40, max=41, },
	["Lupos"]						= { min=23, type="elite" },
	["Magram Bonepaw"]				= { min=37, max=38, },
	["Mangeclaw"]					= { min=11, },
	["Mangy Mountain Boar"] = { min=14, max=15, },
	["Mangy Nightsaber"]			= { min=2, },
	["Mazzranache"]					= { min=9, type="rare" },
	["Mesa Buzzard"]				= { min=34, max=35, },
	["Mist Howler"]				= { min=22, type="rare" },
	["Mistvale Gorilla"] = { min=32, max=33, },
	["Monstrous Crawler"]			= { min=43, max=44, },
	["Monstrous Plaguebat"]			= { min=56, max=58, },
	["Moonstalker Runt"]			= { min=10, max=11, },
	["Moonstalker Sire"]			= { min=17, max=18, },
	["Mother Fang"]					= { min=10, type="rare" },
	["Mottled Boar"] = { min=1, max=2, },
	["Mottled Drywallow Crocolisk"]	= { min=38, max=39, },
	["Mountain Boar"] = { min=10, max=11, },
	["Mountain Lion"]				= { min=32, max=33, },
	["Mudrock Snapjaw"]				= { min=41, max=42, },
	["Mudrock Tortoise"]			= { min=36, max=37, },
	["Naraxis"]						= { min=27, type="rare" },
	["Night Web Matriarch"]			= { min=5, },
	["Night Web Spider"]			= { min=3, max=4, },
	["Nightsaber"]					= { min=5, max=6, },
	["Noxious Plaguebat"]			= { min=54, max=56, },
	["Oasis Snapjaw"]				= { min=15, max=16, },
	["Ol' Sooty"]					= { min=20, type="elite" },
	["Old Cliff Jumper"]			= { min=42, type="elite" },
	["Old Grizzlegut"]				= { min=43, type="rare" },
	["Olm the Wise"]				= { min=52, type="rare"},
	["Ornery Plainstrider"]			= { min=16, max=17, },
	["Panther"]						= { min=32, max=33, },
	["Plague Lurker"]				= { min=54, max=55, },
	["Plaguebat"]					= { min=53, max=55, },
	["Plagued Swine"]				= { min=60, },
	["Plains Creeper"]				= { min=32, max=33, },
	["Porcine Entourage"]			= { min=7, },
	["Prairie Stalker"]				= { min=7, max=8, },
	["Prairie Wolf Alpha"]			= { min=9, max=10, },
	["Prairie Wolf"]				= { min=5, max=6, },
	["Princess"]					= { min=9, },
	["Prowler"]						= { min=9, max=10, },
	["Pygmy Surf Crawler"]			= { min=5, max=6, },
	["Rabid Blisterpaw"]			= { min=47, max=48, },
	["Ragged Scavenger"]			= { min=2, max=3, },
	["Raging Agam'ar"]				= { min=25, max=26, type="elite", },
	["Rak'shiri"]					= { min=57, type="rare" },
	["Ravage"]						= { min=51, type="rare" },
	["Rekk'tilac"]					= { min=48, type="rare" },
	["Ridge Huntress"]				= { min=38, max=39, },
	["Ridge Stalker Patriarch"]		= { min=40, max=41, },
	["Ridge Stalker"]				= { min=36, max=37, },
	["Ripscale"]					= { min=39, type="rare" },
	["Roc"]							= { min=41, max=43, },
	["Rockhide Boar"]				= { min=7, max=8, },
	["Rogue Vale Screecher"]		= { min=44, max=46, },
	["Rotting Agam'ar"]				= { min=28, type="elite", },
	["Salt Flats Vulture"]			= { min=32, max=34, },
	["Saltwater Snapjaw"]			= { min=49, max=50, },
	["Sarkoth"]						= { min=4, },
	["Savannah Patriarch"]			= { min=15, max=16, },
	["Sawtooth Snapper"]			= { min=41, max=42, },
	["Scarlet Tracking Hound"]		= { min=33, max=34, type="elite"},
	["Scarred Crag Boar"] = { min=9, max=10, },
	["Scorpashi Lasher"]			= { min=34, max=35, },
	["Scorpashi Snapper"]			= { min=30, max=31, },
	["Scorpashi Venomlash"]			= { min=38, max=39, },
	["Scorpid Dunestalker"]			= { min=46, max=47, },
	["Scorpid Hunter"]				= { min=40, max=41, },
	["Scorpid Reaver"]				= { min=31, max=32, },
	["Scorpid Tail Lasher"]			= { min=43, max=44, },
	["Scorpid Terror"]				= { min=33, max=34, },
	["Scorpid Worker"]				= { min=3, },
	["Scorpok Stinger"]				= { min=50, max=51, },
	["Sewer Beast"]					= { min=50, type="elite" },
	["Shadow Panther"]				= { min=39, max=40, },
	["Shanda the Spinner"]			= { min=19, type="rare" },
	["Shadowmaw Panther"]			= { min=37, max=38, },
	["Shardtooth Bear"]				= { min=53, max=54, },
	["Shore Crawler"]				= { min=17, max=18, },
	["Shrike Bat"]					= { min=38, max=39, type="elite" },
	["Silithid Creeper"]			= { min=20, max=21, },
	["Silithid Swarmer"]			= { min=21, max=22, },
	["Silt Crawler"]				= { min=40, max=41, },
	["Silvermane Howler"]			= { min=45, max=46, },
	["Silvermane Stalker"]			= { min=47, max=48, },
	["Silvermane Wolf"]				= { min=43, max=44, },
	["Sin'Dall"]				= { min=37, },
	["Skittering Crustacean"]		= { min=22, max=23, type="elite" },
	["Small Crag Boar"] = { min=3, },
	["Snapjaw"]						= { min=30, max=31, },
	["Snapping Crustacean"]			= { min=23, max=24, type="elite" },
	["Snarler"]						= { min=42, type="rare" },
	["Snow Tracker Wolf"]			= { min=6, max=7, },
	["Son of Hakkar"]		= { min=60, type="elite", },
	["Sparkleshell Snapper"]		= { min=34, max=35, },
	["Spawn of Hakkar"]		= { min=51, type="elite", },
	["Spiteflayer"]					= { min=52, type="elite" },
	["Sri'skulk"]					= { min=13, type="rare" },
	["Starving Blisterpaw"]			= { min=41, max=42, },
	["Starving Mountain Lion"]		= { min=23, max=24, },
	["Starving Winter Wolf"]		= { min=8, max=9, },
	["Stonelash Flayer"]			= { min=58, max=59, },
	["Stonelash Pincer"]			= { min=56, max=57, },
	["Stonelash Scorpid"]			= { min=54, max=55, },
	["Stonetusk Boar"] = { min=5, max=6, },
	["Stranglethorn Tiger"]			= { min=32, max=33, },
	["Strigid Hunter"]				= { min=8, max=9, },
	["Strigid Owl"]					= { min=5, max=6, },
	["Swamp Jaguar"]				= { min=36, max=37, },
	["Tarantula"]					= { min=15, max=16, },
	["The Rake"] = { min=10, type="rare" },
	["Thistle Bear"]				= { min=11, max=12, },
	["Thistle Boar"] = { min=2, max=3, },
	["Thunderhawk Cloudscraper"]	= { min=20, max=22, },
	["Thunderhawk Hatchling"]		= { min=18, max=20, },
	["Tide Crawler"]				= { min=12, max=14, },
	["Timber"]						= { min=10, type="rare" },
	["Timberweb Recluse"]			= { min=47, max=48, },
	["Twilight Runner"]				= { min=23, max=24, },
	["Uhk'loc"]						= { min=53, type="rare" },
	["U'cha"] = { min=55, },
	["Un'Goro Thunderer"] = { min=52, max=53, },
	["Vale Screecher"]				= { min=41, max=43, },
	["Venomous Cloud Serpent"]		= { min=26, max=28, },
	["Venomtail Scorpid"]			= { min=9, max=10, },
	["Vicious Night Web Spider"]	= { min=9, max=10, },
	["Vile Sting"] 					= { min=35, type="rareelite" },
	["Vilebranch Raiding Wolf"]		= { min=50, max=51, type="elite" },
	["Washte Pawne"]				= { min=25, },
	["Webwood Silkspinner"]			= { min=8, max=9, },
	["Webwood Venomfang"]			= { min=7, max=8, },
	["Wildthorn Lurker"]			= { min=28, max=29, },
	["Winter Wolf"]					= { min=7, max=8, },
	["Winterspring Owl"]			= { min=54, max=56, },
	["Winterspring Screecher"]		= { min=57, max=59, },
	["Witherbark Broodguard"]		= { min=44, max=45, },
	["Wood Lurker"]					= { min=17, max=18, },
	["Worg"]						= { min=10, max=11, },
	["Young Forest Bear"]			= { min=8, max=9, },
	["Young Goretusk"] = { min=12, max=13, },
	["Young Mesa Buzzard"]			= { min=31, max=32, },
	["Young Panther"]				= { min=30, max=31, },
	["Young Stranglethorn Tiger"]	= { min=30, max=31, },
	["Young Thistle Boar"] = { min=1, max=2, },
	["Zaricotl"]					= { min=55, type="rareelite" },
};
