-- Adding aliases for Bartender2 buttons to help our job :)

------------------------------ Bar1 ------------------------------
Bar1Button1 = ActionButton1
Bar1Button2 = ActionButton2
Bar1Button3 = ActionButton3
Bar1Button4 = ActionButton4
Bar1Button5 = ActionButton5
Bar1Button6 = ActionButton6
Bar1Button7 = ActionButton7
Bar1Button8 = ActionButton8
Bar1Button9 = ActionButton9
Bar1Button10 = ActionButton10
Bar1Button11 = ActionButton11
Bar1Button12 = ActionButton12

Bar1Button1Icon = ActionButton1Icon
Bar1Button2Icon = ActionButton2Icon
Bar1Button3Icon = ActionButton3Icon
Bar1Button4Icon = ActionButton4Icon
Bar1Button5Icon = ActionButton5Icon
Bar1Button6Icon = ActionButton6Icon
Bar1Button7Icon = ActionButton7Icon
Bar1Button8Icon = ActionButton8Icon
Bar1Button9Icon = ActionButton9Icon
Bar1Button10Icon = ActionButton10Icon
Bar1Button11Icon = ActionButton11Icon
Bar1Button12Icon = ActionButton12Icon

Bar1Button1NT = ActionButton1NormalTexture
Bar1Button2NT = ActionButton2NormalTexture
Bar1Button3NT = ActionButton3NormalTexture
Bar1Button4NT = ActionButton4NormalTexture
Bar1Button5NT = ActionButton5NormalTexture
Bar1Button6NT = ActionButton6NormalTexture
Bar1Button7NT = ActionButton7NormalTexture
Bar1Button8NT = ActionButton8NormalTexture
Bar1Button9NT = ActionButton9NormalTexture
Bar1Button10NT = ActionButton10NormalTexture
Bar1Button11NT = ActionButton11NormalTexture
Bar1Button12NT = ActionButton12NormalTexture

Bar1Button1HK = ActionButton1HotKey
Bar1Button2HK = ActionButton2HotKey
Bar1Button3HK = ActionButton3HotKey
Bar1Button4HK = ActionButton4HotKey
Bar1Button5HK = ActionButton5HotKey
Bar1Button6HK = ActionButton6HotKey
Bar1Button7HK = ActionButton7HotKey
Bar1Button8HK = ActionButton8HotKey
Bar1Button9HK = ActionButton9HotKey
Bar1Button10HK = ActionButton10HotKey
Bar1Button11HK = ActionButton11HotKey
Bar1Button12HK = ActionButton12HotKey

------------------------------ Bar2 ------------------------------
Bar2Button1 = MultiBarBottomLeftButton1
Bar2Button2 = MultiBarBottomLeftButton2
Bar2Button3 = MultiBarBottomLeftButton3
Bar2Button4 = MultiBarBottomLeftButton4
Bar2Button5 = MultiBarBottomLeftButton5
Bar2Button6 = MultiBarBottomLeftButton6
Bar2Button7 = MultiBarBottomLeftButton7
Bar2Button8 = MultiBarBottomLeftButton8
Bar2Button9 = MultiBarBottomLeftButton9
Bar2Button10 = MultiBarBottomLeftButton10
Bar2Button11 = MultiBarBottomLeftButton11
Bar2Button12 = MultiBarBottomLeftButton12

Bar2Button1Icon = MultiBarBottomLeftButton1Icon
Bar2Button2Icon = MultiBarBottomLeftButton2Icon
Bar2Button3Icon = MultiBarBottomLeftButton3Icon
Bar2Button4Icon = MultiBarBottomLeftButton4Icon
Bar2Button5Icon = MultiBarBottomLeftButton5Icon
Bar2Button6Icon = MultiBarBottomLeftButton6Icon
Bar2Button7Icon = MultiBarBottomLeftButton7Icon
Bar2Button8Icon = MultiBarBottomLeftButton8Icon
Bar2Button9Icon = MultiBarBottomLeftButton9Icon
Bar2Button10Icon = MultiBarBottomLeftButton10Icon
Bar2Button11Icon = MultiBarBottomLeftButton11Icon
Bar2Button12Icon = MultiBarBottomLeftButton12Icon

Bar2Button1NT = MultiBarBottomLeftButton1NormalTexture
Bar2Button2NT = MultiBarBottomLeftButton2NormalTexture
Bar2Button3NT = MultiBarBottomLeftButton3NormalTexture
Bar2Button4NT = MultiBarBottomLeftButton4NormalTexture
Bar2Button5NT = MultiBarBottomLeftButton5NormalTexture
Bar2Button6NT = MultiBarBottomLeftButton6NormalTexture
Bar2Button7NT = MultiBarBottomLeftButton7NormalTexture
Bar2Button8NT = MultiBarBottomLeftButton8NormalTexture
Bar2Button9NT = MultiBarBottomLeftButton9NormalTexture
Bar2Button10NT = MultiBarBottomLeftButton10NormalTexture
Bar2Button11NT = MultiBarBottomLeftButton11NormalTexture
Bar2Button12NT = MultiBarBottomLeftButton12NormalTexture

Bar2Button1HK = MultiBarBottomLeftButton1HotKey
Bar2Button2HK = MultiBarBottomLeftButton2HotKey
Bar2Button3HK = MultiBarBottomLeftButton3HotKey
Bar2Button4HK = MultiBarBottomLeftButton4HotKey
Bar2Button5HK = MultiBarBottomLeftButton5HotKey
Bar2Button6HK = MultiBarBottomLeftButton6HotKey
Bar2Button7HK = MultiBarBottomLeftButton7HotKey
Bar2Button8HK = MultiBarBottomLeftButton8HotKey
Bar2Button9HK = MultiBarBottomLeftButton9HotKey
Bar2Button10HK = MultiBarBottomLeftButton10HotKey
Bar2Button11HK = MultiBarBottomLeftButton11HotKey
Bar2Button12HK = MultiBarBottomLeftButton12HotKey

------------------------------ Bar3 ------------------------------
Bar3Button1 = MultiBarBottomRightButton1
Bar3Button2 = MultiBarBottomRightButton2
Bar3Button3 = MultiBarBottomRightButton3
Bar3Button4 = MultiBarBottomRightButton4
Bar3Button5 = MultiBarBottomRightButton5
Bar3Button6 = MultiBarBottomRightButton6
Bar3Button7 = MultiBarBottomRightButton7
Bar3Button8 = MultiBarBottomRightButton8
Bar3Button9 = MultiBarBottomRightButton9
Bar3Button10 = MultiBarBottomRightButton10
Bar3Button11 = MultiBarBottomRightButton11
Bar3Button12 = MultiBarBottomRightButton12

Bar3Button1Icon = MultiBarBottomRightButton1Icon
Bar3Button2Icon = MultiBarBottomRightButton2Icon
Bar3Button3Icon = MultiBarBottomRightButton3Icon
Bar3Button4Icon = MultiBarBottomRightButton4Icon
Bar3Button5Icon = MultiBarBottomRightButton5Icon
Bar3Button6Icon = MultiBarBottomRightButton6Icon
Bar3Button7Icon = MultiBarBottomRightButton7Icon
Bar3Button8Icon = MultiBarBottomRightButton8Icon
Bar3Button9Icon = MultiBarBottomRightButton9Icon
Bar3Button10Icon = MultiBarBottomRightButton10Icon
Bar3Button11Icon = MultiBarBottomRightButton11Icon
Bar3Button12Icon = MultiBarBottomRightButton12Icon

Bar3Button1NT = MultiBarBottomRightButton1NormalTexture
Bar3Button2NT = MultiBarBottomRightButton2NormalTexture
Bar3Button3NT = MultiBarBottomRightButton3NormalTexture
Bar3Button4NT = MultiBarBottomRightButton4NormalTexture
Bar3Button5NT = MultiBarBottomRightButton5NormalTexture
Bar3Button6NT = MultiBarBottomRightButton6NormalTexture
Bar3Button7NT = MultiBarBottomRightButton7NormalTexture
Bar3Button8NT = MultiBarBottomRightButton8NormalTexture
Bar3Button9NT = MultiBarBottomRightButton9NormalTexture
Bar3Button10NT = MultiBarBottomRightButton10NormalTexture
Bar3Button11NT = MultiBarBottomRightButton11NormalTexture
Bar3Button12NT = MultiBarBottomRightButton12NormalTexture

Bar3Button1HK = MultiBarBottomRightButton1HotKey
Bar3Button2HK = MultiBarBottomRightButton2HotKey
Bar3Button3HK = MultiBarBottomRightButton3HotKey
Bar3Button4HK = MultiBarBottomRightButton4HotKey
Bar3Button5HK = MultiBarBottomRightButton5HotKey
Bar3Button6HK = MultiBarBottomRightButton6HotKey
Bar3Button7HK = MultiBarBottomRightButton7HotKey
Bar3Button8HK = MultiBarBottomRightButton8HotKey
Bar3Button9HK = MultiBarBottomRightButton9HotKey
Bar3Button10HK = MultiBarBottomRightButton10HotKey
Bar3Button11HK = MultiBarBottomRightButton11HotKey
Bar3Button12HK = MultiBarBottomRightButton12HotKey

------------------------------ Bar4 ------------------------------
Bar4Button1 = MultiBarRightButton1
Bar4Button2 = MultiBarRightButton2
Bar4Button3 = MultiBarRightButton3
Bar4Button4 = MultiBarRightButton4
Bar4Button5 = MultiBarRightButton5
Bar4Button6 = MultiBarRightButton6
Bar4Button7 = MultiBarRightButton7
Bar4Button8 = MultiBarRightButton8
Bar4Button9 = MultiBarRightButton9
Bar4Button10 = MultiBarRightButton10
Bar4Button11 = MultiBarRightButton11
Bar4Button12 = MultiBarRightButton12

Bar4Button1Icon = MultiBarRightButton1Icon
Bar4Button2Icon = MultiBarRightButton2Icon
Bar4Button3Icon = MultiBarRightButton3Icon
Bar4Button4Icon = MultiBarRightButton4Icon
Bar4Button5Icon = MultiBarRightButton5Icon
Bar4Button6Icon = MultiBarRightButton6Icon
Bar4Button7Icon = MultiBarRightButton7Icon
Bar4Button8Icon = MultiBarRightButton8Icon
Bar4Button9Icon = MultiBarRightButton9Icon
Bar4Button10Icon = MultiBarRightButton10Icon
Bar4Button11Icon = MultiBarRightButton11Icon
Bar4Button12Icon = MultiBarRightButton12Icon

Bar4Button1NT = MultiBarRightButton1NormalTexture
Bar4Button2NT = MultiBarRightButton2NormalTexture
Bar4Button3NT = MultiBarRightButton3NormalTexture
Bar4Button4NT = MultiBarRightButton4NormalTexture
Bar4Button5NT = MultiBarRightButton5NormalTexture
Bar4Button6NT = MultiBarRightButton6NormalTexture
Bar4Button7NT = MultiBarRightButton7NormalTexture
Bar4Button8NT = MultiBarRightButton8NormalTexture
Bar4Button9NT = MultiBarRightButton9NormalTexture
Bar4Button10NT = MultiBarRightButton10NormalTexture
Bar4Button11NT = MultiBarRightButton11NormalTexture
Bar4Button12NT = MultiBarRightButton12NormalTexture

Bar4Button1HK = MultiBarRightButton1HotKey
Bar4Button2HK = MultiBarRightButton2HotKey
Bar4Button3HK = MultiBarRightButton3HotKey
Bar4Button4HK = MultiBarRightButton4HotKey
Bar4Button5HK = MultiBarRightButton5HotKey
Bar4Button6HK = MultiBarRightButton6HotKey
Bar4Button7HK = MultiBarRightButton7HotKey
Bar4Button8HK = MultiBarRightButton8HotKey
Bar4Button9HK = MultiBarRightButton9HotKey
Bar4Button10HK = MultiBarRightButton10HotKey
Bar4Button11HK = MultiBarRightButton11HotKey
Bar4Button12HK = MultiBarRightButton12HotKey

------------------------------ Bar5 ------------------------------
Bar5Button1 = MultiBarLeftButton1
Bar5Button2 = MultiBarLeftButton2
Bar5Button3 = MultiBarLeftButton3
Bar5Button4 = MultiBarLeftButton4
Bar5Button5 = MultiBarLeftButton5
Bar5Button6 = MultiBarLeftButton6
Bar5Button7 = MultiBarLeftButton7
Bar5Button8 = MultiBarLeftButton8
Bar5Button9 = MultiBarLeftButton9
Bar5Button10 = MultiBarLeftButton10
Bar5Button11 = MultiBarLeftButton11
Bar5Button12 = MultiBarLeftButton12

Bar5Button1Icon = MultiBarLeftButton1Icon
Bar5Button2Icon = MultiBarLeftButton2Icon
Bar5Button3Icon = MultiBarLeftButton3Icon
Bar5Button4Icon = MultiBarLeftButton4Icon
Bar5Button5Icon = MultiBarLeftButton5Icon
Bar5Button6Icon = MultiBarLeftButton6Icon
Bar5Button7Icon = MultiBarLeftButton7Icon
Bar5Button8Icon = MultiBarLeftButton8Icon
Bar5Button9Icon = MultiBarLeftButton9Icon
Bar5Button10Icon = MultiBarLeftButton10Icon
Bar5Button11Icon = MultiBarLeftButton11Icon
Bar5Button12Icon = MultiBarLeftButton12Icon

Bar5Button1NT = MultiBarLeftButton1NormalTexture
Bar5Button2NT = MultiBarLeftButton2NormalTexture
Bar5Button3NT = MultiBarLeftButton3NormalTexture
Bar5Button4NT = MultiBarLeftButton4NormalTexture
Bar5Button5NT = MultiBarLeftButton5NormalTexture
Bar5Button6NT = MultiBarLeftButton6NormalTexture
Bar5Button7NT = MultiBarLeftButton7NormalTexture
Bar5Button8NT = MultiBarLeftButton8NormalTexture
Bar5Button9NT = MultiBarLeftButton9NormalTexture
Bar5Button10NT = MultiBarLeftButton10NormalTexture
Bar5Button11NT = MultiBarLeftButton11NormalTexture
Bar5Button12NT = MultiBarLeftButton12NormalTexture

Bar5Button1HK = MultiBarLeftButton1HotKey
Bar5Button2HK = MultiBarLeftButton2HotKey
Bar5Button3HK = MultiBarLeftButton3HotKey
Bar5Button4HK = MultiBarLeftButton4HotKey
Bar5Button5HK = MultiBarLeftButton5HotKey
Bar5Button6HK = MultiBarLeftButton6HotKey
Bar5Button7HK = MultiBarLeftButton7HotKey
Bar5Button8HK = MultiBarLeftButton8HotKey
Bar5Button9HK = MultiBarLeftButton9HotKey
Bar5Button10HK = MultiBarLeftButton10HotKey
Bar5Button11HK = MultiBarLeftButton11HotKey
Bar5Button12HK = MultiBarLeftButton12HotKey

------------------------------ Bar6 ------------------------------
Bar6Button1 = ShapeshiftButton1
Bar6Button2 = ShapeshiftButton2
Bar6Button3 = ShapeshiftButton3
Bar6Button4 = ShapeshiftButton4
Bar6Button5 = ShapeshiftButton5
Bar6Button6 = ShapeshiftButton6
Bar6Button7 = ShapeshiftButton7
Bar6Button8 = ShapeshiftButton8
Bar6Button9 = ShapeshiftButton9
Bar6Button10 = ShapeshiftButton10

Bar6Button1Icon = ShapeshiftButton1Icon
Bar6Button2Icon = ShapeshiftButton2Icon
Bar6Button3Icon = ShapeshiftButton3Icon
Bar6Button4Icon = ShapeshiftButton4Icon
Bar6Button5Icon = ShapeshiftButton5Icon
Bar6Button6Icon = ShapeshiftButton6Icon
Bar6Button7Icon = ShapeshiftButton7Icon
Bar6Button8Icon = ShapeshiftButton8Icon
Bar6Button9Icon = ShapeshiftButton9Icon
Bar6Button10Icon = ShapeshiftButton10Icon

Bar6Button1NT = ShapeshiftButton1NormalTexture
Bar6Button2NT = ShapeshiftButton2NormalTexture
Bar6Button3NT = ShapeshiftButton3NormalTexture
Bar6Button4NT = ShapeshiftButton4NormalTexture
Bar6Button5NT = ShapeshiftButton5NormalTexture
Bar6Button6NT = ShapeshiftButton6NormalTexture
Bar6Button7NT = ShapeshiftButton7NormalTexture
Bar6Button8NT = ShapeshiftButton8NormalTexture
Bar6Button9NT = ShapeshiftButton9NormalTexture
Bar6Button10NT = ShapeshiftButton10NormalTexture

------------------------------ Bar7 ------------------------------
Bar7Button1 = PetActionButton1
Bar7Button2 = PetActionButton2
Bar7Button3 = PetActionButton3
Bar7Button4 = PetActionButton4
Bar7Button5 = PetActionButton5
Bar7Button6 = PetActionButton6
Bar7Button7 = PetActionButton7
Bar7Button8 = PetActionButton8
Bar7Button9 = PetActionButton9
Bar7Button10 = PetActionButton10

Bar7Button1Icon = PetActionButton1Icon
Bar7Button2Icon = PetActionButton2Icon
Bar7Button3Icon = PetActionButton3Icon
Bar7Button4Icon = PetActionButton4Icon
Bar7Button5Icon = PetActionButton5Icon
Bar7Button6Icon = PetActionButton6Icon
Bar7Button7Icon = PetActionButton7Icon
Bar7Button8Icon = PetActionButton8Icon
Bar7Button9Icon = PetActionButton9Icon
Bar7Button10Icon = PetActionButton10Icon

Bar7Button1NT = PetActionButton1NormalTexture2
Bar7Button2NT = PetActionButton2NormalTexture2
Bar7Button3NT = PetActionButton3NormalTexture2
Bar7Button4NT = PetActionButton4NormalTexture2
Bar7Button5NT = PetActionButton5NormalTexture2
Bar7Button6NT = PetActionButton6NormalTexture2
Bar7Button7NT = PetActionButton7NormalTexture2
Bar7Button8NT = PetActionButton8NormalTexture2
Bar7Button9NT = PetActionButton9NormalTexture2
Bar7Button10NT = PetActionButton10NormalTexture2

------------------------------ Bar8 ------------------------------
Bar8Button1 = CharacterBag3Slot
Bar8Button2 = CharacterBag2Slot
Bar8Button3 = CharacterBag1Slot
Bar8Button4 = CharacterBag0Slot
Bar8Button5 = MainMenuBarBackpackButton

Bar8Button1NT = CharacterBag3SlotNormalTexture
Bar8Button2NT = CharacterBag2SlotNormalTexture
Bar8Button3NT = CharacterBag1SlotNormalTexture
Bar8Button4NT = CharacterBag0SlotNormalTexture
Bar8Button5NT = MainMenuBarBackpackButtonNormalTexture

Bar8Button1Icon = CharacterBag3SlotIconTexture
Bar8Button2Icon = CharacterBag2SlotIconTexture
Bar8Button3Icon = CharacterBag1SlotIconTexture
Bar8Button4Icon = CharacterBag0SlotIconTexture
Bar8Button5Icon = MainMenuBarBackpackButtonIconTexture

------------------------------ Bar9 ------------------------------
Bar9Button1 = CharacterMicroButton
Bar9Button2 = SpellbookMicroButton
Bar9Button3 = TalentMicroButton
Bar9Button4 = QuestLogMicroButton
Bar9Button5 = SocialsMicroButton
Bar9Button6 = WorldMapMicroButton
Bar9Button7 = MainMenuMicroButton
Bar9Button8 = HelpMicroButton

------------------------------ Bar10 ------------------------------
Bar10Button1 = BonusActionButton1
Bar10Button2 = BonusActionButton2
Bar10Button3 = BonusActionButton3
Bar10Button4 = BonusActionButton4
Bar10Button5 = BonusActionButton5
Bar10Button6 = BonusActionButton6
Bar10Button7 = BonusActionButton7
Bar10Button8 = BonusActionButton8
Bar10Button9 = BonusActionButton9
Bar10Button10 = BonusActionButton10
Bar10Button11 = BonusActionButton11
Bar10Button12 = BonusActionButton12

Bar10Button1Icon = BonusActionButton1Icon
Bar10Button2Icon = BonusActionButton2Icon
Bar10Button3Icon = BonusActionButton3Icon
Bar10Button4Icon = BonusActionButton4Icon
Bar10Button5Icon = BonusActionButton5Icon
Bar10Button6Icon = BonusActionButton6Icon
Bar10Button7Icon = BonusActionButton7Icon
Bar10Button8Icon = BonusActionButton8Icon
Bar10Button9Icon = BonusActionButton9Icon
Bar10Button10Icon = BonusActionButton10Icon
Bar10Button11Icon = BonusActionButton11Icon
Bar10Button12Icon = BonusActionButton12Icon

Bar10Button1NT = BonusActionButton1NormalTexture
Bar10Button2NT = BonusActionButton2NormalTexture
Bar10Button3NT = BonusActionButton3NormalTexture
Bar10Button4NT = BonusActionButton4NormalTexture
Bar10Button5NT = BonusActionButton5NormalTexture
Bar10Button6NT = BonusActionButton6NormalTexture
Bar10Button7NT = BonusActionButton7NormalTexture
Bar10Button8NT = BonusActionButton8NormalTexture
Bar10Button9NT = BonusActionButton9NormalTexture
Bar10Button10NT = BonusActionButton10NormalTexture
Bar10Button11NT = BonusActionButton11NormalTexture
Bar10Button12NT = BonusActionButton12NormalTexture

Bar10Button1HK = BonusActionButton1HotKey
Bar10Button2HK = BonusActionButton2HotKey
Bar10Button3HK = BonusActionButton3HotKey
Bar10Button4HK = BonusActionButton4HotKey
Bar10Button5HK = BonusActionButton5HotKey
Bar10Button6HK = BonusActionButton6HotKey
Bar10Button7HK = BonusActionButton7HotKey
Bar10Button8HK = BonusActionButton8HotKey
Bar10Button9HK = BonusActionButton9HotKey
Bar10Button10HK = BonusActionButton10HotKey
Bar10Button11HK = BonusActionButton11HotKey
Bar10Button12HK = BonusActionButton12HotKey

------------------------------ Others ------------------------------
Shapebar = Bar6
Petbar = Bar7
Bagbar = Bar8
Microbar = Bar9
Bonusbar = Bar10
