function ReagentData_LoadEnchanting()
ReagentData['crafted']['enchanting'] = {
     ['Enchant Bracer - Minor Health'] = {
      skill = 1 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant bracers to increase the health of the wearer by 5.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 1,
      },
     },
     ['Runed Copper Rod'] = {
      skill = 1 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = '[BoP]',
      reagents = {
           [ReagentData['rod']['copper']] = 1,
           [ReagentData['dust']['strange']] = 1,
           [ReagentData['essence']['lessermagic']] = 1,
      },
     },
     ['Lesser Magic Wand'] = {
      skill = 10 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = '(Wand) Dmg: 6-11, Spd: 1.50, DPS: 5.7, MinLvl: 5',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['wood']['simple']] = 1,
           [ReagentData['essence']['lessermagic']] = 1,
      },
     },
     ['Enchant Chest - Minor Health'] = {
      skill = 15 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a piece of chest armor so that it increases the health of the wearer by 5.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 1,
      },
     },
     ['Enchant Bracer - Minor Deflect'] = {
      skill = 20 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant bracers so that the defense skill of the wearer is increased by 1.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['essence']['lessermagic']] = 1,
           [ReagentData['dust']['strange']] = 1,
      },
     },
     ['Enchant Chest - Minor Mana'] = {
      skill = 20 ,
      type = 'Enchanting',
      source = 'Vendor, Drop',
      description = 'Permanently enchant a piece of chest armor so that it increases the mana of the wearer by 5.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['essence']['lessermagic']] = 1,
      },
     },
     ['Enchant Chest - Minor Absorption'] = {
      skill = 40 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Enchant a piece of chest armor so it has a 2% chance per hit of giving you 10 points of damage absorption.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 2,
           [ReagentData['essence']['lessermagic']] = 1,
      },
     },
     ['Enchant Cloak - Minor Resistance'] = {
      skill = 45 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a cloak so that it increases the resistance to all schools of magic by 1.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 1,
           [ReagentData['essence']['lessermagic']] = 2,
      },
     },
     ['Enchant Bracer - Minor Stamina'] = {
      skill = 50 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant bracers so they increase the wearer\'s Stamina by 1.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 3,
      },
     },
     ['Enchant Bracer - Minor Spirit'] = {
      skill = 60 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant bracers so they increase the wearer\'s Spirit by 1.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['essence']['lessermagic']] = 2,
      },
     },
     ['Enchant Chest - Lesser Health'] = {
      skill = 60 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a piece of chest armor so that it increases the health of the wearer by 15.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 2,
           [ReagentData['essence']['lessermagic']] = 2,
      },
     },
     ['Enchant Bracer - Minor Agility'] = {
      skill = 80 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant bracers so they increase the wearer\'s Agility by 1.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 2,
           [ReagentData['essence']['greatermagic']] = 1,
      },
     },
     ['Enchant Bracer - Minor Strength'] = {
      skill = 80 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant bracers so they increase the wearer\'s Strength by 1.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 5,
      },
     },
     ['Enchant Chest - Lesser Mana'] = {
      skill = 80 ,
      type = 'Enchanting',
      source = 'Vendor',
      description = 'Permanently enchant a piece of chest armor so that it increases the mana of the wearer by 20.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['essence']['greatermagic']] = 1,
           [ReagentData['essence']['lessermagic']] = 1,
      },
     },
     ['Enchant Weapon - Minor Beastslayer'] = {
      skill = 90 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant a Melee Weapon to do 2 additional points of damage to Beasts.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 4,
           [ReagentData['essence']['greatermagic']] = 2,
      },
     },
     ['Enchant Weapon - Minor Striking'] = {
      skill = 90 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a Melee Weapon to do 1 additional point of damage.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 2,
           [ReagentData['essence']['greatermagic']] = 1,
           [ReagentData['shard']['smallglimmering']] = 1,
      },
     },
     ['Enchant Cloak - Minor Protection'] = {
      skill = 91 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Enchant a cloak to provide 10 additional points of armor.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 3,
           [ReagentData['essence']['greatermagic']] = 1,
      },
     },
     ['Greater Magic Wand'] = {
      skill = 91 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = '(Wand) Dmg: 15-28, Spd: 1.80, DPS: 11.9, MinLvl: 13',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['wood']['simple']] = 1,
           [ReagentData['essence']['greatermagic']] = 1,
      },
     },
     ['Enchant 2H Weapon - Lesser Intellect'] = {
      skill = 100 ,
      type = 'Enchanting',
      source = 'Vendor',
      description = 'Permanently enchant a Two-Handed Melee Weapon to add 3 to intellect.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['essence']['greatermagic']] = 3,
      },
     },
     ['Enchant 2H Weapon - Minor Impact'] = {
      skill = 100 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a Two-Handed Melee Weapon to do 2 additional points of damage.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 4,
           [ReagentData['shard']['smallglimmering']] = 1,
      },
     },
     ['Runed Silver Rod'] = {
      skill = 100 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = '[BoP]',
      reagents = {
           [ReagentData['rod']['silver']] = 1,
           [ReagentData['dust']['strange']] = 6,
           [ReagentData['essence']['greatermagic']] = 3,
           [ReagentData['gem']['shadow']] = 1,
      },
     },
     ['Enchant Shield - Minor Stamina'] = {
      skill = 105 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a shield so that it increases the Stamina of the bearer by 1.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['essence']['lesserastral']] = 1,
           [ReagentData['dust']['strange']] = 2,
      },
     },
     ['Enchant 2H Weapon - Lesser Spirit'] = {
      skill = 110 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant a Two-Handed Melee Weapon to add 3 to Spirit.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['essence']['lesserastral']] = 1,
           [ReagentData['dust']['strange']] = 6,
      },
     },
     ['Enchant Cloak - Minor Agility'] = {
      skill = 110 ,
      type = 'Enchanting',
      source = 'Vendor, Drop',
      description = 'Permanently enchant a cloak to grant +1 Agility.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['essence']['lesserastral']] = 1,
      },
     },
     ['Enchant Cloak - Lesser Protection'] = {
      skill = 115 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a cloak to increase armor by 20.',
      tools = 'Runed Copper Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 6,
           [ReagentData['shard']['smallglimmering']] = 1,
      },
     },
     ['Enchant Shield - Lesser Protection'] = {
      skill = 115 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant a shield to increase its armor by 30.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['essence']['lesserastral']] = 1,
           [ReagentData['dust']['strange']] = 1,
           [ReagentData['shard']['smallglimmering']] = 1,
      },
     },
     ['Enchant Bracer - Lesser Spirit'] = {
      skill = 120 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant a bracer so it increases the wearer\'s Spirit by 3.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['essence']['lesserastral']] = 2,
      },
     },
     ['Enchant Chest - Health'] = {
      skill = 120 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a piece of chest armor to increase the health of the wearer by 25.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 4,
           [ReagentData['essence']['lesserastral']] = 1,
      },
     },
     ['Enchant Boots - Minor Agility'] = {
      skill = 125 ,
      type = 'Enchanting',
      source = 'Vendor',
      description = 'Permanently enchant a pair of boots so they increase the wearer\'s Agility by 1.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 6,
           [ReagentData['essence']['lesserastral']] = 2,
      },
     },
     ['Enchant Boots - Minor Stamina'] = {
      skill = 125 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a pair of boots so they increase the wearer\'s Stamina by 1.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 8,
      },
     },
     ['Enchant Cloak - Lesser Fire Resistance'] = {
      skill = 125 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a cloak so that it increases resistance to fire by 5.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['oil']['fire']] = 1,
           [ReagentData['essence']['lesserastral']] = 1,
      },
     },
     ['Enchant Bracer - Lesser Stamina'] = {
      skill = 130 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a bracer so it increases the wearer\'s Stamina by 3.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 2,
      },
     },
     ['Enchant Shield - Lesser Spirit'] = {
      skill = 130 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a shield to give 3 spirit.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['essence']['lesserastral']] = 2,
           [ReagentData['dust']['strange']] = 4,
      },
     },
     ['Enchant Cloak - Lesser Shadow Resistance'] = {
      skill = 135 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant a cloak so that it increases resistance to shadow by 10.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['essence']['greaterastral']] = 1,
           [ReagentData['potion']['shadowprotection']] = 1,
      },
     },
     ['Enchant Bracer - Lesser Strength'] = {
      skill = 140 ,
      type = 'Enchanting',
      source = 'Vendor',
      description = 'Permanently enchant a bracer so it increases the wearer\'s Strength by 3.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 2,
      },
     },
     ['Enchant Chest - Lesser Absorption'] = {
      skill = 140 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Enchant a piece of chest armor so it has a 5% chance per hit of giving you 25 points of damage absorption.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['strange']] = 2,
           [ReagentData['essence']['greaterastral']] = 1,
           [ReagentData['shard']['largeglimmering']] = 1,
      },
     },
     ['Enchant Weapon - Lesser Striking'] = {
      skill = 140 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a Melee Weapon to do 2 additional points of damage.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 2,
           [ReagentData['shard']['largeglimmering']] = 1,
      },
     },
     ['Enchant 2H Weapon - Lesser Impact'] = {
      skill = 145 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a Two-handed Melee Weapon to do 3 additional points of damage.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 3,
           [ReagentData['shard']['largeglimmering']] = 1,
      },
     },
     ['Enchant Chest - Mana'] = {
      skill = 145 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a piece of chest armor to increase the mana of the wearer by 30.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['essence']['greaterastral']] = 1,
           [ReagentData['essence']['lesserastral']] = 2,
      },
     },
     ['Enchant Gloves - Fishing'] = {
      skill = 145 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant gloves to grant +2 fishing skill.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 1,
           [ReagentData['oil']['blackmouth']] = 3,
      },
     },
     ['Enchant Gloves - Herbalism'] = {
      skill = 145 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant gloves to grant +2 herbalism skill.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 1,
           [ReagentData['herb']['kingsblood']] = 3,
      },
     },
     ['Enchant Gloves - Mining'] = {
      skill = 145 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant gloves to grant +2 mining skill.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 1,
           [ReagentData['ore']['iron']] = 3,
      },
     },
     ['Enchant Bracer - Lesser Intellect'] = {
      skill = 150 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a bracer so it increases the wearer\'s Intellect by 3.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['essence']['greaterastral']] = 2,
      },
     },
     ['Enchant Chest - Minor Stats'] = {
      skill = 150 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a piece of chest armor to grant +1 to all stats.',
      tools = 'Runed Silver Rod',
      reagents = {
           [ReagentData['essence']['greaterastral']] = 1,
           [ReagentData['dust']['soul']] = 1,
           [ReagentData['shard']['largeglimmering']] = 1,
      },
     },
     ['Lesser Mystic Wand'] = {
      skill = 150 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = '(Wand) DPS: 23.1, MinLvl: 26, 21 - 39 Arcane Damage, Speed 1.30',
      reagents = {
           [ReagentData['wood']['star']] = 1,
           [ReagentData['essence']['lessermystic']] = 1,
           [ReagentData['dust']['soul']] = 1,
      },
     },
     ['Runed Golden Rod'] = {
      skill = 150 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = '[BoP]',
      reagents = {
           [ReagentData['rod']['golden']] = 1,
           [ReagentData['pearl']['iridescent']] = 1,
           [ReagentData['essence']['greaterastral']] = 2,
           [ReagentData['dust']['soul']] = 2,
      },
     },
     ['Enchant Cloak - Defense'] = {
      skill = 155 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a cloak to give 30 additional armor.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['shard']['smallglowing']] = 1,
           [ReagentData['dust']['soul']] = 3,
      },
     },
     ['Enchant Shield - Lesser Stamina'] = {
      skill = 155 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a shield to give 3 Stamina.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['lessermystic']] = 1,
           [ReagentData['dust']['soul']] = 1,
      },
     },
     ['Enchant Boots - Lesser Agility'] = {
      skill = 160 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant boots to give +3 Agility.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 1,
           [ReagentData['essence']['lessermystic']] = 1,
      },
     },
     ['Enchant Chest - Greater Health'] = {
      skill = 160 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a piece of chest armor to give +35 health.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 3,
      },
     },
     ['Enchant Bracer - Spirit'] = {
      skill = 165 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchants bracers to give +5 Spirit.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['lessermystic']] = 1,
      },
     },
     ['Enchant Boots - Lesser Stamina'] = {
      skill = 170 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant boots to give +3 Stamina.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 4,
      },
     },
     ['Enchant Bracer - Lesser Deflection'] = {
      skill = 170 ,
      type = 'Enchanting',
      source = 'Vendor',
      description = 'Permanently enchants bracers to give +2 Defense.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['lessermystic']] = 1,
           [ReagentData['dust']['soul']] = 2,
      },
     },
     ['Enchant Bracer - Stamina'] = {
      skill = 170 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchants bracers to give +5 Stamina.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['dust']['soul']] = 6,
      },
     },
     ['Enchant Cloak - Fire Resistance'] = {
      skill = 175 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a cloak to give 7 Fire Resistance.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['lessermystic']] = 1,
           [ReagentData['element']['fire']] = 1,
      },
     },
     ['Enchant Weapon - Lesser Beastslayer'] = {
      skill = 175 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant a Melee Weapon to do 6 additional points of damage to Beasts.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['lessermystic']] = 1,
           [ReagentData['monster']['largefang']] = 2,
           [ReagentData['shard']['smallglowing']] = 1,
      },
     },
     ['Enchant Weapon - Lesser Elemental Slayer'] = {
      skill = 175 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant a Melee Weapon to do 6 additional damage against Elementals.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['lessermystic']] = 1,
           [ReagentData['element']['earth']] = 1,
           [ReagentData['shard']['smallglowing']] = 1,
      },
     },
     ['Greater Mystic Wand'] = {
      skill = 175 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = '(Wand) Dmg: 38-71, Spd: 2.00, DPS: 27.2, MinLvl: 30',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['wood']['star']] = 1,
           [ReagentData['essence']['greatermystic']] = 1,
           [ReagentData['dust']['vision']] = 1,
      },
     },
     ['Enchant Bracer - Strength'] = {
      skill = 180 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchants bracers to give +5 Strength.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['dust']['vision']] = 1,
      },
     },
     ['Enchant Shield - Spirit'] = {
      skill = 180 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a shield to give 5 Spirit.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['greatermystic']] = 1,
           [ReagentData['dust']['vision']] = 1,
      },
     },
     ['Enchant Chest - Greater Mana'] = {
      skill = 185 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a piece of chest armor to give +50 mana.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['greatermystic']] = 1,
      },
     },
     ['Enchant Boots - Lesser Spirit'] = {
      skill = 190 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant boots to give +3 Spirit.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['greatermystic']] = 1,
           [ReagentData['essence']['lessermystic']] = 2,
      },
     },
     ['Enchant Weapon - Winter\'s Might'] = {
      skill = 190 ,
      type = 'Enchanting',
      source = 'Quest',
      description = 'Permanently enchant a weapon to grant up to 7 additional frost damage when casting frost spells.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['greatermystic']] = 3,
           [ReagentData['dust']['vision']] = 3,
           [ReagentData['shard']['largeglowing']] = 1,
           [ReagentData['herb']['wintersbite']] = 2,
      },
     },
     ['Enchant Shield - Lesser Block'] = {
      skill = 195 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant a shield to give +2% chance to block.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['greatermystic']] = 2,
           [ReagentData['dust']['vision']] = 2,
           [ReagentData['shard']['largeglowing']] = 1,
      },
     },
     ['Enchant Weapon - Striking'] = {
      skill = 195 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a Melee Weapon to do 3 additional points of damage.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['greatermystic']] = 2,
           [ReagentData['shard']['largeglowing']] = 1,
      },
     },
     ['Enchant 2H Weapon - Impact'] = {
      skill = 200 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a Two-handed Melee Weapon to do 5 additional points of damage.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['dust']['vision']] = 4,
           [ReagentData['shard']['largeglowing']] = 1,
      },
     },
     ['Enchant Chest - Lesser Stats'] = {
      skill = 200 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a piece of chest armor to grant +2 to all stats.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['essence']['greatermystic']] = 2,
           [ReagentData['dust']['vision']] = 2,
           [ReagentData['shard']['largeglowing']] = 1,
      },
     },
     ['Enchant Gloves - Skinning'] = {
      skill = 200 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant gloves to grant +5 skinning skill.',
      tools = 'Runed Golden Rod',
      reagents = {
           [ReagentData['dust']['vision']] = 1,
           [ReagentData['scale']['greenwhelp']] = 3,
      },
     },
     ['Runed Truesilver Rod'] = {
      skill = 200 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = '[BoP]',
      reagents = {
           [ReagentData['rod']['truesilver']] = 1,
           [ReagentData['pearl']['black']] = 1,
           [ReagentData['essence']['greatermystic']] = 2,
           [ReagentData['dust']['vision']] = 2,
      },
     },
     ['Enchant Cloak - Greater Defense'] = {
      skill = 205 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a cloak to give 50 additional armor.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['dust']['vision']] = 3,
      },
     },
     ['Enchant Cloak - Resistance'] = {
      skill = 205 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a cloak to give 3 to all resistances.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['essence']['lessernether']] = 1,
      },
     },
     ['Enchant Bracer - Intellect'] = {
      skill = 210 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchants bracers to give +5 Intellect.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['essence']['lessernether']] = 2,
      },
     },
     ['Enchant Gloves - Agility'] = {
      skill = 210 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant gloves to grant +5 Agility.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['essence']['lessernether']] = 1,
           [ReagentData['dust']['vision']] = 1,
      },
     },
     ['Enchant Shield - Stamina'] = {
      skill = 210 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant a shield to give +5 Stamina.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['dust']['vision']] = 5,
      },
     },
     ['Enchant Boots - Stamina'] = {
      skill = 215 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant boots to give +5 Stamina.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['dust']['vision']] = 5,
      },
     },
     ['Enchant Gloves - Advanced Mining'] = {
      skill = 215 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant gloves to grant +5 mining skill.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['dust']['vision']] = 3,
           [ReagentData['bar']['truesilver']] = 3,
      },
     },
     ['Enchant Bracer - Greater Spirit'] = {
      skill = 220 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchants bracers to give +7 Spirit.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['essence']['lessernether']] = 3,
           [ReagentData['dust']['vision']] = 1,
      },
     },
     ['Enchant Chest - Superior Health'] = {
      skill = 220 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant a piece of chest armor to grant +50 health.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['dust']['vision']] = 6,
      },
     },
     ['Enchant Boots - Minor Speed'] = {
      skill = 225 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant boots to give a slight movement speed increase.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['shard']['smallradiant']] = 1,
           [ReagentData['gem']['aquamarine']] = 1,
           [ReagentData['essence']['lessernether']] = 1,
      },
     },
     ['Enchant Cloak - Lesser Agility'] = {
      skill = 225 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant a cloak to give 3 Agility.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['essence']['lessernether']] = 2,
      },
     },
     ['Enchant Gloves - Advanced Herbalism'] = {
      skill = 225 ,
      type = 'Enchanting',
      source = 'Drop',
      description = 'Permanently enchant gloves to grant +5 herbalism skill.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['dust']['vision']] = 3,
           [ReagentData['herb']['sungrass']] = 3,
      },
     },
     ['Enchant Gloves - Strength'] = {
      skill = 225 ,
      type = 'Enchanting',
      source = 'Trainer',
      description = 'Permanently enchant gloves to grant +5 Strength.',
      tools = 'Runed Truesilver Rod',
      reagents = {
           [ReagentData['essence']['lessernether']] = 2,
           [ReagentData['dust']['vision']] = 3,
      },
    },
    ['Enchant Chest - Superior Mana'] = {
         skill = 230 ,
         type = 'Enchanting',
         source = 'Trainer',
         description = 'Permanently enchant a piece of chest armor to give +65 mana.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['greaternether']] = 1,
          [ReagentData['essence']['lessernether']] = 2,
         },
    },
    ['Enchant Shield - Greater Spirit'] = {
         skill = 230 ,
         type = 'Enchanting',
         source = 'Trainer',
         description = 'Permanently enchant a shield to give +7 Spirit.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['greaternether']] = 1,
          [ReagentData['dust']['dream']] = 2,
         },
    },
    ['Enchant Weapon - Demonslaying'] = {
         skill = 230 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a melee weapon to have a chance of stunning and doing heavy damage to demons.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['shard']['smallradiant']] = 1,
          [ReagentData['dust']['dream']] = 2,
          [ReagentData['potion']['elixirofdemonslaying']] = 1,
         },
    },
    ['Enchant Boots - Agility'] = {
         skill = 235 ,
         type = 'Enchanting',
         source = 'Trainer',
         description = 'Permanently enchant boots to give +5 Agility.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['greaternether']] = 2,
         },
    },
    ['Enchant Bracer - Deflection'] = {
         skill = 235 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchants bracers to give +3 Defense.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['greaternether']] = 1,
          [ReagentData['dust']['dream']] = 2,
         },
    },
    ['Enchant Shield - Frost Resistance'] = {
         skill = 235 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a shield to give +8 Frost Resistance.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['shard']['largeradiant']] = 1,
          [ReagentData['oil']['frost']] = 1,
         },
    },
    ['Enchant 2H Weapon - Greater Impact'] = {
         skill = 240 ,
         type = 'Enchanting',
         source = 'Trainer',
         description = 'Permanently enchant a two-handed melee weapon to do +7 damage.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['shard']['largeradiant']] = 2,
          [ReagentData['dust']['dream']] = 2,
         },
    },
    ['Enchant Bracer - Greater Strength'] = {
         skill = 240 ,
         type = 'Enchanting',
         source = 'Trainer',
         description = 'Permanently enchants bracers to give +7 Strength.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['dust']['dream']] = 2,
          [ReagentData['essence']['greaternether']] = 1,
         },
    },
    ['Enchant Bracer - Greater Stamina'] = {
         skill = 245 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchants bracers to give +7 Stamina.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['dust']['dream']] = 5,
         },
    },
    ['Enchant Chest - Stats'] = {
         skill = 245 ,
         type = 'Enchanting',
         source = 'Trainer',
         description = 'Permanently enchant a piece of chest armor to grant +3 to all stats.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['shard']['largeradiant']] = 1,
          [ReagentData['dust']['dream']] = 3,
          [ReagentData['essence']['greaternether']] = 2,
         },
    },
    ['Enchant Weapon - Greater Striking'] = {
         skill = 245 ,
         type = 'Enchanting',
         source = 'Trainer',
         description = 'Permanently enchant a Melee Weapon to do 4 additional points of damage.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['shard']['largeradiant']] = 2,
          [ReagentData['essence']['greaternether']] = 2,
         },
    },
    ['Enchant Gloves - Minor Haste'] = {
         skill = 250 ,
         type = 'Enchanting',
         source = 'Trainer',
         description = 'Permanently enchant gloves to grant a +1% attack speed bonus.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['shard']['largeradiant']] = 2,
          [ReagentData['herb']['wildvine']] = 2,
         },
    },
    ['Enchant Gloves - Riding Skill'] = {
         skill = 250 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant gloves to grant a minor movement bonus while mounted.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['shard']['largeradiant']] = 2,
          [ReagentData['dust']['dream']] = 3,
         },
    },
    ['Enchanted Leather'] = {
         skill = 250 ,
         type = 'Enchanting',
         source = 'Trainer',
         description = 'Enchanted Leather',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['leather']['rugged']] = 1,
          [ReagentData['essence']['lessereternal']] = 1,
         },
    },
    ['Enchanted Thorium'] = {
         skill = 250 ,
         type = 'Enchanting',
         source = 'Trainer',
         description = 'Enchanted Thorium Bar',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['bar']['thorium']] = 1,
          [ReagentData['dust']['dream']] = 3,
         },
    },
    ['Enchant Bracer - Greater Intellect'] = {
         skill = 255 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchants bracers to give +7 Intellect.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['lessereternal']] = 3,
         },
    },
    ['Enchant Boots - Greater Stamina'] = {
         skill = 260 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant boots to give +7 Stamina.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['dust']['dream']] = 10,
         },
    },
    ['Enchant Cloak - Greater Resistance'] = {
         skill = 265 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a cloak to give 5 to all resistances.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['lessereternal']] = 2,
          [ReagentData['element']['heartoffire']] = 1,
          [ReagentData['element']['coreofearth']] = 1,
          [ReagentData['element']['globeofwater']] = 1,
          [ReagentData['element']['breathofwind']] = 1,
          [ReagentData['element']['ichorofundeath']] = 1,
         },
    },
    ['Enchant Shield - Greater Stamina'] = {
         skill = 265 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchant a shield to give +7 Stamina.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['dust']['dream']] = 10,
         },
    },
    ['Enchant Weapon - Fiery Weapon'] = {
         skill = 265 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a melee weapon to often strike for 40 additional fire damage.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['shard']['smallradiant']] = 4,
          [ReagentData['element']['essenceoffire']] = 1,
         },
    },
    ['Smoking Heart of the Mountain'] = {
         skill = 265 ,
         type = 'Enchanting',
         source = 'Drop',
         description = '[BoP] [U] (Trinket) AC: 150, FR: 7, NR: 7, CR: 7, SR: 7, MinLvl: 50',
         tools = 'Black Forge',
         reagents = {
          [ReagentData['gem']['bloodofthemountain']] = 1,
          [ReagentData['element']['essenceoffire']] = 1,
          [ReagentData['shard']['smallbrilliant']] = 3,
         },
    },
    ['Enchant Bracer - Superior Spirit'] = {
         skill = 270 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchants bracers to give +9 Spirit.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['lessereternal']] = 3,
          [ReagentData['dust']['dream']] = 10,
         },
    },
    ['Enchant Gloves - Greater Agility'] = {
         skill = 270 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant gloves to grant +7 Agility.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['lessereternal']] = 3,
          [ReagentData['dust']['illusion']] = 3,
         },
    },
    ['Enchant Boots - Spirit'] = {
         skill = 275 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant boots to give +5 Spirit.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['greatereternal']] = 2,
          [ReagentData['essence']['lessereternal']] = 1,
         },
    },
    ['Enchant Chest - Major Health'] = {
         skill = 275 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchant a piece of chest armor to grant +100 health.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['dust']['illusion']] = 6,
          [ReagentData['shard']['smallbrilliant']] = 1,
         },
    },
    ['Enchant Shield - Superior Spirit'] = {
         skill = 280 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a shield to give +9 Spirit.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['greatereternal']] = 2,
          [ReagentData['dust']['illusion']] = 4,
         },
    },
    ['Enchant Cloak - Superior Defense'] = {
         skill = 285 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchant a cloak to give 70 additional armor.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['dust']['illusion']] = 8,
         },
    },
    ['Enchant Weapon - Icy Chill'] = {
         skill = 285 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a melee weapon to often chill the target reducing their movement and attack speed.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['shard']['smallbrilliant']] = 4,
          [ReagentData['element']['essenceofwater']] = 1,
          [ReagentData['element']['essenceofair']] = 1,
          [ReagentData['herb']['icecap']] = 1,
         },
    },
    ['Enchant Bracer - Mana Regeneration'] = {
         skill = 290 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchants bracers to restore 4 mana every 5 seconds.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['dust']['illusion']] = 16,
          [ReagentData['essence']['greatereternal']] = 4,
          [ReagentData['element']['essenceofwater']] = 2,
         },
    },
    ['Enchant Chest - Major Mana'] = {
         skill = 290 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a piece of chest armor to give +100 mana.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['greatereternal']] = 3,
          [ReagentData['shard']['smallbrilliant']] = 1,
         },
    },
    ['Enchant 2H Weapon - Agility'] = {
         skill = 290,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchant a two-handed melee weapon to grant +25 Agility.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 10,
          [ReagentData['essence']['greatereternal']] = 6,
          [ReagentData['dust']['illusion']] = 14,
          [ReagentData['element']['essenceofair']] = 4,
         },
    },
    ['Enchant Weapon - Agility'] = {
         skill = 290 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchant a melee weapon to grant +15 Agility.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 6,
          [ReagentData['essence']['greatereternal']] = 6,
          [ReagentData['dust']['illusion']] = 4,
          [ReagentData['element']['essenceofair']] = 2,
         },
    },
    ['Enchant Weapon - Strength'] = {
         skill = 290 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchant a melee weapon to grant +15 strength.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 6,
          [ReagentData['essence']['greatereternal']] = 6,
          [ReagentData['dust']['illusion']] = 4,
          [ReagentData['element']['essenceofearth']] = 2,
         },
    },
    ['Runed Arcanite Rod'] = {
         skill = 290 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = '[BoP]',
         reagents = {
          [ReagentData['rod']['arcanite']] = 1,
          [ReagentData['pearl']['golden']] = 1,
          [ReagentData['dust']['illusion']] = 10,
          [ReagentData['essence']['greatereternal']] = 4,
          [ReagentData['shard']['smallbrilliant']] = 4,
          [ReagentData['shard']['largebrilliant']] = 2,
         },
    },
    ['Enchant 2H Weapon - Superior Impact'] = {
         skill = 295 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a two-handed melee weapon to do +9 damage.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 4,
          [ReagentData['dust']['illusion']] = 10,
         },
    },
    ['Enchant Boots - Greater Agility'] = {
         skill = 295 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant boots to give +7 Agility.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['greatereternal']] = 8,
         },
    },
    ['Enchant Bracer - Superior Strength'] = {
         skill = 295 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchants bracers to give +9 Strength.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['dust']['illusion']] = 6,
          [ReagentData['essence']['greatereternal']] = 6,
         },
    },
    ['Enchant Gloves - Greater Strength'] = {
         skill = 295 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant gloves to grant +7 Strength.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['essence']['greatereternal']] = 4,
          [ReagentData['dust']['illusion']] = 4,
         },
    },
    ['Enchant Weapon - Unholy Weapon'] = {
         skill = 295 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a melee weapon to often inflict a curse on the target reducing their melee damage.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 4,
          [ReagentData['element']['essenceofundeath']] = 4,
         },
    },
    ['Enchant 2H Weapon - Major Intellect'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a Two-Handed Melee Weapon to add 9 to intellect.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['essence']['greatereternal']] = 12,
          [ReagentData['shard']['largebrilliant']] = 2,
         },
    },
    ['Enchant 2H Weapon - Major Spirit'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a Two-Handed Melee Weapon to add 9 to Spirit.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['essence']['greatereternal']] = 12,
          [ReagentData['shard']['largebrilliant']] = 2,
         },
    },
    ['Enchant Bracer - Healing Power'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchants bracers to increase the effects of your healing spells by 24.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 2,
          [ReagentData['dust']['illusion']] = 20,
          [ReagentData['essence']['greatereternal']] = 4,
          [ReagentData['element']['livingessence']] = 6,
         },
    },
    ['Enchant Bracer - Superior Stamina'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchants bracers to give +9 Stamina.',
         tools = 'Runed Truesilver Rod',
         reagents = {
          [ReagentData['dust']['illusion']] = 15,
         },
    },
    ['Enchant Chest - Greater Stats'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a piece of chest armor to grant +4 to all stats.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 4,
          [ReagentData['dust']['illusion']] = 15,
          [ReagentData['essence']['greatereternal']] = 10,
         },
    },
    ['Enchant Weapon - Crusader'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a melee weapon so that often when attacking in melee it heals for 75 to 125 and increases Strength by 100 for 15 sec.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 4,
          [ReagentData['monster']['righteousorb']] = 2,
         },
    },
    ['Enchant Weapon - Healing Power'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a Melee Weapon to add up to 55 points of healing to healing spells.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 4,
          [ReagentData['essence']['greatereternal']] = 8,
          [ReagentData['element']['livingessence']] = 6,
          [ReagentData['element']['essenceofwater']] = 6,
          [ReagentData['monster']['righteousorb']] = 1,
         },
    },
    ['Enchant Weapon - Lifestealing'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a melee weapon to often steal life from the enemy and give it to the wielder.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 6,
          [ReagentData['element']['essenceofundeath']] = 6,
          [ReagentData['element']['livingessence']] = 6,
         },
    },
    ['Enchant Weapon - Mighty Intellect'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchant a melee weapon to grant +22 Intellect.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 15,
          [ReagentData['essence']['greatereternal']] = 12,
          [ReagentData['dust']['illusion']] = 20,
         },
    },
    ['Enchant Weapon - Mighty Spirit'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchant a melee weapon to grant +20 Spirit.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 10,
          [ReagentData['essence']['greatereternal']] = 8,
          [ReagentData['dust']['illusion']] = 15,
         },
    },
    ['Enchant Weapon - Spell Power'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a Melee Weapon to add up to 30 damage to spells.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 4,
          [ReagentData['essence']['greatereternal']] = 12,
          [ReagentData['element']['essenceoffire']] = 4,
          [ReagentData['element']['essenceofwater']] = 4,
          [ReagentData['element']['essenceofair']] = 4,
          [ReagentData['pearl']['golden']] = 2,
         },
    },
    ['Enchant Weapon - Superior Striking'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a Melee Weapon to do 5 additional points of damage.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 2,
          [ReagentData['essence']['greatereternal']] = 10,
          
         },
    },
    ['Enchant Gloves - Threat'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant gloves to increase threat from all attacks and spells by 2%.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 6,
          [ReagentData['shard']['nexuscrystal']] = 4,
          [ReagentData['monster']['larvalacid']] = 4,
         },
    },
    ['Enchant Gloves - Shadow Power'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant gloves to increase shadow damage by up to 20.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 10,
          [ReagentData['shard']['nexuscrystal']] = 3,
          [ReagentData['element']['essenceofundeath']] = 4,
         },
    },
    ['Enchant Gloves - Frost Power'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant gloves to increase frost damage by up to 20.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 10,
          [ReagentData['shard']['nexuscrystal']] = 3,
          [ReagentData['element']['essenceofwater']] = 4,
         },
    },
    ['Enchant Gloves - Fire Power'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant gloves to increase fire damage by up to 20.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 10,
          [ReagentData['shard']['nexuscrystal']] = 2,
          [ReagentData['element']['essenceoffire']] = 4,
         },
    },
    ['Enchant Gloves - Healing Power'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = "Permanently enchant gloves to increase the caster\'s healing spells by up to 30.",
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 8,
          [ReagentData['shard']['nexuscrystal']] = 3,
          [ReagentData['monster']['righteousorb']] = 1,
         },
    },
    ['Enchant Gloves - Superior Agility'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant gloves to increase agility by 15.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 8,
          [ReagentData['shard']['nexuscrystal']] = 3,
          [ReagentData['element']['essenceofair']] = 4,
         },
    },
    ['Enchant Cloak - Greater Fire Resistance'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchant a cloak to give 15 fire resistance.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 8,
          [ReagentData['shard']['nexuscrystal']] = 3,
          [ReagentData['element']['essenceoffire']] = 4,
         },
    },
    ['Enchant Cloak - Greater Nature Resistance'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'Permanently enchant a cloak to give 15 nature resistance.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 8,
          [ReagentData['shard']['nexuscrystal']] = 2,
          [ReagentData['element']['livingessence']] = 4,
         },
    },
    ['Enchant Cloak - Stealth'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a cloak to give a increase to stealth.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 8,
          [ReagentData['shard']['nexuscrystal']] = 3,
          [ReagentData['herb']['blacklotus']] = 2,
         },
    },
    ['Enchant Cloak - Subtelty'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a cloak to decrease threat caused by the wearer by 2%.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 6,
          [ReagentData['shard']['nexuscrystal']] = 4,
          [ReagentData['gem']['blackdiamond']] = 2,
         },
    },
    ['Enchant Cloak - Dodge'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Drop',
         description = 'Permanently enchant a cloak to give a 1% chance to dodge.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 8,
          [ReagentData['shard']['nexuscrystal']] = 3,
          [ReagentData['monster']['guardianstone']] = 2,
         },
    },
    ['Brilliant Wizard Oil'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'While applied to target weapon it increases spell damage by up to 36 and increases Spell Critical chance by 1% . Lasts for 30 minutes.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 2,
          [ReagentData['herb']['firebloom']] = 3,
          [ReagentData['vial']['imbued']] = 2,
         },
    },
    ['Brilliant Mana Oil'] = {
         skill = 300 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'While applied to target weapon it restores 12 mana to the caster every 5 seconds and increases the effect of healing spells by up to 25. Lasts for 30 minutes. ',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['shard']['largebrilliant']] = 2,
          [ReagentData['herb']['purplelotus']] = 3,
          [ReagentData['vial']['imbued']] = 1,
         },
    },
    ['Wizard Oil'] = {
         skill = 275 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'While applied to target weapon it increases spell damage by up to 24. Lasts for 30 minutes.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['dust']['illusion']] = 3,
          [ReagentData['herb']['firebloom']] = 2,
          [ReagentData['vial']['crystal']] = 1,
         },
    },
    ['Lesser Mana Oil'] = {
         skill = 250 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'While applied to target weapon it restores 8 mana to the caster every 5 seconds. Lasts for 30 minutes.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['dust']['dream']] = 3,
          [ReagentData['herb']['purplelotus']] = 2,
          [ReagentData['vial']['crystal']] = 1,
         },
    },
    ['Lesser Wizard Oil'] = {
         skill = 200 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'While applied to target weapon it increases spell damage by up to 16. Lasts for 30 minutes.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['dust']['vision']] = 3,
          [ReagentData['reagent']['stranglethornseed']] = 1,
          [ReagentData['vial']['leaded']] = 1,
         },
    },
    ['Minor Mana Oil'] = {
         skill = 150 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'While applied to target weapon it restores 4 mana to the caster every 5 seconds. Lasts for 30 minutes.',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['dust']['soul']] = 3,
          [ReagentData['reagent']['mapleseed']] = 2,
          [ReagentData['vial']['leaded']] = 1,
         },
    },
    ['Minor Wizard Oil'] = {
         skill = 45 ,
         type = 'Enchanting',
         source = 'Vendor',
         description = 'While applied to target weapon it increases spell damage by up to 8. Lasts for 30 minutes. ',
         tools = 'Runed Arcanite Rod',
         reagents = {
          [ReagentData['dust']['strange']] = 2,
          [ReagentData['reagent']['mapleseed']] = 1,
          [ReagentData['vial']['empty']] = 1,
         },
    },
   }
end