------<<<<<< English Localization >>>>>>------
------<<<<<< -------------------- >>>>>>------
if GetLocale()=="enUS"
or GetLocale()=="enGB" then

TITAN_ZONELEVEL_MENU_TEXT = "Zone Level";
TITAN_ZONELEVEL_BUTTON_TEXT = "Zone Level: %s";
TITAN_ZONELEVEL_TOOLTIP = "Zone Level";
TITAN_ZONELEVEL_MENU_SHOW_ZONE_NAME = "Show Zone Name";
TITAN_ZONELEVEL_MENU_SHOW_NAME = "Hide \"Zone Level:\"";
TITAN_ZONELEVEL_TEXT = "%s - %s";
TITAN_ZONELEVEL_LOADING ="Loading"
TITAN_ZONELEVEL_PVP = "PVP: "
TITAN_ZONELEVEL_HOSTILE = "hostile"
TITAN_ZONELEVEL_FRIENDLY = "friendly"
TITAN_ZONELEVEL_CONTESTED = "contested"

ZONELEVEL_ZONENOTFOUND = "Unknown zone: \"%s\"";
ZONELEVEL_ZONENOTFOUNDTOOLTIP = "Zone info unavailable";
ZONELEVEL_CITYTEXT = "Level range: N/A";
ZONELEVEL_ZONETEXT = TitanUtils_GetNormalText("Level range: ");

--<< A >>--
TITAN_ZONELEVEL_ABAS = "Abyssal Sands"; -- 41 / 54 --
TITAN_ZONELEVEL_ADST = "Addle's Stead"; -- 19 / 26 --
TITAN_ZONELEVEL_AEPE = "Aerie Peak"; -- 41 / 41 --
TITAN_ZONELEVEL_AGGO = "Agama'gor"; -- 13 / 22 --
TITAN_ZONELEVEL_AGFACR = "Agamand Family Crypt"; -- 9 / 13 --
TITAN_ZONELEVEL_AGMI = "Agamand Mills"; -- 6 / 11 --
TITAN_ZONELEVEL_AGEN = "Agmond's End"; -- 37 / 43 --
TITAN_ZONELEVEL_AGFO = "Agnor Fortress"; -- 35 / 39 --
TITAN_ZONELEVEL_AGWA = "Agol'watha"; -- 43 / 48 --
TITAN_ZONELEVEL_ALFA = "Alexston Farmstead"; -- 11 / 19 --
TITAN_ZONELEVEL_ALST = "Algaz Station"; -- 10 / 12 --
TITAN_ZONELEVEL_ALOFST = "Altar of Storms"; -- 53 / 57 --
TITAN_ZONELEVEL_ALMO = "Alterac Mountains"; -- 21 / 37 --
TITAN_ZONELEVEL_ALVA = "Alterac Valley"; -- 30 / 50 --
TITAN_ZONELEVEL_ALMI = "Alther's Mill"; -- 16 - 21 --
TITAN_ZONELEVEL_AM = "Ambermill"; -- 12 / 21 --
TITAN_ZONELEVEL_AMRA = "Amberstill Ranch"; -- 6 / 12 --
TITAN_ZONELEVEL_AMAR = "Ameth'aran"; -- 10 / 16 --
TITAN_ZONELEVEL_ANEN = "Angerfang Encampment"; -- 24 / 32 --
TITAN_ZONELEVEL_ANFO = "Angor Fortress"; -- 35 / 39 --
TITAN_ZONELEVEL_APRE = "Apocryphan's Rest"; -- 39 / 41 --
TITAN_ZONELEVEL_ARHI = "Arathi Highlands"; -- 30 / 50 --
TITAN_ZONELEVEL_ASH = "Ashenvale"; -- 18 / 40 --
TITAN_ZONELEVEL_AST = "Astranaar"; -- 19 / 37 --
TITAN_ZONELEVEL_AU = "Auberdine"; -- 0 / 0 --
TITAN_ZONELEVEL_AZ = "Azshara"; -- 44 / 55 --
TITAN_ZONELEVEL_AZMI = "Azurelode Mine"; -- 24 / 30 --

--<< B >>--
TITAN_ZONELEVEL_BA = "Badlands"; -- 35 / 55 --
TITAN_ZONELEVEL_BAMO = "Bael Modan"; -- 22 / 30 --
TITAN_ZONELEVEL_BAKE = "Bael'dun Keep"; -- 23 / 30 --
TITAN_ZONELEVEL_BADU = "Bael'dunigsite" ; -- 7 / 9 --
TITAN_ZONELEVEL_BALARU = "Bal'lal Ruins"; -- 32 / 55 --
TITAN_ZONELEVEL_BAMARU = "Balia'mah Ruins"; -- 37 / 42 --
TITAN_ZONELEVEL_BAFA = "Balnir Farmstead"; -- 7 / 11 --
TITAN_ZONELEVEL_BABA = "Baradin Bay"; -- 20 / 22 --
TITAN_ZONELEVEL_BAR = "Barrowens"; -- 50 / 52 --
TITAN_ZONELEVEL_BAAR = "Bashal'Aran"; -- 10 / 17 --
TITAN_ZONELEVEL_BAHA = "Bathran's Haunt"; -- 19 / 20 --
TITAN_ZONELEVEL_BAST = "Bay of Storms"; -- 52 / 60 --
TITAN_ZONELEVEL_BEHE = "Bear's Head"; -- 46 / 53 --
TITAN_ZONELEVEL_BEHA = "Beggar's Haunt"; -- 0 / 0 --
TITAN_ZONELEVEL_BEPE = "Beren's Peril"; -- 19 / 21 --
TITAN_ZONELEVEL_BIRE = "Bitter Reaches"; -- 52 / 55 --
TITAN_ZONELEVEL_BLCHMA = "Black Channel Marsh"; -- 20 / 25 --
TITAN_ZONELEVEL_BLDE = "Blackfathom Deeps"; -- 20 / 27 --
TITAN_ZONELEVEL_BLE = "Blackfathomeeps"; -- 18 / 30 --
TITAN_ZONELEVEL_BLDE = "Blackrock Depths" -- 48 / 56 --
TITAN_ZONELEVEL_BLMO = "Blackrock Mountain"; -- 46 / 58 --
TITAN_ZONELEVEL_BLPA = "Blackrock Pass"; -- 51 / 53 --
TITAN_ZONELEVEL_BLSP = "Blackrock Spire"; -- 53 / 55 --
TITAN_ZONELEVEL_BLST = "Blackrock Stronghold"; -- 54 / 58 --
TITAN_ZONELEVEL_BLRI = "Blackthorn Ridge"; -- 20 / 26 --
TITAN_ZONELEVEL_BLCO = "Blackwater Cove"; -- 0 / 0 --
TITAN_ZONELEVEL_BLSH = "Blackwater Shipwrecks"; -- 0 / 0 --
TITAN_ZONELEVEL_BLRI = "Blackwolf River"; -- 18 / 25 --
TITAN_ZONELEVEL_BLLA = "Blackwood Lake"; -- 54 / 58 --
TITAN_ZONELEVEL_BLA = "Blackwooden"; -- 16 / 20 --
TITAN_ZONELEVEL_BLBA = "Bladefist Bay"; -- 5 / 10 --
TITAN_ZONELEVEL_BLLAN = "Blasted Lands"; -- 45 / 57 --
TITAN_ZONELEVEL_BLVI = "Bloodhoof Village"; -- 5 / 14 --
TITAN_ZONELEVEL_BLCO = "Bloodsail Compound"; -- 40 / 43 --
TITAN_ZONELEVEL_BLFA = "Bloodvenom Falls"; -- 49 / 56 --
TITAN_ZONELEVEL_BLPO = "Bloodvenom Post"; -- 55 / 62 --
TITAN_ZONELEVEL_BLRIV = "Bloodvenom River"; -- 49 / 62 --
TITAN_ZONELEVEL_BLU = "Bluefen"; -- 35 / 37 --
TITAN_ZONELEVEL_BLMA = "Bluegill Marsh"; -- 20 / 25 --
TITAN_ZONELEVEL_BOLE = "Bogen's Ledge"; -- 42 / 45 --
TITAN_ZONELEVEL_BOHO = "Bolgan's Hole"; -- 33 / 37 --
TITAN_ZONELEVEL_BOBA = "Booty Bay"; -- 30 / 60 --
TITAN_ZONELEVEL_BOSH = "Bough Shadow"; -- 61 / 62 --
TITAN_ZONELEVEL_BOLOADMI = "Boulder Load Mine"; -- 0 / 0 --
TITAN_ZONELEVEL_BOLODEMI = "Boulder Lode Mine"; -- 14 / 19 --
TITAN_ZONELEVEL_BOGO = "Boulder'gor"; -- 30 / 50 --
TITAN_ZONELEVEL_BOHA = "Boulderfist Hall"; -- 35 / 39 --
TITAN_ZONELEVEL_BOOU = "Boulderfist Outpost"; -- 33 / 36 --
TITAN_ZONELEVEL_BORA = "Boulderslide Ravine"; -- 16 / 20 --
TITAN_ZONELEVEL_BRAVI = "Brackenwall Village"; -- 36 / 55 --
TITAN_ZONELEVEL_BRPUPA = "Brackwell Pumpkin Patch"; -- 7 / 10 --
TITAN_ZONELEVEL_BRA = "Bramblescar"; -- 16 / 26 --
TITAN_ZONELEVEL_BRWIME = "Brave Wind Mesa"; --  0 / 0 --
TITAN_ZONELEVEL_BREVI = "Brewnall Village"; -- 7 / 8 --
TITAN_ZONELEVEL_BRLA = "Brightwater Lake"; -- 6 / 16 --
TITAN_ZONELEVEL_BRGR = "Brightwood Grove"; -- 20 / 29 --
TITAN_ZONELEVEL_BRI = "Brill"; -- 5 / 7 --
TITAN_ZONELEVEL_BRPI = "Broken Pillar"; -- 43 / 48 --
TITAN_ZONELEVEL_BRMI = "Browman Mill"; -- 55 / 60 --
TITAN_ZONELEVEL_BUFA = "Bucklebree Farm"; -- 0 / 0 --
TITAN_ZONELEVEL_BUBLCO = "Burning Blade Coven"; -- 3 / 5 --
TITAN_ZONELEVEL_BUST = "Burning Steppes"; -- 50 / 58 --

--<< C >>--
TITAN_ZONELEVEL_CA = "Caerarrow"; -- 0 / 0 --
TITAN_ZONELEVEL_CAAP = "Camp Aparaje"; -- 14 / 17 --
TITAN_ZONELEVEL_CABO = "Camp Boff"; -- 36 / 43 --
TITAN_ZONELEVEL_CACA = "Camp Cagg"; -- 36 / 45 --
TITAN_ZONELEVEL_CAET = "Camp E'thok"; -- 26 / 30 --
TITAN_ZONELEVEL_CAKO = "Camp Kosh"; -- 35 / 35 --
TITAN_ZONELEVEL_CAMO = "Camp Mojache"; -- 30 / 65 --
TITAN_ZONELEVEL_CATA = "Camp Taurajo"; -- 15 / 40 --
TITAN_ZONELEVEL_CAWU = "Camp Wurg"; -- 36 / 43 --
TITAN_ZONELEVEL_CAOFTI = "Caverns of Time"; -- 50 / 50 --
TITAN_ZONELEVEL_CHBRVA = "Chill Breeze Valley"; -- 6 / 11 --
TITAN_ZONELEVEL_CHPO = "Chillwind Point"; -- 30 / 58 --
TITAN_ZONELEVEL_CIOFEABI = "Circle of East Binding"; -- 30 / 42 --
TITAN_ZONELEVEL_CIOFINBI = "Circle of Inner Binding"; -- 30 / 42 --
TITAN_ZONELEVEL_CIOFOUBI = "Circle of Outer Binding"; -- 30 / 42 --
TITAN_ZONELEVEL_CIOFWEBI = "Circle of West Binding"; -- 30 / 39 --
TITAN_ZONELEVEL_CLFA = "Cliffspring Falls"; -- 13 / 17 --
TITAN_ZONELEVEL_CLRI = "Cliffspring River"; -- 13 / 20 --
TITAN_ZONELEVEL_COHEMA = "Cold Hearth Manor"; -- 5 / 9 --
TITAN_ZONELEVEL_COPA = "Coldridge Pass"; -- 1 / 6 --
TITAN_ZONELEVEL_COVA = "Coldridge Valley"; -- 1 / 5 --
TITAN_ZONELEVEL_COCR = "Corin's Crossing"; -- 54 / 58 --
TITAN_ZONELEVEL_COSA = "Corrahn'sagger"; -- 20 / 34 --
TITAN_ZONELEVEL_CRLA = "Cragpool Lake"; -- 18 / 27 --
TITAN_ZONELEVEL_CRGUTO = "Crown Guard Tower"; -- 53 / 55 --
TITAN_ZONELEVEL_CROU = "Crusader Outpost"; -- 7 / 11 --
TITAN_ZONELEVEL_CRSOU = "Crusader's Outpost"; -- 6 / 7 --
TITAN_ZONELEVEL_CRHO = "Crushridge Hold"; -- 35 / 36 --
TITAN_ZONELEVEL_CRLA = "Crystal Lake"; -- 5 / 9 --
TITAN_ZONELEVEL_CRMI = "Crystalvein Mine"; -- 41 / 42 --

--<< D >>--
TITAN_ZONELEVEL_DAFA = "Dabyrie's Farmstead"; -- 30 / 35 --
TITAN_ZONELEVEL_DAL = "Dalaran"; -- 24 / 35 --
TITAN_ZONELEVEL_DATE = "Dalson's Tears"; -- 50 / 56 --
TITAN_ZONELEVEL_DAFO = "Dandred's Fold"; -- 30 / 40 --
TITAN_ZONELEVEL_DAPO = "Dark Portal"; -- 49 / 61 --
TITAN_ZONELEVEL_DAPI = "Darkcloud Pinnacle"; -- 24 / 34 --
TITAN_ZONELEVEL_DARI = "Darkshire"; -- 2 / 40 --
TITAN_ZONELEVEL_DARO = "Darkshore"; -- 9 / 26 --
TITAN_ZONELEVEL_DAST = "Darkspear Strand"; -- 1 / 8 --
TITAN_ZONELEVEL_DAGO = "Darkwhisper Gorge"; -- 59 / 60 --
TITAN_ZONELEVEL_DAR = "Darnassus"; -- 0 / 0 --
TITAN_ZONELEVEL_DAHI = "Darrow Hill"; -- 22 / 32 --
TITAN_ZONELEVEL_DALA = "Darrowmere Lake"; -- 12 / 60 --
TITAN_ZONELEVEL_DARR = "Darrowshire"; -- 53 / 55 --
TITAN_ZONELEVEL_DAWOCA = "Dawning Wood Catacombs"; -- 25 / 29 --
TITAN_ZONELEVEL_DESH = "Deadeye Shore"; -- 2 / 8 --
TITAN_ZONELEVEL_DECR = "Deadman's Crossing"; -- 55 / 56 --
TITAN_ZONELEVEL_DEAD = "Deadmines" -- 15 / 20 --
TITAN_ZONELEVEL_DEPA = "Deadwind Pass"; -- 55 / 56 --
TITAN_ZONELEVEL_DEVI = "Deadwood Village"; -- 47 / 53 --
TITAN_ZONELEVEL_DEAT = "Deathknell"; -- 1 / 5 --
TITAN_ZONELEVEL_DEELMI = "Deep Elem Mine"; -- 11 / 15 --
TITAN_ZONELEVEL_DEFACA = "Demon Fall Canyon"; -- 29 / 30 --
TITAN_ZONELEVEL_DEFARI = "Demon Fall Ridge"; -- 0 / 0 --
TITAN_ZONELEVEL_DEST = "Demonic Stronghold"; -- 0 / 0 --
TITAN_ZONELEVEL_DEPL = "Demont's Place"; -- 14 / 17 --
TITAN_ZONELEVEL_DES = "Desolace"; -- 30 / 40 --
TITAN_ZONELEVEL_DIMA = "Dire Maul"; -- 43 / 47 --
TITAN_ZONELEVEL_DIHI = "Direforge Hill"; -- 0 / 0 --
TITAN_ZONELEVEL_DRDA = "Draco'dar"; -- 55 / 58 --
TITAN_ZONELEVEL_DRGA = "Dragonmaw Gates"; -- 0 / 0 --
TITAN_ZONELEVEL_DRHO = "Dreadmaul Hold"; -- 45 / 58 --
TITAN_ZONELEVEL_DRPO = "Dreadmaul Post"; -- 50 / 55 --
TITAN_ZONELEVEL_DRRO = "Dreadmaul Rock"; -- 50 / 56 --
TITAN_ZONELEVEL_DRPE = "Dreadmist Peak"; -- 10 / 25 --
TITAN_ZONELEVEL_DRE = "Dreadmisten"; -- 10 / 15 --
TITAN_ZONELEVEL_DRSH = "Dreadmurk Shore"; -- 35 / 38 --
TITAN_ZONELEVEL_DRBO = "Dream Bough"; -- 62 / 62 --
TITAN_ZONELEVEL_DRRA = "Drygulch Ravine"; -- 5 / 11 --
TITAN_ZONELEVEL_DRGO = "Drywhisker Gorge"; -- 35 / 38 --
TITAN_ZONELEVEL_DUAL = "Dun Algaz"; -- 11 / 22 --
TITAN_ZONELEVEL_DUBA = "Dun Baldar"; -- 0 / 0 --
TITAN_ZONELEVEL_DUGA = "Dun Garok"; -- 24 / 32 --
TITAN_ZONELEVEL_DUMA = "Dun Mandarr"; -- 56 / 59 --
TITAN_ZONELEVEL_DUMOD = "Dun Modr"; -- 27 / 34 --
TITAN_ZONELEVEL_DUMORO = "Dun Morogh"; -- 5 / 12 --
TITAN_ZONELEVEL_DUCO = "Dunemaul Compound"; -- 50 / 43 --
TITAN_ZONELEVEL_DUKE = "Durnholde Keep"; -- 20 / 40 --
TITAN_ZONELEVEL_DUR = "Durotar"; -- 1 / 45 --
TITAN_ZONELEVEL_DUS = "Duskwood"; -- 18 / 40 --
TITAN_ZONELEVEL_DUGR = "Dustbelch Grotto"; -- 0 / 0 --
TITAN_ZONELEVEL_DUBA = "Dustwallow Bay"; -- 35 / 43 --
TITAN_ZONELEVEL_DUMA = "Dustwallow Marsh"; -- 22 / 55 --
TITAN_ZONELEVEL_DUCA = "Dustwind Cave"; -- 8 / 11 --
TITAN_ZONELEVEL_DUGU = "Dustwind Gulch"; -- 35 / 40 --

--<< E >>--
TITAN_ZONELEVEL_EAPI = "East Pillar"; -- 0 / 0 --
TITAN_ZONELEVEL_EAPL = "Eastern Plaguelands"; -- 12 / 60 --
TITAN_ZONELEVEL_EAST = "Eastern Strand"; -- 26 / 32 --
TITAN_ZONELEVEL_EARU = "Eastmoon Ruins"; -- 43 / 48 --
TITAN_ZONELEVEL_EALOCA = "Eastvale Logging Camp"; -- 8 / 10 --
TITAN_ZONELEVEL_EAGA = "Eastwall Gate"; -- 56 / 57 --
TITAN_ZONELEVEL_EATO = "Eastwall Tower"; -- 56 / 59 --
TITAN_ZONELEVEL_ECIS = "Echo Isles"; -- 2 / 10 --
TITAN_ZONELEVEL_ESRIMI = "Echo Ridge Mine"; -- 3 / 8 --
TITAN_ZONELEVEL_ELFO = "Elwynn Forest"; -- 1 / 12 --
TITAN_ZONELEVEL_EMSE = "Emberstrife'sen"; -- 61 / 61 --
TITAN_ZONELEVEL_EMSA = "Emerald Sanctuary"; -- 47 / 49 --
TITAN_ZONELEVEL_ETRE = "Ethel Rethor"; -- 31 / 35 --
TITAN_ZONELEVEL_EVE = "Everlook"; -- 30 / 60 --

--<< F >>--
TITAN_ZONELEVEL_FACO = "Faldir's Cove"; -- 39 / 40 --
TITAN_ZONELEVEL_FARI = "Falfarren River"; -- 24 / 28 --
TITAN_ZONELEVEL_FASKLA = "Fallen Sky Lake"; -- 19 / 30 --
TITAN_ZONELEVEL_FASA = "Fallow Sanctuary"; -- 25 / 41 --
TITAN_ZONELEVEL_FARE = "Faol's Rest"; -- 0 / 0 --
TITAN_ZONELEVEL_FAWAPO = "Far Watch Post"; -- 4 / 14 --
TITAN_ZONELEVEL_FAMI = "Fargodeep Mine"; -- 5 / 20 --
TITAN_ZONELEVEL_FEHO = "Featherbeard's Hovel"; -- 41 / 42 --
TITAN_ZONELEVEL_FEST = "Feathermoon Stronghold"; -- 40 / 62 --
TITAN_ZONELEVEL_FEHI = "Felfire Hill"; -- 26 / 30 --
TITAN_ZONELEVEL_FEVI = "Felpaw Village"; -- 51 / 56 --
TITAN_ZONELEVEL_FEFI = "Felstone Field"; -- 50 / 54 --
TITAN_ZONELEVEL_FEL = "Felwood"; -- 1 / 55 --
TITAN_ZONELEVEL_FEIS = "Fenris Isle"; -- 15 / 31 --
TITAN_ZONELEVEL_FEKE = "Fenris Keep"; -- 16 / 24 --
TITAN_ZONELEVEL_FESCVA = "Feral Scar Vale"; -- 41 / 46 --
TITAN_ZONELEVEL_FER = "Feralas"; -- 30 / 62 --
TITAN_ZONELEVEL_FIOFGI = "Field of Giants"; -- 18 / 26 --
TITAN_ZONELEVEL_FIPLRI = "Fire Plume Ridge"; -- 50 / 56 --
TITAN_ZONELEVEL_FISCSH = "Fire Scar Shrine"; -- 22 / 24 --
TITAN_ZONELEVEL_FISTME = "Fire Stone Mesa"; -- 0 / 0 --
TITAN_ZONELEVEL_FLCR = "Flame Crest"; -- 54 / 57 --
TITAN_ZONELEVEL_FOSO = "Forest Song"; -- 26 / 62 --
TITAN_ZONELEVEL_FOED = "Forest's Edge"; -- 5 / 20 --
TITAN_ZONELEVEL_FOTO = "Forgewright's Tomb"; -- 60 / 60 --
TITAN_ZONELEVEL_FORI = "Forlorn Ridge"; -- 46 / 47 --
TITAN_ZONELEVEL_FORO = "Forlorn Rowe"; -- 20 / 35 --
TITAN_ZONELEVEL_FRIS = "Fray Island"; -- 14 / 14 --
TITAN_ZONELEVEL_FRHI = "Frayfeather Highlands"; -- 43 / 47 --
TITAN_ZONELEVEL_FRPO = "Freewind Post"; -- 20 / 55 --
TITAN_ZONELEVEL_FRHOSP = "Frostfire Hot Springs"; -- 53 / 56 --
TITAN_ZONELEVEL_FRHO = "Frostmane Hold"; -- 7 / 11 --
TITAN_ZONELEVEL_FRRO = "Frostsaber Rock"; -- 50 / 60 --
TITAN_ZONELEVEL_FRGO = "Frostwhisper Gorge"; -- 59 / 60 --
TITAN_ZONELEVEL_FRKE = "Frostwolf Keep"; -- 0 / 0 --
TITAN_ZONELEVEL_FURO = "Fungal Rock"; -- 50 / 55 --
TITAN_ZONELEVEL_FUPUFA = "Furlbrow's Pumpkin Farm"; -- 9 / 15 --

--<< G >>--
TITAN_ZONELEVEL_GAD = "Gadgetzan"; -- 40 / 43 --
TITAN_ZONELEVEL_GAWI = "Gahrron's Withering"; -- 55 / 58 --
TITAN_ZONELEVEL_GACR = "Galak Crag"; -- 0 / 0 --
TITAN_ZONELEVEL_GAHO = "Galak Hold"; -- 0 / 0 --
TITAN_ZONELEVEL_GAVA = "Galardell Valley"; -- 21 / 26 --
TITAN_ZONELEVEL_GACO = "Gallows' Corner"; -- 33 / 36 --
TITAN_ZONELEVEL_GAHA = "Garren's Haunt"; -- 6 / 10 --
TITAN_ZONELEVEL_GAAR = "Garrison Armory"; -- 46 / 50 --
TITAN_ZONELEVEL_GAOFIR = "Gates of Ironforge"; -- 7 / 8 --
TITAN_ZONELEVEL_GANA = "Gavin's Naze"; -- 24 / 34 --
TITAN_ZONELEVEL_GEVI = "Gelkis Village"; -- 32 / 36 --
TITAN_ZONELEVEL_GHWAPO = "Ghost Walker Post"; -- 35 / 50 --
TITAN_ZONELEVEL_GIIS = "Gillijim's Isle"; -- 0 / 0 --
TITAN_ZONELEVEL_GNO = "Gnomeregan"; -- 9 / 35 --
TITAN_ZONELEVEL_GOSKFA = "Go'Shek Farm"; -- 32 / 38 --
TITAN_ZONELEVEL_GOBOQU = "Gol'Bolar Quarry"; -- 7 / 10 --
TITAN_ZONELEVEL_GOHOSP = "Golakka Hot Springs"; -- 52 / 55 --
TITAN_ZONELEVEL_GOCOQU = "Gold Coast Quarry"; -- 10 / 17 --
TITAN_ZONELEVEL_GORO = "Gold Road"; -- 10 / 26 --
TITAN_ZONELEVEL_GOL = "Goldshire"; -- 1 / 6 --
TITAN_ZONELEVEL_GOOU = "Gordunni Outpost"; -- 40 / 43 --
TITAN_ZONELEVEL_GRVA = "Greatwood Vale"; -- 14 / 17 --
TITAN_ZONELEVEL_GRVI = "Greenpaw Village"; -- 22 / 35 --
TITAN_ZONELEVEL_GRBA = "Grim Batol"; -- 0 / 0 --
TITAN_ZONELEVEL_GRCO = "Grimtotem Compound"; -- 40 / 44 --
TITAN_ZONELEVEL_GRPO = "Grimtotem Post"; -- 15 / 22 --
TITAN_ZONELEVEL_GRRI = "Grizzlepaw Ridge"; -- 11 / 20 --
TITAN_ZONELEVEL_GRFA = "Grol'dom Farm"; -- 11 / 16 --
TITAN_ZONELEVEL_GRBACA = "Grom'gol Base Camp"; -- 33 / 60 --
TITAN_ZONELEVEL_GRAN = "Grove of the Ancients"; -- 15 / 19 --
TITAN_ZONELEVEL_GRCA = "Growless Cave"; -- 32 / 37 --
TITAN_ZONELEVEL_GUPO = "Gunstan's Post"; -- 0 / 0 --
TITAN_ZONELEVEL_GURE = "Gunther's Retreat"; -- 7 / 9 --
TITAN_ZONELEVEL_GUAR = "Gurubashi Arena"; -- 37 / 44 --

--<< H >>--
TITAN_ZONELEVEL_HAEN = "Haldarr Encampment"; -- 44 / 53 --
TITAN_ZONELEVEL_HAM = "Hammerfall"; -- 30 / 38 --
TITAN_ZONELEVEL_HASISI1 = "Hammertoe'sig Site"; -- 0 / 0 --
TITAN_ZONELEVEL_HASISI2 = "Hammertoe'sigsite"; -- 35 / 39 --
TITAN_ZONELEVEL_HEA = "Hearthglenn"; -- 55 / 61 --
TITAN_ZONELEVEL_HEBELA = "Helm's Bed Lake"; -- 7 / 12 --
TITAN_ZONELEVEL_HECL = "Hetaera's Clutch"; -- 53 / 55 --
TITAN_ZONELEVEL_HIPA = "Hidden Path"; -- 0 / 0 --
TITAN_ZONELEVEL_HIPE = "High Perch"; -- 28 / 31 --
TITAN_ZONELEVEL_HIWI = "High Wilderness"; -- 41 / 46 --
TITAN_ZONELEVEL_HIG = "Highperch"; -- 27 / 32 --
TITAN_ZONELEVEL_HIFI = "Hillsbrad Fields"; -- 20 / 33 --
TITAN_ZONELEVEL_HIFO = "Hillsbrad Foothills"; -- 20 / 32 --
TITAN_ZONELEVEL_HIL = "Hillsbrad"; -- 26 / 30 --
TITAN_ZONELEVEL_HIWA = "Hiri'watha"; -- 25 / 47 --
TITAN_ZONELEVEL_HOST = "Honor's Stand"; -- 13 / 18 --

--<< I >>--
TITAN_ZONELEVEL_ICTHHI = "Ice Thistle Hills"; -- 55 / 58 --
TITAN_ZONELEVEL_ICGA = "Iceblood Garrison"; -- 0 / 0 --
TITAN_ZONELEVEL_ICLA = "Iceflow Lake"; -- 7 / 10 --
TITAN_ZONELEVEL_IDLA = "Idlewind Lake"; -- 0 / 0 --
TITAN_ZONELEVEL_IRLA = "Iris Lake"; -- 20 / 22 --
TITAN_ZONELEVEL_IRCO = "Ironband's Compound"; -- 9 / 12 --
TITAN_ZONELEVEL_IREXSI = "Ironband's Excavation Site"; -- 13 / 22 --
TITAN_ZONELEVEL_IRTO = "Ironbeard's Tomb"; -- 22 / 26 --
TITAN_ZONELEVEL_IRO = "Ironforge"; -- 0 / 0 --
TITAN_ZONELEVEL_IRPL = "Ironstone Plateau"; -- 48 / 50 --
TITAN_ZONELEVEL_IRCA = "Irontree Cavern"; -- 52 / 54 --
TITAN_ZONELEVEL_IRWO = "Irontree Woods"; -- 1 / 56 --
TITAN_ZONELEVEL_ISOFLA = "Island ofoctor Lapidis"; -- 0 / 0 --
TITAN_ZONELEVEL_ISOF = "Isle of Dread"; -- 43 / 47 --
TITAN_ZONELEVEL_ITCA = "Itharius's Cave"; -- 34 / 37 --

--<< J >>--
TITAN_ZONELEVEL_JAGL = "Jadefire Glen"; -- 47 / 51 --
TITAN_ZONELEVEL_JARU = "Jadefire Run"; -- 49 / 53 --
TITAN_ZONELEVEL_JALA = "Jademir Lake"; -- 60 / 62 --
TITAN_ZONELEVEL_JAE = "Jaedenar"; -- 48 / 53 --
TITAN_ZONELEVEL_JARE = "Jagged Reef"; -- 50 / 53 --
TITAN_ZONELEVEL_JAFA = "Jaggedswine Farm"; -- 2 / 11 --
TITAN_ZONELEVEL_JAIS = "Jaguero Isle"; -- 50 / 55 --
TITAN_ZONELEVEL_JAPO = "Janerio's Point"; -- 0 / 50 --
TITAN_ZONELEVEL_JANMI = "Jangolode Mine"; -- 10 / 19 --
TITAN_ZONELEVEL_JASMI = "Jasperlode Mine"; -- 6 / 8 --
TITAN_ZONELEVEL_JELA = "Jerod's Landing"; -- 8 / 10 --
TITAN_ZONELEVEL_JI = "Jintha'Alor"; -- 5 / 53 --

--<< K >>--
TITAN_ZONELEVEL_KARU = "Kal'ai Ruins"; -- 35 / 36 --
TITAN_ZONELEVEL_KAKE = "Kargathia Keep"; -- 28 / 30 --
TITAN_ZONELEVEL_KAOU = "Kargathia Outpost"; -- 0 / 0 --
TITAN_ZONELEVEL_KAR = "Kargath"; -- 30 / 60 --
TITAN_ZONELEVEL_KHA = "Kharanos"; -- 5 / 30 --
TITAN_ZONELEVEL_KOGR = "Kodo Graveyard"; -- 31 / 38 --
TITAN_ZONELEVEL_KOCR = "Kolkar Crag"; -- 2 / 9 --
TITAN_ZONELEVEL_KOVI = "Kolkar Village"; -- 30 / 33 --
TITAN_ZONELEVEL_KOHU = "Kormek's Hut"; -- 30 / 34 --
TITAN_ZONELEVEL_KUCO = "Kurzen's Compound"; -- 30 / 35 --

--<< L >>--
TITAN_ZONELEVEL_LAEV = "Lake Everstill"; -- 16 / 22 --
TITAN_ZONELEVEL_LAFA = "Lake Falathim"; -- 18 / 20 --
TITAN_ZONELEVEL_LAKE = "Lake Kel'Theril"; -- 54 / 57 --
TITAN_ZONELEVEL_LAMEN = "Lake Mennar"; -- 50 / 54 --
TITAN_ZONELEVEL_LAMER = "Lake Mereldar"; -- 53 / 56 --
TITAN_ZONELEVEL_LANA = "Lake Nazferiti"; -- 30 / 36 --
TITAN_ZONELEVEL_LAHI = "Lakeridge Highway"; -- 14 / 19 --
TITAN_ZONELEVEL_LAK = "Lakeshire"; -- 0 / 0 --
TITAN_ZONELEVEL_LATAPI = "Lakkari Tar Pits"; -- 48 / 61 --
TITAN_ZONELEVEL_LAENBE = "Land's End Beach"; -- 48 / 50 --
TITAN_ZONELEVEL_LAPA = "Lariss Pavillion"; -- 40 / 46 --
TITAN_ZONELEVEL_LEEN = "Legash Encampment"; -- 51 / 51 --
TITAN_ZONELEVEL_LERA = "Lethlor Ravine"; -- 41 / 57 --
TITAN_ZONELEVEL_LIHOCH = "Light's Hope Chapel"; -- 52 / 62 --
TITAN_ZONELEVEL_LIG = "Lighthouse"; -- 0 / 0 --
TITAN_ZONELEVEL_LITAPI = "Lik'ash Tar Pits"; -- 0 / 0 --
TITAN_ZONELEVEL_LOMO = "Loch Modan"; -- 10 / 36 --
TITAN_ZONELEVEL_LON = "Longshore"; -- 10 / 19 --
TITAN_ZONELEVEL_LOINCA = "Lordamere Internment Camp"; -- 24 / 36 --
TITAN_ZONELEVEL_LOLA = "Lordamere Lake"; -- 12 / 35 --
TITAN_ZONELEVEL_LOPO = "Lost Point"; -- 37 / 37 --
TITAN_ZONELEVEL_LORICO = "Lost Rigger Cove"; -- 44 / 54 --
TITAN_ZONELEVEL_LOWI = "Lower Wilds"; -- 36 / 65 --
TITAN_ZONELEVEL_LUOA = "Lushwater Oasis"; -- 12 / 30 --

--<< M >>--
TITAN_ZONELEVEL_MAPO = "Maestra's Post"; -- 18 / 42 --
TITAN_ZONELEVEL_MAVI = "Magram Village"; -- 32 / 37 --
TITAN_ZONELEVEL_MAJI = "Malaka'jin"; -- 20 / 30 --
TITAN_ZONELEVEL_MAOR = "Malden's Orchard"; -- 10 / 12 --
TITAN_ZONELEVEL_MACO = "Mannoroc Coven"; -- 30 / 40 --
TITAN_ZONELEVEL_MAMI = "Manor Mistmantle"; -- 29 / 30 --
TITAN_ZONELEVEL_MARO = "Mantle Rock"; -- 0 / 0 --
TITAN_ZONELEVEL_MAR = "Maraudon"; -- 37 / 50 --
TITAN_ZONELEVEL_MARE = "Marshal's Refuge"; -- 51 / 54 --
TITAN_ZONELEVEL_MAAL = "Mazra'Alor"; -- 58 / 59 --
TITAN_ZONELEVEL_MAZ = "Mazthoril"; -- 56 / 59 --
TITAN_ZONELEVEL_MEBA = "Menethil Bay"; -- 20 / 29 --
TITAN_ZONELEVEL_MEHA = "Menethil Harbor"; -- 0 / 0 --
TITAN_ZONELEVEL_MIFL = "Mirage Flats"; -- 37 / 55 --
TITAN_ZONELEVEL_MILA = "Mirkfallon Lake"; -- 14 / 25 --
TITAN_ZONELEVEL_MILAOR = "Mirror Lake Orchard"; -- 5 / 6 --
TITAN_ZONELEVEL_MILA = "Mirror Lake"; -- 5 / 9 --
TITAN_ZONELEVEL_MIED = "Mist's Edge"; -- 9 / 21 --
TITAN_ZONELEVEL_MIVA = "Mistvale Valley"; -- 40 / 41 --
TITAN_ZONELEVEL_MIPIRE = "Misty Pine Refuge"; -- 7 / 8 --
TITAN_ZONELEVEL_MIREPO = "Misty Reed Post"; -- 39 / 53 --
TITAN_ZONELEVEL_MIREST = "Misty Reed Strand"; -- 12 / 53 --
TITAN_ZONELEVEL_MISH = "Misty Shore"; -- 30 / 31 --
TITAN_ZONELEVEL_MIVA = "Misty Valley"; -- 36 / 42 --
TITAN_ZONELEVEL_MIRU = "Mizjah Ruins"; -- 1 / 50 --
TITAN_ZONELEVEL_MOST = "Mo'Grosh Stronghold"; -- 18 / 20 --
TITAN_ZONELEVEL_MOGO = "Mok'Gordun"; -- 0 / 0 --
TITAN_ZONELEVEL_MOB = "Moonbrook"; -- 1 / 26 --
TITAN_ZONELEVEL_MON = "Moonwell"; -- 23 / 27 --
TITAN_ZONELEVEL_MOVI = "Morgan's Vigil"; -- 0 / 0 --
TITAN_ZONELEVEL_MOAR = "Morlos'Aran"; -- 47 / 49 --
TITAN_ZONELEVEL_MOOGMO = "Mosh'Ogg Ogre Mound"; -- 37 / 42 --
TITAN_ZONELEVEL_MOFE = "Mosshide Fen"; -- 20 / 22 --
TITAN_ZONELEVEL_MUL = "Mulgore"; -- 5 / 14 --
TITAN_ZONELEVEL_MYLA = "Mystral Lake"; -- 21 / 35 --

--<< N >>--
TITAN_ZONELEVEL_NEWE = "Nek'mani Wellspring"; -- 43 / 44 --
TITAN_ZONELEVEL_NEEX = "Nesingwary's Expedition"; -- 30 / 34 --
TITAN_ZONELEVEL_NEST = "Nethander Stead"; -- 24 / 32 --
TITAN_ZONELEVEL_NEKE = "Nethergarde Keep"; -- 55 / 55 --
TITAN_ZONELEVEL_NIRU = "Night Run"; -- 25 / 26 --
TITAN_ZONELEVEL_NIHO = "Night Web's Hollow"; -- 2 / 5 --
TITAN_ZONELEVEL_NIVA = "Nightmare Vale"; -- 5 / 6 --
TITAN_ZONELEVEL_NIWO = "Nightsong Woods"; -- 20 / 30 --
TITAN_ZONELEVEL_NIPO = "Nijel's Point"; -- 32 / 45 --
TITAN_ZONELEVEL_NORU = "Noonshade Ruins"; -- 40 / 43 --
TITAN_ZONELEVEL_NOGAOU = "North Gate Outpost"; -- 8 / 18 --
TITAN_ZONELEVEL_NOPOTO = "North Point Tower"; -- 35 / 38 --
TITAN_ZONELEVEL_NOTIHO = "North Tide's Hollow"; -- 12 / 25 --
TITAN_ZONELEVEL_NOTIRU = "North Tide's Run"; -- 12 / 22 --
TITAN_ZONELEVEL_NOR = "Northdale"; -- 57 / 58 --
TITAN_ZONELEVEL_NOMA = "Northfold Manor"; -- 30 / 36 --
TITAN_ZONELEVEL_NOLUCA = "Northridge Lumber Camp"; -- 52 / 56 --
TITAN_ZONELEVEL_NORI = "Northshire River"; -- 0 / 0 --
TITAN_ZONELEVEL_NOVA = "Northshire Valley"; -- 1 / 10 --
TITAN_ZONELEVEL_NOHO = "Northwatch Hold"; -- 13 / 36 --

--<< O >>--
TITAN_ZONELEVEL_OBCA = "O'Breen's Camp"; -- 0 / 0 --
TITAN_ZONELEVEL_OLFA = "Olsen's Farthing"; -- 11 / 13 --
TITAN_ZONELEVEL_ONE = "Oneiros"; -- 60 / 62 --
TITAN_ZONELEVEL_ONLA = "Onyxia's Lair"; -- 0 / 0 --
TITAN_ZONELEVEL_ORG = "Orgrimmar"; -- 1 / 30 --
TITAN_ZONELEVEL_OWWITH = "Owl Wing Thicket"; -- 56 / 59 --

--<< P >>--
TITAN_ZONELEVEL_PARO = "Palemane Rock"; -- 5 / 8 --
TITAN_ZONELEVEL_PESC = "Pestilent Scar"; -- 54 / 56 --
TITAN_ZONELEVEL_PLA = "Plaguewood"; -- 53 / 58 --
TITAN_ZONELEVEL_POTE = "Pool of Tears"; -- 37 / 62 --
TITAN_ZONELEVEL_PUIS = "Purgation Isle"; -- 28 / 31 --
TITAN_ZONELEVEL_PYVI = "Pyrewood Village"; -- 12 / 18 --

--<< Q >>--
TITAN_ZONELEVEL_QUDA = "Quel'Danil Lodge"; -- 12 / 49 --
TITAN_ZONELEVEL_QULI = "Quel'Lithien Lodge"; -- 57 / 60 --

--<< R >>--
TITAN_ZONELEVEL_RASCHO = "Rage Scar Hold"; -- 46 / 49 --
TITAN_ZONELEVEL_RACH = "Ragefire Chasm"; -- 13 / 15 --
TITAN_ZONELEVEL_RAGR = "Raptor Grounds"; -- 16 / 18 --
TITAN_ZONELEVEL_RARI = "Raptor Ridge"; -- 0 / 0 --
TITAN_ZONELEVEL_RAT = "Ratchet"; -- 13 / 45 --
TITAN_ZONELEVEL_RACA = "Ravaged Caravan"; -- 6 / 12 --
TITAN_ZONELEVEL_RAHICE = "Raven Hill Cemetery"; -- 19 / 35 --
TITAN_ZONELEVEL_RAVHI = "Raven Hill"; -- 18 / 26 --
TITAN_ZONELEVEL_RAMO = "Ravencrest Monument"; -- 53 / 55 --
TITAN_ZONELEVEL_RARE = "Raynewood Retreat"; -- 21 / 35 --
TITAN_ZONELEVEL_RAHIBA = "Razor Hill Barracks"; -- 14 / 32 --
TITAN_ZONELEVEL_RAZHI = "Razor Hill"; -- 1 / 35 --
TITAN_ZONELEVEL_RADO = "Razorfen Downs"; -- 35 / 40 --
TITAN_ZONELEVEL_RAKR = "Razorfen Kraul"; -- 12 / 34 --
TITAN_ZONELEVEL_RAZ = "Razorfenowns"; -- 23 / 40 --
TITAN_ZONELEVEL_RAZGR = "Razormane Grounds"; -- 1 / 32 --
TITAN_ZONELEVEL_RAZCA = "Razorwind Canyon"; -- 4 / 8 --
TITAN_ZONELEVEL_RECA = "Rebel Camp"; -- 30 / 31 --
TITAN_ZONELEVEL_RECLME = "Red Cloud Mesa"; -- 1 / 7 --
TITAN_ZONELEVEL_RERO = "Red Rocks"; -- 7 / 10 --
TITAN_ZONELEVEL_REDCA = "Redridge Canyons"; -- 16 / 25 --
TITAN_ZONELEVEL_REMO = "Redridge Mountains"; -- 14 / 35 --
TITAN_ZONELEVEL_REPO = "Refuge Pointe"; -- 30 / 39 --
TITAN_ZONELEVEL_REEXSI = "Remtravel's Excavation Site"; -- 15 / 20 --
TITAN_ZONELEVEL_RENCA = "Render's Camp"; -- 16 / 25 --
TITAN_ZONELEVEL_RENRO = "Render's Rock"; -- 19 / 25 --
TITAN_ZONELEVEL_REVA = "Render's Valley"; -- 17 / 22 --
TITAN_ZONELEVEL_RETCA = "Rethban Caverns"; -- 17 / 24 --
TITAN_ZONELEVEL_RITO = "Ridgepoint Tower"; -- 8 / 11 --
TITAN_ZONELEVEL_RITH = "Rise of theefiler"; -- 45 / 53 --
TITAN_ZONELEVEL_ROFA = "Rocktusk Farm"; -- 5 / 11 --
TITAN_ZONELEVEL_ROG = "Roguefeatheren"; -- 28 / 31 --
TITAN_ZONELEVEL_ROSO = "Roland'soom"; -- 30 / 31 --
TITAN_ZONELEVEL_RUAB = "Ruins of Aboraz"; -- 43 / 44 --
TITAN_ZONELEVEL_RUAL = "Ruins of Alterac"; -- 32 / 49 --
TITAN_ZONELEVEL_RUANE = "Ruins of Anderhol"; -- 50 / 60 --
TITAN_ZONELEVEL_RUANO = "Ruins of Andorhal"; -- 52 / 61 --
TITAN_ZONELEVEL_RUCO = "Ruins of Constellas"; -- 47 / 54 --
TITAN_ZONELEVEL_RUEL = "Ruins of Eldarath"; -- 46 / 53 --
TITAN_ZONELEVEL_RUIS = "Ruins of Isildien"; -- 41 / 47 --
TITAN_ZONELEVEL_RUJU = "Ruins of Jubuwal"; -- 43 / 44 --
TITAN_ZONELEVEL_RULO = "Ruins of Lordaeron"; -- 6 / 15 --
TITAN_ZONELEVEL_RUMA = "Ruins of Mathyrstra"; -- 17 / 21 --
TITAN_ZONELEVEL_RURA = "Ruins of Ravenwind"; -- 47 / 50 --
TITAN_ZONELEVEL_RUSO = "Ruins of Solarsal"; -- 40 / 43 --
TITAN_ZONELEVEL_RUTH = "Ruins of Thaurisan"; -- 50 / 57 --
TITAN_ZONELEVEL_RUZUK = "Ruins of Zul'Kunda"; -- 32 / 41 --
TITAN_ZONELEVEL_RUZUM = "Ruins of Zul'Mamwe"; -- 37 / 45 --

--<< S >>--
TITAN_ZONELEVEL_SAFA = "Saldean's Farm"; -- 10 / 19 --
TITAN_ZONELEVEL_SAGL = "Saltspray Glen"; -- 23 / 26 --
TITAN_ZONELEVEL_SAWA = "Sandsorrow Watch"; -- 41 / 48 --
TITAN_ZONELEVEL_SAST = "Sar'theris Strand"; -- 30 / 55 --
TITAN_ZONELEVEL_SAIS = "Sardor Isle"; -- 0 / 0 --
TITAN_ZONELEVEL_SAR = "Sargeron"; -- 0 / 0 --
TITAN_ZONELEVEL_SAT = "Satyrnaar"; -- 26 / 30 --
TITAN_ZONELEVEL_SBA = "sBaldar"; -- 0 / 0 --
TITAN_ZONELEVEL_SCBACA = "Scarlet Base Camp"; -- 53 / 54 --
TITAN_ZONELEVEL_SCMO = "Scarlet Monastery"; -- 29 / 40 --
TITAN_ZONELEVEL_SCWAPO = "Scarlet Watch Post"; -- 8 / 12 --
TITAN_ZONELEVEL_SCH = "Scholomance"; -- 57 / 60 --
TITAN_ZONELEVEL_SCCA = "Scrabblescrew's Camp"; -- 34 / 38 --
TITAN_ZONELEVEL_SCCO = "Scuttle Coast"; -- 1 / 13 --
TITAN_ZONELEVEL_SEGO = "Searing Gorge"; -- 43 / 58 --
TITAN_ZONELEVEL_SEVI = "Sen'jin Village"; -- 1 / 50 --
TITAN_ZONELEVEL_SEHI = "Sentinel Hill"; -- 10 / 30 --
TITAN_ZONELEVEL_SEPO = "Sentry Point"; -- 32 / 34 --
TITAN_ZONELEVEL_SER = "Seradane"; -- 60 / 62 --
TITAN_ZONELEVEL_SECO = "Serpent's Coil"; -- 47 / 55 --
TITAN_ZONELEVEL_SHHO = "Shadow Hold"; -- 50 / 59 --
TITAN_ZONELEVEL_SHKE = "Shadowfang Keep"; -- 13 / 27 --
TITAN_ZONELEVEL_SHA = "Shadowfang"; -- 0 / 0 --
TITAN_ZONELEVEL_SHVI = "Shadowprey Village"; -- 10 / 60 --
TITAN_ZONELEVEL_SHSH = "Shadowsong Shrine"; -- 45 / 48 --
TITAN_ZONELEVEL_SHAL = "Shadra'Alor"; -- 25 / 55 --
TITAN_ZONELEVEL_SHREIN = "Shady Rest Inn"; -- 0 / 0 --
TITAN_ZONELEVEL_SHSCVA = "Shatter Scar Vale"; -- 49 / 54 --
TITAN_ZONELEVEL_SHBE = "Shell Beach"; -- 0 / 0 --
TITAN_ZONELEVEL_SHRI = "Shimmer Ridge"; -- 7 / 10 --
TITAN_ZONELEVEL_SHCA = "Shindigger's Camp"; -- 45 / 46 --
TITAN_ZONELEVEL_SHDOFL = "Shrine of the Dormant Flame"; -- 12 / 12 --
TITAN_ZONELEVEL_SHFAWA = "Shrine of the fallen warrior"; -- 12 / 14 --
TITAN_ZONELEVEL_SHTH = "Shrine of theeceiver"; -- 50 / 52 --
TITAN_ZONELEVEL_SISTMI = "Silver Stream Mine"; -- 10 / 15 --
TITAN_ZONELEVEL_SIFO = "Silverpine Forest"; -- 10 / 25 --
TITAN_ZONELEVEL_SIRE = "Silverwind Refuge"; -- 40 / 40 --
TITAN_ZONELEVEL_SIOU = "Silverwing Outpost"; -- 21 / 24 --
TITAN_ZONELEVEL_SICA = "Sishir Canyon"; -- 14 / 22 --
TITAN_ZONELEVEL_SKRO = "Skulk Rock"; -- 46 / 48 --
TITAN_ZONELEVEL_SKRI = "Skyline Ridge"; -- 0 / 0 --
TITAN_ZONELEVEL_SLHO = "Slaughter Hollow"; -- 0 / 0 --
TITAN_ZONELEVEL_SLRO = "Slither Rock"; -- 50 / 60 --
TITAN_ZONELEVEL_SONA = "Sofera's Naze"; -- 32 / 35 --
TITAN_ZONELEVEL_SOGL = "Solace Glade"; -- 0 / 0 --
TITAN_ZONELEVEL_SOFA = "Solliden Farmstead"; -- 5 / 7 --
TITAN_ZONELEVEL_SOHI = "Sorrow Hill"; -- 50 / 57 --
TITAN_ZONELEVEL_SOR = "Sorrowmurk"; -- 37 / 62 --
TITAN_ZONELEVEL_SOGAOU = "South Gate Outpost"; -- 9 / 10 --
TITAN_ZONELEVEL_SOGAPA = "South Gate Pass"; -- 9 / 10 --
TITAN_ZONELEVEL_SOTIRU = "South Tide's Run"; -- 0 / 0 --
TITAN_ZONELEVEL_SOSH = "Southbreak Shore"; -- 48 / 50 --
TITAN_ZONELEVEL_SOBA = "Southern Barrens"; -- 8 / 45 --
TITAN_ZONELEVEL_SOGORO = "Southern Gold Road"; -- 14 / 34 --
TITAN_ZONELEVEL_SOSACO = "Southern Savage Coast"; -- 39 / 44 --
TITAN_ZONELEVEL_SORI = "Southfury River"; -- 4 / 48 --
TITAN_ZONELEVEL_SORU = "Southmoon Ruins"; -- 43 / 50 --
TITAN_ZONELEVEL_SOTO = "Southpoint Tower"; -- 21 / 22 --
TITAN_ZONELEVEL_SOBE = "Southridge Beach"; -- 50 / 55 --
TITAN_ZONELEVEL_SOU = "Southshore"; -- 22 / 38 --
TITAN_ZONELEVEL_SPRO = "Spirit Rock"; -- 13 / 15 --
TITAN_ZONELEVEL_SPI = "Spiriten"; -- 40 / 44 --
TITAN_ZONELEVEL_SPJU = "Splinterspear Junction"; -- 34 / 37 --
TITAN_ZONELEVEL_SPPO = "Splintertree Post"; -- 26 / 44 --
TITAN_ZONELEVEL_SPCR = "Splithoof Crag"; -- 24 / 27 --
TITAN_ZONELEVEL_SPHO = "Splithoof Hold"; -- 24 / 30 --
TITAN_ZONELEVEL_STCA = "Stagalbog Cave"; -- 40 / 55 --
TITAN_ZONELEVEL_STA = "Stagalbog"; -- 30 / 55 --
TITAN_ZONELEVEL_STAVA = "Stanglethorn Vale"; -- 30 / 55 --
TITAN_ZONELEVEL_STVI = "Starfall Village"; -- 54 / 56 --
TITAN_ZONELEVEL_STPO = "Steamwheedle Port"; -- 30 / 53 --
TITAN_ZONELEVEL_STSE = "Steelgrill'sepot"; -- 5 / 8 --
TITAN_ZONELEVEL_STEPO = "Stendel's Pond"; -- 11 / 17 --
TITAN_ZONELEVEL_STIPO = "Stillwater Pond"; -- 5 / 8 --
TITAN_ZONELEVEL_STO = "Stonard"; -- 30 / 60 --
TITAN_ZONELEVEL_STCALA = "Stone Cairn Lake"; -- 7 / 10 --
TITAN_ZONELEVEL_STLA = "Stonebull Lake"; -- 5 / 14 --
TITAN_ZONELEVEL_STOVA = "Stonesplinter Valley"; -- 11 / 17 --
TITAN_ZONELEVEL_STMO = "Stonetalon Mountains"; -- 21 / 24 --
TITAN_ZONELEVEL_STPE = "Stonetalon Peak"; -- 22 / 27 --
TITAN_ZONELEVEL_STFA = "Stonewatch Falls"; -- 19 / 22 --
TITAN_ZONELEVEL_STKE = "Stonewatch Keep"; -- 21 / 26 --
TITAN_ZONELEVEL_STTO = "Stonewatch Tower"; -- 16 / 26 --
TITAN_ZONELEVEL_STW = "Stonewatch"; -- 20 / 26 --
TITAN_ZONELEVEL_STPA = "Stonewrought Pass"; -- 0 / 0 --
TITAN_ZONELEVEL_STG = "Stonewroughtam"; -- 10 / 30 --
TITAN_ZONELEVEL_STCI = "Stormwind City"; -- 0 / 0 --
TITAN_ZONELEVEL_STR = "Strahnbrad"; -- 34 / 37 --
TITAN_ZONELEVEL_STRVA = "Stranglethorn Vale"; -- 30 / 45 --
TITAN_ZONELEVEL_STH = "Strathome"; -- 55 / 60 --
TITAN_ZONELEVEL_STKE = "Stromgarde Keep"; -- 35 / 40 --
TITAN_ZONELEVEL_SURORE = "Sun Rock Retreat"; -- 17 / 55 --
TITAN_ZONELEVEL_SUMA = "Sundown Marsh"; -- 21 / 26 --
TITAN_ZONELEVEL_SWSO = "Swamp of Sorrows"; -- 25 / 62 --

--<< T >>--
TITAN_ZONELEVEL_TAGL = "Talonbranch Glade"; -- 52 / 53 --
TITAN_ZONELEVEL_TAN = "Tanaris"; -- 40 / 50 --
TITAN_ZONELEVEL_TAMI = "Tarren Mill"; -- 20 / 56 --
TITAN_ZONELEVEL_TEL = "Teldrassil"; -- 1 / 10 --
TITAN_ZONELEVEL_TEAZ = "Temple of Arkkoran"; -- 53 / 60 --
TITAN_ZONELEVEL_TEZM = "Temple of Zin-Malor"; -- 48 / 55 --
TITAN_ZONELEVEL_TERE = "Terrace of Repose"; -- 29 / 30 --
TITAN_ZONELEVEL_TERU = "Terror Run"; -- 50 / 55 --
TITAN_ZONELEVEL_TEWP = "Terror Wing Path"; -- 50 / 55 --
TITAN_ZONELEVEL_TER = "Terrordale"; -- 53 / 58 --
TITAN_ZONELEVEL_TEAR = "Tethris Aran"; -- 0 / 0 --
TITAN_ZONELEVEL_THA = "Thalanaar"; -- 0 / 0 --
TITAN_ZONELEVEL_THBC = "Thalassian Base Camp"; -- 51 / 53 --
TITAN_ZONELEVEL_THSP = "Thandol Span"; -- 22 / 22 --
TITAN_ZONELEVEL_THEAZ = "The Altar of Zul"; -- 44 / 52 --
TITAN_ZONELEVEL_THEBA = "The Barrens"; -- 5 / 35 --
TITAN_ZONELEVEL_THEBU = "The Bulwark"; -- 50 / 60 --
TITAN_ZONELEVEL_THECAST = "The Cape of Stranglethorn"; -- 37 / 55 --
TITAN_ZONELEVEL_THECEM = "The Cemetary"; -- 0 / 0 --
TITAN_ZONELEVEL_THECHVA = "The Charred Vale"; -- 23 / 30 --
TITAN_ZONELEVEL_THECRRU = "The Creeping Ruin"; -- 44 / 46 --
TITAN_ZONELEVEL_THECRO = "The Crossroads"; -- 10 / 55 --
TITAN_ZONELEVEL_THECRSH = "The Crystal Shore"; -- 40 / 47 --
TITAN_ZONELEVEL_THEFALO = "The Farstrider Lodge"; -- 15 / 15 --
TITAN_ZONELEVEL_THEFOCA = "The Foothill Caverns"; -- 0 / 0 --
TITAN_ZONELEVEL_THEFOCO = "The Forgotten Coast"; -- 41 / 49 --
TITAN_ZONELEVEL_THEFOPO = "The Forgotten Pools"; -- 12 / 17 --
TITAN_ZONELEVEL_THEFUVA = "The Fungal Vale"; -- 57 / 59 --
TITAN_ZONELEVEL_THEGACH = "The Gaping Chasm"; -- 44 / 50 --
TITAN_ZONELEVEL_THEGOPL = "The Golden Plains"; -- 6 / 12 --
TITAN_ZONELEVEL_THEGRLI = "The Great Lift"; -- 25 / 27 --
TITAN_ZONELEVEL_THEGRBE = "The Green Belt"; -- 21 / 27 --
TITAN_ZONELEVEL_THEGRWA = "The Greymane Wall"; -- 15 / 25 --
TITAN_ZONELEVEL_THEGRQU = "The Grinding Quarry"; -- 47 / 50 --
TITAN_ZONELEVEL_THEGRZ = "The Grizzleden"; -- 5 / 7 --
TITAN_ZONELEVEL_THEHA = "The Harborage"; -- 35 / 42 --
TITAN_ZONELEVEL_THEHE = "The Headland"; -- 23 / 34 --
TITAN_ZONELEVEL_THEHIGR = "The Hidden Grove"; -- 56 / 58 --
TITAN_ZONELEVEL_THEHIN = "The Hinterlands"; -- 12 / 58 --
TITAN_ZONELEVEL_THEHOVA = "The Howling Vale"; -- 0 / 0 --
TITAN_ZONELEVEL_THEHUBA = "The Hushed Bank"; -- 18 / 22 --
TITAN_ZONELEVEL_THEINSC = "The Infectis Scar"; -- 54 / 56 --
TITAN_ZONELEVEL_THEIVPA = "The Ivar Patch"; -- 11 / 15 --
TITAN_ZONELEVEL_THEJAST = "The Jansen Stead"; -- 9 / 13 --
TITAN_ZONELEVEL_THELOC = "The Loch"; -- 10 / 22 --
TITAN_ZONELEVEL_THELOWA = "The Long Wash"; -- 10 / 13 --
TITAN_ZONELEVEL_THELOFL = "The Lost Fleet"; -- 21 / 28 --
TITAN_ZONELEVEL_THEMAVI = "The Maclure Vineyards"; -- 5 / 20 --
TITAN_ZONELEVEL_THEMATE = "The Maker's Terrace"; -- 35 / 37 --
TITAN_ZONELEVEL_THEMAST = "The Marris Stead"; -- 53 / 62 --
TITAN_ZONELEVEL_THEMAR = "The Marshlands"; -- 48 / 61 --
TITAN_ZONELEVEL_THEMAS = "The Masonary"; -- 48 / 50 --
TITAN_ZONELEVEL_THEMAGL = "The Master's Glaive"; -- 16 / 20 --
TITAN_ZONELEVEL_THEMECO = "The Merchant Coast"; -- 12 / 38 --
TITAN_ZONELEVEL_THEMOFA = "The Molsen Farm"; -- 10 / 19 --
TITAN_ZONELEVEL_THEMOSP = "The Molten Span"; -- 48 / 49 --
TITAN_ZONELEVEL_THEMORA = "The Mor'shan Rampart"; -- 11 / 21 --
TITAN_ZONELEVEL_THENOCO = "The North Coast"; -- 7 / 9 --
TITAN_ZONELEVEL_THENOLA = "The Noxious Lair"; -- 44 / 50 --
TITAN_ZONELEVEL_THEOVCL = "The Overlook Cliffs"; -- 30 / 50 --
TITAN_ZONELEVEL_THEPA = "The Pillar of Ash"; -- 55 / 57 --
TITAN_ZONELEVEL_THEQU = "The Quagmire"; -- 36 / 45 --
TITAN_ZONELEVEL_THEROPL = "The Rolling Plains"; -- 5 / 12 --
TITAN_ZONELEVEL_THEROOR = "The Rotting Orchard"; -- 26 / 29 --
TITAN_ZONELEVEL_THERURE = "The Ruined Reaches"; -- 45 / 55 --
TITAN_ZONELEVEL_THERUKT = "The Ruins of Kel'Theril"; -- 54 / 56 --
TITAN_ZONELEVEL_THERULO = "The Ruins of Lordaeron"; -- 6 / 13 --
TITAN_ZONELEVEL_THERUOR = "The Ruins of Ordil'Aran"; -- 18 / 19 --
TITAN_ZONELEVEL_THERUST = "The Ruins of Stardust"; -- 21 / 24 --
TITAN_ZONELEVEL_THERUSI = "The Rustmaulig Site"; -- 32 / 35 --
TITAN_ZONELEVEL_THESASA = "The Salty Sailor"; -- 50 / 50 --
TITAN_ZONELEVEL_THESAN = "The Sanctum"; -- 39 / 44 --
TITAN_ZONELEVEL_THESACO = "The Savage Coast"; -- 31 / 55 --
TITAN_ZONELEVEL_THESCMO = "The Scarlet Monastery"; -- 30 / 40 --
TITAN_ZONELEVEL_THESCCA = "The Screeching Canyon"; -- 26 / 30 --
TITAN_ZONELEVEL_THESEP = "The Sepulcher"; -- 10 / 22 --
TITAN_ZONELEVEL_THESHNO = "The Shady Nook"; -- 24 / 26 --
TITAN_ZONELEVEL_THESHAST = "The Shattered Strand"; -- 50 / 52 --
TITAN_ZONELEVEL_THESHMI = "The Shifting Mire"; -- 34 / 55 --
TITAN_ZONELEVEL_THESHFL = "The Shimmering Flats"; -- 27 / 37 --
TITAN_ZONELEVEL_THESHIST = "The Shining Strand"; -- 10 / 19 --
TITAN_ZONELEVEL_THESHAE = "The Shrine of Aessina"; -- 17 / 27 --
TITAN_ZONELEVEL_THESKT = "The Skitteringark"; -- 12 / 15 --
TITAN_ZONELEVEL_THESLSC = "The Slithering Scar"; -- 48 / 53 --
TITAN_ZONELEVEL_THESLFE = "The Sludge Fen"; -- 13 / 19 --
TITAN_ZONELEVEL_THESTOA = "The Stagnant Oasis"; -- 12 / 18 --
TITAN_ZONELEVEL_THESTO = "The Stockades"; -- 23 / 26 --
TITAN_ZONELEVEL_THESTFA = "The Stonefield Farm"; -- 5 / 9 --
TITAN_ZONELEVEL_THESUTE = "The Sunken Temple"; -- 44 / 50 --
TITAN_ZONELEVEL_THETASC = "The Tainted Scar"; -- 61 / 61 --
TITAN_ZONELEVEL_THETAPA = "The Talondeep Path"; -- 14 / 25 --
TITAN_ZONELEVEL_THETAL = "The Talonen"; -- 22 / 30 --
TITAN_ZONELEVEL_THETIST = "The Tidus Stair"; -- 13 / 36 --
TITAN_ZONELEVEL_THETOAR = "The Tower of Arathor"; -- 37 / 40 --
TITAN_ZONELEVEL_THETUHI = "The Tundrid Hills"; -- 5 / 12 --
TITAN_ZONELEVEL_THETWCO = "The Twin Colossals"; -- 44 / 50 --
TITAN_ZONELEVEL_THEUND = "The Undercroft"; -- 53 / 55 --
TITAN_ZONELEVEL_THEUPL = "The Uplands"; -- 30 / 37 --
TITAN_ZONELEVEL_THEVESE = "The Veiled Sea"; -- 33 / 35 --
TITAN_ZONELEVEL_THEVEMI = "The Venture Co. Mine"; -- 6 / 12 --
TITAN_ZONELEVEL_THEVIRE = "The Vile Reef"; -- 35 / 40 --
TITAN_ZONELEVEL_THEWACA = "The Wailing Caverns"; -- 15 /27 --
TITAN_ZONELEVEL_THEWENO = "The Weathered Nook"; -- 0 / 0 --
TITAN_ZONELEVEL_THEWHES = "The Whipple Estate"; -- 0 / 0 --
TITAN_ZONELEVEL_THEWOTR = "The World Tree"; -- 0 / 0 --
TITAN_ZONELEVEL_THEWRHA = "The Writhing Haunt"; -- 52 / 55 --
TITAN_ZONELEVEL_THEWRI = "The Writhingeep"; -- 42 / 46 --
TITAN_ZONELEVEL_THEYOFA = "The Yorgen Farmstead"; -- 23 / 35 --
TITAN_ZONELEVEL_THEZOST = "The Zoram Strand"; -- 18 / 40 --
TITAN_ZONELEVEL_THHEHI = "Theagger Hills"; -- 15 / 30 --
TITAN_ZONELEVEL_THHEBA = "Thearkened Bank"; -- 9 / 21 --
TITAN_ZONELEVEL_THHEAIS = "Theawning Isles"; -- 15 / 31 --
TITAN_ZONELEVEL_THHEAC = "Theead Acre"; -- 16 / 26 --
TITAN_ZONELEVEL_THHEFI = "Theead Field"; -- 11 / 14 --
TITAN_ZONELEVEL_THHEE = "Theeadmines"; -- 15 / 22 --
TITAN_ZONELEVEL_THHEFE = "Theecrepit Ferry"; -- 13 / 16 --
TITAN_ZONELEVEL_THHERO = "Thelgen Rock"; -- 20 / 22 --
TITAN_ZONELEVEL_THHEL = "Thelsamar"; -- 10 / 30 --
TITAN_ZONELEVEL_THHEDABA = "Theor'Danil Barrowen"; -- 19 / 32 --
TITAN_ZONELEVEL_THHEER = "Theragonmurk"; -- 37 / 45 --
TITAN_ZONELEVEL_THHERIS = "Theramore Isle"; -- 35 / 55 --
TITAN_ZONELEVEL_THHERE = "Therowned Reef"; -- 39 / 39 --
TITAN_ZONELEVEL_THHEHIL = "Thery Hills"; -- 13 / 20 --
TITAN_ZONELEVEL_THHEPL = "Theust Plains"; -- 15 / 24 --
TITAN_ZONELEVEL_THHEU = "Theustbowl"; -- 36 / 55 --
TITAN_ZONELEVEL_THICA = "Thieves Camp"; -- 0 / 0 --
TITAN_ZONELEVEL_THIVI = "Thistlefur Village"; -- 20 / 25 --
TITAN_ZONELEVEL_THIVA = "Thistleshrub Valley"; -- 47 / 50 --
TITAN_ZONELEVEL_THORI = "Thondroril River"; -- 53 / 56 --
TITAN_ZONELEVEL_THOWA = "Thoradin's Wall"; -- 24 / 33 --
TITAN_ZONELEVEL_THOHI = "Thorn Hill"; -- 10 / 19 --
TITAN_ZONELEVEL_THONE = "Thousand Needles"; -- 10 / 42 --
TITAN_ZONELEVEL_THRCO = "Three Corners"; -- 14 / 35 --
TITAN_ZONELEVEL_THUAXFO = "Thunder Axe Fortress"; -- 30 / 32 --
TITAN_ZONELEVEL_THUBL = "Thunder Bluff"; -- 3 / 75 --
TITAN_ZONELEVEL_THUFA = "Thunder Falls"; -- 0 / 0 --
TITAN_ZONELEVEL_THURI = "Thunder Ridge"; -- 2 / 12 --
TITAN_ZONELEVEL_THUN = "Thunderbrewistillery"; -- 30 / 30 --
TITAN_ZONELEVEL_THUWAWE = "Thunderhorn Water Well"; -- 6 / 12 --
TITAN_ZONELEVEL_TICO = "Tidefury Cove"; -- 42 / 43 --
TITAN_ZONELEVEL_TIHO = "Timbermaw Hold"; -- 48 / 55 --
TITAN_ZONELEVEL_TIPO = "Timbermaw Post"; -- 53 / 56 --
TITAN_ZONELEVEL_TIKE = "Tiragarde Keep"; -- 1 / 9 --
TITAN_ZONELEVEL_TIGL = "Tirisfal Glades"; -- 5 / 45 --
TITAN_ZONELEVEL_TKRU = "Tkashi Ruins"; -- 30 / 37 --
TITAN_ZONELEVEL_TOAL = "Tower of Althalaxx"; -- 16 / 28 --
TITAN_ZONELEVEL_TOAZ = "Tower of Azora"; -- 6 / 8 --
TITAN_ZONELEVEL_TOEL = "Tower of Eldara"; -- 0 / 0 --
TITAN_ZONELEVEL_TOIL = "Tower of Ilgalar"; -- 25 / 26 --
TITAN_ZONELEVEL_TRGACE = "Tranquil Gardens Cemetery"; -- 21 / 30 --
TITAN_ZONELEVEL_TWGR = "Twilight Grove"; -- 0 / 0 --
TITAN_ZONELEVEL_TWSH = "Twilight Shore"; -- 10 / 21 --
TITAN_ZONELEVEL_TWVA = "Twilight Vale"; -- 10 / 20 --

--<< U >>--
TITAN_ZONELEVEL_ULDA = "Uldaman"; -- 35 / 50 --
TITAN_ZONELEVEL_ULDU = "Uldum"; -- 48 / 49 --
TITAN_ZONELEVEL_UNGOCR = "Un'Goro Crater"; -- 48 / 61 --
TITAN_ZONELEVEL_URS = "Ursolan"; -- 50 / 52 --

--<< V >>--
TITAN_ZONELEVEL_VAFI = "Valgan's Field"; -- 10 / 14 --
TITAN_ZONELEVEL_VABO = "Valley of Bones"; -- 37 / 40 --
TITAN_ZONELEVEL_VAFA = "Valley of Fangs"; -- 35 / 42 --
TITAN_ZONELEVEL_VAHE = "Valley of Heroes"; -- 0 / 0 --
TITAN_ZONELEVEL_VAKI = "Valley of Kings"; -- 11 / 12 --
TITAN_ZONELEVEL_VASP = "Valley of Spears"; -- 37 / 42 --
TITAN_ZONELEVEL_VABL = "Valley of the Bloodfuries"; -- 0 / 0 --
TITAN_ZONELEVEL_VAWA = "Valley of the Watchers"; -- 43 / 49 --
TITAN_ZONELEVEL_VATR = "Valley of Trials"; -- 1 / 35 --
TITAN_ZONELEVEL_VAL = "Valormok"; -- 45 / 55 --
TITAN_ZONELEVEL_VALA = "Valorwind Lake"; -- 43 / 47 --
TITAN_ZONELEVEL_VAEN = "Vanndir Encampment"; -- 0 / 0 --
TITAN_ZONELEVEL_VEVA = "Venomweb Vale"; -- 8 / 30 --
TITAN_ZONELEVEL_VEBACA = "Venture Co. Base Camp"; -- 31 / 42 --
TITAN_ZONELEVEL_VEOPCE = "Venture Co. Operations Center"; -- 31 / 38 --
TITAN_ZONELEVEL_VERI = "Verdantis River"; -- 42 / 46 --
TITAN_ZONELEVEL_VUOGMO = "Vul'Gol Ogre Mound"; -- 27 / 30 --

--<< W >>--
TITAN_ZONELEVEL_WACA = "Wailing Caverns"; -- 12 / 16 --
TITAN_ZONELEVEL_WALUCA = "Warsong Lumber Camp"; -- 25 / 29 --
TITAN_ZONELEVEL_WAFI = "Waterspring Field"; -- 40 / 46 --
TITAN_ZONELEVEL_WABE = "Wavestrider Beach"; -- 40 / 45 --
TITAN_ZONELEVEL_WEPA = "Webwinder Path"; -- 15 / 30 --
TITAN_ZONELEVEL_WEPI = "West Pillar"; -- 0 / 0 --
TITAN_ZONELEVEL_WEGA = "Westbrook Garrison"; -- 5 / 9 --
TITAN_ZONELEVEL_WEPL = "Western Plaguelands"; -- 50 / 63 --
TITAN_ZONELEVEL_WEST = "Western Strand"; -- 24 / 32 --
TITAN_ZONELEVEL_WELI = "Westfall Lighthouse"; -- 0 / 0 --
TITAN_ZONELEVEL_WES = "Westfall"; -- 9 / 19 --
TITAN_ZONELEVEL_WET = "Wetlands"; -- 20 / 27 --
TITAN_ZONELEVEL_WHEXSI = "Whelgar's Excavation Site"; -- 22 / 29 --
TITAN_ZONELEVEL_WHGA = "Whispering Gardens"; -- 10 / 30 --
TITAN_ZONELEVEL_WHSH = "Whispering Shore"; -- 0 / 0 --
TITAN_ZONELEVEL_WHPO = "Whitereach Post"; -- 24 / 42 --
TITAN_ZONELEVEL_WISH = "Wild Shore"; -- 40 / 52 --
TITAN_ZONELEVEL_WILRI = "Wildbend River"; -- 13 / 14 --
TITAN_ZONELEVEL_WIKE = "Wildhammer Keep"; -- 45 / 45 --
TITAN_ZONELEVEL_WILWAWE = "Wildmane Water Well"; -- 8 / 10 --
TITAN_ZONELEVEL_WILA = "Wildwind Lake"; -- 43 / 46 --
TITAN_ZONELEVEL_WICA = "Windbreak Canyon"; -- 27 / 29 --
TITAN_ZONELEVEL_WINRI = "Windfury Ridge"; -- 8 / 11 --
TITAN_ZONELEVEL_WICR = "Windshear Crag"; -- 14 / 23 --
TITAN_ZONELEVEL_WIMI = "Windshear Mine"; -- 20 / 22 --
TITAN_ZONELEVEL_WINVI = "Winterfall Village"; -- 55 / 59 --
TITAN_ZONELEVEL_WINWAWE = "Winterhoof Water Well"; -- 5 / 8 --
TITAN_ZONELEVEL_WIN = "Winterspring"; -- 53 /60 --
TITAN_ZONELEVEL_WIHI = "Witch Hill"; -- 35 / 38 --
TITAN_ZONELEVEL_WITVI = "Witherbark Village"; -- 31 / 37 --
TITAN_ZONELEVEL_WOHI = "Woodpaw Hills"; -- 40 / 46 --
TITAN_ZONELEVEL_WOO = "Woodpawen"; -- 42 / 44 --

--<< X >>--
TITAN_ZONELEVEL_XAV = "Xavian"; -- 25 / 30 --

--<< Z >>--
TITAN_ZONELEVEL_ZADE = "Zalashji's Den"; -- 0 / 0 --
TITAN_ZONELEVEL_ZIRU = "Ziata'jai Ruins"; -- 37 / 40 --
TITAN_ZONELEVEL_ZOOU = "Zoram'gar Outpost"; -- 18 / 35 --
TITAN_ZONELEVEL_ZUGU = "Zul Gurub"; -- 0 / 0 --
TITAN_ZONELEVEL_ZUFA = "Zul'Farrak"; -- 30 / 48 --
TITAN_ZONELEVEL_ZUMA = "Zul'Mashar"; -- 57 / 59 --
TITAN_ZONELEVEL_ZUWA = "Zun'watha"; -- 40 / 42 --
TITAN_ZONELEVEL_AURU = "Zuuldaia Ruins"; -- 35 / 38 --

--<< Loading >> --
TITAN_ZONELEVEL_LOAD = "Loading";


return
end

------<<<<<< French Localization >>>>>>------
------<<<<<< ------------------- >>>>>>------
if GetLocale()=="frFR" then



return
end

------<<<<<< German Localization >>>>>>------
------<<<<<< ------------------- >>>>>>------
if GetLocale()=="deDE" then



return
end
