
TITAN_FACTIONS_MENU_TEXT = "Factions"
TITAN_FACTIONS_BUTTON_LABEL = "Factions"
TITAN_FACTIONS_BUTTON_TEXT = "%s"
TITAN_FACTIONS_TOOLTIP = "Factions Info"

TITAN_FACTIONS_SHOW_RAW = "Show raw only"
TITAN_FACTIONS_SHOW_BOTH = "Show raw and percentage"

TITAN_FACTIONS_SHOW_SESSION = "Show session gains"
TITAN_FACTIONS_SHOW_RUNECLOTH = "Show runecloth counts"

TITAN_FACTIONS_HIDE_INACTIVE = "Hide inactive factions"
TITAN_FACTIONS_HIDE_EXALTED = "Hide "..FACTION_STANDING_LABEL8.." factions"

TITAN_FACTIONS_MONITOR = "Monitor"
TITAN_FACTIONS_MONITOR_TOGGLE_TEXT = "Show monitored faction"
TITAN_FACTIONS_MONITORBLIZZARD_TOGGLE_TEXT = "Use Blizzard's faction watch"

TITAN_FACTIONS_INACTIVE = "Inactive"

TITAN_FACTIONS_DARKSPEAR_TROLLS = "Darkspear Trolls"
TITAN_FACTIONS_ORGRIMMAR = "Orgrimmar"
TITAN_FACTIONS_THUNDER_BLUFF = "Thunder Bluff"
TITAN_FACTIONS_UNDERCITY = "Undercity"

TITAN_FACTIONS_DARNASSUS = "Darnassus"
TITAN_FACTIONS_GNOMEREGAN_EXILES = "Gnomeregan Exiles"
TITAN_FACTIONS_IRONFORGE = "Ironforge"
TITAN_FACTIONS_STORMWIND_CITY = "Stormwind City"

TITAN_FACTIONS_ABOUT_TEXT = "About"
TITAN_FACTIONS_ABOUT_VERSION = "Version"
TITAN_FACTIONS_ABOUT_OAUTHOR = "Original Author"
TITAN_FACTIONS_ABOUT_CAUTHOR = "Current Author"
