--
-- Post-localization processing
--
if (not INVTYPE_WAND) then INVTYPE_WAND = EQUIPCOMPARE_INVTYPE_WAND end;
if (not INVTYPE_GUN) then INVTYPE_GUN = EQUIPCOMPARE_INVTYPE_GUN end;
if (not INVTYPE_GUNPROJECTILE) then INVTYPE_GUNPROJECTILE = EQUIPCOMPARE_INVTYPE_GUNPROJECTILE end;
if (not INVTYPE_BOWPROJECTILE) then INVTYPE_BOWPROJECTILE = EQUIPCOMPARE_INVTYPE_BOWPROJECTILE end;
if (not INVTYPE_CROSSBOW) then INVTYPE_CROSSBOW = EQUIPCOMPARE_INVTYPE_CROSSBOW end;
if (not INVTYPE_THROWN) then INVTYPE_THROWN = EQUIPCOMPARE_INVTYPE_THROWN end;
