-- Version : English - Ramble 

MYINVENTORY_NAME = "MyInventory"
MYINVENTORY_DESCRIPTION = "All in one inventory mod"

MYINVENTORYFRAME_TITLE = "Inventory"

-- SLASHCOMMANDS
MYINVENTORY_COMMANDS    = {"/myinventory", "/mi"}
MYINVENTORY_CMD_OPTIONS = {
	MYBAGS_CMD_OPT_TOGGLE,
	MYBAGS_CMD_OPT_FREEZE,
	MYBAGS_CMD_OPT_NOESC,
	MYBAGS_CMD_OPT_COLUMNS,
	MYBAGS_CMD_OPT_REPLACE,
	MYBAGS_CMD_OPT_BAG,
	MYBAGS_CMD_OPT_GRAPHICS,
	MYBAGS_CMD_OPT_HIGHLIGHT,
	MYBAGS_CMD_OPT_LOCK,
	MYBAGS_CMD_OPT_TITLE,
	MYBAGS_CMD_OPT_CASH,
	MYBAGS_CMD_OPT_BUTTONS,
	MYBAGS_CMD_OPT_AIOI,
	MYBAGS_CMD_OPT_REVERSE,
	MYBAGS_CMD_OPT_BORDER,
	MYBAGS_CMD_OPT_PLAYERSEL,
	MYBAGS_CMD_OPT_COUNT,
	MYBAGS_CMD_OPT_SCALE,
	MYBAGS_CMD_OPT_STRATA,
	MYBAGS_CMD_OPT_ANCHOR,
	MYBAGS_CMD_RESET,
	MYBAGS_CMD_OPT_SLOTCOLOR,
	MYBAGS_CMD_OPT_COMPANION,
}
