if (GetLocale() == "frFR") then 

PowaText = {
	welcome = "Tapez /powa pour afficher les options, pour les fonctions avanc\195\169es tapez /powa help",

	aucune = "Aucune",
	aucun = "Aucun",
	largeur = "Largeur",
	hauteur = "Hauteur",

	aideTexture = "La texture \195\160 afficher. Vous pouvez facilement remplacer les textures en changeant les fichier Aura#.tga du dossier de l'AddOn.",
	aideAnim1 = "Anime la texture ou pas, avec diff\195\169rents effets.",
	aideAnim2 = "Cette animation sera affich\195\169e avec moins d'opacit\195\169 que la principale. Attention, afin de ne pas surcharger le tout, une seule animation secondaire sera affich\195\169e a la fois.",
	aideDeform = "Etire la texture vers le haut ou en largeur.",
	aideColor = "Cliquez ici pour changer la couleur de la texture.",
	aideBuff = "Entrez ici le nom du buff, ou une partie du nom, qui doit activer/d\195\169sactiver l'effet. Vous pouvez entrer plusieurs noms s'ils sont s\195\169par\195\169 comme il convient (ex: Super Buff/Puissance)",
	aideBuff2 = "Entrez ici le nom du d\195\169buff, ou une partie du nom, qui doit activer/d\195\169sactiver l'effet. Vous pouvez entrer plusieurs noms s'ils sont s\195\169par\195\169 comme il convient (ex: Maladie noire/Peste)",
	aideBuff3 = "Entrez ici le type du d\195\169buff qui doit activer ou d\195\169sactiver l'effet (Poison, Maladie, Mal\195\169diction, Magie ou Aucun). Vous pouvez aussi entrer plusieurs types de d\195\169buffs \195\160 la fois.",
	aideDebuff = "Cochez cette case si vous voulez que cet effet s'applique plut\195\180t \195\160 un d\195\169buff.",
	aideDebuffType = "Cochez cette case si vous voulez que cet effet s'applique ˆ un type de d\195\169buff particulier (commun\195\169ment : Poison, Maladie, Mal\195\169diction, Magie...)",
	aideQuickHide = "Cochez cette case afin que la disparition des effets soit instantan\195\169e.",
	aideShowTimer = "Cochez cette case pour afficher la dur\195\169e de cet effet.",
	aideInverse = "Cochez cette case pour afficher cet effet uniquement quand le buff/d\195\169buff n'est pas actif.",
	aideCommande1 = "Options avanc\195\169es :",
	aideCommande2 = "D\195\169fini le nombre maximum de textures disponibles (de 20 \195\160 50)",
	aideCommande2a = "Nombre maximum de textures fix\195\169s \195\160",
	aideCommande3 = "D\195\169fini le nombre maximum d'effets disponibles (de 10 \195\160 100)",
	aideCommande3a = "Nombre maximum d'effets fix\195\169s \195\160",
	aideDisable = "D\195\169sactive tous les effets",
	aideDuration = "Pass\195\169 ce d\195\169lai, l'animation sera masqu\195\169e (0 pour d\195\169sactiver)",
	aideListe = "Ceci est la liste des effets disponibles par tous les personnages. Attention, seuls les effets pr\195\169sents dans l'\195\169diteur d'effet seront actifs.",
	aideMaxTex = "Defini le maximum de textures disponibles dans l'Editeur d'Effets. Si vous rajoutez des textures en les mettant dans le dossier de l'AddOn (nomm\195\169es de AURA1.tga \195\160 AURA50.tga) c'est ici qu'il faudra le signaler.",
	nomBuff = "Nom du Buff",
	nomDebuff = "Nom du Debuff",
	nomDebuffType = "Type de Debuff",
	nomCheckDebuff = "Debuff",
	nomCheckDebuffType = "Type du Debuff",
	nomCheckQuickHide = "Disparition rapide",
	nomCheckShowTimer = "Afficher la dur\195\169e",
	nomCheckInverse = "Afficher si inactif",
	nomTexture = "Texture",
	nomAnim1 = "Anim. principale",
	nomAnim2 = "Anim. secondaire",
	nomSpeed = "Vitesse d'Anim.",
	nomBegin = "Anim. de d\195\169part",
	nomDuration = "Dur\195\169e de l'Anim.",
	nomSymetrie = "Sym\195\169trie",
	nomAlpha = "Transparence",
	nomPos = "Position",
	nomTaille = "Taille",
	nomDeform = "D\195\169formation",
	nomTest = "Tester",
	nomHide = "Tout masquer",
	nomClose = "Fermer",
	nomTitre = "Effet",
	nomListe = "Liste >>",
	nomCentiemes = "Afficher centiemes",
	nomDisable = "D\195\169sactiver Power Auras",
	nomEffectEditor = "Editeur d'Effets",
	nomAdvOptions = "Options Avanc\195\169es",
	nomMaxTex = "Maximum de textures disponibles",
	listheader = "Liste des Buffs/Debuffs",
	listdelete = "Efface cet effet.",
	listload = "Copie cet effet dans la fenetre d'\195\169dition en cours.",
	listadd = ">> Ajouter",
	listaddall = ">> Ajouter tout",
	listaideadd = "Sauvegarde dans la liste l'effet actuellement \195\169dit\195\169.",
	listaideaddall = "Sauvegarde dans la liste tous les effets de ce personnage.",
	erreur1 = "Erreur : L'effet actuel n'a aucun nom.",
	erreur2 = "Erreur : Un effet portant ce nom existe d\195\169j\195\160.",
	erreur3 = "Erreur : Pas assez de place pour sauver."
};

else

PowaText = {
	welcome = "Type /powa to view the options, for the advanced functions, type /powa help",

	aucune = "None",
	aucun = "None",
	largeur = "Width",
	hauteur = "Height",

	aideTexture = "The texture to be shown. You can easily replace textures by changing the files Aura#.tga in the Addon's directory.",
	aideAnim1 = "Animate the texture or not, with various effects.",
	aideAnim2 = "This animation will be shown with less opacity than the main animation. Attention, to not overload the screen, only a single secondary animation will be shown at the same time.",
	aideDeform = "Stretch the texture in height or in width.",
	aideColor = "Click here to change the color of the texture.",
	aideBuff = "Enter here the name of the buff, or a part of the name, which must activate/deactivate the effect. You can enter several names if they are decently separated (ex: Super Buff/Power)",
	aideBuff2 = "Enter here the name of the debuff, or a part of the name, which must activate/deactivate the effect. You can enter several names if they are decently separated (ex: Dark Disease/Plague)",
	aideBuff3 = "Enter here the type of the debuff which must activate or deactivate the effect (Poison, Disease, Curse, Magic or None). You can also enter several types of debuff.",
	aideDebuff = "Check this to maket this effect applies to a debuff.",
	aideDebuffType = "Check this to make this effect applies to a specific kind of debuff (Poison, Disease, Curse, Magic...)",
	aideQuickHide = "Check this to make effects disappear immediately.",
	aideShowTimer = "Check this to show the timer of this effect.",
	aideInverse = "Check this to show this effect only when buff/debuff is not active.",	
	aideCommande1 = "Advanced options :",
	aideCommande2 = "Change the maximum number of textures available (20 to 50)",
	aideCommande2a = "Maximum number of textures changed to",
	aideCommande3 = "Change the maximum number of effects available (10 to 100)",
	aideCommande3a = "Maximum number of effects changed to",
	aideDisable = "Disable all effects",
	aideDuration = "After this time, this effect will disapear (0 to deactivate)",
	aideListe = "This is the list of effects available by all characters. Beware, only the effects in the Effect Editor will be active.",
	aideMaxTex = "Define the maximum number of textures available on the Effect Editor. If you add textures on the Mod directory (with the names AURA1.tga to AURA50.tga), you must indicate the correct number here.",
	nomBuff = "Name of the Buff",
	nomDebuff = "Name of the Debuff",
	nomDebuffType = "Type of the Debuff",
	nomCheckDebuff = "Debuff",
	nomCheckDebuffType = "Debuff's type",
	nomCheckQuickHide = "Quick hide effect",
	nomCheckShowTimer = "Show Timer",
	nomCheckInverse = "Show when not active",	
	nomTexture = "Texture",
	nomAnim1 = "Main Anim.",
	nomAnim2 = "Secondary Anim.",
	nomSpeed = "Anim. speed",
	nomBegin = "Begin anim.",
	nomDuration = "Anim. duration",
	nomSymetrie = "Symmetry",
	nomAlpha = "Opacity",
	nomPos = "Position",
	nomTaille = "Size",
	nomDeform = "Deformation",
	nomTest = "Test",
	nomHide = "Hide all",
	nomClose = "Close",
	nomTitre = "Effect",
	nomListe = "List >>",
	nomCentiemes = "Show hundredth",
	nomDisable = "Desactivate Power Auras",
	nomEffectEditor = "Effect Editor",
	nomAdvOptions = "Advanced Options",
	nomMaxTex = "Maximum of textures available",
	listheader = "Buffs/Debuffs List",
	listdelete = "Delete this effect.",
	listload = "Copy this effect to the current edition window.",
	listadd = ">> Add",
	listaddall = ">> Add all",
	listaideadd = "Save in the list the current edited effect.",
	listaideaddall = "Save in the list all the effects of this character.",
	erreur1 = "Error : The current effect dont have any name.",
	erreur2 = "Error : A saved effect already have this name.",
	erreur3 = "Error : Not enough room to save this effect."
};

end

