function TitanLocalizeSP()
	TITAN_DEBUG = "<Titan>";
	TITAN_INFO = "<Titan>"
	
	TITAN_NA = "N/A";
	TITAN_SECONDS = "segundos";
	TITAN_MINUTES = "minutos";
	TITAN_HOURS = "horas";
	TITAN_DAYS = "dias";
	TITAN_SECONDS_ABBR = "s";
	TITAN_MINUTES_ABBR = "m";
	TITAN_HOURS_ABBR = "h";
	TITAN_DAYS_ABBR = "d";
	TITAN_MILLISECOND = "ms";
	TITAN_KILOBYTES_PER_SECOND = "KB/s";
	TITAN_KILOBITS_PER_SECOND = "kbps"
	TITAN_MEGABYTE = "MB";
	
	TITAN_MOVABLE_TOOLTIP = "Pinchar para mover";

	TITAN_PANEL_ERROR_DUP_PLUGIN = " Aparece registrado dos veces, esto causara que Titan panel falle por favour corriga el problema"
	
	TITAN_PANEL = "Titan Panel";
	TITAN_PANEL_MENU_TITLE = "Titan Panel";
	TITAN_PANEL_MENU_HIDE = "Ocultar";
	TITAN_PANEL_MENU_CUSTOMIZE = "Configure";
	TITAN_PANEL_MENU_SHOW_COLORED_TEXT = "Texto en Color";
	TITAN_PANEL_MENU_SHOW_ICON = "Iconos";
	TITAN_PANEL_MENU_SHOW_LABEL_TEXT = "Etiqueta de Texto";
	TITAN_PANEL_MENU_AUTOHIDE = "Auto-ocluta";
	TITAN_PANEL_MENU_BGMINIMAP = "CampoBatalla en mini-mapa";
	TITAN_PANEL_MENU_CENTER_TEXT = "Texto Centrado";
	TITAN_PANEL_MENU_DISPLAY_ONTOP = "Mostrar arriba";
	TITAN_PANEL_MENU_DISPLAY_BOTH = "Mostrar ambas barras";
	TITAN_PANEL_MENU_DISABLE_PUSH = "Desactiva ajuste pantalla";
	TITAN_PANEL_MENU_BUILTINS = "Titan Built-ins";
	TITAN_PANEL_MENU_LEFT_SIDE = "Lado Izquierdo";
	TITAN_PANEL_MENU_RIGHT_SIDE = "Lado Derecho";
	TITAN_PANEL_MENU_LOAD_SETTINGS = "Cargar Ajustes";
	TITAN_PANEL_MENU_DOUBLE_BAR = "Doble Barra";
	TITAN_PANEL_MENU_OPTIONS = "Opciones";
	TITAN_PANEL_MENU_PLUGINS = "Plugins";
	TITAN_PANEL_MENU_VERSION_SHOWN = "Mostrar version plugin";
	TITAN_PANEL_MENU_DISBALE_FONT = "Desativa escala letra";
	TITAN_PANEL_MENU_CATEGORIES = {"General","Combate","Informacion","Interfaz","Profesiones"}
	TITAN_PANEL_MENU_TOOLTIPS_SHOWN = "Cuadro Dialogo";
	TITAN_PANEL_MENU_CASTINGBAR = "Mueve barra casteo";
	
	TITAN_AUTOHIDE_TOOLTIP = "Encender/Apagar boton auto-oculta";
	TITAN_AUTOHIDE_MENU_TEXT = "Auto-oculta";
	
	TITAN_AMMO_FORMAT = "%d";
	TITAN_AMMO_BUTTON_LABEL_AMMO = "Municion: ";
	TITAN_AMMO_BUTTON_LABEL_THROWN = "Arrojadiza: ";
	TITAN_AMMO_BUTTON_LABEL_AMMO_THROWN = "Municion/Arrojadiza: ";
	TITAN_AMMO_TOOLTIP = "Contador Municion/Arrojadiza Equipada";
	TITAN_AMMO_MENU_TEXT = "Municion/Arrojadiza";
	TITAN_AMMO_THROWN_KEYWORD = "Arrojadiza";
	
	TITAN_BAG_FORMAT = "%d/%d";
	TITAN_BAG_BUTTON_LABEL = "Bolsas: ";
	TITAN_BAG_TOOLTIP = "Uso Bolsas";
	TITAN_BAG_TOOLTIP_HINTS = "Consejo: Click-Izq. Abre todas las bolsas.";
	TITAN_BAG_MENU_TEXT = "Bolsas";
	TITAN_BAG_MENU_SHOW_USED_SLOTS = "Mostrar huecos usados";
	TITAN_BAG_MENU_SHOW_AVAILABLE_SLOTS = "Mostrar huecos libres";
	TITAN_BAG_MENU_IGNORE_AMMO_POUCH_SLOTS = "Ignora huecos sacos municion";
	TITAN_BAG_MENU_IGNORE_SHARD_BAGS_SLOTS = "Ignora sacos shard";
	TITAN_BAG_MENU_IGNORE_PROF_BAGS_SLOTS = "Ignora sacos profesiones";
	TITAN_BAG_SHARD_BAG_NAMES = {"Soul","Felcloth Bag"};
	TITAN_BAG_AMMO_POUCH_NAMES = {"Ammo", "Quiver", "Bandolier", "Shot", "Lamina"};
	TITAN_BAG_PROF_BAG_NAMES = {"Enchanted Mageweave Pouch","Enchanted Runecloth Bag","Cenarion Herb Bag","Satchel of Cenarius"};

	TITAN_BGMINIMAP_MENU_TEXT = "CampoBatalla minimapa"
	TITAN_BGMINIMAP_TOOLTIP = "Boton CampoBatalla minimapa"
	
	TITAN_CLOCK_TOOLTIP = "Reloj";
	TITAN_CLOCK_TOOLTIP_VALUE = "Horario: ";
	TITAN_CLOCK_TOOLTIP_HINT1 = "Consejo: click-Izq. Ajusta el horario"
	TITAN_CLOCK_TOOLTIP_HINT2 = "y el formato de tiempo 12/24H.";
	TITAN_CLOCK_CONTROL_TOOLTIP = "Horario: ";
	TITAN_CLOCK_CONTROL_TITLE = "Horario";
	TITAN_CLOCK_CONTROL_HIGH = "+12";
	TITAN_CLOCK_CONTROL_LOW = "-12";
	TITAN_CLOCK_CHECKBUTTON = "24H Fmt";
	TITAN_CLOCK_CHECKBUTTON_TOOLTIP = "Boton cambio formato entre 12-horas y 24-horas";
	TITAN_CLOCK_MENU_TEXT = "Reloj";
	TITAN_CLOCK_MENU_DISPLAY_ON_RIGHT_SIDE = "Mostrar al final en la derecha";
	
	TITAN_COORDS_FORMAT = "(%.d, %.d)";
	TITAN_COORDS_BUTTON_LABEL = "Loc: ";
	TITAN_COORDS_TOOLTIP = "Info Localizacion";
	TITAN_COORDS_TOOLTIP_HINTS_1 = "Consejo: Shift + click-Izq. para poner localizacion";
	TITAN_COORDS_TOOLTIP_HINTS_2 = "en el chat de mensajes.";
	TITAN_COORDS_TOOLTIP_ZONE = "Zona: ";
	TITAN_COORDS_TOOLTIP_SUBZONE = "SubZona: ";
	TITAN_COORDS_TOOLTIP_PVPINFO = "Info PVP: ";
	TITAN_COORDS_TOOLTIP_HOMELOCATION = "Lozalizacion Casa";
	TITAN_COORDS_TOOLTIP_INN = "Posada: ";
	TITAN_COORDS_MENU_TEXT = "Localizacion";
	TITAN_COORDS_MENU_SHOW_ZONE_ON_PANEL_TEXT = "Mostrar Texto Zona";
	TITAN_COORDS_MENU_SHOW_COORDS_ON_MAP_TEXT = "Coordenadas en MapaMundi";
	TITAN_COORDS_MAP_COORDS_TEXT = "%d, %d";
	TITAN_COORDS_MAP_CURSOR_COORDS_TEXT = "Cursor(X,Y): %s";
	TITAN_COORDS_MAP_PLAYER_COORDS_TEXT = "Jugador(X,Y): %s";
	
	TITAN_FPS_FORMAT = "%.1f";
	TITAN_FPS_BUTTON_LABEL = "FPS: ";
	TITAN_FPS_MENU_TEXT = "FPS";
	TITAN_FPS_TOOLTIP_CURRENT_FPS = "Actuales FPS: ";
	TITAN_FPS_TOOLTIP_AVG_FPS = "Mejores FPS: ";
	TITAN_FPS_TOOLTIP_MIN_FPS = "Minimas FPS: ";
	TITAN_FPS_TOOLTIP_MAX_FPS = "Maximas FPS: ";
	TITAN_FPS_TOOLTIP = "Ventanas por Segundo";
	
	TITAN_HONOR_BUTTON_LABEL_RANK = RANK..": ";
	TITAN_HONOR_BUTTON_LABEL_HK = "MH: ";
	TITAN_HONOR_BUTTON_LABEL_DK = "MD: ";
	TITAN_HONOR_TOOLTIP = "Info Honor PVP";
	TITAN_HONOR_MENU_TEXT = "Honor PVP";
	
	TITAN_LATENCY_FORMAT = "%d"..TITAN_MILLISECOND;
	TITAN_LATENCY_BANDWIDTH_FORMAT = "%.3f "..TITAN_KILOBYTES_PER_SECOND;
	TITAN_LATENCY_BUTTON_LABEL = "Latencia: ";
	TITAN_LATENCY_TOOLTIP = "Estado Red";
	TITAN_LATENCY_TOOLTIP_LATENCY = "Latencia: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_IN = "AnchoBanda entrante: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_OUT = "AnchoBanda salida: ";
	TITAN_LATENCY_MENU_TEXT = "Latencia";
	
	TITAN_LOOTTYPE_BUTTON_LABEL = "Saqueo: ";
	TITAN_LOOTTYPE_FREE_FOR_ALL = "Libre para Todos";
	TITAN_LOOTTYPE_ROUND_ROBIN = "Ronda Robin";
	TITAN_LOOTTYPE_MASTER_LOOTER = "Maestro Saqueador";
	TITAN_LOOTTYPE_GROUP_LOOT = "Saqueo en Grupo";
	TITAN_LOOTTYPE_NEED_BEFORE_GREED = "Necesito antes de Greed";
	TITAN_LOOTTYPE_TOOLTIP = "Tipo Saqueo";
	TITAN_LOOTTYPE_MENU_TEXT = "Tipo Saqueo";
	
	TITAN_MEMORY_FORMAT = "%.3f"..TITAN_MEGABYTE;
	TITAN_MEMORY_RATE_FORMAT = "%.3f"..TITAN_KILOBYTES_PER_SECOND;
	TITAN_MEMORY_BUTTON_LABEL = "Memoria: ";
	TITAN_MEMORY_TOOLTIP = "Uso Memoria";
	TITAN_MEMORY_TOOLTIP_CURRENT_MEMORY = "Actual: ";
	TITAN_MEMORY_TOOLTIP_INITIAL_MEMORY = "Inicial: ";
	TITAN_MEMORY_TOOLTIP_INCREASING_RATE = "Ratio Incrementado: ";
	TITAN_MEMORY_TOOLTIP_GC_INFO = "Garbage-Collection Info: ";
	TITAN_MEMORY_TOOLTIP_GC_THRESHOLD = "GC threshold: ";
	TITAN_MEMORY_TOOLTIP_TIME_TO_GC = "Tiempo para Siguiente GC: "
	TITAN_MEMORY_MENU_TEXT = "Memoria";
	TITAN_MEMORY_MENU_RESET_SESSION = "Resetea Datos memoria";
	
	TITAN_MONEY_GOLD = "o";
	TITAN_MONEY_SILVER = "p";
	TITAN_MONEY_COPPER = "c";
	TITAN_MONEY_FORMAT = "%d"..TITAN_MONEY_GOLD..", %d"..TITAN_MONEY_SILVER..", %d"..TITAN_MONEY_COPPER;
	TITAN_MONEY_MENU_TEXT = "Dinero";
	TITAN_MONEY_MENU_RESET_SESSION = "Resetea sesion";
	TITAN_MONEY_TOOLTIP = "Fluctuacion Monetaria";
	TITAN_MONEY_TOOLTIP_HINTS = "Consejo: Click-Izq. Para coger dinero.";
	TITAN_MONEY_TOOLTIP_CURRENT = "Actual: ";
	TITAN_MONEY_TOOLTIP_INITIAL = "Inicial: ";
	TITAN_MONEY_TOOLTIP_EARNED = "Ganado: ";
	TITAN_MONEY_TOOLTIP_LOST = "Gastado: ";
	TITAN_MONEY_TOOLTIP_EARNED_HOUR = "Ganado/hr: ";
	TITAN_MONEY_TOOLTIP_LOST_HOUR = "Gastado/hr: ";
	
	TITAN_PERFORMANCE_TOOLTIP = "Monitorizacion";
	TITAN_PERFORMANCE_MENU_TEXT = "Monitorizacion";
	TITAN_PERFORMANCE_MENU_SHOW_FPS = "Muestra FPS";
	TITAN_PERFORMANCE_MENU_SHOW_LATENCY = "Muestra Latencia";
	TITAN_PERFORMANCE_MENU_SHOW_MEMORY = "Muestra Memoria";

	TITAN_RIDER_HINT = "Actualmente estas: ";
	TITAN_RIDER_OPTIONS_SHOWSTATE = "Mostrar Estado Jugador";
	TITAN_RIDER_OPTIONS_EQUIP = "Objetos Equipados";
	TITAN_RIDER_STATES = {"A pie", "Montado", "Volando", "Oveja"};
	TITAN_RIDER_ITEMS = 3;
	TITAN_RIDER_ITEM_NAMES = {nil,"Carrot on a Stick",nil};
	TITAN_RIDER_ITEM_DESCS = {"Mithril Spurs",nil,"Minor Mount Speed Increase"};
	TITAN_RIDER_ITEM_SLOTS = {"FeetSlot","Trinket0Slot","HandsSlot"}

	TITAN_TRANS_TOOLTIP = "Control Transparencia";
	TITAN_TRANS_TOOLTIP_VALUE = "Transparencia Panel: ";
	TITAN_TRANS_TOOLTIP_HINT1 = "Consejo: Click-Izq. Ajustara la";
	TITAN_TRANS_TOOLTIP_HINT2 = "transparenccia del panel.";
	TITAN_TRANS_CONTROL_TOOLTIP = "Transparencia Panel: ";
	TITAN_TRANS_CONTROL_TITLE = "Transparencia";
	TITAN_TRANS_CONTROL_HIGH = "100%";
	TITAN_TRANS_CONTROL_LOW = "0%";
	TITAN_TRANS_MENU_TEXT = "Transparencia Panel";
	
	TITAN_UISCALE_TOOLTIP = "UI/Panel/Escala Letra";
	TITAN_UISCALE_TOOLTIP_VALUE_UI = "UI Escala: ";
	TITAN_UISCALE_TOOLTIP_VALUE_PANEL = "Escala Panel: ";
	TITAN_UISCALE_TOOLTIP_VALUE_FONT = "Escala Letra: ";
	TITAN_UISCALE_TOOLTIP_HINT1 = "Consejo: Click-izq. Ajustara el tamano del";
	TITAN_UISCALE_TOOLTIP_HINT2 = "panel o de la interfaz del juego.";
	TITAN_UISCALE_CONTROL_TOOLTIP_UI = "Escala UI: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_PANEL = "Escala Panel: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_FONT = "Escala Letra: ";
	TITAN_UISCALE_CONTROL_TITLE_UI = "Escala UI";
	TITAN_UISCALE_CONTROL_TITLE_PANEL = "Escala Panel";
	TITAN_UISCALE_CONTROL_TITLE_FONT = "Font Scale";
	TITAN_UISCALE_CONTROL_HIGH_UI = "100%";
	TITAN_UISCALE_CONTROL_HIGH_PANEL = "125%";
	TITAN_UISCALE_CONTROL_HIGH_FONT = "200%";
	TITAN_UISCALE_CONTROL_LOW_UI = "64%";
	TITAN_UISCALE_CONTROL_LOW_PANEL = "75%";
	TITAN_UISCALE_CONTROL_LOW_FONT = "50%";
	TITAN_UISCALE_MENU_TEXT = "UI/Panel/Escala Letra";
	
	TITAN_VOLUME_TOOLTIP = "Control Volumen";
	TITAN_VOLUME_TOOLTIP_VALUE = "Master sound volume: ";
	TITAN_VOLUME_TOOLTIP_HINT1 = "Consejo: Click-Izq. Para ajustar el"
	TITAN_VOLUME_TOOLTIP_HINT2 = "master sound volume.";
	TITAN_VOLUME_CONTROL_TOOLTIP = "Master Sound Volume: ";
	TITAN_VOLUME_CONTROL_TITLE = "Volumen";
	TITAN_VOLUME_CONTROL_HIGH = "Alto";
	TITAN_VOLUME_CONTROL_LOW = "Bajo";
	TITAN_VOLUME_MENU_TEXT = "Volumen";
	
	TITAN_XP_FORMAT = "%d";
	TITAN_XP_PERCENT_FORMAT = TITAN_XP_FORMAT.." (%.1f%%)";
	TITAN_XP_BUTTON_LABEL_XPHR_LEVEL = "XP/hr este nivel: ";
	TITAN_XP_BUTTON_LABEL_XPHR_SESSION = "XP/hr esta sesion: ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_LEVEL = "Tiempo para subir: ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_SESSION = "Tiempo para subir: ";
	TITAN_XP_TOOLTIP = "INFO Experiencia(XP)";
	TITAN_XP_TOOLTIP_TOTAL_TIME = "Total jugado: ";
	TITAN_XP_TOOLTIP_LEVEL_TIME = "Jugado este nivel: ";
	TITAN_XP_TOOLTIP_SESSION_TIME = "Jusgado esta sesion: ";
	TITAN_XP_TOOLTIP_TOTAL_XP = "Total XP requerida este nivel: ";
	TITAN_XP_TOOLTIP_LEVEL_XP = "XP ganada este nivel: ";
	TITAN_XP_TOOLTIP_TOLEVEL_XP = "XP necesaria para subir: ";
	TITAN_XP_TOOLTIP_SESSION_XP = "XP ganada esta session: ";
	TITAN_XP_TOOLTIP_XPHR_LEVEL = "XP/hr este nivel: ";
	TITAN_XP_TOOLTIP_XPHR_SESSION = "XP/hr esta sesion: ";
	TITAN_XP_TOOLTIP_TOLEVEL_LEVEL = "Tiempo para subir (ratio nivel): ";
	TITAN_XP_TOOLTIP_TOLEVEL_SESSION = "Tiempo para subir (ratio sesion): ";
	TITAN_XP_MENU_TEXT = "Experiencia(XP)";
	TITAN_XP_MENU_SHOW_XPHR_THIS_LEVEL = "Mostrar XP/hr este nivel";
	TITAN_XP_MENU_SHOW_XPHR_THIS_SESSION = "Mostrar XP/hr esta sesion";
	TITAN_XP_MENU_RESET_SESSION = "Resetea sesion";
	
	TITAN_REGEN_MENU_TEXT 		= "Regeneracion"
	TITAN_REGEN_MENU_TOOLTIP_TITLE	= "Ratios Regeneracion"
	TITAN_REGEN_MENU_SHOW1 		= "Muestra"
	TITAN_REGEN_MENU_SHOW2 		= "PV"
	TITAN_REGEN_MENU_SHOW3 		= "PM"
	TITAN_REGEN_MENU_SHOW4		= "Como Porcentaje"
	TITAN_REGEN_BUTTON_TEXT_HP 		= "PV: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_HP_PERCENT 	= "PV: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP 		= " PM: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP_PERCENT 	= " PM: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP1 		= "Salud: \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP2 		= "Mana: \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP3 		= "Mejor ERgen PV: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP4 		= "Peor Regen PV: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP5 		= "Mejor Regen PM: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP6 		= "Peor REgen PM: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP7		= "PM Regen ultima Pelea: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..GREEN_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE.."%%)";

	TITAN_ITEMBONUSES_TEXT = "Bonus Objetos";
	TITAN_ITEMBONUSES_DISPLAY_NONE = "No Mostrar";
	TITAN_ITEMBONUSES_SHORTDISPLAY = "Etiqueta de Texto";
	TITAN_ITEMBONUSES_BONUSSCANNER_MISSING = "Requerido BonusScanner AddOn";

	TITAN_ITEMBONUSES_CAT_ATT = "Atributos";
	TITAN_ITEMBONUSES_CAT_RES = "Resistencia";
	TITAN_ITEMBONUSES_CAT_SKILL = "Habilidades";
	TITAN_ITEMBONUSES_CAT_BON = "Melee y Combate a Distancia";
	TITAN_ITEMBONUSES_CAT_SBON = "Hechizos";
	TITAN_ITEMBONUSES_CAT_OBON = "Vida y Mana";

	TITAN_HONORPLUS_BUTTON_LABEL_RANK = RANK..": ";
	TITAN_HONORPLUS_CLASSINDEX = {
		["Druid"]   = 1,
		["Hunter"]  = 2,
		["Mage"]    = 3,
		["Paladin"] = 4,
		["Priest"]  = 5,
		["Rogue"]   = 6,
		["Shaman"]  = 7,
		["Warlock"] = 8,
		["Warrior"] = 9,
		["Druide"] = 1,
		["J\195\164ger"] = 2,
		["Magier"] = 3,
		["Paladin"] = 4,
		["Priester"] = 5,
		["Schurke"] = 6,
		["Schamane"] = 7,
		["Hexenmeister"] = 8,
		["Krieger"] = 9,
		["Druide"] = 1,
		["Chasseur"] = 2,
		["Mage"] = 3,
		["Paladin"] = 4,
		["Pr\195\170tre"] = 5,
		["Voleur"] = 6,
		["Chaman"] = 7,
		["D\195\169moniste"] = 8,
		["Guerrier"] = 9,
	};
	
	TITAN_HONORPLUS_BUTTON_LABEL_HK = "MH: ";
	TITAN_HONORPLUS_BUTTON_LABEL_DK = "MD: ";
	TITAN_HONORPLUS_TOOLTIP = "Info PVP Honor+";
	TITAN_HONORPLUS_TOOLTIP_THISWEEK = "Esta Semana"
	TITAN_HONORPLUS_MENU_TEXT = "Honor+";
	TITAN_HONORPLUS_MENU_CALCTODAY = "Add-on Calcula MH de Hoy";
	TITAN_HONORPLUS_MENU_SCT = "Mostrar en Scrolling Combat Text";
	TITAN_HONORPLUS_MENU_OPIUM = "Soporte Opium";
	TITAN_HONORPLUS_MENU_SCOREBOARDCLASSCOLORSYMBOL = "Scoreboard Color Class Symbol";
	TITAN_HONORPLUS_MENU_SCOREBOARDCLASSCOLORLIST = "Scoreboard Color Class Name";
	TITAN_HONORPLUS_MENU_SCOREBOARDKILLS = "Show Today's Kills on Scoreboard";
	TITAN_HONORPLUS_MENU_PRINTBONUS = "Muestra Bonus honor en ventana chat";
	TITAN_HONORPLUS_MENU_TOOLTIP = "Info Cuadro Dialogo";
	TITAN_HONORPLUS_MENU_SORTBYHONOR = "Por Honor";
	TITAN_HONORPLUS_MENU_SORTBYKILLS = "Por Muertes";
	TITAN_HONORPLUS_ESTIMATED = "%s muere, [%d veces hoy.], Rango: %s. [Honor Educado: %d]";
	TITAN_HONORPLUS_BONUSHONORGAINED = "Ganas %s bonus honor.";
	TITAN_HONORPLUS_BONUS = "Bonus";
	TITAN_HONORPLUS_PROGRESS = "Progreso";
	TITAN_HONORPLUS_TODAYHONOR = "Honor Hoy";
	TITAN_HONORPLUS_KILLS = "Matados";
	TITAN_HONORPLUS_DEATHS = "Muerto";
	TITAN_HONORPLUS_TOTAL = "Total";
	TITAN_HONORPLUS_TOP15 = "Top 15";
	TITAN_HONORPLUS_PVPSTATS = "PvP Stats";
	TITAN_HONORPLUS_NOKILLS = "No Muertes";
	TITAN_HONORPLUS_HINT = "Consejo: Click-Izq. Para diferentes estadisticas.";
	TITAN_HONORPLUS_HINT_TOOLTIP = "(click-Izq para mas)";
	TITAN_HONORPLUS_TOOLTIP_TODAYSKILLS = "Numero de muertes hoy.\nSi muere mas de 4 veces, entonces no mas honor de ese jugador.";
	TITAN_HONORPLUS_KILLEDTODAY = "Matados Hoy";
	TITAN_HONORPLUS_MENU_AUTORELEASE = "Auto-Release";
	TITAN_HONORPLUS_MENU_AUTOJOINBG = "Auto-Join Battlegrounds";
	TITAN_HONORPLUS_AUTOJOINBG = "Auto-unirse a CampoBatalla en 10 segundos...";
	TITAN_HONORPLUS_AUTOJOINBG_CANCEL = "Cancelado unirse a CampoBatalla.";
	TITAN_HONORPLUS_AUTOJOINBG_DONE = "Uniendose a CampoBatalla. Buena Suerte!";

	--Titan Repair
	REPAIR_LOCALE = {
		pattern = "^Durability (%d+) / (%d+)$",
		menu = "Info Durabilidad",
		tooltip = "Info Durabilidad",
		button = "Durabilidad: ",
		percentage = "Como Porcentaje",
		itemname = "Nombre Objeto",
		undamaged = "Objetos no danados",
		nothing = "Nada danado",
		confirmation = "Realmente quieres reparar todos los objetos equipados?",
		popup = "Mostrar Popup reparacion",
		repinventory = "Reparara Inventario tambien",
		showinventory = "Calcula dano Inventario"
	};

	TITAN_PLUGINS_MENU_TITLE = "Plug-ins";
	
	CUSTOMIZATION_FEATURE_COMING_SOON = "Opciones de configuracion viene pronto...";
end
