local L = AceLibrary("AceLocale-2.0"):new("ag_UnitFrames")

aUF.Layouts.ABF = {
		Name = "ABF",
		Tip = "ABF Tip",
		ResizeBars = false,
		BackgroundBarColor = true,
		AlphaBar = true,
		RaidColorName = false,
		PetClassName = true,	
		ComboGFX = true,
		HappinessBar = true,
		
		ThemeData = {
			all = {
				FrameHeight = 25,
				FrameWidth = 140,

				Combo1 = 	{ 		Point = "BOTTOMRIGHT",
									RelativePoint = "BOTTOMRIGHT",
									x = 1,
									y = -1,	
									Height = 10,
									HeightAdd = 0,									
									Width = 10,
								},
								
				HealthBar_BG = 	{ 	Point = "TOPLEFT",
									RelativePoint = "TOPLEFT",
									x = 5,
									y = -5,	
									Visibility = {"HealthBar_BG","HealthBar","BarHealthText","HealthText",},
									Height = 15,
									HeightAdd = 0,									
									Width = 90,
								},
									
				ManaBar_BG = 	{	Point = "TOPLEFT",
									RelativePoint = "TOPLEFT", 
									x = 5, 
									y = -21, 
									HeightAdd = 12,
									Visibility = {"ManaBar_BG","ManaBar","BarManaText","ManaText","ClassText",},	
									Height = 11,
									Width = 90,
								},
								
				XPBar_BG = 		{	Point = "TOPLEFT", 
									RelativeTo = "ManaBar_BG", 
									RelativeToSecondary = "HealthBar_BG", 
									RelativePoint = "BOTTOMLEFT", 
									x = 0, 
									y = -1, 
									HeightAdd = 5,
									Visibility = {"XPBar_BG","XPBar","XPBar_Rest"},	
									Width = 90,
									Height = 4,
								},
									
				NameBackground=	{	Hidden = true,
								},
								
					Happiness =	{	Point = "TOPLEFT",
									RelativeTo = "HealthBar_BG",
									RelativePoint = "TOPLEFT", 
									x=0,
									y=0,
									Height = 15,
									Width = 90,
									Visibility = {"Happiness",},
								},
								
				NameLabel = 	{ 	Font = L"Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf", 
									FontSize = 9, 
									Width = 90, 
									Point = "LEFT", 
									RelativeTo = "HealthBar", 
									RelativePoint = "LEFT", 
									x = 2, 
									y =0,
								},
				
				ClassText =	 	{ 	Font = L"Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf",
									FontSize = 8, 
									Justify = "LEFT",
									Width = 90, 
									Point = "LEFT", 
									RelativeTo = "ManaBar", 
									RelativePoint = "LEFT", 
									x = 2, 
									y =0.5,
								},
					
				HealthText = 	{ 	Font = "Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf", 
									FontSize = 9,
									Point = "RIGHT", 
									RelativeTo = "HealthBar_BG", 
									RelativePoint = "RIGHT", 
									x=-2,
									y=0,
									Width = 60,
									Justify = "RIGHT",
								},
					
				ManaText = 		{ 	Font = "Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf", 
									FontSize = 8,
									Point = "RIGHT", 
									RelativeTo = "ManaBar_BG", 
									RelativePoint = "RIGHT", 
									x=-2,
									y=0.5,
									Width = 60,
									Justify = "RIGHT",
								},
									
				BarHealthText = { 	Font = "Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf", 
									FontSize = 9,
									RelativeTo = "HealthBar_BG",
									Point = "CENTER",
									RelativePoint = "CENTER",
									x=0,
									y=0,
									Width = 60,									
									
								},
									
				BarManaText = 	{ 	Font = "Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf", 
									FontSize = 8,
									RelativeTo = "ManaBar_BG",
									Point = "CENTER",
									RelativePoint = "CENTER",
									x=0,
									y=0,
									Width = 60,							
								},
				
				PVPIcon = 		{ 	Point = "TOPRIGHT", 
									RelativePoint = "TOPRIGHT", 
									x = 14, 
									y= 2,
								},

				InCombatIcon = 		{ 	Point = "BOTTOMLEFT", 
									RelativePoint = "BOTTOMLEFT", 
									x = -4, 
									y= -3,
								},

				RestingIcon = 		{ 	Point = "TOPRIGHT", 
									RelativePoint = "TOPRIGHT", 
									x = 5, 
									y= 6,
								},

				RaidTargetIcon =	{	Point = "CENTER",
									RelativePoint = "TOP",
									x = 0,
									y = -3,
								},
								
				LeaderIcon = 	{ 	Point = "TOPLEFT", 
									RelativePoint = "TOPLEFT", 
									x = -2, 
									y= 2,
								},
								
				MasterIcon = 	{ 	Point = "TOPLEFT", 
									RelativePoint = "TOPLEFT", 
									x = -5, 
									y= 2,
								},
			},
			raid = {
				FrameWidth = 110,
--				HealthBar_BG = 	{ 	Width = 100,
--								},
--				ManaBar_BG = 	{	Width = 100,
--								},								
			},
		}
	}

