local L = AceLibrary("AceLocale-2.0"):new("ag_UnitFrames")

aUF.Layouts.PerfectRaid = {
		Name = "PerfectRaid",
		Tip = "PerfectRaid",
		ResizeBars = false,
		BackgroundBarColor = false,
		AlphaBar = false,
		RaidColorName == true,
		ComboGFX = true,
		
		ThemeData = {
			all = {
				FrameHeight = 22,
				FrameWidth = 130,	

				Combo1 = 	{ 		Point = "BOTTOMRIGHT",
									RelativePoint = "BOTTOMRIGHT",
									x = 1,
									y = -1,	
									Height = 10,
									HeightAdd = 0,									
									Width = 10,
								},
								
				HealthBar_BG = 	{ 	Point = "LEFT",
									RelativeTo = "NameLabel",				
									RelativePoint = "RIGHT",
									x = 5,
									y = -0.5,	
									Visibility = {"HealthBar_BG","HealthBar","BarHealthText","HealthText",},
									Height = 7,
									Width = 25,
								},
									
				ManaBar_BG = 	{	Point = "TOPLEFT",
									RelativeTo = "HealthBar_BG",				
									RelativePoint = "BOTTOMLEFT", 
									x = 0, 
									y = -2, 
									Visibility = {"ManaBar_BG","ManaBar","BarManaText","ManaText","ClassText",},		
									Height = 4,
									Width = 25,
									HeightAdd = 6,
									Hidden = true,									
								},
								
				XPBar_BG = 		{	Point = "TOPLEFT", 
									RelativeTo = "ManaBar_BG",
									RelativeToSecondary = "HealthBar_BG", 									
									RelativePoint = "BOTTOMLEFT", 
									x = 0, 
									y = -2, 
									Visibility = {"XPBar_BG","XPBar","XPBar_Rest"},	
									Width = 25,
									Height = 3,
									HeightAdd = 5,
									Hidden = true,
								},

				NameBackground=	{	Point = "TOPLEFT",
									RelativePoint = "TOPLEFT", 
									x=6,
									y=-2,
									Height = 18,
									Width = 25,
								},
					Happiness =	{	Point = "TOPLEFT",
									RelativePoint = "TOPLEFT", 
									x=6,
									y=-2,
									Height = 18,
									Width = 25,
									Visibility = {"Happiness",},	
								},
								
				NameLabel = 	{ 	Font = L"Fonts\\FRIZQT__.TTF", 
									FontSize = 9, 
									Width = 55, 
									Point = "TOPLEFT", 
									RelativePoint = "TOPLEFT", 
									x =8, 
									y =-10,
								},
					
				ClassText =	 	{ 	Font = L"Fonts\\FRIZQT__.TTF",
									FontSize = 9,
									Justify = "LEFT",
									Width = 60, 
									Point = "TOPLEFT", 
									RelativePoint = "TOPLEFT", 
									x =-5, 
									y =0,
									Hidden = true,
								},
				
				HealthText = 	{ 	Font = "Fonts\\FRIZQT__.TTF", 
									FontSize = 8,
									Point = "RIGHT", 
									RelativeTo = "HealthBar_BG", 
									RelativePoint = "RIGHT", 
									x=-2,
									y=0,
									Width = 60,									
								},
					
				ManaText = 		{ 	Font = "Fonts\\FRIZQT__.TTF", 
									FontSize = 8,
									Point = "RIGHT", 
									RelativeTo = "ManaBar_BG", 
									RelativePoint = "RIGHT", 
									x=-2,
									y=0.5,
									Width = 60,									
								},
									
				BarHealthText = { 	Font = "Fonts\\FRIZQT__.TTF", 
									FontSize = 8,
									RelativeTo = "HealthBar_BG",
									Point = "CENTER",
									RelativePoint = "CENTER",
									x=0,
									y=0,
									Width = 60,									
								},
									
				BarManaText = 	{ 	Font = "Fonts\\FRIZQT__.TTF", 
									FontSize = 8,
									RelativeTo = "ManaBar_BG",
									Point = "CENTER",
									RelativePoint = "CENTER",
									x=0,
									y=0,
									Width = 60,									
								},
				
				PVPIcon = 		{ 	Point = "TOPRIGHT", 
									RelativePoint = "TOPRIGHT", 
									x = 14, 
									y= 2,
								},

				InCombatIcon = 		{ 	Hidden = true,
								},

				RestingIcon =		{	Hidden = true,
								},

				RaidTargetIcon =	{	Point = "CENTER",
									RelativePoint = "TOP",
									x = 0,
									y = -3,
								},
								
				LeaderIcon = 	{ 	Point = "TOPLEFT", 
									RelativePoint = "TOPLEFT", 
									x = -2, 
									y= 2,
								},
								
				MasterIcon = 	{ 	Point = "TOPLEFT", 
									RelativePoint = "TOPLEFT", 
									x = -5, 
									y= 2,
								},
			}
		}
	}
