MendeleevLocals.infosets = {
	{
		name		= MendeleevLocals.CatNames.Gather,
		setindex = "gatherskill",
		--color = {0.0, 0.75, 0.8},
		colour = "|cff8470FF",
		header = MendeleevLocals.Category.Gather,
		sets = {
			gatherskillfishing    = MendeleevLocals.Gather.Fish,
			gatherskilldisenchant = MendeleevLocals.Gather.Disen,
			gatherskillherbalism  = MendeleevLocals.Gather.Herb,
			gatherskillmining     = MendeleevLocals.Gather.Mine,
			gatherskillskinning   = MendeleevLocals.Gather.Skin,
		}
	},
	{
		name = MendeleevLocals.CatNames.Mine,
		setindex = "minedgem",
		--color = {0.75, 0.75, 0.75},
		colour = "|cffB0C4DE",
		header = MendeleevLocals.Category.Mine,
		sets = {
			minedgemcopper      = MendeleevLocals.Mine.Copper,
			minedgemtin         = MendeleevLocals.Mine.Tin,
			minedgemsilver      = MendeleevLocals.Mine.Silver,
			minedgemiron        = MendeleevLocals.Mine.Iron,
			minedgemgold        = MendeleevLocals.Mine.Gold,
			minedgemmithril     = MendeleevLocals.Mine.Mithril,
			minedgemtruesilver  = MendeleevLocals.Mine.TSilver,
			minedgemthorium     = MendeleevLocals.Mine.Thorium,
			minedgemzgthorium   = MendeleevLocals.Mine.ZGThorium,
			minedgemrichthorium = MendeleevLocals.Mine.RThorium,
			minedgemdarkiron    = MendeleevLocals.Mine.DIron,
		}
	},
	{
		name = MendeleevLocals.CatNames.Trade,
		setindex = "tradeskill",
		--color = {1.0, 0.82, 0.0},
		colour = "|cffF5DEB3",
		header = MendeleevLocals.Category.Used,
		sets = {
			tradeskillalchemy        = MendeleevLocals.Used.Alch,
			tradeskillblacksmithing  = MendeleevLocals.Used.Smth,
			tradeskillcooking        = MendeleevLocals.Used.Cook,
			tradeskillenchanting     = MendeleevLocals.Used.Enchan,
			tradeskillengineering    = MendeleevLocals.Used.Eng,
			tradeskillfirstaid       = MendeleevLocals.Used.Aid,
			tradeskillleatherworking = MendeleevLocals.Used.Leather,
			tradeskilltailoring      = MendeleevLocals.Used.Tailor,
		}
	},
	{
		name = MendeleevLocals.CatNames.Class,
		setindex = "reagent",
		colour = "|cffff00ff",
		--color = {1.0, 0.0, 1.0},
		header = MendeleevLocals.Category.Classes,
		sets = {
			reagentpaladin = MendeleevLocals.Classes.Pal,
			reagentdruid   = MendeleevLocals.Classes.Dru,
			reagentmage    = MendeleevLocals.Classes.Mag,
			reagentpriest  = MendeleevLocals.Classes.Pri,
			reagentrogue   = MendeleevLocals.Classes.Rog,
			reagentshaman  = MendeleevLocals.Classes.Sha,
			reagentwarlock = MendeleevLocals.Classes.Warl,
		}
	},
	{
		name = MendeleevLocals.CatNames.ZGE,
		setindex = "zulgurubenchants",
		--color = { },
		colour = "|cffDC143C",
		header = MendeleevLocals.Category.ZGE,
		sets = {
			zulgurubdruidenchant   = MendeleevLocals.Classes.Dru,
			zulgurubhunterenchant  = MendeleevLocals.Classes.Hun,
			zulgurubmageenchant    = MendeleevLocals.Classes.Mag,
			zulgurubpaladinenchant = MendeleevLocals.Classes.Pal,
			zulgurubpriestenchant  = MendeleevLocals.Classes.Pri,
			zulgurubrogueenchant   = MendeleevLocals.Classes.Rog,
			zulgurubshamanenchant  = MendeleevLocals.Classes.Sha,
			zulgurubwarlockenchant = MendeleevLocals.Classes.Warl,
			zulgurubwarriorenchant = MendeleevLocals.Classes.Warr,
		}
	},
	{
		name = MendeleevLocals.CatNames.ZGCl,
		setindex = "zulgurubclasses",
		--color = { },
		colour = "|cffDC143D",
		header = MendeleevLocals.Category.ZG,
		useval = function (v) return MendeleevLocals.Rep[v] or " (Unk)" end,
		sets = {
			zulgurubdruid   	= MendeleevLocals.Classes.Dru,
			zulgurubhunter  	= MendeleevLocals.Classes.Hun,
			zulgurubmage    	= MendeleevLocals.Classes.Mag,
			zulgurubpaladin 	= MendeleevLocals.Classes.Pal,
			zulgurubpriest  	= MendeleevLocals.Classes.Pri,
			zulgurubrogue   	= MendeleevLocals.Classes.Rog,
			zulgurubshaman  	= MendeleevLocals.Classes.Sha,
			zulgurubwarlock 	= MendeleevLocals.Classes.Warl,
			zulgurubwarrior 	= MendeleevLocals.Classes.Warr,
		}
	},
--	{
--		name = MendeleevLocals.CatNames.ZGCO,
--		setindex = "zulgurubclasses",
--		filter = "zulgurubcoin",
--		--color = { },
--		header = "Coins-only test",
--		useval = function (v) return MendeleevLocals.Rep[v] or " (Unk)" end,
--		sets = {
--			zulgurubdruid   	= MendeleevLocals.Classes.Dru,
--			zulgurubhunter  	= MendeleevLocals.Classes.Hun,
--			zulgurubmage    	= MendeleevLocals.Classes.Mag,
--			zulgurubpaladin 	= MendeleevLocals.Classes.Pal,
--			zulgurubpriest  	= MendeleevLocals.Classes.Pri,
--			zulgurubrogue   	= MendeleevLocals.Classes.Rog,
--			zulgurubshaman  	= MendeleevLocals.Classes.Sha,
--			zulgurubwarlock 	= MendeleevLocals.Classes.Warl,
--			zulgurubwarrior 	= MendeleevLocals.Classes.Warr,
--		}
--	},
	{
		name = MendeleevLocals.CatNames.AQCC,
		setindex = "ahnqirajclassescc",
		--color = { },
		colour = "|cff7FFF00",
		header = MendeleevLocals.Category.AQCC,
		useval = function (v) return MendeleevLocals.Rep[v] or " (Unk)" end,
		sets = {
			ahnqirajdruidcc  	= MendeleevLocals.Classes.Dru,
			ahnqirajhuntercc  	= MendeleevLocals.Classes.Hun,
			ahnqirajmagecc     	= MendeleevLocals.Classes.Mag,
			ahnqirajpaladincc 	= MendeleevLocals.Classes.Pal,
			ahnqirajpriestcc   	= MendeleevLocals.Classes.Pri,
			ahnqirajroguecc   	= MendeleevLocals.Classes.Rog,
			ahnqirajshamancc  	= MendeleevLocals.Classes.Sha,
			ahnqirajwarlockcc 	= MendeleevLocals.Classes.Warl,
			ahnqirajwarriorcc 	= MendeleevLocals.Classes.Warr,
		}
	},
	{
		name = MendeleevLocals.CatNames.AQBON,
		setindex = "ahnqirajclassesbon",
		--color = { },
		colour = "|cffDAA520",
		header = MendeleevLocals.Category.AQBON,
		useval = function (v) return MendeleevLocals.Rep[v] or " (Unk)" end,
		sets = {
			ahnqirajdruidbon  	= MendeleevLocals.Classes.Dru,
			ahnqirajhunterbon  	= MendeleevLocals.Classes.Hun,
			ahnqirajmagebon     = MendeleevLocals.Classes.Mag,
			ahnqirajpaladinbon 	= MendeleevLocals.Classes.Pal,
			ahnqirajpriestbon   = MendeleevLocals.Classes.Pri,
			ahnqirajroguebon   	= MendeleevLocals.Classes.Rog,
			ahnqirajshamanbon  	= MendeleevLocals.Classes.Sha,
			ahnqirajwarlockbon 	= MendeleevLocals.Classes.Warl,
			ahnqirajwarriorbon 	= MendeleevLocals.Classes.Warr,
		}
	},
	{
		name = MendeleevLocals.CatNames.Food,
		setindex = "foodclass",
		--color = {0.2, 0.6, 0.8},
		colour = "|cff87CEFA",
		header = MendeleevLocals.Category.Foodtype,
		sets = {
			foodclassbread  	= MendeleevLocals.Foodtype.Bread,
			foodclassfish   	= MendeleevLocals.Foodtype.Fish,
			foodclassmeat   	= MendeleevLocals.Foodtype.Meat,
			foodclasscheese 	= MendeleevLocals.Foodtype.Cheese,
			foodclassfruit  	= MendeleevLocals.Foodtype.Fruit,
			foodclassfungus 	= MendeleevLocals.Foodtype.Fungus,
			foodclassmisc   	= MendeleevLocals.Foodtype.Misc,
		}
	},
	{
		name = MendeleevLocals.CatNames.Booze,
		setindex = "booze",
		--color = {1,1,1},
		colour = "|cffB0C4DE",
		header = " ",
		useval = function (v) return string.format("%.1f%% alc/vol", v/10) end,
		sets = {
			booze  = "",
		}
	},
	{
		name = MendeleevLocals.CatNames.Faire,
		setindex = "faire",
		--color = {1,0.2,1},
		colour = "|cffFFFF00",
		header = MendeleevLocals.Category.Faire,
		useval = function (v) return string.format(" (%d tickets)", v) end,
		sets = {
			faireengin   	= MendeleevLocals.Used.Eng,
			fairegreys   	= MendeleevLocals.Faire.Junk,
			faireleather 	= MendeleevLocals.Faire.Leather,
			fairesmithy  	= MendeleevLocals.Used.Smth,
		}
	},
	{
		name = MendeleevLocals.CatNames.Lock,
		setindex = {"keyskeleton", "lockboxes", "seaforium"},
		--color = {1,1,1},
		colour = "|cffFFFF00",
		header = " ",
		useval = function (v) return v end,
		sets = {
			keyskeleton 	= MendeleevLocals.Misc.Lock,
			lockboxes   	= MendeleevLocals.Misc.Lock,
			seaforium   	= MendeleevLocals.Misc.Lock,
		}
	},
	{
		name = MendeleevLocals.CatNames.World,
		setindex = "worlddrops",
		--color = {1,0.3,0},
		colour = "|cffB0C4DE",
		header = MendeleevLocals.Category.Found,
		sets = {
			worlddrops 	= MendeleevLocals.Category.WorldDrop,
		}
	},
	{
		name = MendeleevLocals.CatNames.RaidZ,
		setindex = "raidzones",
		--color = {1,0.3,0},
		colour = "|cffFFA500",
		header = MendeleevLocals.Category.Found,
		sets = {
			moltencore    	= MendeleevLocals.Instance.Raid.MC,
			blackwinglair 	= MendeleevLocals.Instance.Raid.BWL,
			onyxiaslair   	= MendeleevLocals.Instance.Raid.OL,
			zulgurub      	= MendeleevLocals.Instance.Raid.ZG,
		}
	},
	{
		name = MendeleevLocals.CatNames.RaidB,
		setindex = "raidbosses",
		--color = {1,0.6,0},
		colour = "|cffFFA500",
		header = MendeleevLocals.Category.Dropped,
		useval = function (v) return (v > 0 and string.format(" (%.2f%%)", v/100)) or "" end,
		sets = {
			nefarian               = MendeleevLocals.Boss.Raid.Nef,
			vaelastraszthecorrupt  = MendeleevLocals.Boss.Raid.Vael,
			razorgoretheuntamed    = MendeleevLocals.Boss.Raid.Razor,
			broodlordlashlayer     = MendeleevLocals.Boss.Raid.Broodlord,
			chromaggus             = MendeleevLocals.Boss.Raid.Chrom,
			ebonroc                = MendeleevLocals.Boss.Raid.Ebon,
			firemaw                = MendeleevLocals.Boss.Raid.Firemaw,
			flamegor               = MendeleevLocals.Boss.Raid.Flamegor,
			majordomoexecutus      = MendeleevLocals.Boss.Raid.Domo	,
			ragnaros               = MendeleevLocals.Boss.Raid.Rag,
			barongeddon            = MendeleevLocals.Boss.Raid.Geddon,
			golemaggtheincinerator = MendeleevLocals.Boss.Raid.Golemagg,
			garr                   = MendeleevLocals.Boss.Raid.Garr	,
			sulfuronharbinger      = MendeleevLocals.Boss.Raid.Sulfuron,
			shazzrah               = MendeleevLocals.Boss.Raid.Shazz,
			lucifron               = MendeleevLocals.Boss.Raid.Luci,
			gehennas               = MendeleevLocals.Boss.Raid.Gehe	,
			magmadar               = MendeleevLocals.Boss.Raid.Magmadar,
			onyxia                 = MendeleevLocals.Boss.Raid.Onyxia,
			azuregos               = MendeleevLocals.Boss.Raid.Azure,
			lordkazzak             = MendeleevLocals.Boss.Raid.Kazzak,
			ysondre                = MendeleevLocals.Boss.Raid.Yso,
			emeriss                = MendeleevLocals.Boss.Raid.Eme	,
			taerar                 = MendeleevLocals.Boss.Raid.Tae,
			lethon                 = MendeleevLocals.Boss.Raid.Lethon,
			highpriestessjeklik    = MendeleevLocals.Boss.Raid.Jek,
			highpriestvenoxis      = MendeleevLocals.Boss.Raid.Ven,
			highpriestthekal       = MendeleevLocals.Boss.Raid.Thek,
			highpriestessarlokk    = MendeleevLocals.Boss.Raid.Arl,
			highpriestessmarli     = MendeleevLocals.Boss.Raid.Mar,
			jindothehexxer         = MendeleevLocals.Boss.Raid.Jin	,
			bloodlordmandokir      = MendeleevLocals.Boss.Raid.Mando,
			gahzranka              = MendeleevLocals.Boss.Raid.Gahz,
			grilek                 = MendeleevLocals.Boss.Raid.Gri,
			hazzarah               = MendeleevLocals.Boss.Raid.Hazz	,
			renataki               = MendeleevLocals.Boss.Raid.Rena,
			wushoolay              = MendeleevLocals.Boss.Raid.Wush,
			hakkar                 = MendeleevLocals.Boss.Raid.Hakkar,
		}
	},
	{
		name = MendeleevLocals.CatNames.InstZ,
		setindex = "instancezones",
		--color = {1,0.3,0},
		colour = "|cffD02090",
		header = MendeleevLocals.Category.Found,
		sets = {
			diremauleast 		= MendeleevLocals.Instance.Reg.DiremaulEast,
			diremaulwest 		= MendeleevLocals.Instance.Reg.DiremaulWest,
			diremaulnorth 		= MendeleevLocals.Instance.Reg.DiremaulNorth,
			scholomance        	= MendeleevLocals.Instance.Reg.Scholo,
			stratholme         	= MendeleevLocals.Instance.Reg.Strat,
			blackrockspire     	= MendeleevLocals.Instance.Reg.BS,
			blackrockdepths    	= MendeleevLocals.Instance.Reg.BD,
			maraudon           	= MendeleevLocals.Instance.Reg.Mauradon,
			templeofatalhakkar 	= MendeleevLocals.Instance.Reg.ST,
			shadowfangkeep      = MendeleevLocals.Instance.Reg.SFK,
		}
	},
	{
		name = MendeleevLocals.CatNames.InstB,
		setindex = "instancebosses",
		--color = {1,0.6,0},
		colour = "|cffD02090",
		header = MendeleevLocals.Category.Dropped,
		useval = function (v) return (v > 0 and string.format(" (%.2f%%)", v/100)) or "" end,
		sets = {
			diremaultrash 			= MendeleevLocals.Misc.TrashMobs,
			diremaulwesttrash 		= MendeleevLocals.Misc.TrashMobs,
			diremauleasttrash 		= MendeleevLocals.Misc.TrashMobs,
			chorushtheobserver 		= MendeleevLocals.Boss.Reg.Chorush,
			lordhelnurath 			= MendeleevLocals.Boss.Reg.Helnurath,
			pimgib 				= MendeleevLocals.Boss.Reg.Pimgib,
			knotthimblejackscache 	= MendeleevLocals.Boss.Reg.Knotthimble,
			alzzinthewildshaper 	= MendeleevLocals.Boss.Reg.Alzzin,
			ambassadorflamelash 	= MendeleevLocals.Boss.Reg.Flamelash,
			angerrel 				= MendeleevLocals.Boss.Reg.Anger	,
			archivistgalford 		= MendeleevLocals.Boss.Reg.Galford,
			atalalarion 			= MendeleevLocals.Boss.Reg.Alarion,
			avatarofhakkar 		= MendeleevLocals.Boss.Reg.AvatarHakkar,
			baelgar 				= MendeleevLocals.Boss.Reg.Baelgar,
			balnazzar 			= MendeleevLocals.Boss.Reg.Balnazzar,
			baronessanastari 		= MendeleevLocals.Boss.Reg.Anastari,
			baronrivendare 		= MendeleevLocals.Boss.Reg.Rivendare,
			cannonmasterwilley 		= MendeleevLocals.Boss.Reg.Willy,
			captainkromcrush 		= MendeleevLocals.Boss.Reg.Kromcrush,
			celebrasthecursed 		= MendeleevLocals.Boss.Reg.Celebras,
			crystalfang 			= MendeleevLocals.Boss.Reg.CFang,
			darkmastergandling 		= MendeleevLocals.Boss.Reg.Gandling,
			doctortheolenkrastinov 	= MendeleevLocals.Boss.Reg.TKrastinov,
			doomrel 				= MendeleevLocals.Boss.Reg.Doom,
			doperel 				= MendeleevLocals.Boss.Reg.Dope,
			dreamscythe 			= MendeleevLocals.Boss.Reg.Dreamscythe,
			emperordagranthaurissian = MendeleevLocals.Boss.Reg.Thaurissian,
			fineousdarkvire 		= MendeleevLocals.Boss.Reg.Darkvire,
			gasher 				= MendeleevLocals.Boss.Reg.Gasher,
			generalangerforge 		= MendeleevLocals.Boss.Reg.Angerforge,
			generaldrakkisath 		= MendeleevLocals.Boss.Reg.Drakkisath,
			gloomrel 				= MendeleevLocals.Boss.Reg.Gloom,
			golemlordargelmach 		= MendeleevLocals.Boss.Reg.Argelmach,
			goralukanvilcrack 		= MendeleevLocals.Boss.Reg.Anvilcrack,
			guardfengus 			= MendeleevLocals.Boss.Reg.Fengus,
			guardmoldar 			= MendeleevLocals.Boss.Reg.Moldar,
			guardslipkik 			= MendeleevLocals.Boss.Reg.Slipkik,
			gyth 				= MendeleevLocals.Boss.Reg.Gyth,
			halycon 				= MendeleevLocals.Boss.Reg.Halycon,
			haterel 				= MendeleevLocals.Boss.Reg.Hate,
			hazzas 				= MendeleevLocals.Boss.Reg.Hazzas,
			hearthsingerforresten 	= MendeleevLocals.Boss.Reg.Forresten,
			highinterrogatorgerstahn = MendeleevLocals.Boss.Reg.Gerstahn,
			highlordomokk 			= MendeleevLocals.Boss.Reg.Omokk,
			hukku 				= MendeleevLocals.Boss.Reg.Hukku,
			hurleyblackbreath 		= MendeleevLocals.Boss.Reg.Blackbreath,
			hydrospawn 			= MendeleevLocals.Boss.Reg.Hydrospawn,
			illyannaravenoak 		= MendeleevLocals.Boss.Reg.Illyanna,
			immolthar 			= MendeleevLocals.Boss.Reg.Immolthar,
			instructormalicia 		= MendeleevLocals.Boss.Reg.Malicia,
			jammalantheprophet 		= MendeleevLocals.Boss.Reg.Jammal,
			jandicebarov 			= MendeleevLocals.Boss.Reg.Jandice,
			kinggordok 			= MendeleevLocals.Boss.Reg.Gordok,
			kirtonostheherald 		= MendeleevLocals.Boss.Reg.Kirtonos,
			ladyilluciabarov 		= MendeleevLocals.Boss.Reg.Illucia,
			landslide 			= MendeleevLocals.Boss.Reg.Landslide,
			lethtendris 			= MendeleevLocals.Boss.Reg.Lethendris,
			lordalexeibarov 		= MendeleevLocals.Boss.Reg.Alexei,
			lordincendius 			= MendeleevLocals.Boss.Reg.Incendius,
			lordvyletongue 		= MendeleevLocals.Boss.Reg.Vyletongue,
			lorekeeperpolkelt 		= MendeleevLocals.Boss.Reg.Polkelt,
			loro 				= MendeleevLocals.Boss.Reg.Loro,
			magisterkalendris 		= MendeleevLocals.Boss.Reg.Kalendris,
			magistratebarthilas 	= MendeleevLocals.Boss.Reg.Barthilas,
			magmus 				= MendeleevLocals.Boss.Reg.Magmus,
			malekithepallid 		= MendeleevLocals.Boss.Reg.Maleki,
			mardukblackpool		= MendeleevLocals.Boss.Reg.Marduk,
			meshloktheharvester 	= MendeleevLocals.Boss.Reg.Meshlok,
			mijan 				= MendeleevLocals.Boss.Reg.Mijan,
			morphaz 				= MendeleevLocals.Boss.Reg.Morphaz,
			mothersmolderweb 		= MendeleevLocals.Boss.Reg.Smolderweb,
			nerubenkan 			= MendeleevLocals.Boss.Reg.Nerub,
			noxxion 				= MendeleevLocals.Boss.Reg.Noxx,
			ogomthewretched 		= MendeleevLocals.Boss.Reg.Ogom,
			overlordwyrmthalak 		= MendeleevLocals.Boss.Reg.Wyrmthalak,
			phalanx 				= MendeleevLocals.Boss.Reg.Phalanx,
			pluggerspazzring 		= MendeleevLocals.Boss.Reg.Spazzring,
			postmastermalown 		= MendeleevLocals.Boss.Reg.Malown,
			princessmoirabronzebeard = MendeleevLocals.Boss.Reg.Moira,
			princesstheradras		= MendeleevLocals.Boss.Reg.Theradras,
			princetortheldrin 		= MendeleevLocals.Boss.Reg.Tortheldrin,
			pusillin 				= MendeleevLocals.Boss.Reg.Pusillin,
			pyroguardemberseer 		= MendeleevLocals.Boss.Reg.Emberseer,
			ramsteinthegorger 		= MendeleevLocals.Boss.Reg.Ramstein,
			rasfrostwhisper 		= MendeleevLocals.Boss.Reg.Frostwhisper,
			rattlegore 			= MendeleevLocals.Boss.Reg.Rattlegore,
			razorlash 			= MendeleevLocals.Boss.Reg.Razorlash,
			rendblackhand 			= MendeleevLocals.Boss.Reg.Rend,
			ribblyscrewspigot 		= MendeleevLocals.Boss.Reg.Screwspigot,
			rotgrip 				= MendeleevLocals.Boss.Reg.Rotgrip,
			seethrel 				= MendeleevLocals.Boss.Reg.Seeth,
			shadeoferanikus 		= MendeleevLocals.Boss.Reg.Eranikus,
			shadowhuntervoshgajin 	= MendeleevLocals.Boss.Reg.VoshGajin,
			solakarflamewreath 		= MendeleevLocals.Boss.Reg.Flamewreath,
			stomperkreeg 			= MendeleevLocals.Boss.Reg.Kreeg,
			tendriswarpwood 		= MendeleevLocals.Boss.Reg.Warpwood,
			thebeast 				= MendeleevLocals.Boss.Reg.TheBeast,
			theravenian 			= MendeleevLocals.Boss.Reg.Ravenian,
			timmythecruel 			= MendeleevLocals.Boss.Reg.Timmy,
			tinkerergizlock 		= MendeleevLocals.Boss.Reg.Gizlock,
			tsuzee 				= MendeleevLocals.Boss.Reg.Tsu,
			vectus 				= MendeleevLocals.Boss.Reg.Vectus,
			vilerel 				= MendeleevLocals.Boss.Reg.Vile,
			warmastervoone 		= MendeleevLocals.Boss.Reg.Voone,
			weaver 				= MendeleevLocals.Boss.Reg.Weaver,
			zevrimthornhoof 		= MendeleevLocals.Boss.Reg.Thornhoof,
			zolo 				= MendeleevLocals.Boss.Reg.Zolo,
			zullor 				= MendeleevLocals.Boss.Reg.Zullo,
			shadowfangkeeptrash 	= MendeleevLocals.Misc.TrashMobs,
	        	archmagearugal      	= MendeleevLocals.Boss.Reg.Arugal,
	        	razorclawthebutcher 	= MendeleevLocals.Boss.Reg.Razorclaw,
	        	commanderspringvale 	= MendeleevLocals.Boss.Reg.Springvale,
	        	wolfmasternandos    	= MendeleevLocals.Boss.Reg.Nandos,
	        	odotheblindwatcher  	= MendeleevLocals.Boss.Reg.Odo,
	        	deathsworncaptain   	= MendeleevLocals.Boss.Reg.DeathswornCapt,
	        	baronsilverlaine    	= MendeleevLocals.Boss.Reg.Silverlaine,
            	fenrusthedevourer   	= MendeleevLocals.Boss.Reg.Fenrus,
            	arugalsvoidwalker   	= MendeleevLocals.Boss.Reg.ArugalsVW,
		}
	},
}

MendeleevLocals.custominfosets = {"stacksize","itemid","crafting"}