-- English localization strings for ZoneLevel

AcMt = "Alterac Mountains";
ABsn = "Arathi Basin";
AHld = "Arathi Highlands";
AnQj = "Ahn-Quiraj"
AnQG = "Gates of Ahn'Qiraj"
AnQR = "Ruins of Ahn'Qiraj"
AnQT = "Temple of Ahn'Qiraj"
Ashv = "Ashenvale";
Azsr = "Azshara";
AVal = "Alterac Valley";
Bdld = "Badlands";
BgSt = "Burning Steppes";
BlfD = "Blackfathom Deeps";
BlLd = "Blasted Lands";
BlMt = "Blackrock Mountain";
BlrD = "Blackrock Depths";
BlrS = "Blackrock Spire";
Brns = "The Barrens";
BlwL = "Blackwing Lair";
BtyB = "Booty Bay";
CvTm = "Caverns of Time";
Darn = "Darnassus";
Ddmn = "The Deadmines";
Dksr = "Darkshore";
Dkwd = "Duskwood";
DrMl = "Dire Maul";
Drtr = "Durotar";
Dslc = "Desolace";
DtwM = "Dustwallow Marsh";
DunM = "Dun Morogh";
DwPs = "Deadwind Pass";
EPlg = "Eastern Plaguelands";
EwnF = "Elwynn Forest";
Flwd = "Felwood";
Frls = "Feralas";
Goro = "Un'Goro Crater";
Grgn = "Gnomeregan";
Gtzn = "Gadgetzan";
HdFt = "Hillsbrad Foothills";
Htld = "The Hinterlands";
Hyal = "Hyjal";
Irfg = "Ironforge";
KNdl = "Thousand Needles";
LMod = "Loch Modan";
MCor = "Molten Core";
Mlgr = "Mulgore";
Mngd = "Moonglade";
Mrdn = "Maraudon";
Naxx = "Naxxramas";
Onyx = "Onyxia's Lair";
Orgr = "Orgrimmar";
Outl = "Outland"
Rcht = "Ratchet";
RfCm = "Ragefire Chasm";
RfDn = "Razorfen Downs";
RfKr = "Razorfen Kraul";
RrMt = "Redridge Mountains";
SfKp = "Shadowfang Keep";
SgGg = "Searing Gorge";
Slmc = "Scholomance";
Slts = "Silithus";
SoSs = "Swamp of Sorrows";
Stck = "The Stockade";
Sthm = "Stratholme";
StMn = "Scarlet Monastery";
StMt = "Stonetalon Mountains";
StrV = "Stranglethorn Vale";
StwC = "Stormwind City";
SvpF = "Silverpine Forest";
TdrB = "Thunder Bluff";
Tfal = "Tirisfal Glades";
Tldr = "Teldrassil";
Tmpl = "The Temple of Atal'Hakkar";
Tnrs = "Tanaris";
Tram = "Deeprun Tram";
Ucty = "Undercity";
Uldm = "Uldaman";
WCvn = "Wailing Caverns";
WGch = "Warsong Gulch";
WPlg = "Western Plaguelands";
Wtfl = "Westfall";
Wtld = "Wetlands";
Wtsg = "Winterspring";
ZlFk = "Zul'Farrak";
ZlGb = "Zul'Gurub";

ZONELEVEL_DESC = "Adds a graphical indicator of mob levels in a zone as related to your level.";
ZONELEVEL_ZONENOTFOUND = "Zone levels for \"%s\" unknown. Please let me know what's in the quotes so we can get this fixed. Thanks!";
ZONELEVEL_ZONENOTFOUNDTOOLTIP = "Zone info unavailable";
ZONELEVEL_CITYTEXT = "Level range: N/A";
ZONELEVEL_ZONETEXT = "Level range: %d - %d";
ZONELEVEL_HELP_HEADER = "--ZoneLevel Help--\n";
ZONELEVEL_MINIMAP_SHORT = "Show in minimap";
ZONELEVEL_HELP_MINIMAP = "Toggle levels in minimap name";
ZONELEVEL_HELP_MAPCMD = ": /zonelevel maptext\n";
ZONELEVEL_HELP_ICON = "Toggle icon";
ZONELEVEL_HELP_ICOCMD = ": /zonelevel icon\n";
ZONELEVEL_HELP_CMD = "Alternative slash command: /zlvl";
ZONELEVEL_BADOPT = "Unknown option for Zonelevel. Type /zlvl to get help.";
ZONELEVEL_NOZONE = "ZoneLevel: You are not in a zone. I am impressed.";
ZONELEVEL_TEXT = "Minimap Text"
ZONELEVEL_ICON = "Icon"
