AtlasLootSetItems = {
    T3Mage = {
        { 0,"Spell_Frost_IceStorm","=q6=#t3s3#", ""},
        { 22498, "INV_Crown_01", "=q4=Frostfire Circlet", "=ds="..AtlasLootBossNames["Naxxramas"][4] },
        { 22499, "INV_Shoulder_25", "=q4=Frostfire Shoulderpads", "=ds="..AtlasLootBossNames["Naxxramas"][1]..", "..AtlasLootBossNames["Naxxramas"][2] },
        { 22496, "INV_Chest_Cloth_43", "=q4=Frostfire Robe", "=ds="..AtlasLootBossNames["Naxxramas"][10] },
        { 22503, "INV_Bracer_13", "=q4=Frostfire Bindings", "=ds="..AtlasLootBossNames["Naxxramas"][5]..", "..AtlasLootBossNames["Naxxramas"][6] },
        { 22501, "INV_Gauntlets_17", "=q4=Frostfire Gloves", "=ds="..AtlasLootBossNames["Naxxramas"][7] },
        { 22502, "INV_Belt_03", "=q4=Frostfire Belt", "=ds="..AtlasLootBossNames["Naxxramas"][11]..", "..AtlasLootBossNames["Naxxramas"][12] },
        { 22497, "INV_Pants_Cloth_05", "=q4=Frostfire Leggings", "=ds="..AtlasLootBossNames["Naxxramas"][13] },
        { 22500, "INV_Boots_Fabric_01", "=q4=Frostfire Sandals", "=ds="..AtlasLootBossNames["Naxxramas"][3]..", "..AtlasLootBossNames["Naxxramas"][8]..", "..AtlasLootBossNames["Naxxramas"][9]  },
        { 0, "INV_Misc_QuestionMark", "=q4=Frostfire Ring", "=ds="..AtlasLootBossNames["Naxxramas"][15] },
        };
    T3Warlock = {
        { 0,"Spell_Shadow_CurseOfTounges","=q6=#t3s8#","" },
        { 22506, "INV_Crown_01", "=q4=Plagueheart Circlet", "=ds="..AtlasLootBossNames["Naxxramas"][4] },
        { 22507, "INV_Shoulder_25", "=q4=Plagueheart Shoulderpads", "=ds="..AtlasLootBossNames["Naxxramas"][1]..", "..AtlasLootBossNames["Naxxramas"][2]},
        { 22504, "INV_Chest_Cloth_43", "=q4=Plagueheart Robe", "=ds="..AtlasLootBossNames["Naxxramas"][10] },
        { 22511, "INV_Bracer_13", "=q4=Plagueheart Bindings", "=ds="..AtlasLootBossNames["Naxxramas"][5]..", "..AtlasLootBossNames["Naxxramas"][6] },
        { 22509, "INV_Gauntlets_17", "=q4=Plagueheart Gloves", "=ds="..AtlasLootBossNames["Naxxramas"][7] },
        { 22510, "INV_Belt_03", "=q4=Plagueheart Belt", "=ds="..AtlasLootBossNames["Naxxramas"][11]..", "..AtlasLootBossNames["Naxxramas"][12] },
        { 22505, "INV_Pants_Cloth_05", "=q4=Plagueheart Leggings", "=ds="..AtlasLootBossNames["Naxxramas"][13] },
        { 22508, "INV_Boots_Fabric_01", "=q4=Plagueheart Sandals", "=ds="..AtlasLootBossNames["Naxxramas"][3]..", "..AtlasLootBossNames["Naxxramas"][8]..", "..AtlasLootBossNames["Naxxramas"][9] },
        { 0, "INV_Misc_QuestionMark", "=q4=Plagueheart Ring", "=ds="..AtlasLootBossNames["Naxxramas"][15] },
        };
    T3Priest = {
        { 0,"Spell_Holy_PowerWordShield","=q6=#t3s5#","" },
        { 22514, "INV_Crown_01", "=q4=Circlet of Faith", "=ds="..AtlasLootBossNames["Naxxramas"][4] },
        { 22515, "INV_Shoulder_25", "=q4=Shoulderpads of Faith", "=ds="..AtlasLootBossNames["Naxxramas"][1]..", "..AtlasLootBossNames["Naxxramas"][2] },
        { 22512, "INV_Chest_Cloth_43", "=q4=Robe of Faith", "=ds="..AtlasLootBossNames["Naxxramas"][10] },
        { 22519, "INV_Bracer_13", "=q4=Bindings of Faith", "=ds="..AtlasLootBossNames["Naxxramas"][5]..", "..AtlasLootBossNames["Naxxramas"][6] },
        { 22517, "INV_Gauntlets_17", "=q4=Gloves of Faith", "=ds="..AtlasLootBossNames["Naxxramas"][7] },
        { 22518, "INV_Belt_08", "=q4=Belt of Faith", "=ds="..AtlasLootBossNames["Naxxramas"][11]..", "..AtlasLootBossNames["Naxxramas"][12] },
        { 22513, "INV_Pants_Cloth_05", "=q4=Leggings of Faith", "=ds="..AtlasLootBossNames["Naxxramas"][13] },
        { 22516, "INV_Boots_Fabric_01", "=q4=Sandals of Faith", "=ds="..AtlasLootBossNames["Naxxramas"][3]..", "..AtlasLootBossNames["Naxxramas"][8]..", "..AtlasLootBossNames["Naxxramas"][9] },
        { 0, "INV_Misc_QuestionMark", "=q4=Ring of Faith", "=ds="..AtlasLootBossNames["Naxxramas"][15] },
        };
    T3Rogue = {
        { 0,"Ability_BackStab","=q6=#t3s6#","" },
        { 22478, "INV_Helmet_58", "=q4=Bonescythe Helmet", "=ds="..AtlasLootBossNames["Naxxramas"][4] },
        { 22479, "INV_Shoulder_29", "=q4=Bonescythe Pauldrons", "=ds="..AtlasLootBossNames["Naxxramas"][1]..", "..AtlasLootBossNames["Naxxramas"][2] },
        { 22476, "INV_Chest_Plate02", "=q4=Bonescythe Breastplate", "=ds="..AtlasLootBossNames["Naxxramas"][10] },
        { 22483, "INV_Bracer_15", "=q4=Bonescythe Bracers", "=ds="..AtlasLootBossNames["Naxxramas"][5]..", "..AtlasLootBossNames["Naxxramas"][6] },
        { 22481, "INV_Gauntlets_28", "=q4=Bonescythe Gauntlets", "=ds="..AtlasLootBossNames["Naxxramas"][7] },
        { 22482, "INV_Belt_27", "=q4=Bonescythe Waistguard", "=ds="..AtlasLootBossNames["Naxxramas"][11]..", "..AtlasLootBossNames["Naxxramas"][12] },
        { 22477, "INV_Pants_Plate_05", "=q4=Bonescythe Legplates", "=ds="..AtlasLootBossNames["Naxxramas"][13] },
        { 22480, "INV_Boots_Plate_06", "=q4=Bonescythe Sabatons", "=ds="..AtlasLootBossNames["Naxxramas"][3]..", "..AtlasLootBossNames["Naxxramas"][8]..", "..AtlasLootBossNames["Naxxramas"][9] },
        { 0, "INV_Misc_QuestionMark", "=q4=Bonescythe Ring", "=ds="..AtlasLootBossNames["Naxxramas"][15] },
        };
    T3Druid = {
        { 0,"Spell_Nature_Regeneration","=q6=#t3s1#","" },
        { 22490, "INV_Helmet_15", "=q4=Dreamwalker Headpiece", "=ds="..AtlasLootBossNames["Naxxramas"][4] },
        { 22491, "INV_Shoulder_14", "=q4=Dreamwalker Spaulders", "=ds="..AtlasLootBossNames["Naxxramas"][1]..", "..AtlasLootBossNames["Naxxramas"][2] },
        { 22488, "INV_Chest_Chain_15", "=q4=Dreamwalker Tunic", "=ds="..AtlasLootBossNames["Naxxramas"][10] },
        { 22495, "INV_Bracer_02", "=q4=Dreamwalker Wristguards", "=ds="..AtlasLootBossNames["Naxxramas"][5]..", "..AtlasLootBossNames["Naxxramas"][6] },
        { 22493, "INV_Gauntlets_25", "=q4=Dreamwalker Handguards", "=ds="..AtlasLootBossNames["Naxxramas"][7] },
        { 22494, "INV_Belt_22", "=q4=Dreamwalker Girdle", "=ds="..AtlasLootBossNames["Naxxramas"][11]..", "..AtlasLootBossNames["Naxxramas"][12] },
        { 22489, "INV_Pants_Mail_15", "=q4=Dreamwalker Legguards", "=ds="..AtlasLootBossNames["Naxxramas"][13] },
        { 22492, "INV_Boots_Chain_05", "=q4=Dreamwalker Boots", "=ds="..AtlasLootBossNames["Naxxramas"][3]..", "..AtlasLootBossNames["Naxxramas"][8]..", "..AtlasLootBossNames["Naxxramas"][9] },
        { 0, "INV_Misc_QuestionMark", "=q4=Ring of the Dreamwalker", "=ds="..AtlasLootBossNames["Naxxramas"][15] },
        };
    T3Hunter = {
        { 0,"Ability_Hunter_RunningShot","=q6=#t3s2#","" },
        { 22438, "INV_Helmet_15", "=q4=Cryptstalker Headpiece", "=ds="..AtlasLootBossNames["Naxxramas"][4] },
        { 22439, "INV_Shoulder_14", "=q4=Cryptstalker Spaulders", "=ds="..AtlasLootBossNames["Naxxramas"][1]..", "..AtlasLootBossNames["Naxxramas"][2] },
        { 22436, "INV_Chest_Chain_15", "=q4=Cryptstalker Tunic", "=ds="..AtlasLootBossNames["Naxxramas"][10] },
        { 22443, "INV_Bracer_02", "=q4=Cryptstalker Wristguards", "=ds="..AtlasLootBossNames["Naxxramas"][5]..", "..AtlasLootBossNames["Naxxramas"][6] },
        { 22441, "INV_Gauntlets_25", "=q4=Cryptstalker Handguards", "=ds="..AtlasLootBossNames["Naxxramas"][7] },
        { 22442, "INV_Belt_22", "=q4=Cryptstalker Girdle", "=ds="..AtlasLootBossNames["Naxxramas"][11]..", "..AtlasLootBossNames["Naxxramas"][12] },
        { 22437, "INV_Pants_Mail_15", "=q4=Cryptstalker Legguards", "=ds="..AtlasLootBossNames["Naxxramas"][13] },
        { 22440, "INV_Boots_Chain_05", "=q4=Cryptstalker Boots", "=ds="..AtlasLootBossNames["Naxxramas"][3]..", "..AtlasLootBossNames["Naxxramas"][8]..", "..AtlasLootBossNames["Naxxramas"][9] },
        { 0, "INV_Misc_QuestionMark", "=q4=Ring of the Cryptstalker", "=ds="..AtlasLootBossNames["Naxxramas"][15] },
        };
    T3Paladin = {
        { 0,"Spell_Holy_SealOfMight","=q6=#t3s4#","" },
        { 22428, "INV_Helmet_15", "=q4=Redemption Headpiece", "=ds="..AtlasLootBossNames["Naxxramas"][4] },
        { 22429, "INV_Shoulder_14", "=q4=Redemption Spaulders", "=ds="..AtlasLootBossNames["Naxxramas"][1]..", "..AtlasLootBossNames["Naxxramas"][2] },
        { 22425, "INV_Chest_Chain_15", "=q4=Redemption Tunic", "=ds="..AtlasLootBossNames["Naxxramas"][10] },
        { 22424, "INV_Bracer_02", "=q4=Redemption Wristguards", "=ds="..AtlasLootBossNames["Naxxramas"][5]..", "..AtlasLootBossNames["Naxxramas"][6] },
        { 22426, "INV_Gauntlets_25", "=q4=Redemption Handguards", "=ds="..AtlasLootBossNames["Naxxramas"][7] },
        { 22431, "INV_Belt_22", "=q4=Redemption Girdle", "=ds="..AtlasLootBossNames["Naxxramas"][11]..", "..AtlasLootBossNames["Naxxramas"][12] },
        { 22427, "INV_Pants_Mail_15", "=q4=Redemption Legguards", "=ds="..AtlasLootBossNames["Naxxramas"][13] },
        { 22430, "INV_Boots_Chain_05", "=q4=Redemption Boots", "=ds="..AtlasLootBossNames["Naxxramas"][3]..", "..AtlasLootBossNames["Naxxramas"][8]..", "..AtlasLootBossNames["Naxxramas"][9] },
        { 0, "INV_Misc_QuestionMark", "=q4=Ring of Redemption", "=ds="..AtlasLootBossNames["Naxxramas"][15] },
        };
    T3Shaman = {
        { 0,"Spell_FireResistanceTotem_01","=q6=#t3s7#","" },
        { 22466, "INV_Helmet_15", "=q4=Earthshatter Headpiece", "=ds="..AtlasLootBossNames["Naxxramas"][4] },
        { 22467, "INV_Shoulder_14", "=q4=Earthshatter Spaulders", "=ds="..AtlasLootBossNames["Naxxramas"][1]..", "..AtlasLootBossNames["Naxxramas"][2] },
        { 22464, "INV_Chest_Chain_15", "=q4=Earthshatter Tunic", "=ds="..AtlasLootBossNames["Naxxramas"][10] },
        { 22471, "INV_Bracer_02", "=q4=Earthshatter Wristguards", "=ds="..AtlasLootBossNames["Naxxramas"][5]..", "..AtlasLootBossNames["Naxxramas"][6] },
        { 22469, "INV_Gauntlets_25", "=q4=Earthshatter Handguards", "=ds="..AtlasLootBossNames["Naxxramas"][7] },
        { 22470, "INV_Belt_22", "=q4=Earthshatter Girdle", "=ds="..AtlasLootBossNames["Naxxramas"][11]..", "..AtlasLootBossNames["Naxxramas"][12] },
        { 22465, "INV_Pants_Mail_15", "=q4=Earthshatter Legguards", "=ds="..AtlasLootBossNames["Naxxramas"][13] },
        { 22468, "INV_Boots_Chain_05", "=q4=Earthshatter Boots", "=ds="..AtlasLootBossNames["Naxxramas"][3]..", "..AtlasLootBossNames["Naxxramas"][8]..", "..AtlasLootBossNames["Naxxramas"][9] },
        { 0, "INV_Misc_QuestionMark", "=q4=Ring of the Earthshatterer", "=ds="..AtlasLootBossNames["Naxxramas"][15] },
        };
    T3Warrior = {
        { 0,"INV_Shield_05","=q6=#t3s9#","" },
        { 22418, "INV_Helmet_58", "=q4=Dreadnaught Helmet", "=ds="..AtlasLootBossNames["Naxxramas"][4] },
        { 22419, "INV_Shoulder_29", "=q4=Dreadnaught Pauldrons", "=ds="..AtlasLootBossNames["Naxxramas"][1]..", "..AtlasLootBossNames["Naxxramas"][2] },
        { 22416, "INV_Chest_Plate02", "=q4=Dreadnaught Breastplate", "=ds="..AtlasLootBossNames["Naxxramas"][10] },
        { 22423, "INV_Bracer_15", "=q4=Dreadnaught Bracers", "=ds="..AtlasLootBossNames["Naxxramas"][5]..", "..AtlasLootBossNames["Naxxramas"][6] },
        { 22421, "INV_Gauntlets_28", "=q4=Dreadnaught Gauntlets", "=ds="..AtlasLootBossNames["Naxxramas"][7] },
        { 22422, "INV_Belt_27", "=q4=Dreadnaught Waistguard", "=ds="..AtlasLootBossNames["Naxxramas"][11]..", "..AtlasLootBossNames["Naxxramas"][12] },
        { 22417, "INV_Pants_Plate_05", "=q4=Dreadnaught Legplates", "=ds="..AtlasLootBossNames["Naxxramas"][13] },
        { 22420, "INV_Boots_Plate_06", "=q4=Dreadnaught Sabatons", "=ds="..AtlasLootBossNames["Naxxramas"][3]..", "..AtlasLootBossNames["Naxxramas"][8]..", "..AtlasLootBossNames["Naxxramas"][9] },
        { 0, "INV_Misc_QuestionMark", "=q4=Ring of the Dreadnaught", "=ds="..AtlasLootBossNames["Naxxramas"][15] },
        };
        
    T2Mage = {
        { 0,"Spell_Frost_IceStorm","=q6=#t2s3#","" },
        { 16914, "INV_Helmet_70", "=q4=Netherwind Crown", "=ds="..AtlasLootBossNames["OnyxiasLair"][1] , "14.09%" },
        { 16917, "INV_Shoulder_32", "=q4=Netherwind Mantle", "=ds="..AtlasLootBossNames["BlackwingLair"][7],     "18.09%" },
        { 16916, "INV_Chest_Cloth_03", "=q4=Netherwind Robes", "=ds="..AtlasLootBossNames["BlackwingLair"][8],     "14.03%" },
        { 16918, "INV_Bracer_09", "=q4=Netherwind Bindings", "=ds="..AtlasLootBossNames["BlackwingLair"][1],         "20.41%" },
        { 16913, "INV_Gauntlets_14", "=q4=Netherwind Gloves", "=ds="..AtlasLootBossNames["BlackwingLair"][4]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][5]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][6],     "7.37%" },
        { 16818, "INV_Belt_22", "=q4=Netherwind Belt", "=ds="..AtlasLootBossNames["BlackwingLair"][2],     "19.94%" },
        { 16915, "INV_Pants_08", "=q4=Netherwind Pants", "=ds="..AtlasLootBossNames["MoltenCore"][10], "17.37%" },
        { 16912, "INV_Boots_07", "=q4=Netherwind Boots", "=ds="..AtlasLootBossNames["BlackwingLair"][3],       "17.17%" },
        };

    T2Priest = {
        { 0,"Spell_Holy_PowerWordShield","=q6=#t2s5#","" },
        { 16921, "INV_Helmet_24", "=q4=Halo of Transcendence",  "=ds="..AtlasLootBossNames["OnyxiasLair"][1], " 13.39%" },
        { 16924, "INV_Shoulder_02", "=q4=Pauldrons of Transcendence", "=ds="..AtlasLootBossNames["BlackwingLair"][7],   "17.83%" },
        { 16923, "INV_Chest_Cloth_03", "=q4=Robes of Transcendence", "=ds="..AtlasLootBossNames["BlackwingLair"][8],   "14.83%" },
        { 16926, "INV_Bracer_09", "=q4=Bindings of Transcendence", "=ds="..AtlasLootBossNames["BlackwingLair"][1],       "20.37%" },
        { 16920, "INV_Gauntlets_14", "=q4=Handguards of Transcendence", "=ds="..AtlasLootBossNames["BlackwingLair"][4]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][5]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][6],   "6.01%" },
        { 16925, "INV_Belt_22", "=q4=Belt of Transcendence", "=ds="..AtlasLootBossNames["BlackwingLair"][2],   "18.76%" },
        { 16922, "INV_Pants_08", "=q4=Leggings of Transcendence", "=ds="..AtlasLootBossNames["MoltenCore"][10], "17.30%" },
        { 16919, "INV_Boots_07", "=q4=Boots of Transcendence", "=ds="..AtlasLootBossNames["BlackwingLair"][3],     "14.61%" },
        };

    T2Warlock = {
        { 0,"Spell_Shadow_CurseOfTounges","=q6=#t2s8#","" },
        { 16929, "INV_Helmet_08", "=q4=Nemesis Skullcap","=ds="..AtlasLootBossNames["OnyxiasLair"][1], " 13.54%" },
        { 16932, "INV_Shoulder_19", "=q4=Nemesis Spaulders", "=ds="..AtlasLootBossNames["BlackwingLair"][7],  "16.26%" },
        { 16931, "INV_Chest_Leather_01", "=q4=Nemesis Robes", "=ds="..AtlasLootBossNames["BlackwingLair"][8],  "12.46%" },
        { 16934, "INV_Bracer_07", "=q4=Nemesis Bracers", "=ds="..AtlasLootBossNames["BlackwingLair"][1],      "18.11%" },
        { 16928, "INV_Gauntlets_19", "=q4=Nemesis Gloves", "=ds="..AtlasLootBossNames["BlackwingLair"][4]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][5]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][6],  "5.28%" },
        { 16933, "INV_Belt_13", "=q4=Nemesis Belt", "=ds="..AtlasLootBossNames["BlackwingLair"][2],  "18.42%" },
        { 16930, "INV_Pants_07", "=q4=Nemesis Leggings", "=ds="..AtlasLootBossNames["MoltenCore"][10], "16.87%" },
        { 16927, "INV_Boots_05", "=q4=Nemesis Boots", "=ds="..AtlasLootBossNames["BlackwingLair"][3],    "15.32%" },
        };

    T2Rogue = {
        { 0,"Ability_BackStab","=q6=#t2s6#","" },
        { 16908, "INV_Helmet_41", "=q4=Bloodfang Hood", "=ds="..AtlasLootBossNames["OnyxiasLair"][1], " 13.21%" },
        { 16832, "INV_Shoulder_23", "=q4=Bloodfang Spaulders", "=ds="..AtlasLootBossNames["BlackwingLair"][7],    "17.03%" },
        { 16905, "INV_Chest_Cloth_07", "=q4=Bloodfang Chestpiece", "=ds="..AtlasLootBossNames["BlackwingLair"][8],    "14.21%" },
        { 16911, "INV_Bracer_02", "=q4=Bloodfang Bracers", "=ds="..AtlasLootBossNames["BlackwingLair"][1],        "20.69%" },
        { 16907, "INV_Gauntlets_21", "=q4=Bloodfang Gloves", "=ds="..AtlasLootBossNames["BlackwingLair"][4]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][5]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][6],    "6.84%" },
        { 16910, "INV_Belt_23", "=q4=Bloodfang Belt", "=ds="..AtlasLootBossNames["BlackwingLair"][2],    "19.69%" },
        { 16909, "INV_Pants_06", "=q4=Bloodfang Pants", "=ds="..AtlasLootBossNames["MoltenCore"][10], "17.18%" },
        { 16906, "INV_Boots_08", "=q4=Bloodfang Boots", "=ds="..AtlasLootBossNames["BlackwingLair"][3],      "15.66%" },
        };

    T2Druid = {
	    { 0,"Spell_Nature_Regeneration","=q6=#t2s1#","" },
        { 16900, "INV_Helmet_09", "=q4=Stormrage Cover", "=ds="..AtlasLootBossNames["OnyxiasLair"][1], " 13.08%" },
	    { 16902, "INV_Shoulder_07", "=q4=Stormrage Pauldrons", "=ds="..AtlasLootBossNames["BlackwingLair"][7],    "14.63%" },
	    { 16897, "INV_Chest_Chain_16", "=q4=Stormrage Chestguard", "=ds="..AtlasLootBossNames["BlackwingLair"][8],    "11.89%" },
	    { 16904, "INV_Bracer_03", "=q4=Stormrage Bracers", "=ds="..AtlasLootBossNames["BlackwingLair"][1],        "17.38%" },
        { 16899, "INV_Gauntlets_25", "=q4=Stormrage Handguards", "=ds="..AtlasLootBossNames["BlackwingLair"][4]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][5]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][6],    "5.34%" },
	    { 16903, "INV_Belt_06", "=q4=Stormrage Belt", "=ds="..AtlasLootBossNames["BlackwingLair"][2],    "16.90%" },
        { 16901, "INV_Pants_06", "=q4=Stormrage Legguards", "=ds="..AtlasLootBossNames["MoltenCore"][10], "15.49%" },
	    { 16898, "INV_Boots_08", "=q4=Stormrage Boots", "=ds="..AtlasLootBossNames["BlackwingLair"][3],      "13.79%" },
	};

    T2Shaman = {
        { 0,"Spell_FireResistanceTotem_01","=q6=#t2s7#","" },
        { 16947, "INV_Helmet_69", "=q4=Helmet of Ten Storms", "=ds="..AtlasLootBossNames["OnyxiasLair"][1], "  4.86%" },
        { 16945, "INV_Shoulder_33", "=q4=Epaulets of Ten Storms", "=ds="..AtlasLootBossNames["BlackwingLair"][7],   " 6.73%" },
        { 16950, "INV_Chest_Chain_11", "=q4=Breastplate of Ten Storms", "=ds="..AtlasLootBossNames["BlackwingLair"][8],   " 5.65%" },
        { 16943, "INV_Bracer_16", "=q4=Bracers of Ten Storms", "=ds="..AtlasLootBossNames["BlackwingLair"][1],       " 7.54%" },
        { 16948, "INV_Gauntlets_11", "=q4=Gauntlets of Ten Storms", "=ds="..AtlasLootBossNames["BlackwingLair"][4]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][5]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][6],   "2.13%" },
        { 16944, "INV_Belt_14", "=q4=Belt of Ten Storms", "=ds="..AtlasLootBossNames["BlackwingLair"][2],   " 6.93%" },
        { 16946, "INV_Pants_03", "=q4=Legplates of Ten Storms", "=ds="..AtlasLootBossNames["MoltenCore"][10], " 5.97%" },
        { 16949, "INV_Boots_Plate_06", "=q4=Greaves of Ten Storms", "=ds="..AtlasLootBossNames["BlackwingLair"][3],     " 5.57%" },
        };

    T2Hunter = {
	    { 0,"Ability_Hunter_RunningShot","=q6=#t2s2#","" },
        { 16939, "INV_Helmet_05", "=q4=Dragonstalker's Helm", "=ds="..AtlasLootBossNames["OnyxiasLair"][1], " 13.91%" },
	    { 16937, "INV_Shoulder_10", "=q4=Dragonstalker's Spaulders", "=ds="..AtlasLootBossNames["BlackwingLair"][7],   "16.20%" },
	    { 16942, "INV_Chest_Chain_03", "=q4=Dragonstalker's Breastplate", "=ds="..AtlasLootBossNames["BlackwingLair"][8],   "13.30%" },
	    { 16935, "INV_Bracer_17", "=q4=Dragonstalker's Bracers", "=ds="..AtlasLootBossNames["BlackwingLair"][1],       "19.13%" },
        { 16940, "INV_Gauntlets_10", "=q4=Dragonstalker's Gauntlets", "=ds="..AtlasLootBossNames["BlackwingLair"][4]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][5]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][6],   "6.13%" },
	    { 16936, "INV_Belt_28", "=q4=Dragonstalker's Belt", "=ds="..AtlasLootBossNames["BlackwingLair"][2],   "20.17%" },
        { 16938, "INV_Pants_03", "=q4=Dragonstalker's Legguards", "=ds="..AtlasLootBossNames["MoltenCore"][10], "16.02%" },
	    { 16941, "INV_Boots_Plate_07", "=q4=Dragonstalker's Greaves", "=ds="..AtlasLootBossNames["BlackwingLair"][3],     "17.78%" },
	};

    T2Warrior = {
        { 0,"INV_Shield_05","=q6=#t2s9#","" },
        { 16963, "INV_Helmet_71", "=q4=Helm of Wrath", "=ds="..AtlasLootBossNames["OnyxiasLair"][1], " 13.65%" },
        { 16961, "INV_Shoulder_34", "=q4=Pauldrons of Wrath", "=ds="..AtlasLootBossNames["BlackwingLair"][7],  "16.83%" },
        { 16966, "INV_Chest_Plate16", "=q4=Breastplate of Wrath", "=ds="..AtlasLootBossNames["BlackwingLair"][8],  "15.06%" },
        { 16959, "INV_Bracer_19", "=q4=Bracelets of Wrath", "=ds="..AtlasLootBossNames["BlackwingLair"][1],      "20.29%" },
        { 16964, "INV_Gauntlets_10", "=q4=Gauntlets of Wrath", "=ds="..AtlasLootBossNames["BlackwingLair"][4]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][5]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][6],  "5.93%" },
        { 16960, "INV_Belt_09", "=q4=Waistband of Wrath", "=ds="..AtlasLootBossNames["BlackwingLair"][2],  "20.03%" },
        { 16962, "INV_Pants_04", "=q4=Legplates of Wrath", "=ds="..AtlasLootBossNames["MoltenCore"][10], "17.23%" },
        { 16965, "INV_Boots_Plate_04", "=q4=Sabatons of Wrath", "=ds="..AtlasLootBossNames["BlackwingLair"][3],    "16.84%" },
        };

    T2Paladin = {
	    { 0,"Spell_Holy_SealOfMight","=q6=#t2s4#","" },
        { 16955, "INV_Helmet_74", "=q4=Judgement Crown", "=ds="..AtlasLootBossNames["OnyxiasLair"][1], "  8.64%" },
	    { 16953, "INV_Shoulder_37", "=q4=Judgement Spaulders", "=ds="..AtlasLootBossNames["BlackwingLair"][7],  "10.97%" },
	    { 16958, "INV_Chest_Plate03", "=q4=Judgement Breastplate", "=ds="..AtlasLootBossNames["BlackwingLair"][8],  " 9.24%" },
	    { 16951, "INV_Bracer_18", "=q4=Judgement Bindings", "=ds="..AtlasLootBossNames["BlackwingLair"][1],      "13.61%" },
        { 16956, "INV_Gauntlets_29", "=q4=Judgement Gauntlets", "=ds="..AtlasLootBossNames["BlackwingLair"][4]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][5]..", ".."=ds="..AtlasLootBossNames["BlackwingLair"][6],  "3.58%" },
	    { 16952, "INV_Belt_27", "=q4=Judgement Belt", "=ds="..AtlasLootBossNames["BlackwingLair"][2],  "12.23%" },
        { 16954, "INV_Pants_04", "=q4=Judgement Legplates", "=ds="..AtlasLootBossNames["MoltenCore"][10], "10.81%" },
	    { 16957, "INV_Boots_Plate_09", "=q4=Judgement Sabatons", "=ds="..AtlasLootBossNames["BlackwingLair"][3],    "11.28%" },
	};
        
    T1Mage = {
        { 0,"Spell_Frost_IceStorm","=q6=#t1s3#","" },
        { 16795, "INV_Helmet_53", "=q4=Arcanist Crown", "=ds="..AtlasLootBossNames["MoltenCore"][4] , "11.31%" },
        { 16797, "INV_Shoulder_02", "=q4=Arcanist Mantle", "=ds="..AtlasLootBossNames["MoltenCore"][6], "19.92%" },
        { 16798, "INV_Chest_Cloth_03", "=q4=Arcanist Robes", "=ds="..AtlasLootBossNames["MoltenCore"][7], "16.51%" },
        { 16799, "INV_Belt_29", "=q4=Arcanist Bindings", "=ds="..AtlasLootBossNames["Common"][1], "0.16%" },
        { 16801, "INV_Gauntlets_14", "=q4=Arcanist Gloves", "=ds="..AtlasLootBossNames["MoltenCore"][5], "19.59%" },
        { 16802, "INV_Belt_30", "=q4=Arcanist Belt", "=ds="..AtlasLootBossNames["Common"][1], "0.16%"  },
        { 16796, "INV_Pants_08", "=q4=Arcanist Leggings", "=ds="..AtlasLootBossNames["MoltenCore"][2], "14.57%" },
        { 16800, "INV_Boots_07", "=q4=Arcanist Boots",  "=ds="..AtlasLootBossNames["MoltenCore"][1], "12.06%" },
        };

   T1Priest = {
        { 0,"Spell_Holy_PowerWordShield","=q6=#t1s5#","" },
        { 16813, "INV_Helmet_34", "=q4=Circlet of Prophecy", "=ds="..AtlasLootBossNames["MoltenCore"][4] , "11.36%" },
        { 16816, "INV_Shoulder_02", "=q4=Mantle of Prophecy", "=ds="..AtlasLootBossNames["MoltenCore"][8], "21.06%" },
        { 16815, "INV_Chest_Cloth_03", "=q4=Robes of Prophecy", "=ds="..AtlasLootBossNames["MoltenCore"][7], "15.65%" },
        { 16819, "INV_Bracer_09", "=q4=Vambraces of Prophecy",   "=ds="..AtlasLootBossNames["Common"][1], "0.16%" },
        { 16812, "INV_Gauntlets_14", "=q4=Gloves of Prophecy", "=ds="..AtlasLootBossNames["MoltenCore"][3], "18.65%" },
        { 16817, "INV_Belt_22", "=q4=Girdle of Prophecy", "=ds="..AtlasLootBossNames["Common"][1], "0.18%" },
        { 16814, "INV_Pants_08", "=q4=Pants of Prophecy", "=ds="..AtlasLootBossNames["MoltenCore"][2], "14.33%" },
        { 16811, "INV_Gauntlets_07", "=q4=Boots of Prophecy", "=ds="..AtlasLootBossNames["MoltenCore"][5], "14.90%" },
        };

   T1Warlock = {
        { 0,"Spell_Shadow_CurseOfTounges","=q6=#t1s8#","" },
        { 16808, "INV_Helmet_08", "=q4=Felheart Horns", "=ds="..AtlasLootBossNames["MoltenCore"][4], "10.62%" },
        { 16807, "INV_Shoulder_23", "=q4=Felheart Shoulder Pads", "=ds="..AtlasLootBossNames["MoltenCore"][6], "19.78%" },
        { 16809, "INV_Chest_Cloth_09", "=q4=Felheart Robes", "=ds="..AtlasLootBossNames["MoltenCore"][7], "15.66%" },
        { 16804, "INV_Bracer_07", "=q4=Felheart Bracers", "=ds="..AtlasLootBossNames["Common"][1], "0.16%" },
        { 16805, "INV_Gauntlets_19", "=q4=Felheart Gloves", "=ds="..AtlasLootBossNames["MoltenCore"][1],  "14.89%" },
        { 16806, "INV_Belt_13", "=q4=Felheart Belt", "=ds="..AtlasLootBossNames["Common"][1], "0.19%" },
        { 16810, "INV_Pants_Cloth_14", "=q4=Felheart Pants", "=ds="..AtlasLootBossNames["MoltenCore"][2], "13.75%" },
        { 16803, "INV_Boots_Cloth_05", "=q4=Felheart Slippers", "=ds="..AtlasLootBossNames["MoltenCore"][5], "15.28%" },
        };

   T1Rogue = {
        { 0,"Ability_BackStab","=q6=#t1s6#","" },
        { 16821, "INV_Helmet_41", "=q4=Nightslayer Cover", "=ds="..AtlasLootBossNames["MoltenCore"][4], "10.38%" },
        { 16823, "INV_Shoulder_25", "=q4=Nightslayer Shoulder Pads", "=ds="..AtlasLootBossNames["MoltenCore"][8], "20.66%" },
        { 16820, "INV_Chest_Cloth_07", "=q4=Nightslayer Chestpiece", "=ds="..AtlasLootBossNames["MoltenCore"][7], "16.76%" },
        { 16825, "INV_Bracer_02", "=q4=Nightslayer Bracelets", "=ds="..AtlasLootBossNames["Common"][1], "0.17%" },
        { 16826, "INV_Gauntlets_21", "=q4=Nightslayer Gloves", "=ds="..AtlasLootBossNames["MoltenCore"][3], "19.47%" },
        { 16827, "INV_Belt_23", "=q4=Nightslayer Belt", "=ds="..AtlasLootBossNames["Common"][1], "0.15%" },
        { 16822, "INV_Pants_06", "=q4=Nightslayer Pants", "=ds="..AtlasLootBossNames["MoltenCore"][2], "13.83%" },
        { 16824, "INV_Gauntlets_08", "=q4=Nightslayer Boots", "=ds="..AtlasLootBossNames["MoltenCore"][5], "15.58%" },
        };

   T1Druid = {
	    { 0,"Spell_Nature_Regeneration","=q6=#t1s1#","" },
	    { 16834, "INV_Helmet_09", "=q4=Cenarion Helm", "=ds="..AtlasLootBossNames["MoltenCore"][4], "11.51%" },
	    { 16836, "INV_Shoulder_07", "=q4=Cenarion Spaulders", "=ds="..AtlasLootBossNames["MoltenCore"][6], "19.52%" },
        { 16833, "INV_Chest_Cloth_06", "=q4=Cenarion Vestments", "=ds="..AtlasLootBossNames["MoltenCore"][7], "15.21%" },
        { 16830, "INV_Bracer_03", "=q4=Cenarion Bracers", "=ds="..AtlasLootBossNames["Common"][1], "0.17%" },
        { 16831, "INV_Gauntlets_07", "=q4=Cenarion Gloves", "=ds="..AtlasLootBossNames["MoltenCore"][5], "19.53%" },
	    { 16828, "INV_Belt_06", "=q4=Cenarion Belt", "=ds="..AtlasLootBossNames["Common"][1], "0.16%" },
        { 16835, "INV_Pants_06", "=q4=Cenarion Leggings", "=ds="..AtlasLootBossNames["MoltenCore"][2], "12.90%" },
        { 16829, "INV_Boots_08", "=q4=Cenarion Boots", "=ds="..AtlasLootBossNames["MoltenCore"][1],    "10.72%" },
	};

   T1Shaman = {
        { 0,"Spell_FireResistanceTotem_01","=q6=#t1s7#","" },
        { 16842, "INV_Helmet_09", "=q4=Earthfury Helmet", "=ds="..AtlasLootBossNames["MoltenCore"][4], " 3.91%" },
        { 16844, "INV_Shoulder_29", "=q4=Earthfury Epaulets", "=ds="..AtlasLootBossNames["MoltenCore"][6], " 7.29%" },
        { 16841, "INV_Chest_Chain_11", "=q4=Earthfury Vestments", "=ds="..AtlasLootBossNames["MoltenCore"][7], " 6.08%" },
        { 16840, "INV_Bracer_16", "=q4=Earthfury Bracers", "=ds="..AtlasLootBossNames["Common"][1], "0.06%" },
        { 16839, "INV_Gauntlets_11", "=q4=Earthfury Gauntlets", "=ds="..AtlasLootBossNames["MoltenCore"][3], " 7.38%" },
        { 16838, "INV_Belt_14", "=q4=Earthfury Belt", "=ds="..AtlasLootBossNames["Common"][1], "0.07%" },
        { 16843, "INV_Pants_03", "=q4=Earthfury Legguards", "=ds="..AtlasLootBossNames["MoltenCore"][2], " 4.73%" },
        { 16837, "INV_Boots_Plate_06", "=q4=Earthfury Boots", "=ds="..AtlasLootBossNames["MoltenCore"][1],   " 4.16%" },
        };

   T1Hunter = {
	    { 0,"Ability_Hunter_RunningShot","=q6=#t1s2#","" },
	    { 16846, "INV_Helmet_05", "=q4=Giantstalker's Helmet", "=ds="..AtlasLootBossNames["MoltenCore"][4], "11.57%" },
	    { 16848, "INV_Shoulder_10", "=q4=Giantstalker's Epaulets", "=ds="..AtlasLootBossNames["MoltenCore"][8], "19.64%" },
        { 16845, "INV_Chest_Chain_03", "=q4=Giantstalker's Breastplate", "=ds="..AtlasLootBossNames["MoltenCore"][7], "15.83%" },
	    { 16850, "INV_Bracer_17", "=q4=Giantstalker's Bracers", "=ds="..AtlasLootBossNames["Common"][1], "0.18%" },
        { 16852, "INV_Gauntlets_10", "=q4=Giantstalker's Gloves", "=ds="..AtlasLootBossNames["MoltenCore"][5], "18.58%" },
        { 16851, "INV_Belt_28", "=q4=Giantstalker's Belt", "=ds="..AtlasLootBossNames["Common"][1], "0.17%" },
        { 16847, "INV_Pants_Mail_03", "=q4=Giantstalker's Leggings", "=ds="..AtlasLootBossNames["MoltenCore"][2], "13.28%" },
	    { 16849, "INV_Boots_Chain_13", "=q4=Giantstalker's Boots", "=ds="..AtlasLootBossNames["MoltenCore"][3], "14.54%" },
	};

   T1Warrior = {
        { 0,"INV_Shield_05","=q6=#t1s9#","" },
        { 16866, "INV_Helmet_09", "=q4=Helm of Might", "=ds="..AtlasLootBossNames["MoltenCore"][4], "11.39%" },
        { 16868, "INV_Shoulder_15", "=q4=Pauldrons of Might", "=ds="..AtlasLootBossNames["MoltenCore"][8], "21.14%" },
        { 16865, "INV_Chest_Plate16", "=q4=Breastplate of Might", "=ds="..AtlasLootBossNames["MoltenCore"][7], "15.28%" },
        { 16861, "INV_Bracer_19", "=q4=Bracers of Might", "=ds="..AtlasLootBossNames["Common"][1], "0.16%" },
        { 16863, "INV_Gauntlets_10", "=q4=Gauntlets of Might", "=ds="..AtlasLootBossNames["MoltenCore"][1],  "16.40%" },
        { 16864, "INV_Belt_09", "=q4=Belt of Might", "=ds="..AtlasLootBossNames["Common"][1], "0.16%" },
        { 16867, "INV_Pants_04", "=q4=Legplates of Might", "=ds="..AtlasLootBossNames["MoltenCore"][2], "13.97%" },
        { 16862, "INV_Boots_Plate_04", "=q4=Sabatons of Might", "=ds="..AtlasLootBossNames["MoltenCore"][3], "14.48%" },
        };


   T1Paladin = {
	    { 0,"Spell_Holy_SealOfMight","=q6=#t1s4#","" },
	    { 16854, "INV_Helmet_05", "=q4=Lawbringer Helm", "=ds="..AtlasLootBossNames["MoltenCore"][4], " 7.23%" },
	    { 16856, "INV_Shoulder_20", "=q4=Lawbringer Spaulders", "=ds="..AtlasLootBossNames["MoltenCore"][6], "12.62%" },
	    { 16853, "INV_Chest_Plate03", "=q4=Lawbringer Chestguard", "=ds="..AtlasLootBossNames["MoltenCore"][7], " 9.53%" },
	    { 16857, "INV_Bracer_18", "=q4=Lawbringer Bracers", "=ds="..AtlasLootBossNames["Common"][1], "0.11%" },
        { 16860, "INV_Gauntlets_29", "=q4=Lawbringer Gauntlets", "=ds="..AtlasLootBossNames["MoltenCore"][3], "11.77%" },
        { 16858, "INV_Belt_27", "=q4=Lawbringer Belt", "=ds="..AtlasLootBossNames["Common"][1], "0.10%" },
        { 16855, "INV_Pants_04", "=q4=Lawbringer Legplates", "=ds="..AtlasLootBossNames["MoltenCore"][2], " 8.54%" },
        { 16859, "INV_Boots_Plate_09", "=q4=Lawbringer Boots", "=ds="..AtlasLootBossNames["MoltenCore"][1], " 7.20%" },
	};
        
    T0Mage = {
        { 0,"Spell_Frost_IceStorm", "=q6=#t0s3#", "" },
        { 16686, "INV_Crown_02", "=q3=Magister's Crown", "=ds="..AtlasLootBossNames["Scholomance"][16], "8.60%" },
        { 16689, "INV_Shoulder_23", "=q3=Magister's Mantle", "=ds="..AtlasLootBossNames["Scholomance"][8], "11.93%" },
        { 16688,"INV_Chest_Cloth_25","=q3=Magister's Robes", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][10], "7.24%" },
        { 16683, "INV_Jewelry_Ring_23", "=q3=Magister's Bindings", "=ds="..AtlasLootBossNames["Common"][1], "1.19%" },
        { 16684, "INV_Gauntlets_17", "=q3=Magister's Gloves", "=ds="..AtlasLootBossNames["Scholomance"][11], "9.75%" },
        { 16685, "INV_Belt_08", "=q3=Magister's Belt", "=ds="..AtlasLootBossNames["Common"][1], "1.32%" },
        { 16687, "INV_Pants_06", "=q3=Magister's Leggings", "=ds="..AtlasLootBossNames["Stratholme"][18], "6.79%" },
        { 16682, "INV_Boots_02", "=q3=Magister's Boots", "=ds="..AtlasLootBossNames["Stratholme"][4], "10.86%" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0,"Spell_Frost_IceStorm", "=q6=#t05s3#", "" },
        { 22065, "INV_Crown_02", "=q4=Sorcerer's Crown", "" },
        { 22068, "INV_Shoulder_23", "=q3=Sorcerer's Mantle", "" },
        { 22069, "INV_Chest_Cloth_25","=q4=Sorcerer's Robes", "" },
        { 22063, "INV_Jewelry_Ring_23", "=q3=Sorcerer's Bindings", "" },
        { 22066, "INV_Gauntlets_17", "=q4=Sorcerer's Gloves", "" },
        { 22062, "INV_Belt_08", "=q3=Sorcerer's Belt", "" },
        { 22067, "INV_Pants_06", "=q3=Sorcerer's Leggings", "" },
        { 22064, "INV_Boots_02", "=q4=Sorcerer's Boots", "" },
        };

    T0Priest = {
        { 0,"Spell_Holy_PowerWordShield","=q6=#t0s5#","" },
        { 16693, "INV_Crown_01", "=q3=Devout Crown", "=ds="..AtlasLootBossNames["Scholomance"][16], "7.89%" },
        { 16695, "INV_Shoulder_02", "=q3=Devout Mantle", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][2], "12.84%" },
        { 16690,"INV_Chest_Cloth_11","=q3=Devout Robe", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][10], "6.20%" },
        { 16697, "INV_Belt_31", "=q3=Devout Bracers", "=ds="..AtlasLootBossNames["Common"][1], "1.13%" },
        { 16692, "INV_Gauntlets_14", "=q3=Devout Gloves", "=ds="..AtlasLootBossNames["Stratholme"][8], "12.46%" },
        { 16696, "INV_Belt_10", "=q3=Devout Belt", "=ds="..AtlasLootBossNames["Common"][1], "2.07%" },
        { 16694, "INV_Pants_08", "=q3=Devout Skirt", "=ds="..AtlasLootBossNames["Stratholme"][18], "7.42%" },
        { 16691, "INV_Boots_05", "=q3=Devout Sandals", "=ds="..AtlasLootBossNames["Stratholme"][15], "13.64%" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0,"Spell_Holy_PowerWordShield","=q6=#t05s5#","" },
        { 22080, "INV_Crown_01", "=q4=Virtuous Crown", "" },
        { 22082, "INV_Shoulder_02", "=q3=Virtuous Mantle", "" },
        { 22083,"INV_Chest_Cloth_11","=q4=Virtuous Robe", "" },
        { 22079, "INV_Belt_31", "=q3=Virtuous Bracers", "" },
        { 22081, "INV_Gauntlets_14", "=q4=Virtuous Gloves", "" },
        { 22078, "INV_Belt_10", "=q3=Virtuous Belt", "" },
        { 22085, "INV_Pants_08", "=q3=Virtuous Skirt", "" },
        { 22084, "INV_Boots_05", "=q4=Virtuous Sandals", "" },
        };

    T0Warlock = {
        { 0,"Spell_Shadow_CurseOfTounges","=q6=#t0s8#","" },
        { 16698, "INV_Helmet_29", "=q3=Dreadmist Mask", "=ds="..AtlasLootBossNames["Scholomance"][16], "8.78%" },
        { 16701, "INV_Misc_Bone_TaurenSkull_01", "=q3=Dreadmist Mantle", "=ds="..AtlasLootBossNames["Scholomance"][3], "12.20%" },
        { 16700,"INV_Chest_Cloth_49","=q3=Dreadmist Robe", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][10], "8.04%" },
        { 16703, "INV_Bracer_13", "=q3=Dreadmist Bracers", "=ds="..AtlasLootBossNames["Common"][1], "1.68%" },
        { 16705, "INV_Gauntlets_32", "=q3=Dreadmist Wraps", "=ds="..AtlasLootBossNames["Scholomance"][12], "14.54%" },
        { 16702, "INV_Belt_12", "=q3=Dreadmist Belt", "=ds="..AtlasLootBossNames["Common"][1], "1.03%" },
        { 16699, "INV_Pants_08", "=q3=Dreadmist Leggings", "=ds="..AtlasLootBossNames["Stratholme"][18], "7.31%" },
        { 16704, "INV_Boots_05", "=q3=Dreadmist Sandals", "=ds="..AtlasLootBossNames["Stratholme"][13], "13.16%" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0,"Spell_Shadow_CurseOfTounges","=q6=#t05s8#","" },
        { 22074, "INV_Helmet_29", "=q4=Deathmist Mask", "" },
        { 22073, "INV_Misc_Bone_TaurenSkull_01", "=q3=Deathmist Mantle", "" },
        { 22075,"INV_Chest_Cloth_49","=q4=Deathmist Robe", "" },
        { 22071, "INV_Bracer_13", "=q3=Deathmist Bracers", "" },
        { 22077, "INV_Gauntlets_32", "=q4=Deathmist Wraps", "" },
        { 22070, "INV_Belt_12", "=q3=Deathmist Belt", "" },
        { 22072, "INV_Pants_08", "=q3=Deathmist Leggings", "" },
        { 22076, "INV_Boots_05", "=q4=Deathmist Sandals", "" },
        };

    T0Rogue = {
        { 0,"Ability_BackStab","=q6=#t0s6#","" },
        { 16707, "INV_Helmet_41", "=q3=Shadowcraft Cap", "=ds="..AtlasLootBossNames["Scholomance"][16], "6.65%" },
        { 16708, "INV_Shoulder_07", "=q3=Shadowcraft Spaulders", "=ds="..AtlasLootBossNames["Stratholme"][7], "10.68%" },
        { 16721,"INV_Chest_Leather_07","=q3=Shadowcraft Tunic",  "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][10], "6.09%" },
        { 16710, "INV_Bracer_07", "=q3=Shadowcraft Bracers", "=ds="..AtlasLootBossNames["Common"][1], "3.51%" },
        { 16712, "INV_Gauntlets_24", "=q3=Shadowcraft Gloves", "=ds="..AtlasLootBossNames["BlackrockSpireLower"][3], "11.89%" },
        { 16713, "INV_Belt_03", "=q3=Shadowcraft Belt", "=ds="..AtlasLootBossNames["Common"][1], "1.05%" },
        { 16709, "INV_Pants_02", "=q3=Shadowcraft Pants", "=ds="..AtlasLootBossNames["Stratholme"][18], "7.76%" },
        { 16711, "INV_Boots_08", "=q3=Shadowcraft Boots", "=ds="..AtlasLootBossNames["Scholomance"][4], "14.32%" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0,"Ability_BackStab","=q6=#t05s6#","" },
        { 22005, "INV_Helmet_41", "=q4=Darkmantle Cap", "" },
        { 22008, "INV_Shoulder_07", "=q3=Darkmantle Spaulders", "" },
        { 22009,"INV_Chest_Leather_07","=q4=Darkmantle Tunic",  "" },
        { 22004, "INV_Bracer_07", "=q3=Darkmantle Bracers", "" },
        { 22006, "INV_Gauntlets_24", "=q4=Darkmantle Gloves", "" },
        { 22002, "INV_Belt_03", "=q3=Darkmantle Belt", "" },
        { 22007, "INV_Pants_02", "=q3=Darkmantle Pants", "" },
        { 22003, "INV_Boots_08", "=q4=Darkmantle Boots", "" },
        };

    T0Druid = {
	  	{ 0,"Spell_Nature_Regeneration","=q6=#t0s1#","" },
        { 16720, "INV_Helmet_27", "=q3=Wildheart Cowl", "=ds="..AtlasLootBossNames["Scholomance"][16], "7.09%" },
	  	{ 16718, "INV_Shoulder_01", "=q3=Wildheart Spaulders",  "=ds="..AtlasLootBossNames["BlackrockSpireLower"][10], "11.04%" },
	  	{ 16706,"INV_Chest_Plate06","=q3=Wildheart Vest", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][10], "7.36%" },
        { 16716, "INV_Bracer_09", "=q3=Wildheart Bracers", "=ds="..AtlasLootBossNames["Common"][1], "1.85%" },
	  	{ 16717, "INV_Gauntlets_17", "=q3=Wildheart Gloves", "=ds="..AtlasLootBossNames["Stratholme"][5], "12.61%" },
        { 16716, "INV_Belt_15", "=q3=Wildheart Belt", "=ds="..AtlasLootBossNames["Common"][1], "2.60%" },
	  	{ 16719, "INV_Pants_08", "=q3=Wildheart Kilt", "=ds="..AtlasLootBossNames["Stratholme"][18], "6.58%" },
        { 16715, "INV_Boots_08", "=q3=Wildheart Boots", "=ds="..AtlasLootBossNames["BlackrockSpireLower"][6], "13.03%" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0,"Spell_Nature_Regeneration","=q6=#t05s1#","" },
        { 22109, "INV_Helmet_27", "=q4=Feralheart Cowl", "" },
	  	{ 22112, "INV_Shoulder_01", "=q3=Feralheart Spaulders",  "" },
	  	{ 22113,"INV_Chest_Plate06","=q4=Feralheart Vest", "" },
        { 22108, "INV_Bracer_09", "=q3=Feralheart Bracers", "" },
	  	{ 22110, "INV_Gauntlets_17", "=q4=Feralheart Gloves", "" },
        { 22106, "INV_Belt_15", "=q3=Feralheart Belt", "" },
	  	{ 22111, "INV_Pants_08", "=q3=Feralheart Kilt", "" },
        { 22107, "INV_Boots_08", "=q4=Feralheart Boots", "" },
		};

    T0Shaman = {
        { 0,"Spell_FireResistanceTotem_01","=q6=#t0s7#","" },
        { 16667, "INV_Helmet_04", "=q3=Coif of Elements", "=ds="..AtlasLootBossNames["Scholomance"][16], "2.86%" },
        { 16669,"INV_Shoulder_29","=q3=Pauldrons of Elements","=ds="..AtlasLootBossNames["BlackrockSpireUpper"][7], "14.77%" },
        { 16666,"INV_Chest_Chain_11","=q3=Vest of Elements", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][10], "3.03%" },
        { 16671, "INV_Bracer_02", "=q3=Bindings of Elements", "=ds="..AtlasLootBossNames["Common"][1], "1.59%" },
        { 16672,"INV_Gauntlets_11","=q3=Gauntlets of Elements", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][1], "14.23%" },
        { 16673, "INV_Belt_16", "=q3=Cord of Elements", "=ds="..AtlasLootBossNames["Common"][1], "1.06%" },
        { 16668, "INV_Pants_03", "=q3=Kilt of Elements", "=ds="..AtlasLootBossNames["Stratholme"][18], "3.02%" },
        { 16670, "INV_Boots_Wolf", "=q3=Boots of the Elements", "=ds="..AtlasLootBossNames["BlackrockSpireLower"][1], "9.35%" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0,"Spell_FireResistanceTotem_01","=q6=#t05s7#","" },
        { 22097, "INV_Helmet_04", "=q4=Coif of The Five Thunders", "" },
        { 22101,"INV_Shoulder_29","=q3=Pauldrons of The Five Thunders","" },
        { 22102,"INV_Chest_Chain_11","=q4=Vest of The Five Thunders", "" },
        { 22095, "INV_Bracer_02", "=q3=Bindings of The Five Thunders", "" },
        { 22099,"INV_Gauntlets_11","=q4=Gauntlets of The Five Thunders", "" },
        { 22098, "INV_Belt_16", "=q3=Cord of The Five Thunders", "" },
        { 22100, "INV_Pants_03", "=q3=Kilt of The Five Thunders", "" },
        { 22096, "INV_Boots_Wolf", "=q4=Boots of the The Five Thunders", "" },
        };

    T0Hunter = {
		{ 0,"Ability_Hunter_RunningShot","=q6=#t0s2#","" },
        { 16677, "INV_Helmet_24", "=q3=Beaststalker's Cap", "=ds="..AtlasLootBossNames["Scholomance"][16], "7.00%" },
		{ 16679, "INV_Shoulder_10", "=q3=Beaststalker's Mantle", "=ds="..AtlasLootBossNames["BlackrockSpireLower"][12], "9.89%" },
		{ 16674, "INV_Chest_Chain_03","=q3=Beaststalker's Tunic", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][10],   "6.81%" },
		{ 16681, "INV_Bracer_17", "=q3=Beaststalker's Bindings", "=ds="..AtlasLootBossNames["Common"][1], "1.64%" },
        { 16676, "INV_Gauntlets_10", "=q3=Beaststalker's Gloves", "=ds="..AtlasLootBossNames["BlackrockSpireLower"][4], "9.15%" },
        { 16680, "INV_Belt_28", "=q3=Beaststalker's Belt", "=ds="..AtlasLootBossNames["Common"][1], "1.36%" },
        { 16678, "INV_Pants_03", "=q3=Beaststalker's Pants", "=ds="..AtlasLootBossNames["Stratholme"][18], "6.16%" },
        { 16675, "INV_Boots_Plate_07", "=q3=Beaststalker's Boots", "=ds="..AtlasLootBossNames["Stratholme"][14], "13.62%" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0,"Ability_Hunter_RunningShot","=q6=#t05s2#","" },
        { 22013, "INV_Helmet_24", "=q4=Beastmaster's Cap", "" },
		{ 22016, "INV_Shoulder_10", "=q3=Beastmaster's Mantle", "" },
		{ 22060, "INV_Chest_Chain_03","=q4=Beastmaster's Tunic", "" },
		{ 22011, "INV_Bracer_17", "=q3=Beastmaster's Bindings", "" },
        { 22015, "INV_Gauntlets_10", "=q4=Beastmaster's Gloves", "" },
        { 22010, "INV_Belt_28", "=q3=Beastmaster's Belt", "" },
        { 22017, "INV_Pants_03", "=q3=Beastmaster's Pants", "" },
        { 22061, "INV_Boots_Plate_07", "=q4=Beastmaster's Boots", "" },
		};

    T0Warrior = {
        { 0,"INV_Shield_05","=q6=#t0s9#","" },
        { 16731, "INV_Helmet_02", "=q3=Helm of Valor", "=ds="..AtlasLootBossNames["Scholomance"][16], "6.54%" },
        { 16733,"INV_Shoulder_30","=q3=Spaulders of Valor","=ds="..AtlasLootBossNames["BlackrockSpireUpper"][6], "13.39%" },
        { 16730,"INV_Chest_Plate03","=q3=Breastplate of Valor", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][10], "5.83%" },
        { 16735, "INV_Bracer_18", "=q3=Bracers of Valor", "=ds="..AtlasLootBossNames["Common"][1], "1.49%" },
        { 16737, "INV_Gauntlets_26", "=q3=Gauntlets of Valor", "=ds="..AtlasLootBossNames["Stratholme"][17], "9.58%" },
        { 16736, "INV_Belt_34", "=q3=Belt of Valor", "=ds="..AtlasLootBossNames["Common"][1], "1.96%" },
        { 16732, "INV_Pants_04", "=q3=Legplates of Valor", "=ds="..AtlasLootBossNames["Stratholme"][18], "5.74%" },
        { 16734, "INV_Boots_Plate_03", "=q3=Boots of Valor", "=ds="..AtlasLootBossNames["Scholomance"][2], "11.12%" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0,"INV_Shield_05","=q6=#t05s9#","" },
        { 21999, "INV_Helmet_02", "=q4=Helm of Heroism", "" },
        { 22001,"INV_Shoulder_30","=q3=Spaulders of Heroism","" },
        { 21997,"INV_Chest_Plate03","=q4=Breastplate of Heroism", "" },
        { 21996, "INV_Bracer_18", "=q3=Bracers of Heroism", "" },
        { 21998, "INV_Gauntlets_26", "=q4=Gauntlets of Heroism", "" },
        { 21994, "INV_Belt_34", "=q3=Belt of Heroism", "" },
        { 22000, "INV_Pants_04", "=q3=Legplates of Heroism", "" },
        { 21995, "INV_Boots_Plate_03", "=q4=Boots of Heroism", "" },
        };

    T0Paladin = {
		{ 0,"Spell_Holy_SealOfMight","=q6=#t0s4#","" },
        { 16727, "INV_Helmet_08", "=q3=Lightforge Helm", "=ds="..AtlasLootBossNames["Scholomance"][16], "5.32%" },
		{ 16729,"INV_Shoulder_10","=q3=Lightforge Spaulders", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][8], "13.62%" },
        { 16726,"INV_Chest_Plate03","=q3=Lightforge Breastplate", "=ds="..AtlasLootBossNames["BlackrockSpireUpper"][10], "3.76%" },
		{ 16722, "INV_Bracer_14", "=q3=Lightforge Bracers", "=ds="..AtlasLootBossNames["Common"][1], "3.37%" },
        { 16724, "INV_Gauntlets_19", "=q3=Lightforge Gauntlets", "=ds="..AtlasLootBossNames["Stratholme"][6], "10.42%" },
        { 16723, "INV_Belt_11", "=q3=Lightforge Belt", "=ds="..AtlasLootBossNames["Common"][1], "1.93%" },
        { 16728, "INV_Pants_04", "=q3=Lightforge Legplates", "=ds="..AtlasLootBossNames["Stratholme"][18], "4.20%" },
		{ 16725, "INV_Boots_Plate_03", "=q3=Lightforge Boots", "=ds="..AtlasLootBossNames["Stratholme"][9], "11.11%" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0,"Spell_Holy_SealOfMight","=q6=#t05s4#","" },
        { 22091, "INV_Helmet_08", "=q4=Soulforge Helm", "" },
		{ 22093, "INV_Shoulder_10","=q3=Soulforge Spaulders", "" },
        { 22089, "INV_Chest_Plate03","=q4=Soulforge Breastplate", "" },
		{ 22088, "INV_Bracer_14", "=q3=Soulforge Bracers", "" },
        { 22090, "INV_Gauntlets_19", "=q4=Soulforge Gauntlets", "" },
        { 22086, "INV_Belt_11", "=q3=Soulforge Belt", "" },
        { 22092, "INV_Pants_04", "=q3=Soulforge Legplates", "" },
		{ 22087, "INV_Boots_Plate_03", "=q4=Soulforge Boots", "" },
		};
        
    ZGMage = {
        { 0,"Spell_Frost_IceStorm","=q6=#zgs3#","" },
        { 19959, "INV_Jewelry_Necklace_19", "=q4=Hazza'rah's Charm of Magic", "" },
        { 19601, "INV_Jewelry_Necklace_26", "=q4=Jewel of Kajaro", "=ds=#r5#" },
        { 20034, "INV_Chest_Cloth_12", "=q4=Zandalar Illusionist's Robe", "=q4=#x10#=ds=, #r4#" },
        { 19845, "INV_Shoulder_17", "=q4=Zandalar Illusionist's Mantle", "=q4=#x11#=ds=, #r3#" },
        { 19846, "INV_Bracer_07", "=q4=Zandalar Illusionist's Wraps", "=q4=#x12#=ds=, #r2#" },
        };
    ZGWarlock = {
        { 0,"Spell_Shadow_CurseOfTounges","=q6=#zgs8#","" },
        { 19957, "INV_Jewelry_Necklace_19", "=q4=Hazza'rah's Charm of Destruction", "" },
        { 19605, "INV_Jewelry_Necklace_26", "=q4=Kezan's Unstoppable Taint", "=ds=#r5#" },
        { 20033, "INV_Chest_Cloth_12", "=q4=Zandalar Demoniac's Robe", "=q4=#x10#=ds=, #r4#" },
        { 19849, "INV_Shoulder_17", "=q4=Zandalar Demoniac's Mantle", "=q4=#x13#=ds=, #r3#" },
        { 19848, "INV_Bracer_07", "=q4=Zandalar Demoniac's Wraps", "=q4=#x14#=ds=, #r2#" },
        };
    ZGPriest = {
        { 0,"Spell_Holy_PowerWordShield","=q6=#zgs5#","" },
        { 19958, "INV_Jewelry_Necklace_19", "=q4=Hazza'rah's Charm of Healing", "" },
        { 19594, "INV_Jewelry_Necklace_26", "=q4=The All-Seeing Eye of Zuldazar", "=ds=#r5#" },
        { 19841, "INV_Shoulder_01", "=q4=Zandalar Confessor's Mantle", "=q4=#x15#=ds=, #r4#" },
        { 19842, "INV_Belt_08", "=q4=Zandalar Confessor's Bindings", "=q4=#x13#=ds=, #r3#" },
        { 19843, "INV_Bracer_07", "=q4=Zandalar Confessor's Wraps", "=q4=#x14#=ds=, #r2#" },
        };
    ZGRogue = {
        { 0,"Ability_BackStab","=q6=#zgs6#","" },
        { 19954, "INV_Jewelry_Necklace_19", "=q4=Renataki's Charm of Trickery", "" },
        { 19617, "INV_Jewelry_Necklace_26", "=q4=Zandalarian Shadow Mastery Talisman", "=ds=#r5#" },
        { 19834, "INV_Chest_Leather_10", "=q4=Zandalar Madcap's Tunic", "=q4=#x15#=ds=, #r4#" },
        { 19835, "INV_Shoulder_29", "=q4=Zandalar Madcap's Mantle", "=q4=#x16#=ds=, #r3#" },
        { 19836, "INV_Bracer_14", "=q4=Zandalar Madcap's Bracers", "=q4=#x17#=ds=, #r2#" },
        };

    ZGDruid = {
        { 0,"Spell_Nature_Regeneration","=q6=#zgs1#","" },
        { 19955, "INV_Jewelry_Necklace_19", "=q4=Wushoolay's Charm of Nature", "" },
        { 19613, "INV_Jewelry_Necklace_26", "=q4=Pristine Enchanted South Seas Kelp", "=ds=#r5#" },
        { 19838, "INV_Chest_Leather_06", "=q4=Zandalar Haruspex's Tunic", "=q4=#x18#=ds=, #r4#" },
        { 19839, "INV_Belt_01", "=q4=Zandalar Haruspex's Belt","=q4=#x13#=ds=, #r3#" },
        { 19840, "INV_Bracer_08", "=q4=Zandalar Haruspex's Bracers", "=q4=#x14#=ds=, #r2#" },
        };
    ZGHunter = {
        { 0,"Ability_Hunter_RunningShot","=q6=#zgs2#","" },
        { 19953, "INV_Jewelry_Necklace_19", "=q4=Renataki's Charm of Beasts", "" },
        { 19621, "INV_Jewelry_Necklace_26", "=q4=Maelstrom's Wrath", "=ds=#r5#" },
        { 19831, "INV_Shoulder_22", "=q4=Zandalar Predator's Mantle", "=q4=#x15#=ds=, #r4#" },
        { 19832, "INV_Belt_19", "=q4=Zandalar Predator's Belt", "=q4=#x11#=ds=, #r3#" },
        { 19833, "INV_Bracer_18", "=q4=Zandalar Predator's Bracers", "=q4=#x12#=ds=, #r2#" },
        };
    ZGShaman = {
        { 0,"Spell_FireResistanceTotem_01","=q6=#zgs7#","" },
        { 19956, "INV_Jewelry_Necklace_19", "=q4=Wushoolay's Charm of Spirits", "" },
        { 19609, "INV_Jewelry_Necklace_26", "=q4=Unmarred Vision of Voodress", "=ds=#r5#" },
        { 19828, "INV_Chest_Fur", "=q4=Zandalar Augur's Hauberk", "=q4=#x18#=ds=, #r4#" },
        { 19829, "INV_Belt_19", "=q4=Zandalar Augur's Belt", "=q4=#x16#=ds=, #r3#" },
        { 19830, "INV_Bracer_15", "=q4=Zandalar Augur's Bracers", "=q4=#x17#=ds=, #r2#" },
        };
    ZGWarrior = {
        { 0,"INV_Shield_05","=q6=#zgs9#","" },
        { 19951, "INV_Jewelry_Necklace_19", "=q4=Gri'lek's Charm of Might", "" },
        { 19577, "INV_Jewelry_Necklace_26", "=q4=Rage of Mugamba", "=ds=#r5#" },
        { 19822, "INV_Chest_Plate07", "=q4=Zandalar Vindicator's Breastplate", "=q4=#x10#=ds=, #r4#" },
        { 19823, "INV_Belt_32", "=q4=Zandalar Vindicator's Belt", "=q4=#x16#=ds=, #r3#" },
        { 19824, "INV_Bracer_14", "=q4=Zandalar Vindicator's Armguards", "=q4=#x17#=ds=, #r2#" },
        };

    ZGPaladin = {
        { 0,"Spell_Holy_SealOfMight","=q6=#zgs4#","" },
        { 19952, "INV_Jewelry_Necklace_19", "=q4=Gri'lek's Charm of Valor", "" },
        { 19588, "INV_Jewelry_Necklace_26", "=q4=Hero's Brand", "=ds=#r5#" },
        { 19825, "INV_Chest_Plate07", "=q4=Zandalar Freethinker's Breastplate", "=q4=#x18#=ds=, #r4#" },
        { 19826, "INV_Belt_32", "=q4=Zandalar Freethinker's Belt", "=q4=#x11#=ds=, #r3#" },
        { 19827, "INV_Bracer_14", "=q4=Zandalar Freethinker's Armguards", "=q4=#x12#=ds=, #r2#" },
        };
        
    AQ20Mage = {
        { 0,"Spell_Frost_IceStorm","=q6=#aq20s3#","" },
        { 21413, "INV_Sword_57", "=q4=Blade of Vaulted Secrets", "=q4=#x19#=ds=, #r5#" },
        { 21415, "INV_Misc_Cape_19", "=q4=Drape of Vaulted Secrets", "=q3=#x20#=ds=, #r4#" },
        { 21414, "INV_Jewelry_Ring_AhnQiraj_03", "=q4=Band of Vaulted Secrets", "=q3=#x21#=ds=, #r3#" },
        };
    AQ20Warlock = {
        { 0,"Spell_Shadow_CurseOfTounges","=q6=#aq20s8#","" },
        { 21416, "INV_Weapon_ShortBlade_27", "=q4=Kris of Unspoken Names", "=q4=#x19#=ds=, #r5#" },
        { 21418, "INV_Misc_Cape_20", "=q4=Shroud of Unspoken Names", "=q3=#x23#=ds=, #r4#" },
        { 21417, "INV_Jewelry_Ring_AhnQiraj_03", "=q4=Ring of Unspoken Names", "=q3=#x22#=ds=, #r3#" },
        };
    AQ20Priest = {
        { 0,"Spell_Holy_PowerWordShield","=q6=#aq20s5#","" },
        { 21410, "INV_Mace22", "=q4=Gavel of Infinite Wisdom", "=q4=#x19#=ds=, #r5#" },
        { 21412, "INV_Misc_Cape_16", "=q4=Shroud of Infinite Wisdom", "=q3=#x20#=ds=, #r4#" },
        { 21411, "INV_Jewelry_Ring_AhnQiraj_03", "=q4=Ring of Infinite Wisdom", "=q3=#x22#=ds=, #r3#" },
        };
    AQ20Rogue = {
        { 0,"Ability_BackStab","=q6=#aq20s6#","" },
        { 21404, "INV_Weapon_ShortBlade_27", "=q4=Dagger of Veiled Shadows", "=q4=#x24#=ds=, #r5#" },
        { 21406, "INV_Misc_Cape_19", "=q4=Cloak of Veiled Shadows", "=q3=#x20#=ds=, #r4#" },
        { 21405, "INV_Jewelry_Ring_AhnQiraj_03", "=q4=Band of Veiled Shadows", "=q3=#x22#=ds=, #r3#" },
        };
    AQ20Druid = {
        { 0,"Spell_Nature_Regeneration","=q6=#aq20s1#","" },
        { 21407, "INV_Mace22", "=q4=Mace of Unending Life", "=q4=#x19#=ds=, #r5#" },
        { 21409, "INV_Misc_Cape_15", "=q4=Cloak of Unending Life", "=q3=#x23#=ds=, #r4#" },
        { 21408, "INV_Jewelry_Ring_AhnQiraj_03", "=q4=Band of Unending Life", "=q3=#x21#=ds=, #r3#" },
        };

    AQ20Hunter = {
        { 0,"Ability_Hunter_RunningShot","=q6=#aq20s2#","" },
        { 21401, "INV_Axe_15", "=q4=Scythe of the Unseen Path", "=q4=#x24#=ds=, #r5#" },
        { 21403, "INV_Misc_Cape_15", "=q4=Cloak of the Unseen Path", "=q3=#x23#=ds=, #r4#" },
        { 21402, "INV_Jewelry_Ring_AhnQiraj_03", "=q4=Signet of the Unseen Path", "=q3=#x22#=ds=, #r3#" },
        };
    AQ20Paladin = {
        { 0,"Spell_Holy_SealOfMight","=q6=#aq20s4#","" },
        { 21395, "INV_Sword_57", "=q4=Blade of Eternal Justice", "=q4=#x24#=ds=, #r5#" },
        { 21397, "INV_Misc_Cape_14", "=q4=Cape of Eternal Justice", "=q3=#x23#=ds=, #r4#" },
        { 21396, "INV_Jewelry_Ring_AhnQiraj_03", "=q4=Ring of Eternal Justice", "=q3=#x21#=ds=, #r3#" },
        };
    AQ20Shaman = {
        { 0,"Spell_FireResistanceTotem_01","=q6=#aq20s7#","" },
        { 21398, "INV_Mace22", "=q4=Hammer of the Gathering Storm", "=q4=#x24#=ds=, #r5#" },
        { 21400, "INV_Misc_Cape_16", "=q4=Cloak of the Gathering Storm", "=q3=#x23#=ds=, #r4#" },
        { 21399, "INV_Jewelry_Ring_AhnQiraj_03", "=q4=Ring of the Gathering Storm", "=q3=#x21#=ds=, #r3#" },
        };
    AQ20Warrior = {
        { 0,"INV_Shield_05","=q6=#aq20s9#","" },
        { 21392, "INV_Axe_15", "=q4=Sickle of Unyielding Strength", "=q4=#x24#=ds=, #r5#" },
        { 21394, "INV_Misc_Cape_20", "=q4=Drape of Unyielding Strength", "=q3=#x20#=ds=, #r4#" },
        { 21393, "INV_Jewelry_Ring_AhnQiraj_03", "=q4=Signet of Unyielding Strength", "=q3=#x21#=ds=, #r3#" },
        };
        
    AQ40Mage = {
        { 0,"Spell_Frost_IceStorm","=q6=#aq40s3#","" }, --Mage
        { 21343, "INV_Chest_Cloth_11", "=q4=Enigma Robes", "=q4=#x28#=ds=, #r3#" },
        { 21347, "INV_Helmet_06", "=q4=Enigma Circlet", "=q4=#x26#=ds=, #r2#" },
        { 21346, "INV_Pants_Cloth_08", "=q4=Enigma Leggings", "=q4=#x27#=ds=, #r2#" },
        { 21345, "INV_Shoulder_03", "=q4=Enigma Shoulderpads", "=q4=#x25#=ds=, #r1#" },
        { 21344, "INV_Boots_Cloth_03", "=q4=Enigma Boots", "=q4=#x25#=ds=, #r1#" },
        };
    AQ40Priest = {
        { 0,"Spell_Holy_PowerWordShield","=q6=#aq40s5#","" }, --Priest
        { 21351, "INV_Chest_Cloth_10", "=q4=Vestments of the Oracle", "=q4=#x28#=ds=, #r3#" },
        { 21348, "INV_Helmet_06", "=q4=Tiara of the Oracle", "=q4=#x26#=ds=, #r2#" },
        { 21352, "INV_Pants_Cloth_07", "=q4=Trousers of the Oracle","=q4=#x27#=ds=, #r2#" },
        { 21350, "INV_Shoulder_03", "=q4=Mantle of the Oracle", "=q4=#x29#=ds=, #r1#" },
        { 21349, "INV_Boots_Cloth_07", "=q4=Footwraps of the Oracle", "=q4=#x29#=ds=, #r1#" },
        };
    AQ40Warlock = {
        { 0,"Spell_Shadow_CurseOfTounges","=q6=#aq40s8#","" }, --Warlock
        { 21334, "INV_Chest_Cloth_12", "=q4=Doomcaller's Robes", "=q4=#x28#=ds=, #r3#" },
        { 21337, "INV_Helmet_06", "=q4=Doomcaller's Circlet", "=q4=#x26#=ds=, #r2#" },
        { 21336, "INV_Pants_Cloth_02", "=q4=Doomcaller's Trousers", "=q4=#x31#=ds=, #r2#" },
        { 21335, "INV_Shoulder_03", "=q4=Doomcaller's Mantle", "=q4=#x25#=ds=, #r1#" },
        { 21338, "INV_Boots_Cloth_02", "=q4=Doomcaller's Footwraps", "=q4=#x25#=ds=, #r1#" },
        };
    AQ40Rogue = {
        { 0,"Ability_BackStab","=q6=#aq40s6#","" }, --Rogue
        { 21364, "INV_Chest_Leather_08", "=q4=Deathdealer's Vest", "=q4=#x32#=ds=, #r3#" },
        { 21360, "INV_Helmet_04", "=q4=Deathdealer's Helm", "=q4=#x30#=ds=, #r2#" },
        { 21362, "INV_Pants_Leather_07", "=q4=Deathdealer's Leggings", "=q4=#x27#=ds=, #r2#" },
        { 21361, "INV_Shoulder_03", "=q4=Deathdealer's Spaulders", "=q4=#x29#=ds=, #r1#" },
        { 21359, "INV_Boots_08", "=q4=Deathdealer's Boots", "=q4=#x29#=ds=, #r1#" },
        };

    AQ40Druid = {
        { 0,"Spell_Nature_Regeneration","=q6=#aq40s1#","" }, --Druid
        { 21357, "INV_Chest_Leather_08", "=q4=Genesis Vest", "=q4=#x28#=ds=, #r3#" },
        { 21353, "INV_Helmet_06", "=q4=Genesis Helm", "=q4=#x30#=ds=, #r2#" },
        { 21356, "INV_Pants_Leather_01", "=q4=Genesis Trousers", "=q4=#x31#=ds=, #r2#" },
        { 21354, "INV_Shoulder_03", "=q4=Genesis Shoulderpads", "=q4=#x25#=ds=, #r1#" },
        { 21355, "INV_Boots_Cloth_07", "=q4=Genesis Boots", "=q4=#x25#=ds=, #r1#" },
        };
    AQ40Shaman = {
        { 0,"Spell_FireResistanceTotem_01","=q6=#aq40s7#","" }, --Shaman
        { 21374, "INV_Chest_Chain_13", "=q4=Stormcaller's Hauberk", "=q4=#x32#=ds=, #r3#" },
        { 21372, "INV_Helmet_73", "=q4=Stormcaller's Diadem", "=q4=#x30#=ds=, #r2#" },
        { 21375, "INV_Pants_Mail_10", "=q4=Stormcaller's Leggings", "=q4=#x31#=ds=, #r2#" },
        { 21376, "INV_Shoulder_03", "=q4=Stormcaller's Pauldrons", "=q4=#x25#=ds=, #r1#" },
        { 21373, "INV_Boots_Chain_07", "=q4=Stormcaller's Footguards", "=q4=#x25#=ds=, #r1#" },
        };
    AQ40Hunter = {
        { 0,"Ability_Hunter_RunningShot","=q6=#aq40s2#","" }, --Hunter
        { 21370, "INV_Chest_Chain_04", "=q4=Striker's Hauberk", "=q4=#x32#=ds=, #r3#" },
        { 21366, "INV_Helmet_73", "=q4=Striker's Diadem", "=q4=#x30#=ds=, #r2#" },
        { 21368, "INV_Pants_Mail_11", "=q4=Striker's Leggings", "=q4=#x31#=ds=, #r2#" },
        { 21367, "INV_Shoulder_36", "=q4=Striker's Pauldrons", "=q4=#x29#=ds=, #r1#" },
        { 21365, "INV_Boots_Chain_08", "=q4=Striker's Footguards", "=q4=#x29#=ds=, #r1#" },
        };
    AQ40Warrior = {
        { 0,"INV_Shield_05","=q6=#aq40s9#","" }, --Warrior
        { 21331, "INV_Chest_Plate12", "=q4=Conqueror's Breastplate", "=q4=#x32#=ds=, #r3#" },
        { 21329, "INV_Helmet_72", "=q4=Conqueror's Crown", "=q4=#x26#=ds=, #r2#" },
        { 21332, "INV_Pants_Plate_03", "=q4=Conqueror's Legguards", "=q4=#x27#=ds=, #r2#" },
        { 21330, "INV_Shoulder_35", "=q4=Conqueror's Spaulders", "=q4=#x29#=ds=, #r1#" },
        { 21333, "INV_Boots_Plate_05", "=q4=Conqueror's Greaves", "=q4=#x29#=ds=, #r1#" },
        };

    AQ40Paladin = {
        { 0,"Spell_Holy_SealOfMight","=q6=#aq40s4#","" }, --Paladin
        { 21389, "INV_Chest_Plate03", "=q4=Avenger's Breastplate", "=q4=#x32#=ds=, #r3#" },
        { 21387, "INV_Helmet_72", "=q4=Avenger's Crown", "=q4=#x30#=ds=, #r2#" },
        { 21390, "INV_Pants_Plate_02", "=q4=Avenger's Legguards", "=q4=#x31#=ds=, #r2#" },
        { 21391, "INV_Shoulder_35", "=q4=Avenger's Pauldrons", "=q4=#x25#=ds=, #r1#" },
        { 21388, "INV_Boots_Chain_07", "=q4=Avenger's Greaves", "=q4=#x25#=ds=, #r1#" },
        };
        
    PVPHunter = {
        { 0, "INV_BannerPVP_02", "=q6=#pvpea2#", "=q5=#pvps1#" },
        { 16465, "INV_Helmet_05", "=q4=Field Marshal's Chain Helm", "" },
        { 16468, "INV_Shoulder_10", "=q4=Field Marshal's Chain Spaulders", "" },
        { 16466, "INV_Chest_Chain_03", "=q4=Field Marshal's Chain Breastplate", "" },
        { 16463, "INV_Gauntlets_10", "=q4=Marshal's Chain Grips", "" },
        { 16467, "INV_Pants_Mail_17", "=q4=Marshal's Chain Legguards", "" },
        { 16462, "INV_Boots_Plate_07", "=q4=Marshal's Chain Boots", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_02", "=q6=#pvpra2#", "=q5=#pvps2#" },
        { 23306, "INV_Helmet_21", "=q3=Lieutenant Commander's Chain Helm", "" },
        { 23307, "INV_Shoulder_16", "=q3=Lieutenant Commander's Chain Shoulders", "" },
        { 23292, "INV_Chest_Chain_04", "=q3=Knight-Captain's Chain Hauberk", "" },
        { 23279, "INV_Gauntlets_17", "=q3=Knight-Lieutenant's Chain Vices", "" },
        { 23293, "INV_Pants_03", "=q3=Knight-Captain's Chain Legguards", "" },
        { 23278, "INV_Boots_05", "=q3=Knight-Lieutenant's Chain Greaves", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvpeh2#", "=q5=#pvps1#" },
        { 16566, "INV_Helmet_09", "=q4=Warlord's Chain Helmet", "" },
        { 16568, "INV_Shoulder_29", "=q4=Warlord's Chain Shoulders", "" },
        { 16565, "INV_Chest_Chain_11", "=q4=Warlord's Chain Chestpiece", "" },
        { 16571, "INV_Gauntlets_11", "=q4=General's Chain Gloves", "" },
        { 16567, "INV_Pants_Mail_16", "=q4=General's Chain Legguards", "" },
        { 16569, "INV_Boots_Plate_06", "=q4=General's Chain Boots", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvprh2#", "=q5=#pvps2#" },
        { 23251, "INV_Helmet_03", "=q3=Champion's Chain Helm", "" },
        { 23252, "INV_Shoulder_01", "=q3=Champion's Chain Shoulders", "" },
        { 22874, "INV_Chest_Chain_04", "=q3=Legionnaire's Chain Hauberk", "" },
        { 22862, "INV_Gauntlets_17", "=q3=Blood Guard's Chain Vices", "" },
        { 22875, "INV_Pants_03", "=q3=Legionnaire's Chain Legguards", "" },
        { 22843, "INV_Boots_05", "=q3=Blood Guard's Chain Greaves", "" },
    };
    
    PVPMage = {
        { 0, "INV_BannerPVP_02", "=q6=#pvpea3#", "=q5=#pvps1#" },
        { 16441, "INV_Helmet_24", "=q4=Field Marshal's Coronet", "" },
        { 16444, "INV_Shoulder_23", "=q4=Field Marshal's Silk Spaulders", "" },
        { 16443, "INV_Chest_Cloth_12", "=q4=Field Marshal's Silk Vestments", "" },
	    { 16440, "INV_Gauntlets_14", "=q4=Marshal's Silk Gloves", "" },
	    { 16442, "INV_Pants_08", "=q4=Marshal's Silk Leggings", "" },
        { 16437, "INV_Boots_Cloth_03", "=q4=Marshal's Silk Footwraps", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_02", "=q6=#pvpra3#", "=q5=#pvps2#" },
        { 23318, "INV_Helmet_06", "=q3=Lieutenant Commander's Silk Cowl", "" },
        { 23319, "INV_Shoulder_02", "=q3=Lieutenant Commander's Silk Mantle", "" },
        { 23305, "INV_Chest_Cloth_28", "=q3=Knight-Captain's Silk Tunic", "" },
	    { 23290, "INV_Gauntlets_06", "=q3=Knight-Lieutenant's Silk Handwraps", "" },
        { 23304, "INV_Pants_11", "=q3=Knight-Captain's Silk Legguards", "" },
	    { 23291, "INV_Boots_05", "=q3=Knight-Lieutenant's Silk Walkers", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvpeh3#", "=q5=#pvps1#" },
        { 16533, "INV_Helmet_08", "=q4=Warlord's Silk Cowl", "" },
        { 16536, "INV_Shoulder_19", "=q4=Warlord's Silk Amice", "" },
        { 16535, "INV_Chest_Leather_01", "=q4=Warlord's Silk Raiment", "" },
	    { 16540, "INV_Gauntlets_19", "=q4=General's Silk Handguards", "" },
	    { 16534, "INV_Pants_07", "=q4=General's Silk Trousers", "" },
        { 16539, "INV_Boots_05", "=q4=General's Silk Boots", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvprh3#", "=q5=#pvps2#" },
        { 23263, "INV_Helmet_06", "=q3=Champion's Silk Cowl", "" },
        { 23264, "INV_Shoulder_02", "=q3=Champion's Silk Mantle", "" },
        { 22886, "INV_Chest_Cloth_28", "=q3=Legionnaire's Silk Tunic", "" },
	    { 22870, "INV_Gauntlets_06", "=q3=Blood Guard's Silk Handwraps", "" },
        { 22883, "INV_Pants_11", "=q3=Legionnaire's Silk Legguards", "" },
	    { 22860, "INV_Boots_05", "=q3=Blood Guard's Silk Walkers", "" },
	    };

	PVPPriest = {
        { 0, "INV_BannerPVP_02", "=q6=#pvpea4#", "=q5=#pvps1#" },
        { 17602, "INV_Helmet_24", "=q4=Field Marshal's Headdress", "" },
	    { 17604, "INV_Shoulder_02", "=q4=Field Marshal's Satin Mantle", "" },
        { 17605, "INV_Chest_Cloth_02", "=q4=Field Marshal's Satin Vestments", "" },
        { 17608, "INV_Gauntlets_14", "=q4=Marshal's Satin Gloves", "" },
        { 17603, "INV_Pants_06", "=q4=Marshal's Satin Pants", "" },
	    { 17607, "INV_Boots_07", "=q4=Marshal's Satin Sandals", "" },
        { 0, "", "", "" },
	    { 0, "INV_BannerPVP_02", "=q6=#pvpra4#", "=q5=#pvps2#" },
	    { 23316, "INV_Helmet_17", "=q3=Lieutenant Commander's Satin Hood", "" },
        { 23317, "INV_Shoulder_01", "=q3=Lieutenant Commander's Satin Mantle", "" },
        { 23303, "INV_Chest_Leather_01", "=q3=Knight-Captain's Satin Tunic", "" },
        { 23288, "INV_Gauntlets_17", "=q3=Knight-Lieutenant's Satin Handwraps", "" },
        { 23302, "INV_Pants_11", "=q3=Knight-Captain's Satin Legguards", "" },
        { 23289, "INV_Boots_05", "=q3=Knight-Lieutenant's Satin Walkers", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvpeh4#", "=q5=#pvps1#" },
        { 17623, "INV_Helmet_08", "=q4=Warlord's Satin Cowl", "" },
	    { 17622, "INV_Shoulder_19", "=q4=Warlord's Satin Mantle", "" },
        { 17624, "INV_Chest_Leather_01", "=q4=Warlord's Satin Robes", "" },
        { 17620, "INV_Gauntlets_27", "=q4=General's Satin Gloves", "" },
        { 17625, "INV_Pants_07", "=q4=General's Satin Leggings", "" },
	    { 17618, "INV_Boots_05", "=q4=General's Satin Boots", "" },
        { 0, "", "", "" },
	    { 0, "INV_BannerPVP_01", "=q6=#pvprh4#", "=q5=#pvps2#" },
	    { 23261, "INV_Helmet_17", "=q3=Champion's Satin Hood", "" },
        { 23262, "INV_Shoulder_01", "=q3=Champion's Satin Mantle", "" },
        { 22885, "INV_Chest_Leather_01", "=q3=Legionnaire's Satin Tunic", "" },
        { 22869, "INV_Gauntlets_17", "=q3=Blood Guard's Satin Handwraps", "" },
        { 22882, "INV_Pants_11", "=q3=Legionnaire's Satin Legguards", "" },
        { 22859, "INV_Boots_05", "=q3=Blood Guard's Satin Walkers", "" },
        };

    PVPWarlock = {
        { 0, "INV_BannerPVP_02", "=q6=#pvpea7#", "=q5=#pvps1#" },
        { 17578, "INV_Helmet_24", "=q4=Field Marshal's Coronal", "" },
        { 17580, "INV_Shoulder_02", "=q4=Field Marshal's Dreadweave Shoulders", "" },
        { 17581, "INV_Chest_Cloth_09", "=q4=Field Marshal's Dreadweave Robe", "" },
	    { 17584, "INV_Gauntlets_14", "=q4=Marshal's Dreadweave Gloves", "" },
	    { 17579, "INV_Pants_Cloth_09", "=q4=Marshal's Dreadweave Leggings", "" },
        { 17583, "INV_Boots_07", "=q4=Marshal's Dreadweave Boots", "" },
        { 0, "", "", "" },
	    { 0, "INV_BannerPVP_02", "=q6=#pvpra7#", "=q5=#pvps2#" },
        { 23310, "INV_Helmet_08", "=q3=Lieutenant Commander's Dreadweave Cowl", "" },
        { 23311, "INV_Shoulder_01", "=q3=Lieutenant Commander's Dreadweave Spaulders", "" },
        { 23297, "INV_Chest_Leather_01", "=q3=Knight-Captain's Dreadweave Tunic", "" },
        { 23282, "INV_Gauntlets_19", "=q3=Knight-Lieutenant's Dreadweave Handwraps", "" },
        { 23296, "INV_Pants_06", "=q3=Knight-Captain's Dreadweave Legguards", "" },
        { 23283, "INV_Boots_05", "=q3=Knight-Lieutenant's Dreadweave Walkers", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvpeh7#", "=q5=#pvps1#" },
        { 17591, "INV_Helmet_08", "=q4=Warlord's Dreadweave Hood", "" },
        { 17590, "INV_Shoulder_19", "=q4=Warlord's Dreadweave Mantle", "" },
        { 17592, "INV_Chest_Leather_01", "=q4=Warlord's Dreadweave Robe", "" },
	    { 17588, "INV_Gauntlets_19", "=q4=General's Dreadweave Gloves", "" },
	    { 17593, "INV_Pants_07", "=q4=General's Dreadweave Pants", "" },
        { 17586, "INV_Boots_05", "=q4=General's Dreadweave Boots", "" },
        { 0, "", "", "" },
	    { 0, "INV_BannerPVP_01", "=q6=#pvprh7#", "=q5=#pvps2#" },
        { 23255, "INV_Helmet_08", "=q3=Champion's Dreadweave Cowl", "" },
        { 23256, "INV_Shoulder_01", "=q3=Champion's Dreadweave Spaulders", "" },
        { 22884, "INV_Chest_Leather_01", "=q3=Legionnaire's Dreadweave Tunic", "" },
        { 22865, "INV_Gauntlets_19", "=q3=Blood Guard's Dreadweave Handwraps", "" },
        { 22881, "INV_Pants_06", "=q3=Legionnaire's Dreadweave Legguards", "" },
        { 22855, "INV_Boots_05", "=q3=Blood Guard's Dreadweave Walkers", "" },
        };

    PVPRogue = {
        { 0, "INV_BannerPVP_02", "=q6=#pvpea5#", "=q5=#pvps1#" },
        { 16455, "INV_Helmet_41", "=q4=Field Marshal's Leather Mask", "" },
        { 16457, "INV_Shoulder_23", "=q4=Field Marshal's Leather Epaulets", "" },
        { 16453, "INV_Chest_Cloth_07", "=q4=Field Marshal's Leather Chestpiece", "" },
	    { 16454, "INV_Gauntlets_21", "=q4=Marshal's Leather Handgrips", "" },
        { 16456, "INV_Pants_06", "=q4=Marshal's Leather Leggings", "" },
	    { 16446, "INV_Boots_08", "=q4=Marshal's Leather Footguards", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_02", "=q6=#pvpra5#", "=q5=#pvps2#" },
        { 23312, "INV_Helmet_09", "=q3=Lieutenant Commander's Leather Helm", "" },
        { 23313, "INV_Shoulder_14", "=q3=Lieutenant Commander's Leather Shoulders", "" },
        { 23298, "INV_Chest_Leather_05", "=q3=Knight-Captain's Leather Chestpiece", "" },
        { 23284, "INV_Gauntlets_15", "=q3=Knight-Lieutenant's Leather Grips", "" },
        { 23299, "INV_Pants_08", "=q3=Knight-Captain's Leather Legguards", "" },
        { 23285, "INV_Boots_05", "=q3=Knight-Lieutenant's Leather Walkers", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvpeh5#", "=q5=#pvps1#" },
        { 16561, "INV_Helmet_09", "=q4=Warlord's Leather Helm", "" },
        { 16562, "INV_Shoulder_07", "=q4=Warlord's Leather Spaulders", "" },
        { 16563, "INV_Chest_Chain_16", "=q4=Warlord's Leather Breastplate", "" },
	    { 16560, "INV_Gauntlets_25", "=q4=General's Leather Mitts", "" },
        { 16564, "INV_Pants_06", "=q4=General's Leather Legguards", "" },
	    { 16558, "INV_Boots_08", "=q4=General's Leather Treads", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvprh5#", "=q5=#pvps2#" },
        { 23257, "INV_Helmet_09", "=q3=Champion's Leather Helm", "" },
        { 23258, "INV_Shoulder_14", "=q3=Champion's Leather Shoulders", "" },
        { 22879, "INV_Chest_Leather_05", "=q3=Legionnaire's Leather Chestpiece", "" },
        { 22864, "INV_Gauntlets_15", "=q3=Blood Guard's Leather Grips", "" },
        { 22880, "INV_Pants_08", "=q3=Legionnaire's Leather Legguards", "" },
        { 22856, "INV_Boots_05", "=q3=Blood Guard's Leather Walkers", "" },
	    };

	PVPDruid = {
        { 0, "INV_BannerPVP_02", "=q6=#pvpea1#", "=q5=#pvps1#" },
        { 16451, "INV_Helmet_41", "=q4=Field Marshal's Dragonhide Helmet", "" },
        { 16449, "INV_Shoulder_23", "=q4=Field Marshal's Dragonhide Spaulders", "" },
        { 16452, "INV_Chest_Cloth_07", "=q4=Field Marshal's Dragonhide Breastplate", "" },
	    { 16448, "INV_Gauntlets_21", "=q4=Marshal's Dragonhide Gauntlets", "" },
	    { 16450, "INV_Pants_06", "=q4=Marshal's Dragonhide Legguards", "" },
        { 16459, "INV_Boots_08", "=q4=Marshal's Dragonhide Boots", "" },
        { 0, "", "", "" },
	    { 0, "INV_BannerPVP_02", "=q6=#pvpra1#", "=q5=#pvps2#" },
        { 23308, "INV_Helmet_09", "=q3=Lieutenant Commander's Dragonhide Headguard", "" },
        { 23309, "INV_Shoulder_07", "=q3=Lieutenant Commander's Dragonhide Shoulders", "" },
        { 23294, "INV_Chest_Leather_07", "=q3=Knight-Captain's Dragonhide Chestpiece", "" },
        { 23280, "INV_Gauntlets_25", "=q3=Knight-Lieutenant's Dragonhide Grips", "" },
        { 23295, "INV_Pants_06", "=q3=Knight-Captain's Dragonhide Leggings", "" },
        { 23281, "INV_Boots_08", "=q3=Knight-Lieutenant's Dragonhide Treads", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvpeh1#", "=q5=#pvps1#" },
        { 16550, "INV_Helmet_09", "=q4=Warlord's Dragonhide Helmet", "" },
        { 16551, "INV_Shoulder_07", "=q4=Warlord's Dragonhide Epaulets", "" },
        { 16549, "INV_Chest_Chain_16", "=q4=Warlord's Dragonhide Hauberk", "" },
	    { 16555, "INV_Gauntlets_25", "=q4=General's Dragonhide Gloves", "" },
	    { 16552, "INV_Pants_06", "=q4=General's Dragonhide Leggings", "" },
        { 16554, "INV_Boots_08", "=q4=General's Dragonhide Boots", "" },
        { 0, "", "", "" },
	    { 0, "INV_BannerPVP_01", "=q6=#pvprh1#", "=q5=#pvps2#" },
        { 23253, "INV_Helmet_09", "=q3=Champion's Dragonhide Headguard", "" },
        { 23254, "INV_Shoulder_07", "=q3=Champion's Dragonhide Shoulders", "" },
        { 22877, "INV_Chest_Leather_07", "=q3=Legionnaire's Dragonhide Chestpiece", "" },
        { 22863, "INV_Gauntlets_25", "=q3=Blood Guard's Dragonhide Grips", "" },
        { 22878, "INV_Pants_06", "=q3=Legionnaire's Dragonhide Leggings", "" },
        { 22852, "INV_Boots_08", "=q3=Blood Guard's Dragonhide Treads", "" },
        };

    PVPShaman = {
        { 0, "INV_BannerPVP_01", "=q6=#pvpeh6#", "=q5=#pvps1#" },
        { 16578, "INV_Helmet_09", "=q4=Warlord's Mail Helm", "" },
        { 16580, "INV_Shoulder_29", "=q4=Warlord's Mail Spaulders", "" },
        { 16577, "INV_Chest_Chain_11", "=q4=Warlord's Mail Armor", "" },
	    { 16574, "INV_Gauntlets_11", "=q4=General's Mail Gauntlets", "" },
	    { 16579, "INV_Pants_Mail_15", "=q4=General's Mail Leggings", "" },
        { 16573, "INV_Boots_Plate_06", "=q4=General's Mail Boots", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvprh6#", "=q5=#pvps2#" },
        { 23259, "INV_Helmet_09", "=q3=Champion's Mail Headguard", "" },
        { 23260, "INV_Shoulder_04", "=q3=Champion's Mail Pauldrons", "" },
        { 22876, "INV_Chest_Chain_16", "=q3=Legionnaire's Mail Hauberk", "" },
        { 22867, "INV_Gauntlets_11", "=q3=Blood Guard's Mail Vices", "" },
        { 22887, "INV_Pants_09", "=q3=Legionnaire's Mail Legguards", "" },
        { 22857,"INV_Boots_07","=q3=Blood Guard's Mail Greaves","" },
        };
        
    PVPWarrior = {
        { 0, "INV_BannerPVP_02", "=q6=#pvpea8#", "=q5=#pvps1#" },
        { 16478, "INV_Helmet_05", "=q4=Field Marshal's Plate Helm", "" },
        { 16480, "INV_Shoulder_20", "=q4=Field Marshal's Plate Shoulderguards", "" },
        { 16477, "INV_Chest_Plate03", "=q4=Field Marshal's Plate Armor", "" },
	    { 16484, "INV_Gauntlets_29", "=q4=Marshal's Plate Gauntlets", "" },
	    { 16479, "INV_Pants_04", "=q4=Marshal's Plate Legguards", "" },
        { 16483, "INV_Boots_Plate_09", "=q4=Marshal's Plate Boots", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_02", "=q6=#pvpra8#", "=q5=#pvps2#" },
        { 23314, "INV_Helmet_09", "=q3=Lieutenant Commander's Plate Helm", "" },
        { 23315, "INV_Shoulder_11", "=q3=Lieutenant Commander's Plate Shoulders", "" },
        { 23300, "INV_Chest_Plate16", "=q3=Knight-Captain's Plate Hauberk", "" },
        { 23286, "INV_Gauntlets_26", "=q3=Knight-Lieutenant's Plate Gauntlets", "" },
        { 23301, "INV_Pants_06", "=q3=Knight-Captain's Plate Leggings", "" },
        { 23287, "INV_Boots_Plate_09", "=q3=Knight-Lieutenant's Plate Greaves", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvpeh8#", "=q5=#pvps1#" },
        { 16542, "INV_Helmet_09", "=q4=Warlord's Plate Headpiece", "" },
        { 16544, "INV_Shoulder_11", "=q4=Warlord's Plate Shoulders", "" },
        { 16541, "INV_Chest_Plate16", "=q4=Warlord's Plate Armor", "" },
	    { 16548, "INV_Gauntlets_10", "=q4=General's Plate Gauntlets", "" },
	    { 16543, "INV_Pants_04", "=q4=General's Plate Leggings", "" },
        { 16545, "INV_Boots_Plate_04", "=q4=General's Plate Boots", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_01", "=q6=#pvprh8#", "=q5=#pvps2#" },
        { 23244, "INV_Helmet_09", "=q3=Champion's Plate Helm", "" },
        { 23243, "INV_Shoulder_11", "=q3=Champion's Plate Shoulders", "" },
        { 22872, "INV_Chest_Plate16", "=q3=Legionnaire's Plate Hauberk", "" },
        { 22868, "INV_Gauntlets_26", "=q3=Blood Guard's Plate Gauntlets", "" },
        { 22873, "INV_Pants_06", "=q3=Legionnaire's Plate Leggings", "" },
        { 22858, "INV_Boots_Plate_09", "=q3=Blood Guard's Plate Greaves", "" },
	    };

	PVPPaladin = {
        { 0, "INV_BannerPVP_02", "=q6=#pvpea4#", "=q5=#pvps1#" },
        { 16474, "INV_Helmet_05", "=q4=Field Marshal's Lamellar Faceguard", "" },
	    { 16476, "INV_Shoulder_20", "=q4=Field Marshal's Lamellar Pauldrons", "" },
	    { 16473, "INV_Chest_Plate03", "=q4=Field Marshal's Lamellar Chestplate", "" },
	    { 16471, "INV_Gauntlets_29", "=q4=Marshal's Lamellar Gloves", "" },
	    { 16475, "INV_Pants_04", "=q4=Marshal's Lamellar Legplates", "" },
        { 16472, "INV_Boots_Plate_09", "=q4=Marshal's Lamellar Boots", "" },
        { 0, "", "", "" },
	    { 0, "INV_BannerPVP_02", "=q6=#pvpra4#", "=q5=#pvps2#" },
        { 23276, "INV_Helmet_05", "=q3=Lieutenant Commander's Lamellar Headguard", "" },
	    { 23277, "INV_Shoulder_28", "=q3=Lieutenant Commander's Lamellar Shoulders", "" },
	    { 23272, "INV_Chest_Plate03", "=q3=Knight-Captain's Lamellar Breastplate", "" },
        { 23274, "INV_Gauntlets_29", "=q3=Knight-Lieutenant's Lamellar Gauntlets", "" },
	    { 23273, "INV_Pants_06", "=q3=Knight-Captain's Lamellar Leggings", "" },
	    { 23275, "INV_Boots_Plate_03", "=q3=Knight-Lieutenant's Lamellar Sabatons", "" },
	    };
        
    PVPWeapons1 = {
        { 0, "INV_BannerPVP_02", "=q6=#m7#", "" },
        { 18827, "INV_Axe_24", "=q4=Grand Marshal's Handaxe", "=ds=#h1# #w1#" },
        { 18830, "INV_Axe_10", "=q4=Grand Marshal's Sunderer", "=ds=#h2# #w1#" },
        { 18838, "INV_Weapon_ShortBlade_26", "=q4=Grand Marshal's Dirk", "=ds=#h1# #w4#" },
        { 23451, "INV_Weapon_ShortBlade_26", "=q4=Grand Marshal's Mageblade", "=ds=#h1# #w4#" },
        { 18847, "Ability_Rogue_Rupture", "=q4=Grand Marshal's Left Hand Blade", "=ds=#h4# #w13#" },
        { 18843, "INV_Weapon_ShortBlade_07", "=q4=Grand Marshal's Right Hand Blade", "=ds=#h3# #w13#" },
        { 18865, "INV_Mace_13", "=q4=Grand Marshal's Punisher", "=ds=#h1# #w6#" },
        { 23454, "INV_Hammer_02", "=q4=Grand Marshal's Warhammer", "=ds=#h1# #w6#" },
        { 23455, "INV_Hammer_23", "=q4=Grand Marshal's Demolisher", "=ds=#h2# #w6#" },
        { 18867, "INV_Hammer_03", "=q4=Grand Marshal's Battle Hammer", "=ds=#h2# #w6#" },
        { 18869, "INV_Spear_08", "=q4=Grand Marshal's Glaive", "=ds=#w7#" },
        { 18873, "INV_Staff_14", "=q4=Grand Marshal's Stave", "=ds=#w9#" },
        { 12584, "INV_Sword_11", "=q4=Grand Marshal's Longsword", "=ds=#h1# #w10#" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_01", "=q6=#m6#", "" },
        { 18828, "INV_Axe_02", "=q4=High Warlord's Cleaver", "=ds=#h1# #w1#" },
        { 18831, "INV_Axe_21", "=q4=High Warlord's Battle Axe", "=ds=#h2# #w1#" },
        { 18840, "INV_Weapon_ShortBlade_13", "=q4=High Warlord's Razor", "=ds=#h1# #w4#" },
        { 23466, "INV_Weapon_ShortBlade_26", "=q4=High Warlord's Spellblade", "=ds=#h1# #w4#" },
        { 18848, "INV_Misc_MonsterClaw_04", "=q4=High Warlord's Left Claw", "=ds=#h4# #w13#" },
        { 18844, "INV_Misc_MonsterClaw_03", "=q4=High Warlord's Right Claw", "=ds=#h3# #w13#" },
        { 18866, "INV_Hammer_20", "=q4=High Warlord's Bludgeon", "=ds=#h1# #w6#" },
        { 23464, "INV_Hammer_02", "=q4=High Warlord's Battle Mace", "=ds=#h1# #w6#" },
        { 23465, "INV_Mace_09", "=q4=High Warlord's Destroyer", "=ds=#h2# #w6#" },
        { 18868, "INV_Hammer_10", "=q4=High Warlord's Pulverizer", "=ds=#h2# #w6#" },
        { 18871, "INV_Spear_01", "=q4=High Warlord's Pig Sticker", "=ds=#w7#" },
        { 18874, "INV_Misc_Bone_ElfSkull_01", "=q4=High Warlord's War Staff", "=ds=#w9#" },
        { 16345, "INV_Sword_11", "=q4=High Warlord's Blade", "=ds=#h1# #w10#" },
        { 0, "", "", "" },
        };
        
    PVPWeapons2 = {
        { 0, "INV_BannerPVP_02", "=q6=#m7#", "" },
        { 23456, "INV_Sword_05", "=q4=Grand Marshal's Swiftblade", "=ds=#h1# #w10#" },
        { 18876, "INV_Sword_39", "=q4=Grand Marshal's Claymore", "=ds=#h2# #w10#" },
        { 18833, "INV_Weapon_Bow_12", "=q4=Grand Marshal's Bullseye", "=ds=#w2#" },
        { 18836, "INV_Weapon_Crossbow_04", "=q4=Grand Marshal's Repeater", "=ds=#w3#" },
        { 18855, "INV_Weapon_Rifle_08", "=q4=Grand Marshal's Hand Cannon", "=ds=#w5#" },
        { 18825, "INV_Shield_05", "=q4=Grand Marshal's Aegis", "=ds=#w8#" },
        { 23452, "INV_Misc_Book_12", "=q4=Grand Marshal's Tome of Power", "=ds=#s15#" },
        { 23453, "INV_Misc_Book_13", "=q4=Grand Marshal's Tome of Restoration", "=ds=#s15#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_01", "=q6=#m6#", "" },
        { 23467, "INV_Sword_05", "=q4=High Warlord's Quickblade", "=ds=#h1# #w10#" },
        { 18877, "INV_Sword_48", "=q4=High Warlord's Greatsword", "=ds=#h2# #w10#" },
        { 18835, "INV_Weapon_Bow_08", "=q4=High Warlord's Recurve", "=ds=#w2#" },
        { 18837, "INV_Weapon_Crossbow_10", "=q4=High Warlord's Crossbow", "=ds=#w3#" },
        { 18860, "INV_Weapon_Rifle_06", "=q4=High Warlord's Street Sweeper", "=ds=#w5#" },
        { 18826, "INV_Shield_19", "=q4=High Warlord's Shield Wall", "=ds=#w8#" },
        { 23468, "INV_Misc_Book_15", "=q4=High Warlord's Tome of Destruction", "=ds=#s15#" },
        { 23469, "INV_Misc_Book_14", "=q4=High Warlord's Tome of Mending", "=ds=#s15#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        };
    };
    