
-- ************************************* Const / defines *************************************

TITAN_SOULSHARDSCOUNTER_ITEMNAME = "Soul Shard";
TITAN_SOULSHARDSCOUNTER_BUTTON_LABEL = TITAN_SOULSHARDSCOUNTER_ITEMNAME..": ";
TITAN_SOULSHARDSCOUNTER_TOOLTIP_COUNT = TITAN_SOULSHARDSCOUNTER_ITEMNAME..": ";
TITAN_SOULSHARDSCOUNTER_TOOLTIPTEXT= "Current count of "..TITAN_SOULSHARDSCOUNTER_ITEMNAME;
TITAN_SOULSHARDSCOUNTER_MENU_TEXT = "Warlock: "..TITAN_SOULSHARDSCOUNTER_ITEMNAME;
TITAN_SOULSHARDSCOUNTER_WARN_LOW = "Warn when low";
TITAN_SOULSHARDSCOUNTER_WARN_TIMER = "Warning timer";
TITAN_SOULSHARDSCOUNTER_WARN_LIST = { "10 sec", "20 sec", "30 sec", "1 min", "2 min", "3 min", "None" }
TITAN_SOULSHARDSCOUNTER_WARN_COUNT = "Minimum count";

--if ( GetLocale() == "deDE" ) then
--	TITAN_SOULSHARDSCOUNTER_ITEMNAME = "???";
--	TITAN_SOULSHARDSSCOUNTER_BUTTON_LABEL = TITAN_SOULSHARDSCOUNTER_ITEMNAME..": ";
--	TITAN_SOULSHARDSCOUNTER_TOOLTIP_COUNT = TITAN_SOULSHARDSCOUNTER_ITEMNAME..": ";
--	TITAN_SOULSHARDSCOUNTER_TOOLTIPTEXT= "Aktuelle Anzahl von"..TITAN_SOULSHARDSCOUNTER_ITEMNAME;
--	TITAN_SOULSHARDSCOUNTER_MENU_TEXT = "???Warlock: "..TITAN_SOULSHARDSCOUNTER_ITEMNAME;
--	TITAN_SOULSHARDSCOUNTER_WARN_LOW = "???Warn when low";
--	TITAN_SOULSHARDSCOUNTER_WARN_TEXT = "???Warning Timer";
--  TITAN_SOULSHARDSCOUNTER_WARN_LIST = { "10 sek", "20 sek", "30 sek", "1 min", "2 min", "3 min", "Kein" }
--  TITAN_SOULSHARDSCOUNTER_WARN_COUNT = "???Minimum count";
--end

--if ( GetLocale() == "frFR" ) then
--	TITAN_SOULSHARDSCOUNTER_ITEMNAME = "???";
--	TITAN_SOULSHARDSCOUNTER_BUTTON_LABEL = TITAN_SOULSHARDSCOUNTER_ITEMNAME..": ";
--	TITAN_SOULSHARDSCOUNTER_TOOLTIP_COUNT = TITAN_SOULSHARDSCOUNTER_ITEMNAME..": ";
--	TITAN_SOULSHARDSCOUNTER_TOOLTIPTEXT= "Compte courant de "..TITAN_SOULSHARDSCOUNTER_ITEMNAME;
--	TITAN_SOULSHARDSCOUNTER_MENU_TEXT = "???Warlock: "..TITAN_SOULSHARDSCOUNTER_ITEMNAME;
--	TITAN_SOULSHARDSCOUNTER_WARN_LOW = "???Warn when low";
--	TITAN_SOULSHARDSCOUNTER_WARN_TEXT = "???Warning timer";
--  TITAN_SOULSHARDSCOUNTER_WARN_LIST = { "10 sec", "20 sec", "30 sec", "1 min", "2 min", "3 min", "Aucune" }
--  TITAN_SOULSHARDSCOUNTER_WARN_COUNT = "???Minimum count";
--end