if (GetLocale() == "frFR") then
	-- Buttons and Titles
	PERL_LOCALIZED_CONFIG_ALL = "Tous";
	PERL_LOCALIZED_CONFIG_ARCANEBAR = "ArcaneBar";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY = "CombatDisplay";
	PERL_LOCALIZED_CONFIG_PARTY = "Party";
	PERL_LOCALIZED_CONFIG_PARTYPET = "Party Pet";
	PERL_LOCALIZED_CONFIG_PARTYTARGET = "Party Target";
	PERL_LOCALIZED_CONFIG_PLAYER = "Player";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF = "Player Buff";
	PERL_LOCALIZED_CONFIG_PLAYERPET = "Player Pet";
	PERL_LOCALIZED_CONFIG_RAID = "Raid";
	PERL_LOCALIZED_CONFIG_TARGET = "Target";
	PERL_LOCALIZED_CONFIG_TARGETTARGET = "Target Target";
	PERL_LOCALIZED_CONFIG_THIRDPARTY = "Third Party";

	-- Perl Config Shared Strings
	PERL_LOCALIZED_CONFIG_TRANSPARENCY = "Transparence";
	PERL_LOCALIZED_CONFIG_SCALING = "\195\137chelle";
	PERL_LOCALIZED_CONFIG_SCALING_SET_CURRENT = "R\195\169gler A l\'\195\169chelle Actuelle de UI";
	PERL_LOCALIZED_CONFIG_MISC = "Divers";
	PERL_LOCALIZED_CONFIG_DISPLAY_MODE = "Mode d\'affichage";
	PERL_LOCALIZED_CONFIG_DRUIDBAR = "Druid Bar Support";
	PERL_LOCALIZED_CONFIG_MOBHEALTH = "MobHealth Support";
	PERL_LOCALIZED_CONFIG_FIVESEC = "FiveSec Support";
	PERL_LOCALIZED_CONFIG_RESET_FRAMES = "R.A.Z les positions des Cadres";
	PERL_LOCALIZED_CONFIG_PORTRAITS = "Afficher Portrait";
	PERL_LOCALIZED_CONFIG_THREED_PORTRAITS = " Portrait 3D";
	PERL_LOCALIZED_CONFIG_ALWAYS_SHOWN = "Toujours montrer";
	PERL_LOCALIZED_CONFIG_HIDDEN_IN_RAID = "Cacher en Raid";
	PERL_LOCALIZED_CONFIG_ALWAYS_HIDDEN = "Toujours cacher";
	PERL_LOCALIZED_CONFIG_BUFF_LOCATION = "Buff Emplacement";
	PERL_LOCALIZED_CONFIG_DEBUFF_LOCATION = "Debuff Emplacement";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_SMALL = "Buff Taille (12 de base)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_SMALL = "Debuff Taille (12 de base)";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_LARGE = "Buff Taille (16 de base)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_LARGE = "Debuff Taille (16 de base)";
	PERL_LOCALIZED_CONFIG_BUFF_NUMBER = "# de Buffs";
	PERL_LOCALIZED_CONFIG_DEBUFF_NUMBER = "# de Debuffs";
	PERL_LOCALIZED_CONFIG_COMBAT_TEXT = "Combat Text";
	PERL_LOCALIZED_CONFIG_COMPACT = "Compact Mode";
	PERL_LOCALIZED_CONFIG_DISPLAY_PERCENTS = "Afficher les '%'";
	PERL_LOCALIZED_CONFIG_SHORT_BARS = "Barres courtes";
	PERL_LOCALIZED_CONFIG_VERTICAL_FRAMES = "Cadres Vertical";
	PERL_LOCALIZED_CONFIG_HIDE_CLASSICON_FRAME = "Cacher l\'ic\195\180ne de classe";
	PERL_LOCALIZED_CONFIG_HEALER_MODE = "Healeur Mode";
	PERL_LOCALIZED_CONFIG_PET_SUPPORT = "Montrer la Barre du familier";
	PERL_LOCALIZED_CONFIG_CLASS_BUFFDEBUFF = " Buffs/Debuffs de Classes";
	PERL_LOCALIZED_CONFIG_CLASS_COLORED_NAMES = "Nom color\195\169\n selon la classe";
	PERL_LOCALIZED_CONFIG_PVP_RANK_ICON = "JcJ classement icon";
	PERL_LOCALIZED_CONFIG_SMALL = "petit";
	PERL_LOCALIZED_CONFIG_BIG = "grand";
	PERL_LOCALIZED_CONFIG_HIDE_POWER_BARS = "Cacher la barre\n de pouvoir";
	PERL_LOCALIZED_CONFIG_DISPLAY_MANA_DEFICIT = "Display Mana Deficit"
	PERL_LOCALIZED_CONFIG_PVP_STATUS_ICON = "Icon PvP";
	PERL_LOCALIZED_CONFIG_SHOW_BAR_VALUES = "Show Bar Values";
	PERL_LOCALIZED_CONFIG_INVERT_BAR_VALUES = "Invert Bar Values";

	-- Perl Config Generic
	PERL_LOCALIZED_CONFIG_HEADER = "Perl Config";
	PERL_LOCALIZED_CONFIG_CLOSE = "Fermer";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED = "Non Installer";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED_EXPLANATION = "Le mod demand\195\169 n\'est pas install\195\169 ou pas charg\195\169.";	

	-- Perl Config All
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BARS = "Texturer les Barres";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_ONE = "Texture #1";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_TWO = "Texture #2";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_THREE = "Texture #3";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FOUR = "Texture #4";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FIVE = "Texture #5";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_SIX = "Texture #6";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_NONE = "Pas de Texture";
	PERL_LOCALIZED_CONFIG_ALL_MINIMAP_POSITION = "MiniMap Boutton Position";
	PERL_LOCALIZED_CONFIG_ALL_SHOW_MINIMAP = "Montrer MiniMap Boutton";
	PERL_LOCALIZED_CONFIG_ALL_FRAMES = "Cadres";
	PERL_LOCALIZED_CONFIG_ALL_TRANSPARENT_BACKGROUND = "Fond du cadre transparent";
	PERL_LOCALIZED_CONFIG_ALL_LOCK_ALL = "Verrouiller tous cadres";
	PERL_LOCALIZED_CONFIG_ALL_UNLOCK_ALL = "D\195\169verrouiller tous cadres";
	PERL_LOCALIZED_CONFIG_ALL_LOAD = "Charger les Configs Globaux";
	PERL_LOCALIZED_CONFIG_ALL_SAVE = "Sauvegarder les Configs Globaux";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Configs Globaux Charg\195\169.";
	PERL_LOCALIZED_CONFIG_ALL_SAVE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Configs Globaux Sauv\195\169.";
	PERL_LOCALIZED_CONFIG_ALL_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Les positions des cadres ont été R.A.Z. ";
	PERL_LOCALIZED_CONFIG_ALL_CLICKHEALING = "CastParty/Genesis/AceHeal/ClickHeal Support";
	PERL_LOCALIZED_CONFIG_ALL_PROGRESSIVE = "La Barre de Sant\195\169 progressivement Color\195\169e";
	PERL_LOCALIZED_CONFIG_ALL_NO_PROFILE_SELECTED_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": No profile was selected.";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Profile Settings Loaded: ";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_HEADER = "Profile To Load";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_BUTTON = "Load";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_BUTTON = "Delete";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": The following profile has been removed from the list: ";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BACKGROUND = "Textured Background Bar";
	PERL_LOCALIZED_CONFIG_ALL_FADE_BARS = "Fade Status Bars";
	PERL_LOCALIZED_CONFIG_ALL_CLICKCASTABLE_NAME_FRAMES = "Make Name Frames Click Castable";

	-- Perl Config ArcaneBar
	PERL_LOCALIZED_CONFIG_ARCANEBAR_ENABLE = "Activer ArcaneBar";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_DISPLAY_TIMER = "Afficher le Temps d\'incantation";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_HIDE_BLIZZARD = "Cacher la Barre de Blizzard";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_REPLACE_NAME = "Remplace votre nom par le nom du sort";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_LEFT_TIMER = "Left Align Cast Timer";

	-- Perl Config CombatDisplay
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_PERSIST_MODES = "Persist Modes";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_TARGET_SETTINGS = "Cible Configs";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_AUTOATTACK = "w/ Auto Attaque";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ONAGRO = "En combat";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_HEALTH_PERSIST = "Health Persistance";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MANA_PERSIST = "Mana Persistance";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MENU = "Menu au Clic-Droit";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_LOCK = "V\195\169rrouiller "..PERL_LOCALIZED_CONFIG_COMBATDISPLAY.." Cadres";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ENABLE_TARGET = "Activer le cadre de la cible";

	-- Perl Config Party
	PERL_LOCALIZED_CONFIG_PARTY_SPACING = "Espace (80 par d\195\169faut)";
	PERL_LOCALIZED_CONFIG_PARTY_FKEYS = "Afficher F Keys";
	PERL_LOCALIZED_CONFIG_PARTY_LOCK = "V\195\169rrouiller "..PERL_LOCALIZED_CONFIG_PARTY.." Cadre";

	-- Perl Config Party Pet
	PERL_LOCALIZED_CONFIG_PARTYPET_ENABLE = "Activer "..PERL_LOCALIZED_CONFIG_PARTYPET.." Cadres";
	PERL_LOCALIZED_CONFIG_PARTYPET_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": "..PERL_LOCALIZED_CONFIG_PARTYPET.." Les Positions des cadres ont été R.A.Z. ";
	PERL_LOCALIZED_CONFIG_PARTYPET_LOCK = "V\195\169rrouiller "..PERL_LOCALIZED_CONFIG_PARTYPET.." Cadre";

	-- Perl Config Party Target
	PERL_LOCALIZED_CONFIG_PARTYTARGET_ENABLE = "Activer "..PERL_LOCALIZED_CONFIG_PARTYTARGET.." Cadres";
	PERL_LOCALIZED_CONFIG_PARTYTARGET_LOCK = "V\195\169rrouiller "..PERL_LOCALIZED_CONFIG_PARTYTARGET.." Cadre";

	-- Perl Config Player
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_MODE = "Exp\195\169rience Barre Mode";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_EXPERIENCE = "Exp\195\169rience";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_PVPRANK = "Classement JcJ";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_REPUTATION = "R\195\169putation";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_HIDDEN = "Cach\195\169";
	PERL_LOCALIZED_CONFIG_PLAYER_RAID_GROUP = "Montrer le Nombre du groupe en Raid";
	PERL_LOCALIZED_CONFIG_PLAYER_LOCK = "V\195\169rrouiller "..PERL_LOCALIZED_CONFIG_PLAYER.." Cadre";

	-- Perl Config Player Buff
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_ENABLE = "Activer les PlayerBuffs";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_WARNING = "Activer les alertes quand il ne reste que 30sec";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HIDESECONDS = "Hide Seconds";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HORIZONTAL_SPACING = "Horizontal Spacing (10 is default)";

	-- Perl Config Player Pet
	PERL_LOCALIZED_CONFIG_PLAYERPET_EXPERIENCE = "activer la barre d\'exp\195\169rience";
	PERL_LOCALIZED_CONFIG_PLAYERPET_LOCK = "V\195\169rrouiller "..PERL_LOCALIZED_CONFIG_PLAYERPET.." Cadre";

	-- Perl Config Raid
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SETTINGS = "Groupe Configs";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_ONE = "Afficher Groupe 1 (Guerrier)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_TWO = "Afficher Groupe 2 (Mage)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_THREE = "Afficher Groupe 3 (Pr\195\170tre)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_FOUR = "Afficher Groupe 4 (D\195\169moniste)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_FIVE = "Afficher Groupe 5 (Druide)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SIX = "Afficher Groupe 6 (Voleur)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SEVEN = "Afficher Groupe 7 (Chasseur)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_EIGHT = "Afficher Groupe 8 (Paladin)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_NINE = "Afficher Groupe 9 (Chaman)";
	PERL_LOCALIZED_CONFIG_RAID_SORT_BY_CLASS = "Trier Par Classe";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_GROUP_HEADERS = "Afficher l\'en-tetes\n des Groupes";
	PERL_LOCALIZED_CONFIG_RAID_LOCK = "V\195\169rrouiller \n"..PERL_LOCALIZED_CONFIG_RAID.." Cadre";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_ALL = "Montrer Tous Groupes";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_ALL = "Cacher Tous Groupes";
	PERL_LOCALIZED_CONFIG_RAID_CONNECT_FRAMES = "Connect Cadres";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_HEALTH_PERCENTAGES = "Montrer Vie '%'";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_MANA_PERCENTAGES = "Montrer Mana '%'";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_MISSING_HEALTH = "Montrer la Vie Manquante";
	PERL_LOCALIZED_CONFIG_RAID_INVERT_FRAMES = "Inverser les Cadres";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_BUFFS = "Montrer les Buffs";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_DEBUFFS = "Montrer les Debuffs";
	PERL_LOCALIZED_CONFIG_RAID_COLOR_DEBUFF_NAMES = "Colorer les Noms des Debuff";
	PERL_LOCALIZED_CONFIG_RAID_ALTERNATE_FRAME_STYLE = "Cadre alternatif";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_BORDER = "Cacher les Bords";
	PERL_LOCALIZED_CONFIG_RAID_REMOVE_SPACE = "Supprimer l\'espace";
	PERL_LOCALIZED_CONFIG_RAID_TOOLTIP = "CTRA Style Tooltip";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_EMPTY_HEADERS = "Hide Empty Group Headers";

	-- Perl Config Target
	PERL_LOCALIZED_CONFIG_TARGET_BUFFDEBUFF_SCALING = "Buff/Debuff \195\169chelle (100 par d\195\169faut)";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_LOCATION = "Combo Position";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_ICON = "Icon de Classe";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_CIVILIAN_FRAMES = "Classe/Civil Cadres";
	PERL_LOCALIZED_CONFIG_TARGET_RARE_ELITE_FRAME = "Rare/Elite Cadres";
	PERL_LOCALIZED_CONFIG_TARGET_HIDE_BUFFDEBUFF_BACKGROUND = "Cacher le Fond des Buffs";
	PERL_LOCALIZED_CONFIG_TARGET_SOUND_ON_TARGET_CHANGE = "Son quand la Cible Change";
	PERL_LOCALIZED_CONFIG_TARGET_LOCK = "V\195\169rrouiller "..PERL_LOCALIZED_CONFIG_TARGET.." Cadre";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_POINT_FRAME = "Point de Combo Cadre";
	PERL_LOCALIZED_CONFIG_TARGET_DISPLAY_IN_NAME_FRAME = "Afficher dans \n le Carde du Nom";
	PERL_LOCALIZED_CONFIG_TARGET_DEBUFF_STACKS_IN_COMBO_FRAME = "Enpiler les Debuff \n dans le Combo Cadre";
	PERL_LOCALIZED_CONFIG_TARGET_ALTERNATE_FRAME_STYLE = "Cadre alternatif";
	PERL_LOCALIZED_CONFIG_TARGET_INVERT_BUFFS_DEBUFFS = "Invert Buffs/Debuffs";

	-- Perl Config Target Target
	PERL_LOCALIZED_CONFIG_TARGETTARGET_MAIN = "Main";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_MODE = "Alerte Mode";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_SIZE = " Taille de l\'Alert ";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOT = "Activer Cible de Cible";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOTOT = "Activer Cible de Cible de Cible";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_AUDIO_ALERT_ON_AGRO = "Audio Aggro Alerte";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LOCK = "V\195\169rrouiller "..PERL_LOCALIZED_CONFIG_TARGETTARGET.." Cadres";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_BUFFS = "Montrer CdC Buffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_DEBUFFS = "Montrer CdC Debuffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_BUFFS = "Montrer CdCdC Buffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_DEBUFFS = "Montrer CdCdC Debuffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_DPS_MODE = "DPS Mode";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TANK_MODE = "Tank Mode";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_HEALER_MODE = "Healeur Mode";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SMALL_TEXT = "Petit Texte";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LARGE_TEXT = "Grand Texte";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_NO_TEXT = "Pas Texte";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OF_TARGET_FRAME = "Droite du Cadre de la Cible";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OF_TARGET_FRAME = "Haut du Cadre de la Cible";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Le Cadres de la Cible de la Cible a \195\169t\195\169 \"Align\195\169 \195\160 Droite\".";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Le Cadres de la Cible de la Cible a \195\169t\195\169 \"Align\195\169 en Haut\".";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_FRIENDLY_HEALTH = "Show Friendly Health Values";
end