if (GetLocale() == "esES") then
	-- Buttons and Titles
	PERL_LOCALIZED_CONFIG_ALL = "Todo";
	PERL_LOCALIZED_CONFIG_ARCANEBAR = "ArcaneBar";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY = "Vis. Combate";
	PERL_LOCALIZED_CONFIG_PARTY = "Grupo";
	PERL_LOCALIZED_CONFIG_PARTYPET = "Mascota Grupo";
	PERL_LOCALIZED_CONFIG_PARTYTARGET = "Objetivo Grupo";
	PERL_LOCALIZED_CONFIG_PLAYER = "Jugador";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF = "Player Buff";
	PERL_LOCALIZED_CONFIG_PLAYERPET = "Mascota Jugador";
	PERL_LOCALIZED_CONFIG_RAID = "Banda";
	PERL_LOCALIZED_CONFIG_TARGET = "Objetivo";
	PERL_LOCALIZED_CONFIG_TARGETTARGET = "Objetivo Objetivo";
	PERL_LOCALIZED_CONFIG_THIRDPARTY = "Third Party";

	-- Perl Config Shared Strings
	PERL_LOCALIZED_CONFIG_TRANSPARENCY = "Transparencia";
	PERL_LOCALIZED_CONFIG_SCALING = "Escalado";
	PERL_LOCALIZED_CONFIG_SCALING_SET_CURRENT = "Usar el Escalado UI Actual";
	PERL_LOCALIZED_CONFIG_MISC = "Misc";
	PERL_LOCALIZED_CONFIG_DISPLAY_MODE = "Modo de Visualizaci\195\179n";
	PERL_LOCALIZED_CONFIG_DRUIDBAR = "Soporte Druid Bar";
	PERL_LOCALIZED_CONFIG_MOBHEALTH = "Soporte MobHealth";
	PERL_LOCALIZED_CONFIG_FIVESEC = "Soporte FiveSec";
	PERL_LOCALIZED_CONFIG_RESET_FRAMES = "Reiniciar Pos. de Ventanas";
	PERL_LOCALIZED_CONFIG_PORTRAITS = "Mostrar Retrato";
	PERL_LOCALIZED_CONFIG_THREED_PORTRAITS = "Retrato en 3D";
	PERL_LOCALIZED_CONFIG_ALWAYS_SHOWN = "Mostrar Siempre";
	PERL_LOCALIZED_CONFIG_HIDDEN_IN_RAID = "Escondidas en Banda";
	PERL_LOCALIZED_CONFIG_ALWAYS_HIDDEN = "Siempre Escondidas";
	PERL_LOCALIZED_CONFIG_BUFF_LOCATION = "Pos. Ventajas";
	PERL_LOCALIZED_CONFIG_DEBUFF_LOCATION = "Pos. Desventajas";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_SMALL = "Tam. Ventaja (12 defecto)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_SMALL = "Tam. Desventaja (12 defecto)";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_LARGE = "Tama\195\177o Ventaja (16 defecto)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_LARGE = "Tama\195\177o Desventaja (16 defecto)";
	PERL_LOCALIZED_CONFIG_BUFF_NUMBER = "# de Ventajas";
	PERL_LOCALIZED_CONFIG_DEBUFF_NUMBER = "# de Desventajas";
	PERL_LOCALIZED_CONFIG_COMBAT_TEXT = "Texto de Combate";
	PERL_LOCALIZED_CONFIG_COMPACT = "Modo Compacto";
	PERL_LOCALIZED_CONFIG_DISPLAY_PERCENTS = "Mostrar Porcentajes";
	PERL_LOCALIZED_CONFIG_SHORT_BARS = "Barras Cortas";
	PERL_LOCALIZED_CONFIG_VERTICAL_FRAMES = "Ventanas Verticales";
	PERL_LOCALIZED_CONFIG_HIDE_CLASSICON_FRAME = "Esconder Icono de Clase";
	PERL_LOCALIZED_CONFIG_HEALER_MODE = "Modo Curandero";
	PERL_LOCALIZED_CONFIG_PET_SUPPORT = "Mostrar Barras de Mascotas";
	PERL_LOCALIZED_CONFIG_CLASS_BUFFDEBUFF = "Vent/Desven de Clase";
	PERL_LOCALIZED_CONFIG_CLASS_COLORED_NAMES = "Colorear Nom. por Clase";
	PERL_LOCALIZED_CONFIG_PVP_RANK_ICON = "Icono Clasificaci\195\179n JcJ";
	PERL_LOCALIZED_CONFIG_SMALL = "Peque\195\177o";
	PERL_LOCALIZED_CONFIG_BIG = "Grande";
	PERL_LOCALIZED_CONFIG_HIDE_POWER_BARS = "Esconder Barras Mana";
	PERL_LOCALIZED_CONFIG_DISPLAY_MANA_DEFICIT = "Mostrar Deficit Mana"
	PERL_LOCALIZED_CONFIG_PVP_STATUS_ICON = "Icono Estado JcJ";
	PERL_LOCALIZED_CONFIG_SHOW_BAR_VALUES = "Mostrar Valores en la Barra";
	PERL_LOCALIZED_CONFIG_INVERT_BAR_VALUES = "Invert Bar Values";

	-- Perl Config Generic
	PERL_LOCALIZED_CONFIG_HEADER = "Perl Config";
	PERL_LOCALIZED_CONFIG_CLOSE = "Cerrar";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED = "No Instalado";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED_EXPLANATION = "El mod que se necesita no est\195\161 instalado o activado.";

	-- Perl Config All
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BARS = "Texturizar Barras";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_ONE = "Textura #1";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_TWO = "Textura #2";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_THREE = "Textura #3";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FOUR = "Textura #4";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FIVE = "Textura #5";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_SIX = "Textura #6";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_NONE = "Sin Textura";
	PERL_LOCALIZED_CONFIG_ALL_MINIMAP_POSITION = "Posici\195\179n del Bot\195\179n del MiniMapa";
	PERL_LOCALIZED_CONFIG_ALL_SHOW_MINIMAP = "Mostrar Bot\195\179n en el Minimapa";
	PERL_LOCALIZED_CONFIG_ALL_FRAMES = "Ventanas";
	PERL_LOCALIZED_CONFIG_ALL_TRANSPARENT_BACKGROUND = "Fondo de Ventana Transparente";
	PERL_LOCALIZED_CONFIG_ALL_LOCK_ALL = "Bloquear Todas Ventanas";
	PERL_LOCALIZED_CONFIG_ALL_UNLOCK_ALL = "Desbloquear Todas Ventanas";
	PERL_LOCALIZED_CONFIG_ALL_LOAD = "Cargar Config Global";
	PERL_LOCALIZED_CONFIG_ALL_SAVE = "Guardar Config Global";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Par\195\161metros de Configuraci\195\179n Global Cargados.";
	PERL_LOCALIZED_CONFIG_ALL_SAVE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Par\195\161metros de Configuraci\195\179n Global Guardados.";
	PERL_LOCALIZED_CONFIG_ALL_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Posiciones de las Ventanas Restauradas.";
	PERL_LOCALIZED_CONFIG_ALL_CLICKHEALING = "Soporte CastParty/Genesis/AceHeal/ClickHeal";
	PERL_LOCALIZED_CONFIG_ALL_PROGRESSIVE = "Barras de Vida Coloreadas Progresivamente";
	PERL_LOCALIZED_CONFIG_ALL_NO_PROFILE_SELECTED_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": No se seleccion\195\179 ning\195\186n perfil.";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Par\195\161metros del Perfil Cargados: ";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_HEADER = "Perfil a Cargar";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_BUTTON = "Cargar";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_BUTTON = "Borrar";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": El siguiente perfil ha sido eliminado de la lista: ";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BACKGROUND = "Textured Background Bar";
	PERL_LOCALIZED_CONFIG_ALL_FADE_BARS = "Fade Status Bars";
	PERL_LOCALIZED_CONFIG_ALL_CLICKCASTABLE_NAME_FRAMES = "Make Name Frames Click Castable";

	-- Perl Config ArcaneBar
	PERL_LOCALIZED_CONFIG_ARCANEBAR_ENABLE = "Activar "..PERL_LOCALIZED_CONFIG_ARCANEBAR;
	PERL_LOCALIZED_CONFIG_ARCANEBAR_DISPLAY_TIMER = "Mostrar Tiempo de Lanzamiento";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_HIDE_BLIZZARD = "Esconder la Barra de Lanzamiento de Blizzard";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_REPLACE_NAME = "Replace Player Name With Spell Name";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_LEFT_TIMER = "Left Align Cast Timer";

	-- Perl Config CombatDisplay
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_PERSIST_MODES = "Modos Persistentes";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_TARGET_SETTINGS = "Par\195\161metros del Objetivo";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_AUTOATTACK = "Al Autoatacar";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ONAGRO = "Siendo un Objetivo";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_HEALTH_PERSIST = "Persistencia Vida";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MANA_PERSIST = "Persistencia Mana";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MENU = "Men\195\186 con Clic Derecho";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_LOCK = "Bloquear Ventanas "..PERL_LOCALIZED_CONFIG_COMBATDISPLAY;
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ENABLE_TARGET = "Activar Ventana de Objetivo";

	-- Perl Config Party
	PERL_LOCALIZED_CONFIG_PARTY_SPACING = "Espacio (80 por defecto)";
	PERL_LOCALIZED_CONFIG_PARTY_FKEYS = "Mostrar Teclas F";
	PERL_LOCALIZED_CONFIG_PARTY_LOCK = "Bloquear Ventanas "..PERL_LOCALIZED_CONFIG_PARTY;

	-- Perl Config Party Pet
	PERL_LOCALIZED_CONFIG_PARTYPET_ENABLE = "Activar Ventanas de "..PERL_LOCALIZED_CONFIG_PARTYPET;
	PERL_LOCALIZED_CONFIG_PARTYPET_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": La Posici\195\179n de las Ventanas de "..PERL_LOCALIZED_CONFIG_PARTYPET.." se han restaurado.";
	PERL_LOCALIZED_CONFIG_PARTYPET_LOCK = "Bloquear Ventanas "..PERL_LOCALIZED_CONFIG_PARTYPET;

	-- Perl Config Party Target
	PERL_LOCALIZED_CONFIG_PARTYTARGET_ENABLE = "Activar Ventanas de "..PERL_LOCALIZED_CONFIG_PARTYTARGET;
	PERL_LOCALIZED_CONFIG_PARTYTARGET_LOCK = "Bloquear Ventanas "..PERL_LOCALIZED_CONFIG_PARTYTARGET;

	-- Perl Config Player
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_MODE = "Modo Barra Experiencia";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_EXPERIENCE = "Experiencia";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_PVPRANK = "Rango JcJ";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_REPUTATION = "Reputaci\195\179n";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_HIDDEN = "Escondida";
	PERL_LOCALIZED_CONFIG_PLAYER_RAID_GROUP = "Mostrar N\195\186mero del Grupo de Banda";
	PERL_LOCALIZED_CONFIG_PLAYER_LOCK = "Bloquear Ventana de "..PERL_LOCALIZED_CONFIG_PLAYER;

	-- Perl Config Player Buff
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_ENABLE = "Enable Player Frame Buffs";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_WARNING = "Enable 30 Second Spell Warning Messages";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HIDESECONDS = "Hide Seconds";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HORIZONTAL_SPACING = "Horizontal Spacing (10 is default)";

	-- Perl Config Player Pet
	PERL_LOCALIZED_CONFIG_PLAYERPET_EXPERIENCE = "Activar Barra de Experiencia";
	PERL_LOCALIZED_CONFIG_PLAYERPET_LOCK = "Bloquear Ventana de "..PERL_LOCALIZED_CONFIG_PLAYERPET;

	-- Perl Config Raid
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SETTINGS = "Par\195\161metros de Grupo";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_ONE = "Mostrar Grupo 1 (Guerrero)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_TWO = "Mostrar Grupo 2 (Mago)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_THREE = "Mostrar Grupo 3 (Sacerdote)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_FOUR = "Mostrar Grupo 4 (Brujo)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_FIVE = "Mostrar Grupo 5 (Druida)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SIX = "Mostrar Grupo 6 (Pícaro)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SEVEN = "Mostrar Grupo 7 (Cazador)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_EIGHT = "Mostrar Grupo 8 (Paladín)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_NINE = "Mostrar Grupo 9 (Cham\195\161n)";
	PERL_LOCALIZED_CONFIG_RAID_SORT_BY_CLASS = "Ordenar Por Clase";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_GROUP_HEADERS = "Mostrar Signos de Grupo";
	PERL_LOCALIZED_CONFIG_RAID_LOCK = "Bloquear Ventanas "..PERL_LOCALIZED_CONFIG_RAID;
	PERL_LOCALIZED_CONFIG_RAID_SHOW_ALL = "Mostrar Todos los Grupos";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_ALL = "Esconder Todos Los Grupos";
	PERL_LOCALIZED_CONFIG_RAID_CONNECT_FRAMES = "Conectar Ventanas";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_HEALTH_PERCENTAGES = "Mostrar Porcentajes de Vida";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_MANA_PERCENTAGES = "Mostrar Porcentajes de Man\195\161";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_MISSING_HEALTH = "Mostrar Vida Consumida";
	PERL_LOCALIZED_CONFIG_RAID_INVERT_FRAMES = "Invertir Ventanas";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_BUFFS = "Mostrar Ventajas";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_DEBUFFS = "Mostrar Desventajas";
	PERL_LOCALIZED_CONFIG_RAID_COLOR_DEBUFF_NAMES = "Colorear Nombres de Desventajas";
	PERL_LOCALIZED_CONFIG_RAID_ALTERNATE_FRAME_STYLE = "Estilo de Ventana Alternativo";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_BORDER = "Esconder Bordes";
	PERL_LOCALIZED_CONFIG_RAID_REMOVE_SPACE = "Eliminar Espacio";
	PERL_LOCALIZED_CONFIG_RAID_TOOLTIP = "Tooltips Estilo CTRA";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_EMPTY_HEADERS = "Esconder Signos de Grupos Vacíos";

	-- Perl Config Target
	PERL_LOCALIZED_CONFIG_TARGET_BUFFDEBUFF_SCALING = "Escala Ven./Desven. (100 defecto)";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_LOCATION = "Posici\195\179n Combo";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_ICON = "Icono de Clase";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_CIVILIAN_FRAMES = "Ventana Clase/Civil";
	PERL_LOCALIZED_CONFIG_TARGET_RARE_ELITE_FRAME = "Ventana Raro/\195\137lite";
	PERL_LOCALIZED_CONFIG_TARGET_HIDE_BUFFDEBUFF_BACKGROUND = "Esconder Fondo Ventajas/Desvent.";
	PERL_LOCALIZED_CONFIG_TARGET_SOUND_ON_TARGET_CHANGE = "Sonido en Cambio de Objetivo";
	PERL_LOCALIZED_CONFIG_TARGET_LOCK = "Bloquear Ventana de "..PERL_LOCALIZED_CONFIG_TARGET;
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_POINT_FRAME = "Ventana de Puntos de Combo";
	PERL_LOCALIZED_CONFIG_TARGET_DISPLAY_IN_NAME_FRAME = "Mostrar en Ventana de Nombre";
	PERL_LOCALIZED_CONFIG_TARGET_DEBUFF_STACKS_IN_COMBO_FRAME = "Desvent. Acumulan en Combo";
	PERL_LOCALIZED_CONFIG_TARGET_ALTERNATE_FRAME_STYLE = "Estilo Ventana Alternativo";
	PERL_LOCALIZED_CONFIG_TARGET_INVERT_BUFFS_DEBUFFS = "Invertir Ventajas/Desventajas";

	-- Perl Config Target Target
	PERL_LOCALIZED_CONFIG_TARGETTARGET_MAIN = "Principal";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_MODE = "Modo Alerta";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_SIZE = "Tama\195\177o Alerta";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOT = "Activar Objetivo de Objetivo";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOTOT = "Activar Objetivo de Objetivo de Objetivo";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_AUDIO_ALERT_ON_AGRO = "Alertar al Ser Objetivo";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LOCK = "Bloquear Ventanas "..PERL_LOCALIZED_CONFIG_TARGETTARGET;
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_BUFFS = "Mostrar Ventajas de OdO";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_DEBUFFS = "Mostrar Desventajas de OdO";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_BUFFS = "Mostrar Ventajas de OdOdO";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_DEBUFFS = "Mostrar Desventajas de OdOdO";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_DPS_MODE = "Modo DPS";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TANK_MODE = "Modo Tanque";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_HEALER_MODE = "Modo Curandero";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SMALL_TEXT = "Texto Peque\195\177o";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LARGE_TEXT = "Texto Grande";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_NO_TEXT = "Sin Texto";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OF_TARGET_FRAME = "Derecha Ventana Objetivo";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OF_TARGET_FRAME = "Arriba Ventana Objetivo";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Se han alineado a la Derecha las Ventanas de Objetivo de Objetivo.";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Se han alineado Arriba las Ventanas de Objetivo de Objetivo.";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_FRIENDLY_HEALTH = "Mostrar Valores de Vida Amigables";
end