if (GetLocale() == "deDE") then
	-- Buttons and Titles
	PERL_LOCALIZED_CONFIG_ALL = "Alle";
	PERL_LOCALIZED_CONFIG_ARCANEBAR = "ArcaneBar";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY = "CombatDisplay";
	PERL_LOCALIZED_CONFIG_PARTY = "Gruppe";
	PERL_LOCALIZED_CONFIG_PARTYPET = "Gruppen Pet";
	PERL_LOCALIZED_CONFIG_PARTYTARGET = "Gruppen Target";
	PERL_LOCALIZED_CONFIG_PLAYER = "Spieler";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF = "Spieler Buff";
	PERL_LOCALIZED_CONFIG_PLAYERPET = "Spieler Pet";
	PERL_LOCALIZED_CONFIG_RAID = "Raid";
	PERL_LOCALIZED_CONFIG_TARGET = "Target";
	PERL_LOCALIZED_CONFIG_TARGETTARGET = "Target Target";
	PERL_LOCALIZED_CONFIG_THIRDPARTY = "Third Party";

	-- Perl Config Shared Strings
	PERL_LOCALIZED_CONFIG_TRANSPARENCY = "Transparenz";
	PERL_LOCALIZED_CONFIG_SCALING = "Skalierung";
	PERL_LOCALIZED_CONFIG_SCALING_SET_CURRENT = "Zur momentanen UI-Skalierung setzen";
	PERL_LOCALIZED_CONFIG_MISC = "Sonstiges";
	PERL_LOCALIZED_CONFIG_DISPLAY_MODE = "Anzeigemodus";
	PERL_LOCALIZED_CONFIG_DRUIDBAR = "Druid Bar Unterst\195\188tzung";
	PERL_LOCALIZED_CONFIG_MOBHEALTH = "MobHealth Unterst\195\188tzung";
	PERL_LOCALIZED_CONFIG_FIVESEC = "FiveSec Unterst\195\188tzung";
	PERL_LOCALIZED_CONFIG_RESET_FRAMES = "Positionen zur\195\188cksetzen";
	PERL_LOCALIZED_CONFIG_PORTRAITS = "Zeige Portr\195\164t Frames";
	PERL_LOCALIZED_CONFIG_THREED_PORTRAITS = "3D Portr\195\164t Frames";
	PERL_LOCALIZED_CONFIG_ALWAYS_SHOWN = "Immer anzeigen";
	PERL_LOCALIZED_CONFIG_HIDDEN_IN_RAID = "In Raids verstecken";
	PERL_LOCALIZED_CONFIG_ALWAYS_HIDDEN = "Immer verstecken";
	PERL_LOCALIZED_CONFIG_BUFF_LOCATION = "Buff Position";
	PERL_LOCALIZED_CONFIG_DEBUFF_LOCATION = "Debuff Position";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_SMALL = "Buff Gr\195\182\195\159e (12 ist standard)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_SMALL = "Debuff Gr\195\182\195\159e (12 ist standard)";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_LARGE = "Buff Gr\195\182\195\159e (16 ist standard)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_LARGE = "Debuff Gr\195\182\195\159e (16 ist standard)";
	PERL_LOCALIZED_CONFIG_BUFF_NUMBER = "# der Buffs";
	PERL_LOCALIZED_CONFIG_DEBUFF_NUMBER = "# der Debuffs";
	PERL_LOCALIZED_CONFIG_COMBAT_TEXT = "Kampftext";
	PERL_LOCALIZED_CONFIG_COMPACT = "Kompakter Modus";
	PERL_LOCALIZED_CONFIG_DISPLAY_PERCENTS = "Zeige Prozente";
	PERL_LOCALIZED_CONFIG_SHORT_BARS = "Kurze Leisten";
	PERL_LOCALIZED_CONFIG_VERTICAL_FRAMES = "Vertikale Frames";
	PERL_LOCALIZED_CONFIG_HIDE_CLASSICON_FRAME = "Verstecke Klassen Icon Frame";
	PERL_LOCALIZED_CONFIG_HEALER_MODE = "Heiler Modus";
	PERL_LOCALIZED_CONFIG_PET_SUPPORT = "Zeige Pet Leisten";
	PERL_LOCALIZED_CONFIG_CLASS_BUFFDEBUFF = "Klassen Buffs/Debuffs";
	PERL_LOCALIZED_CONFIG_CLASS_COLORED_NAMES = "Klassen farbige Namen";
	PERL_LOCALIZED_CONFIG_PVP_RANK_ICON = "PvP Rang Icon";
	PERL_LOCALIZED_CONFIG_SMALL = "Klein";
	PERL_LOCALIZED_CONFIG_BIG = "Gro\195\159";
	PERL_LOCALIZED_CONFIG_HIDE_POWER_BARS = "Verstecke Power Leisten";
	PERL_LOCALIZED_CONFIG_DISPLAY_MANA_DEFICIT = "Display Mana Deficit"
	PERL_LOCALIZED_CONFIG_PVP_STATUS_ICON = "PvP Status Icon";
	PERL_LOCALIZED_CONFIG_SHOW_BAR_VALUES = "Show Bar Values";
	PERL_LOCALIZED_CONFIG_INVERT_BAR_VALUES = "Invert Bar Values";

	-- Perl Config Generic
	PERL_LOCALIZED_CONFIG_HEADER = "Perl Einstellungen";
	PERL_LOCALIZED_CONFIG_CLOSE = "Schlie\195\159en";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED = "Nicht installiert";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED_EXPLANATION = "Dieses Addon ist nicht installiert oder aktiviert.";

	-- Perl Config All
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BARS = "Strukturierte Leisten";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_ONE = "Textur #1";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_TWO = "Textur #2";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_THREE = "Textur #3";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FOUR = "Textur #4";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FIVE = "Textur #5";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_SIX = "Textur #6";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_NONE = "Keine Textur";
	PERL_LOCALIZED_CONFIG_ALL_MINIMAP_POSITION = "MiniMap Button Position";
	PERL_LOCALIZED_CONFIG_ALL_SHOW_MINIMAP = "Zeige MiniMap Button";
	PERL_LOCALIZED_CONFIG_ALL_FRAMES = "Frames";
	PERL_LOCALIZED_CONFIG_ALL_TRANSPARENT_BACKGROUND = "Transparenter Hintergrund";
	PERL_LOCALIZED_CONFIG_ALL_LOCK_ALL = "Alle Frames fixieren";
	PERL_LOCALIZED_CONFIG_ALL_UNLOCK_ALL = "Alle Frames freigeben";
	PERL_LOCALIZED_CONFIG_ALL_LOAD = "Einstellungen laden";
	PERL_LOCALIZED_CONFIG_ALL_SAVE = "Einstellungen speichern";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Einstellungen geladen.";
	PERL_LOCALIZED_CONFIG_ALL_SAVE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Einstellungen gespeichert.";
	PERL_LOCALIZED_CONFIG_ALL_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Frame Positionen wurde zur\195\188ckgesetzt.";
	PERL_LOCALIZED_CONFIG_ALL_CLICKHEALING = "CastParty/Genesis/AceHeal/ClickHeal Unterst\195\188tzung";
	PERL_LOCALIZED_CONFIG_ALL_PROGRESSIVE = "Farbige Gesundheitsleisten";
	PERL_LOCALIZED_CONFIG_ALL_NO_PROFILE_SELECTED_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": No profile was selected.";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Profile Settings Loaded: ";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_HEADER = "Profile To Load";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_BUTTON = "Load";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_BUTTON = "Delete";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": The following profile has been removed from the list: ";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BACKGROUND = "Textured Background Bar";
	PERL_LOCALIZED_CONFIG_ALL_FADE_BARS = "Fade Status Bars";
	PERL_LOCALIZED_CONFIG_ALL_CLICKCASTABLE_NAME_FRAMES = "Make Name Frames Click Castable";

	-- Perl Config ArcaneBar
	PERL_LOCALIZED_CONFIG_ARCANEBAR_ENABLE = "Aktiviere "..PERL_LOCALIZED_CONFIG_ARCANEBAR;
	PERL_LOCALIZED_CONFIG_ARCANEBAR_DISPLAY_TIMER = "Zeige Zauber-Timer";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_HIDE_BLIZZARD = "Verstecke Blizzard Zauberleiste";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_REPLACE_NAME = "Replace Player Name With Spell Name";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_LEFT_TIMER = "Left Align Cast Timer";

	-- Perl Config CombatDisplay
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_PERSIST_MODES = "Persist Modus";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_TARGET_SETTINGS = "Target Einstellungen";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_AUTOATTACK = "w/ Auto Angriff";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ONAGRO = "Bei Aggro";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_HEALTH_PERSIST = "Gesundheits Persistance";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MANA_PERSIST = "Mana Persistance";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MENU = "Rechts-Klick f195\188r das Men\195\188";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_LOCK = PERL_LOCALIZED_CONFIG_COMBATDISPLAY.." Frame fixieren";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ENABLE_TARGET = "Aktiviere Target Frame";

	-- Perl Config Party
	PERL_LOCALIZED_CONFIG_PARTY_SPACING = "Leerstellen (80 ist standard)";
	PERL_LOCALIZED_CONFIG_PARTY_FKEYS = "Zeige F Tasten";
	PERL_LOCALIZED_CONFIG_PARTY_LOCK = PERL_LOCALIZED_CONFIG_PARTY.." Frame fixieren";

	-- Perl Config Party Pet
	PERL_LOCALIZED_CONFIG_PARTYPET_ENABLE = "Aktiviere "..PERL_LOCALIZED_CONFIG_PARTYPET.." Frames";
	PERL_LOCALIZED_CONFIG_PARTYPET_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": "..PERL_LOCALIZED_CONFIG_PARTYPET.." Frame Positionen wurden zur\195\188ckgesetzt.";
	PERL_LOCALIZED_CONFIG_PARTYPET_LOCK = PERL_LOCALIZED_CONFIG_PARTYPET.." Frame fixieren";

	-- Perl Config Party Target
	PERL_LOCALIZED_CONFIG_PARTYTARGET_ENABLE = "Aktiviere "..PERL_LOCALIZED_CONFIG_PARTYTARGET.." Frames";
	PERL_LOCALIZED_CONFIG_PARTYTARGET_LOCK = PERL_LOCALIZED_CONFIG_PARTYTARGET.." Frame fixieren";

	-- Perl Config Player
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_MODE = "Erfahrungsleisten Modus";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_EXPERIENCE = "Erfahrung";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_PVPRANK = "PvP Rang";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_REPUTATION = "Ruf";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_HIDDEN = "Versteckt";
	PERL_LOCALIZED_CONFIG_PLAYER_RAID_GROUP = "Zeige Raid Gruppennummer";
	PERL_LOCALIZED_CONFIG_PLAYER_LOCK = PERL_LOCALIZED_CONFIG_PLAYER.." Frame fixieren";

	-- Perl Config Player Buff
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_ENABLE = "Enable Player Frame Buffs";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_WARNING = "Enable 30 Second Spell Warning Messages";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HIDESECONDS = "Hide Seconds";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HORIZONTAL_SPACING = "Horizontal Spacing (10 is default)";

	-- Perl Config Player Pet
	PERL_LOCALIZED_CONFIG_PLAYERPET_EXPERIENCE = "Aktiviere Erfahrungsleiste";
	PERL_LOCALIZED_CONFIG_PLAYERPET_LOCK = PERL_LOCALIZED_CONFIG_PLAYERPET.." Frame fixieren";

	-- Perl Config Raid
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SETTINGS = "Gruppen Einstellungen";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_ONE = "Zeige Gruppe 1 (Krieger)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_TWO = "Zeige Gruppe 2 (Magier)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_THREE = "Zeige Gruppe 3 (Priester)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_FOUR = "Zeige Gruppe 4 (Hexenmeister)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_FIVE = "Zeige Gruppe 5 (Druide)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SIX = "Zeige Gruppe 6 (Schurke)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SEVEN = "Zeige Gruppe 7 (J\195\164ger)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_EIGHT = "Zeige Gruppe 8 (Paladin)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_NINE = "Zeige Gruppe 9 (Schamane)";
	PERL_LOCALIZED_CONFIG_RAID_SORT_BY_CLASS = "Nach Klasse sortieren";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_GROUP_HEADERS = "Zeige Gruppen Headers";
	PERL_LOCALIZED_CONFIG_RAID_LOCK = PERL_LOCALIZED_CONFIG_RAID.." Frame fixieren";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_ALL = "Zeige alle Gruppen";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_ALL = "Verstecke alle Gruppen";
	PERL_LOCALIZED_CONFIG_RAID_CONNECT_FRAMES = "Verbinde Frames";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_HEALTH_PERCENTAGES = "Zeige Gesundheit Prozente";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_MANA_PERCENTAGES = "Zeige Mana Prozente";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_MISSING_HEALTH = "Zeige fehlende Gesundheit";
	PERL_LOCALIZED_CONFIG_RAID_INVERT_FRAMES = "Frames umkehren";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_BUFFS = "Zeige Buffs";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_DEBUFFS = "Zeige Debuffs";
	PERL_LOCALIZED_CONFIG_RAID_COLOR_DEBUFF_NAMES = "Farbige Debuff Namen";
	PERL_LOCALIZED_CONFIG_RAID_ALTERNATE_FRAME_STYLE = "Alternativer Frame Style";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_BORDER = "Verstecke Rahmen";
	PERL_LOCALIZED_CONFIG_RAID_REMOVE_SPACE = "Entferne Leerstellen";
	PERL_LOCALIZED_CONFIG_RAID_TOOLTIP = "CTRA Style Tooltip";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_EMPTY_HEADERS = "Hide Empty Group Headers";

	-- Perl Config Target
	PERL_LOCALIZED_CONFIG_TARGET_BUFFDEBUFF_SCALING = "Buff/Debuff Skalierung (100 ist standard)";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_LOCATION = "Combo Position";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_ICON = "Klassen Icon";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_CIVILIAN_FRAMES = "Klasse/Zivilist Frames";
	PERL_LOCALIZED_CONFIG_TARGET_RARE_ELITE_FRAME = "Rar/Elite Frame";
	PERL_LOCALIZED_CONFIG_TARGET_HIDE_BUFFDEBUFF_BACKGROUND = "Verstecke Buff/Debuff Hintergrund";
	PERL_LOCALIZED_CONFIG_TARGET_SOUND_ON_TARGET_CHANGE = "Sound bei Target-Wechsel";
	PERL_LOCALIZED_CONFIG_TARGET_LOCK = PERL_LOCALIZED_CONFIG_TARGET.." Frame fixieren";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_POINT_FRAME = "Combo Punkte Frame";
	PERL_LOCALIZED_CONFIG_TARGET_DISPLAY_IN_NAME_FRAME = "Zeige im Namen Frame";
	PERL_LOCALIZED_CONFIG_TARGET_DEBUFF_STACKS_IN_COMBO_FRAME = "Debuff stapelt in Combo Frame";
	PERL_LOCALIZED_CONFIG_TARGET_ALTERNATE_FRAME_STYLE = "Alternativer Frame Style";
	PERL_LOCALIZED_CONFIG_TARGET_INVERT_BUFFS_DEBUFFS = "Invert Buffs/Debuffs";

	-- Perl Config Target Target
	PERL_LOCALIZED_CONFIG_TARGETTARGET_MAIN = "Main";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_MODE = "Alarm-Modus";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_SIZE = "Alarm Gr\195\182\195\159e";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOT = "Aktiviere Target of Target";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOTOT = "Aktiviere Target of Target of Target";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_AUDIO_ALERT_ON_AGRO = "Audio-Alarm bei Aggro";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LOCK = PERL_LOCALIZED_CONFIG_TARGETTARGET.." Frame fixieren";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_BUFFS = "Zeige ToT Buffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_DEBUFFS = "Zeige ToT Debuffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_BUFFS = "Zeige ToToT Buffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_DEBUFFS = "Zeige ToToT Debuffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_DPS_MODE = "DPS Modus";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TANK_MODE = "Tank Modus";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_HEALER_MODE = "Heiler Modus";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SMALL_TEXT = "Kleiner Text";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LARGE_TEXT = "Gro\195\159er Text";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_NO_TEXT = "Kein Text";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OF_TARGET_FRAME = "Rechts vom Target Frame";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OF_TARGET_FRAME = "\195\156ber dem Target Frame";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Target of Target Frames wurden 'Rechts verbunden'.";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": Target of Target Frames wurden 'Oben verbunden'.";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_FRIENDLY_HEALTH = "Show Friendly Health Values";
end