if (GetLocale() == "zhCN") then
	-- Buttons and Titles
	PERL_LOCALIZED_CONFIG_ALL = "全局设定";
	PERL_LOCALIZED_CONFIG_ARCANEBAR = "施法条";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY = "战斗状态条";
	PERL_LOCALIZED_CONFIG_PARTY = "队伍信息";
	PERL_LOCALIZED_CONFIG_PARTYPET = "队伍宠物";
	PERL_LOCALIZED_CONFIG_PARTYTARGET = "队伍目标";
	PERL_LOCALIZED_CONFIG_PLAYER = "玩家信息";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF = "玩家增益";
	PERL_LOCALIZED_CONFIG_PLAYERPET = "玩家宠物";
	PERL_LOCALIZED_CONFIG_RAID = "团队信息";
	PERL_LOCALIZED_CONFIG_TARGET = "目标信息";
	PERL_LOCALIZED_CONFIG_TARGETTARGET = "目标的目标";
	PERL_LOCALIZED_CONFIG_THIRDPARTY = "第三方插件";

	-- Perl Config Shared Strings
	PERL_LOCALIZED_CONFIG_TRANSPARENCY = "透明度";
	PERL_LOCALIZED_CONFIG_SCALING = "缩放比例";
	PERL_LOCALIZED_CONFIG_SCALING_SET_CURRENT = "设定为当前UI的缩放比例";
	PERL_LOCALIZED_CONFIG_MISC = "其他设置";
	PERL_LOCALIZED_CONFIG_DISPLAY_MODE = "显示模式";
	PERL_LOCALIZED_CONFIG_DRUIDBAR = "支持Druid Bar插件";
	PERL_LOCALIZED_CONFIG_MOBHEALTH = "支持MobHealth插件";
	PERL_LOCALIZED_CONFIG_FIVESEC = "支持FiveSec插件";
	PERL_LOCALIZED_CONFIG_RESET_FRAMES = "重设所有框体";
	PERL_LOCALIZED_CONFIG_PORTRAITS = "显示人物头像";
	PERL_LOCALIZED_CONFIG_THREED_PORTRAITS = "显示3D人物头像";
	PERL_LOCALIZED_CONFIG_ALWAYS_SHOWN = "始终显示";
	PERL_LOCALIZED_CONFIG_HIDDEN_IN_RAID = "在团队是隐藏";
	PERL_LOCALIZED_CONFIG_ALWAYS_HIDDEN = "始终隐藏";
	PERL_LOCALIZED_CONFIG_BUFF_LOCATION = "Buff 位置";
	PERL_LOCALIZED_CONFIG_DEBUFF_LOCATION = "Debuff 位置";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_SMALL = "Buff 大小 (预设为12)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_SMALL = "Debuff 大小 (预设为12)";
	PERL_LOCALIZED_CONFIG_BUFF_SIZE_LARGE = "Buff 大小 (预设为16)";
	PERL_LOCALIZED_CONFIG_DEBUFF_SIZE_LARGE = "Debuff 大小 (预设为16)";
	PERL_LOCALIZED_CONFIG_BUFF_NUMBER = "Buff 数量";
	PERL_LOCALIZED_CONFIG_DEBUFF_NUMBER = "Debuff 数量";
	PERL_LOCALIZED_CONFIG_COMBAT_TEXT = "战斗信息";
	PERL_LOCALIZED_CONFIG_COMPACT = "紧凑模式";
	PERL_LOCALIZED_CONFIG_DISPLAY_PERCENTS = "显示百分比";
	PERL_LOCALIZED_CONFIG_SHORT_BARS = "简略状态条";
	PERL_LOCALIZED_CONFIG_VERTICAL_FRAMES = "垂直显示团队框体";
	PERL_LOCALIZED_CONFIG_HIDE_CLASSICON_FRAME = "隐藏职业图标";
	PERL_LOCALIZED_CONFIG_HEALER_MODE = "治疗者模式";
	PERL_LOCALIZED_CONFIG_PET_SUPPORT = "显示宠物信息条";
	PERL_LOCALIZED_CONFIG_CLASS_BUFFDEBUFF = "显示职业相关Buffs/Debuffs";
	PERL_LOCALIZED_CONFIG_CLASS_COLORED_NAMES = "根据职业改变名字颜色";
	PERL_LOCALIZED_CONFIG_PVP_RANK_ICON = "PvP等级图标";
	PERL_LOCALIZED_CONFIG_SMALL = "小";
	PERL_LOCALIZED_CONFIG_BIG = "大";
	PERL_LOCALIZED_CONFIG_HIDE_POWER_BARS = "隐藏能量条";
	PERL_LOCALIZED_CONFIG_DISPLAY_MANA_DEFICIT = "显示能量条消耗百分比";
	PERL_LOCALIZED_CONFIG_PVP_STATUS_ICON = "PvP 状态图标";
	PERL_LOCALIZED_CONFIG_SHOW_BAR_VALUES = "显示状态和能量条数值";
	PERL_LOCALIZED_CONFIG_INVERT_BAR_VALUES = "反转显示生命及能量条数值";

	-- Perl Config Generic
	PERL_LOCALIZED_CONFIG_HEADER = "Perl控制面板";
	PERL_LOCALIZED_CONFIG_CLOSE = "关闭";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED = "未加载";
	PERL_LOCALIZED_CONFIG_NOTINSTALLED_EXPLANATION = "需要的插件没有安装或者启用";

	-- Perl Config All
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BARS = "状态条背景";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_ONE = "纹理 #1";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_TWO = "纹理 #2";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_THREE = "纹理 #3";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FOUR = "纹理 #4";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_FIVE = "纹理 #5";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_SIX = "纹理 #6";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURE_NONE = "无纹理";
	PERL_LOCALIZED_CONFIG_ALL_MINIMAP_POSITION = "小地图按钮的位置";
	PERL_LOCALIZED_CONFIG_ALL_SHOW_MINIMAP = "显示小地图按钮";
	PERL_LOCALIZED_CONFIG_ALL_FRAMES = "框体";
	PERL_LOCALIZED_CONFIG_ALL_TRANSPARENT_BACKGROUND = "透明背景";
	PERL_LOCALIZED_CONFIG_ALL_LOCK_ALL = "锁定所有框体";
	PERL_LOCALIZED_CONFIG_ALL_UNLOCK_ALL = "解锁所有框体";
	PERL_LOCALIZED_CONFIG_ALL_LOAD = "载入全局设定";
	PERL_LOCALIZED_CONFIG_ALL_SAVE = "保存全局设定";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 全局设定读取成功.";
	PERL_LOCALIZED_CONFIG_ALL_SAVE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 全局设定保存成功.";
	PERL_LOCALIZED_CONFIG_ALL_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 窗体位置已重置.";
	PERL_LOCALIZED_CONFIG_ALL_CLICKHEALING = "支持CastParty/Genesis/AceHeal/ClickHeal";
	PERL_LOCALIZED_CONFIG_ALL_PROGRESSIVE = "生命条颜色动态变化";
	PERL_LOCALIZED_CONFIG_ALL_NO_PROFILE_SELECTED_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 没有选择任何框体项目.";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 框体项目设定载入成功: ";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_HEADER = "载入框体项目";
	PERL_LOCALIZED_CONFIG_ALL_LOAD_PROFILE_BUTTON = "载入";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_BUTTON = "删除";
	PERL_LOCALIZED_CONFIG_ALL_DELETE_PROFILE_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 框体项目设定从列表里移除: ";
	PERL_LOCALIZED_CONFIG_ALL_TEXTURED_BACKGROUND = "有纹理的背景条";
	PERL_LOCALIZED_CONFIG_ALL_FADE_BARS = "背景条动态显示";
	PERL_LOCALIZED_CONFIG_ALL_CLICKCASTABLE_NAME_FRAMES = "单击玩家或目标框体触发施法技能";

	-- Perl Config ArcaneBar
	PERL_LOCALIZED_CONFIG_ARCANEBAR_ENABLE = "启用施法条";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_DISPLAY_TIMER = "显示施法时间";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_HIDE_BLIZZARD = "隐藏系统施法条";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_REPLACE_NAME = "按拼写顺序重新排列玩家名字";
	PERL_LOCALIZED_CONFIG_ARCANEBAR_LEFT_TIMER = "左边显示施法时间";

	-- Perl Config CombatDisplay
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_PERSIST_MODES = "治疗模式";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_TARGET_SETTINGS = "目标设置";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_AUTOATTACK = "自动攻击模式";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ONAGRO = "战斗状态模式";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_HEALTH_PERSIST = "生命值动态模式";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MANA_PERSIST = "魔法值动态模式";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_MENU = "启用右键菜单";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_LOCK = "锁定"..PERL_LOCALIZED_CONFIG_COMBATDISPLAY.."框体";
	PERL_LOCALIZED_CONFIG_COMBATDISPLAY_ENABLE_TARGET = "启用目标框体";

	-- Perl Config Party
	PERL_LOCALIZED_CONFIG_PARTY_SPACING = "间距 (预设为80)";
	PERL_LOCALIZED_CONFIG_PARTY_FKEYS = "显示F键";
	PERL_LOCALIZED_CONFIG_PARTY_LOCK = "锁定"..PERL_LOCALIZED_CONFIG_PARTY.."框体";

	-- Perl Config Party Pet
	PERL_LOCALIZED_CONFIG_PARTYPET_ENABLE = "开启"..PERL_LOCALIZED_CONFIG_PARTYPET.." 框体";
	PERL_LOCALIZED_CONFIG_PARTYPET_RESET_FRAMES_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": "..PERL_LOCALIZED_CONFIG_PARTYPET.."框体位置已经被重置";
	PERL_LOCALIZED_CONFIG_PARTYPET_LOCK = "锁定"..PERL_LOCALIZED_CONFIG_PARTYPET.."框体";

	-- Perl Config Party Target
	PERL_LOCALIZED_CONFIG_PARTYTARGET_ENABLE = "开启"..PERL_LOCALIZED_CONFIG_PARTYTARGET.."框体";
	PERL_LOCALIZED_CONFIG_PARTYTARGET_LOCK = "锁定"..PERL_LOCALIZED_CONFIG_PARTYTARGET.."框体";

	-- Perl Config Player
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_MODE = "经验值条模式";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_EXPERIENCE = "经验值";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_PVPRANK = "PvP 军阶";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_REPUTATION = "声望值";
	PERL_LOCALIZED_CONFIG_PLAYER_XPBAR_HIDDEN = "隐藏";
	PERL_LOCALIZED_CONFIG_PLAYER_RAID_GROUP = "显示团队队伍编号";
	PERL_LOCALIZED_CONFIG_PLAYER_LOCK = "锁定"..PERL_LOCALIZED_CONFIG_PLAYER.."框体";

	-- Perl Config Player Buff
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_ENABLE = "开启玩家Buffs增益框体";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_WARNING = "开启增益时间剩余30秒提示信息";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HIDESECONDS = "增益时间紧凑模式";
	PERL_LOCALIZED_CONFIG_PLAYERBUFF_HORIZONTAL_SPACING = "增益水平间隔(预设为10)";

	-- Perl Config Player Pet
	PERL_LOCALIZED_CONFIG_PLAYERPET_EXPERIENCE = "显示宠物经验条";
	PERL_LOCALIZED_CONFIG_PLAYERPET_LOCK = "锁定"..PERL_LOCALIZED_CONFIG_PLAYERPET.."框体";

	-- Perl Config Raid
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SETTINGS = "队伍设定";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_ONE = "显示小队1(战士)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_TWO = "显示小队2(法师)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_THREE = "显示小队3(牧师)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_FOUR = "显示小队4(术士)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_FIVE = "显示小队5(德鲁伊)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SIX = "显示小队6(盗贼)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_SEVEN = "显示小队7(猎人)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_EIGHT = "显示小队8(圣骑士)";
	PERL_LOCALIZED_CONFIG_RAID_GROUP_NINE = "显示小队9(萨满)";
	PERL_LOCALIZED_CONFIG_RAID_SORT_BY_CLASS = "根据职业排列";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_GROUP_HEADERS = "显示小队标题";
	PERL_LOCALIZED_CONFIG_RAID_LOCK = "锁定"..PERL_LOCALIZED_CONFIG_RAID.."框体";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_ALL = "显示所有小队";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_ALL = "隐藏所有小队";
	PERL_LOCALIZED_CONFIG_RAID_CONNECT_FRAMES = "连接对应框体";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_HEALTH_PERCENTAGES = "显示生命值百分比";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_MANA_PERCENTAGES = "显示能量值百分比";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_MISSING_HEALTH = "显示失去的生命数值";
	PERL_LOCALIZED_CONFIG_RAID_INVERT_FRAMES = "颠倒显示团队框体";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_BUFFS = "显示 Buffs";
	PERL_LOCALIZED_CONFIG_RAID_SHOW_DEBUFFS = "显示 Debuffs";
	PERL_LOCALIZED_CONFIG_RAID_COLOR_DEBUFF_NAMES = "中Debuff名字变色";
	PERL_LOCALIZED_CONFIG_RAID_ALTERNATE_FRAME_STYLE = "改变框体风格";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_BORDER = "隐藏边框";
	PERL_LOCALIZED_CONFIG_RAID_REMOVE_SPACE = "消除间隙";
	PERL_LOCALIZED_CONFIG_RAID_TOOLTIP = "CTRA风格提示信息";
	PERL_LOCALIZED_CONFIG_RAID_HIDE_EMPTY_HEADERS = "隐藏多余小队标题";

	-- Perl Config Target
	PERL_LOCALIZED_CONFIG_TARGET_BUFFDEBUFF_SCALING = "Buff/Debuff 图标缩放(预设为100)";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_LOCATION = "连击点显示位置";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_ICON = "职业图标";
	PERL_LOCALIZED_CONFIG_TARGET_CLASS_CIVILIAN_FRAMES = "职业/平民 框体";
	PERL_LOCALIZED_CONFIG_TARGET_RARE_ELITE_FRAME = "稀有怪/精英 框体";
	PERL_LOCALIZED_CONFIG_TARGET_HIDE_BUFFDEBUFF_BACKGROUND = "隐藏 Buff/Debuff 背景";
	PERL_LOCALIZED_CONFIG_TARGET_SOUND_ON_TARGET_CHANGE = "目标变化声音提示";
	PERL_LOCALIZED_CONFIG_TARGET_LOCK = "锁定"..PERL_LOCALIZED_CONFIG_TARGET.."框体";
	PERL_LOCALIZED_CONFIG_TARGET_COMBO_POINT_FRAME = "连击点框体";
	PERL_LOCALIZED_CONFIG_TARGET_DISPLAY_IN_NAME_FRAME = "显示在姓名栏";
	PERL_LOCALIZED_CONFIG_TARGET_DEBUFF_STACKS_IN_COMBO_FRAME = "显示Debuff叠加数连击点框体";
	PERL_LOCALIZED_CONFIG_TARGET_ALTERNATE_FRAME_STYLE = "改变框体风格";
	PERL_LOCALIZED_CONFIG_TARGET_INVERT_BUFFS_DEBUFFS = "反转Buffs/Debuffs";

	-- Perl Config Target Target
	PERL_LOCALIZED_CONFIG_TARGETTARGET_MAIN = "主选项";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_MODE = "警报模式";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ALERT_SIZE = "警告信息字体大小";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOT = "启用目标的目标";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_ENABLE_TOTOT = "启用目标的目标的目标";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_AUDIO_ALERT_ON_AGRO = "OT音频警报";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LOCK = "锁定"..PERL_LOCALIZED_CONFIG_TARGETTARGET.."框体";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_BUFFS = "显示目标的目标的Buffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOT_DEBUFFS = "显示目标的目标的Debuffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_BUFFS = "显示目标的目标的目标的Buffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_TOTOT_DEBUFFS = "显示目标的目标的目标的Debuffs";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_DPS_MODE = "DPS 模式";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TANK_MODE = "Tank 模式";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_HEALER_MODE = "治疗者模式";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SMALL_TEXT = "小字体(提示信息)";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_LARGE_TEXT = "大字体(提示信息)";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_NO_TEXT = "无字体(无提示信息)";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OF_TARGET_FRAME = "目标的目标框体置右";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OF_TARGET_FRAME = "目标的目标框体置顶";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_RIGHT_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 目标的目标窗体已靠右排列.";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_TOP_OUTPUT = "|cffffff00"..PERL_LOCALIZED_NAME..": 目标的目标窗体已置顶排列.";
	PERL_LOCALIZED_CONFIG_TARGETTARGET_SHOW_FRIENDLY_HEALTH = "显示友好的生命数值";
end