BINDING_HEADER_PETFUNCTIONS = "Pet Functions";

BINDING_NAME_PETATTACK = "Pet attack";
BINDING_NAME_PETFOLLOW = "Pet follow";
BINDING_NAME_PETWAIT = "Pet wait";

BINDING_NAME_DISMISSPET = "Dismiss pet";

BINDING_NAME_PETPASSIVEMODE = "Passive Mode";
BINDING_NAME_PETDEFENSIVEMODE = "Defensive Mode";
BINDING_NAME_PETAGGRESSIVEMODE = "Aggressive Mode";