--[[
Localisation file

]]

MOOGHUD_VERSION = "1.11.1";
MOOGHUD_CLASS_WARRIOR = "Warrior";
MOOGHUD_CLASS_MAGE = "Mage";
MOOGHUD_CLASS_ROGUE = "Rogue";
MOOGHUD_CLASS_DRUID = "Druid";
MOOGHUD_CLASS_HUNTER = "Hunter";
MOOGHUD_CLASS_SHAMAN = "Shaman";
MOOGHUD_CLASS_PRIEST = "Priest";
MOOGHUD_CLASS_WARLOCK = "Warlock";
MOOGHUD_CLASS_PALADIN = "Paladin";
if ( GetLocale() == "frFR" ) then
	MOOGHUD_CLASS_WARRIOR = "Guerrier";
	MOOGHUD_CLASS_MAGE = "Mage";
	MOOGHUD_CLASS_ROGUE = "Voleur";
	MOOGHUD_CLASS_DRUID = "Druide";
	MOOGHUD_CLASS_HUNTER = "Chasseur";
	MOOGHUD_CLASS_SHAMAN = "Chaman";
	MOOGHUD_CLASS_PRIEST = "Pr\195\170tre";
	MOOGHUD_CLASS_WARLOCK = "D\195\169moniste";
	MOOGHUD_CLASS_PALADIN = "Paladin";
end
if ( GetLocale() == "koKR" ) then
	MOOGHUD_CLASS_WARRIOR = "전사";
	MOOGHUD_CLASS_MAGE = "마법사";
	MOOGHUD_CLASS_ROGUE = "도적";
	MOOGHUD_CLASS_DRUID = "드루이드";
	MOOGHUD_CLASS_HUNTER = "사냥꾼";
	MOOGHUD_CLASS_SHAMAN = "주술사";
	MOOGHUD_CLASS_PRIEST = "사제";
	MOOGHUD_CLASS_WARLOCK = "흑마법사";
	MOOGHUD_CLASS_PALADIN = "성기사";
end
if ( GetLocale() == "deDE") then
	MOOGHUD_CLASS_WARRIOR = "Krieger";
	MOOGHUD_CLASS_MAGE = "Magier";
	MOOGHUD_CLASS_ROGUE = "Schurke";
	MOOGHUD_CLASS_DRUID = "Druide";
	MOOGHUD_CLASS_HUNTER = "J\195\164ger";
	MOOGHUD_CLASS_SHAMAN = "Schamane";
	MOOGHUD_CLASS_PRIEST = "Priester";
	MOOGHUD_CLASS_WARLOCK = "Hexenmeister";
	MOOGHUD_CLASS_PALADIN = "Paladin";
end