DUF_VERSION = "2.46";
DUF_DL_VERSION = 1.46;

-- START OF TEXT TO LOCALIZE

DUF_ARROW_RIGHT = ">";
DUF_ARROW_LEFT = "<";
DUF_CLASSLABEL = "Class:";
DUF_CONTEXTLABEL = "Color Contexts:";
DUF_DIFFICULTYLABEL = "Difficulty:";
DUF_HEALTHLABEL = "Health:";
DUF_MANALABEL = "Mana:";
DUF_NUDGE = "Nudge";
DUF_REACTIONLABEL = "Reaction:";

BINDING_HEADER_DUF = "Discord Unit Frames v"..DUF_VERSION;
BINDING_NAME_DUF_OPTIONS = "Show/Hide Options Window";
BINDING_NAME_DUF_TOGGLE_ELEMENTS_LOCK = "Lock/Unlock Elements";
BINDING_NAME_DUF_TOGGLE_FRAMES_LOCK = "Lock/Unlock Frames";

DUF_TEXT = {
		Alliance = "Alliance",
		Alpha = "Alpha",
		AttachFrame = "Attach Frame",
		AttachPoint = "Attach Point",
		AttachTo = "Attach To",
		AutoLock = "Lock Frames & Elements When Closing This Window",
		Background = "Background",
		BackgroundAlpha = "Background Alpha",
		BackgroundColor = "Background Color",
		BackgroundPadding = "Background Padding",
		BarColor = "Bar Color",
		Base = "Base",
		Beast = "Beast",
		Border = "Border",
		BorderAlpha = "Border Alpha",
		BorderColor = "Border Color",
		BorderStyle = "Border Style",
		Boss = "Boss",
		BuffFrame = "Buff Frame",
		BuffsShown = "Max Buffs Shown",
		ClassIcon = "Class Icon",
		Color = "Color",
		Combat = "In Combat",
		ComboPoints = "Combo Points",
		ConnectFrames = "Connect Frames",
		ContextColors = "Context Colors",
		Copy = "COPY",
		CopyFrame = "Copy Settings From",
		Crit = "*CRITICAL*",
		Critter = "Critter",
		CustomEliteTexture = "Custom Elite Texture",
		CustomRareTexture = "Custom Rare Texture",
		CustomSettingsLoaded = "Custom settings loaded.",
		CustomTexture = "Custom Texture",
		CustomTexture2 = "Secondary Bar's Custom Texture",
		CustomTooltip = "Custom Tooltip",
		Dead = "Dead",
		DebuffFrame = "Debuff Frame",
		DebuffsShown = "Max Debuffs Shown",
		Default = "Default",
		DefaultSettingsLoaded = "Default settings loaded.",
		Delete = "DELETE",
		Demon = "Demon",
		DisableMouse = "Disable Mouse",
		DisableTooltip = "Disable Tooltip",
		Dragonkin = "Dragonkin",
		Druid = "Druid",
		Dwarf = "Dwarf",
		Elemental = "Elemental",
		Elite = "Elite",
		EliteTexture = "Elite Texture",
		Energy = "Energy",
		EnergyColor = "Energy Color",
		FacesLeft = "Faces Left",
		Fade = "Fade Amount Lost",
		Female = "Female",
		Fill = "Fill Instead of Deplete",
		FlashForLowHealth = "Flash When Health Is Low",
		FlashWhenActive = "Flash When Active",
		Focus = "Focus",
		FocusColor = "Focus Color",
		Font = "Font",
		FontHeight = "Font Height",
		FrameOptions = "Frame Options",
		Friendly = "Friendly",
		FriendlyNPC = "Friendly NPC",
		FriendlyPlayer = "Friendly Player",
		Ghost = "Ghost",
		Giant = "Giant",
		Gnome = "Gnome",
		HappinessIcon = "Happiness Icon",
		HealthBar = "Health Bar",
		HealthThreshold = "Health % Less Than ",
		Height = "Height",
		Hide = "Hide",
		HideBackground = "Hide Background",
		HideIfNoMana = "Hide If Unit Doesn't Use Mana",
		HidePartyInRaid = "Hide Party Frames In Raids",
		HideTargetTarget = "Hide Target of Target When Soloing",
		HonorBar = "Honor Bar",
		Horde = "Horde",
		Hostile = "Hostile",
		Human = "Human",
		Humanoid = "Humanoid",
		Hunter = "Hunter",
		JustifyH = "Horizontal Justification",
		JustifyV = "Vertical Justification",
		LeaderIcon = "Leader Icon",
		LeftClick = "Left-Click",
		LevelDifference1 = "Trivial",
		LevelDifference2 = "Minor",
		LevelDifference3 = "Even",
		LevelDifference4 = "Tough",
		LevelDifference5 = "Very Tough",
		LevelDifference6 = "Suicide",
		Load = "LOAD",
		LoadCustomSettings = "Load Custom Settings",
		LoadDefaultSettings = "Load Default Settings",
		LoadSettings = "Load Settings:",
		LockElements = "Lock Elements",
		LockFrames = "Lock Frames",
		LootIcon = "Loot Icon",
		LowHealthThreshold = "Low Health Threshold",
		Mage = "Mage",
		Main = "Main",
		Male = "Male",
		Mana = "Mana",
		ManaBar = "Mana Bar",
		ManaColor = "Mana Color",
		ManaThreshold = "Mana % Less Than ",
		MaxCharacters = "Maximum Number of Characters",
		Method = "Method",
		MiddleClick = "Middle Click",
		MiscOptions = "Misc Options",
		Mouseover = "Show On Mouseover",
		MouseoverColor = "Mouseover Color",
		MouseoverGroup = "Mouseover Group",
		Neuter = "Neuter",
		Neutral = "Neutral",
		NightElf = "Night Elf",
		NoCustomSettings = "No custom settings found for Discord Unit Frames.",
		NoDefaultSettings = "No default settings found for Discord Unit Frames.",
		NoSettingsFound = "No settings found.",
		NoTarget = "No Target",
		NotSpecified = "Not specified",
		Offline = "Offline",
		OptionsScale = "Options Window Scale",
		Orc = "Orc",
		Paladin = "Paladin",
		Party = "PARTY",
		PartyPets = "PARTY PETS",
		Pet = "PET",
		Portrait = "Portrait",
		Priest = "Priest",
		PVP = "PvP",
		PVPFree = "PvP Free For All",
		PVPFriendly = "PVP-enabled Player",
		PVPIcon = "PvP Icon",
		QuickLoad = "Quick Load",
		QuickSave = "Quick Save",
		RaceIcon = "Race Icon",
		Rage = "Rage",
		RageColor = "Rage Color",
		RankIcon = "Rank Icon",
		Rare = "Rare",
		RareElite = "Rare Elite",
		ReverseFill = "Reverse Fill Direction",
		RightClick = "Right-Click",
		Rogue = "Rogue",
		SafeCopy = "SAFE COPY",
		SafeLoad = "SAFE LOAD",
		Save = "SAVE",
		SaveSettings = "Save Settings: ",
		Scale = "Scale",
		SecondaryBarColor = "Secondary Bar Color",
		Self = "SELF",
		SettingsDeleted = "Settings deleted.",
		SettingsLoaded = "New settings loaded.",
		SettingsSaved = "Your settings have been saved.",
		Shaman = "Shaman",
		ShowDefault = "Show Default Frame(s)",
		Size = "Size",
		Spacing = "Spacing",
		Special = "Special",
		StatusIcon = "Status Icon",
		Summoned = "Summoned",
		Tapped = "Tapped",
		Target = "TARGET",
		TargetHealthBar = "Target Health Bar",
		TargetManaBar = "Target Mana Bar",
		TargetOfTarget = "TARGET OF TARGET",
		TargetTapped = "Tapped",
		Tauren = "Tauren",
		Text = "Text",
		TextBox1 = "TextBox 1",
		TextBox2 = "TextBox 2",
		TextBox3 = "TextBox 3",
		TextBox4 = "TextBox 4",
		TextBox5 = "TextBox 5",
		TextBox6 = "TextBox 6",
		TextBox7 = "TextBox 7",
		TextBox8 = "TextBox 8",
		TextBox9 = "TextBox 9",
		TextBox10 = "TextBox 10",
		TextColor = "Text Color",
		TextVariables = "Text Variables",
		Troll = "Troll",
		TwoRows = "Two Rows/Columns",
		Undead = "Undead",
		UnlockElements = "Unlock Elements",
		UnlockFrames = "Unlock Frames",
		UpdateSpeed = "Updates Per Second",
		VariablesTitle = "DISCORD UNIT FRAMES TEXT VARIABLES",
		VerticalLayout = "Vertical Layout",
		Warlock = "Warlock",
		Warrior = "Warrior",
		Width = "Width",
		XPBar = "XP Bar",
		You = "* YOU *",
		YourTarget = "* YOUR TARGET *",

		FrameStrata = "Frame Strata",
		FrameLevelOffset = "Frame Level Offset     ",
		UseClassTexture = "Use Class Texture for Players",
		UseRaceTexture = "Use Race Texture for NPCs",
		Label = "Label",
		ShowCircularBorder = "Show Circular Border",
		ResizeBasedOnMax = "Resize Based On Max Amount",
		ShowDuration = "Show Duration",
		DurationHeight = "Duration Font Height",
		DurationAlpha = "Duration Alpha",
		DurationColor = "Duration Color",
		DurationFont = "Duration Font",
		DurationXOffset = "Duration X Offset",
		DurationYOffset = "Duration Y Offset",
		OutOfRange = "OUT OF RANGE",
		HideIfNoText = "Hide If No Text",
		HideOnMouseover = "Hide On Mouseover",
		BackgroundTexture = "BG Texture",
		HideBuffFrame = "Hide Default Buff Frame",
		HSpacing = "Horizontal Spacing",
		VSpacing = "Vertical Spacing",
		DurationFormat = "Use mm:ss Format",
		NewProfile = "New Profile",
		LoadProfile = "Load Profile",
		Create = "CREATE",
		ProfileCreated = "New profile created for Discord Unit Frames.",
		CurrentProfile = "Current Profile",
		FillDirection = "Fill Direction",
		ShowInCombat = "Show In Combat",
		HealthUpdating = "Show When Health Is Less Than Max",
		ManaUpdating = "Show When Mana Is Less Than Max",
		VerticalText = "Vertical Text",
		Outline = "Outline:",
		TrackReputation = "Track Reputation Instead",
		ShowTargetIcon = "Show Target Icon Instead",
		FrameToMove = "Frame To Move",
	};

DUF_TEXTVARIABLES = {
	 "Civilian - $cv",
	 "Class, Abbreviation - $ca",
	 "Class, Mob - $cy",
	 "Class, Player - $cl",
	 "Classification ('Elite', etc.) - $cc",
	 "Classification, Abbreviation - $cx",
	 "Color Code - $co",
	 "Color Context, Class - $cw",
	 "Color Context, Difficulty - $cq",
	 "Color Context, Health - $ch",
	 "Color Context, Mana - $cm",
	 "Color Context, Power Type - $cz",
	 "Color Context, Reaction - $cr",
	 "Combo Points - $cp",
	 "Creature Difficulty ('Trivial', etc.) - $cd",
	 "Creature Family ('Cat', etc.) - $cf",
	 "Creature Type ('Beast', etc.) - $ct",
	 "Death Status - $ds",
	 "Faction - $fa",
	 "Gender - $sx",
	 "Gender, Abbreviation - $sa",
	 "Guild - $gu",
	 "Health, Current - $hc",
	 "Health, Current Percent - $hp",
	 "Health, Lost - $dt",
	 "Health, Lost Percent - $dp",
	 "Health, Max - $hm",
	 "Health, Regen Per Sec - $hr",
	 "Health, Regen Per Tick - $ht",
	 "Honor Percent - $hn",
	 "In Combat - $ic",
	 "Keybinding - $kb",
	 "Level - $lv",
	 "Mana, Current - $mc",
	 "Mana, Current Percent - $mp",
	 "Mana, Lost - $mx",
	 "Mana, Lost Percent - $my",
	 "Mana, Max - $mm",
	 "Mana, Regen Per Sec - $mr",
	 "Mana, Regen Per Tick - $mt",
	 "Mana, Type - $ml",
	 "Name - $nm",
	 "Next Level - $xn",
	 "New Line - $nl",
	 "NPC - $np",
	 "Offline - $of",
	 "Out of Detect Range - $iv",
	 "Pet's Current XP - $px",
	 "Pet's Current XP Percent - $pc",
	 "Pet's Happiness - $ph",
	 "Pet's Max XP Needed to Level - $py",
	 "Pet's Net XP Needed to Level - $pg",
	 "Pet's XP Percent To Go - $pp",
	 "PvP Flagged - $pt",
	 "PvP Rank - $pr",
	 "PvP Rank Number - $pn",
	 "Race - $rc",
	 "Race, Abbreviation - $ra",
	 "Raid Group - $rg",
	 "Reaction ('Hostile', etc.) - $re",
	 "Recent Damage - $rd",
	 "Recent Heals - $rh",
	 "Tapped - $do",
	 "Target's Creature Type - $tt",
	 "Target's Health - $th",
	 "Target's Health Percent - $ta",
	 "Target's Level - $tl",
	 "Target's Mana - $tm",
	 "Target's Mana Percent - $tb",
	 "Target's Max Health - $tx",
	 "Target's Max Mana - $ty",
	 "Target's Name - $tn",
	 "Watched Faction - $wf",
	 "Watched Faction Current Rep - $wc",
	 "Watched Faction Max Rep - $wm",
	 "Watched Faction Reaction - $wr",
	 "Watched Faction Rep Percent - $wp",
	 "XP, Current - $xc",
	 "XP, Current Percent - $xy",
	 "XP, Max Needed to Level - $xl",
	 "XP, Needed to Level - $xd",
	 "XP, Needed to Level Percent - $xx",
	 "XP, Rested Bonus - $xr",
	 "XP, Rested Percent - $xb"
}

DUF_CLASSABBREV = {
		[DUF_TEXT.Warrior] = "War",
		[DUF_TEXT.Priest] = "Pr",
		[DUF_TEXT.Rogue] = "Rog",
		[DUF_TEXT.Shaman] = "Shm",
		[DUF_TEXT.Mage] = "Ma",
		[DUF_TEXT.Paladin] = "Pal",
		[DUF_TEXT.Hunter] = "Hu",
		[DUF_TEXT.Warlock] = "Wlk",
		[DUF_TEXT.Druid] = "Drd"
	};

DUF_RACEABBREV = {
		[DUF_TEXT.Undead] = "Ud",
		[DUF_TEXT.Tauren] = "Ta",
		[DUF_TEXT.NightElf] = "NE",
		[DUF_TEXT.Gnome] = "Gnm",
		[DUF_TEXT.Dwarf] = "Dwf",
		[DUF_TEXT.Human] = "Hum",
		[DUF_TEXT.Troll] = "Trl",
		[DUF_TEXT.Orc] = "Orc"
	};

DUF_SEXABBREV = {
		["Male"] = "M",
		["Female"] = "F",
		["Neuter"] = "N"
	};

DUF_BORDER_STYLES = {
	{ text="Plain", value=1 },
	{ text="Tooltip", value=2 },
	{ text="Dialogue", value=3 },
	{ text="Slider", value=4 }
}

DUF_COLOR_CONTEXTS = {
	{ text="None", value=nil },
	{ text="Difficulty", value=1 },
	{ text="Reaction", value=2 },
	{ text="Class", value=3 },
	{ text="Health", value=4 },
	{ text="Mana", value=5 }
}

DUF_CLICK_OPTIONS = {
	{ text="Do Nothing", value=nil },
	{ text="Target Unit", value=1 },
	{ text="Assist Unit", value=2 },
	{ text="Show Popup", value=3 }
}

DUF_CONNECT_OPTIONS = {
	{ text="Top to Bottom", value=1 },
	{ text="Bottom to Top", value=2 },
	{ text="Left to Right", value=3 },
	{ text="Right to Left", value=4 }
}

DUF_ANCHORS = {
		{ text = "TOPLEFT", value = "TOPLEFT" },
		{ text = "TOP", value = "TOP" },
		{ text = "TOPRIGHT", value = "TOPRIGHT" },
		{ text = "LEFT", value = "LEFT" },
		{ text = "CENTER", value = "CENTER" },
		{ text = "RIGHT", value = "RIGHT" },
		{ text = "BOTTOMLEFT", value = "BOTTOMLEFT" },
		{ text = "BOTTOM", value = "BOTTOM" },
		{ text = "BOTTOMRIGHT", value = "BOTTOMRIGHT" }
	 };

DUF_ATTACH_FRAMES = {
	{ text="UIParent", value="UIParent" },
	{ text="Unit Frame", value="Unit Frame" },
	{ text="Buff Frame", value="_Buffs" },
	{ text="Class Icon", value="_ClassIcon" },
	{ text="Debuff Frame", value="_Debuffs" },
	{ text="Health Bar", value="_HealthBar" },
	{ text="Leader Icon", value="_LeaderIcon" },
	{ text="Loot Icon", value="_LootIcon" },
	{ text="Mana Bar", value="_ManaBar" },
	{ text="Portrait", value="_Portrait" },
	{ text="PvP Icon", value="_PVPIcon" },
	{ text="Race Icon", value="_RaceIcon" },
	{ text="Rank Icon", value="_RankIcon" },
	{ text="Status Icon", value="_StatusIcon" },
	{ text="Target Health Bar", value="_TargetHealthBar" },
	{ text="Target Mana Bar", value="_TargetManaBar" },
	{ text="TextBox 1", value="_TextBox_1" },
	{ text="TextBox 2", value="_TextBox_2" },
	{ text="TextBox 3", value="_TextBox_3" },
	{ text="TextBox 4", value="_TextBox_4" },
	{ text="TextBox 5", value="_TextBox_5" },
	{ text="TextBox 6", value="_TextBox_6" },
	{ text="TextBox 7", value="_TextBox_7" },
	{ text="TextBox 8", value="_TextBox_8" },
	{ text="TextBox 9", value="_TextBox_9" },
	{ text="TextBox 10", value="_TextBox_10" }
};

DUF_JUSTIFICATION_HORIZONTAL = {
	{ text="LEFT", value="LEFT" },
	{ text="RIGHT", value="RIGHT" },
	{ text="CENTER", value="CENTER" }
}

DUF_JUSTIFICATION_VERTICAL = {
	{ text="TOP", value="TOP" },
	{ text="BOTTOM", value="BOTTOM" },
	{ text="CENTER", value="CENTER" }
}

DUF_MOUSEOVER_GROUPS = {
	{ text="None", value=nil },
	{ text="1", value=1 },
	{ text="2", value=2 },
	{ text="3", value=3 },
	{ text="4", value=4 },
	{ text="5", value=5 },
	{ text="6", value=6 },
	{ text="7", value=7 },
	{ text="8", value=8 },
	{ text="9", value=9 },
	{ text="10", value=10 }
}

DUF_STATUSBAR_DIRECTIONS = {
	{ text="Left to Right", value=1 },
	{ text="Right to Left", value=2 },
	{ text="Bottom to Top", value=3 },
	{ text="Top to Bottom", value=4 }
}
-- END OF STUFF TO LOCALIZE

-- German translations courtesy of Boergen.

 if (GetLocale() == "deDE") then
DUF_CLASSLABEL = "Klasse:";
DUF_CONTEXTLABEL = "Farben Kontexte:";
DUF_DIFFICULTYLABEL = "Schwierigkeit:";
DUF_HEALTHLABEL = "Gesundheit:";
DUF_MANALABEL = "Mana:";
DUF_NUDGE = "Feineinstellung";
DUF_REACTIONLABEL = "Reaktion:";

BINDING_NAME_DUF_OPTIONS = "Zeige/Verstecke Optionen Fenster";
BINDING_NAME_DUF_TOGGLE_ELEMENTS_LOCK = "Elemente Fixieren/Freigeben";
BINDING_NAME_DUF_TOGGLE_FRAMES_LOCK = "Frames Fixieren/Freigeben";

DUF_TEXT = {
Alliance = "Allianz",
Alpha = "Alpha",
AttachFrame = "Anheft Frame",
AttachPoint = "Anheft Punkt",
AttachTo = "Anheften an",
Background = "Hintergrund",
BackgroundAlpha = "Hintergrund Alpha",
BackgroundColor = "Hintergrund Farbe",
BackgroundPadding = "Hintergrund F\195\188llung",
BarColor = "Balken Farbe",
Base = "Basis",
Beast = "Wildtier",
Border = "Rahmen",
BorderAlpha = "Rahmen Alpha",
BorderColor = "Rahmen Farbe",
BorderStyle = "Rahmen Aussehen",
Boss = "Boss",
BuffFrame = "Buff Frame",
BuffsShown = "Max angezeigte Buffs",
ClassIcon = "Klassen Icon",
Color = "Farbe",
Combat = "Im Kampf",
ComboPoints = "Kombo Punkte",
ConnectFrames = "Verbinde Frames",
ContextColors = "Kontext Farben",
Copy = "KOPIEREN",
CopyFrame = "Kopiere Einstellungen von",
Crit = "*KRITISCH*",
Critter = "Tier",
CustomEliteTexture = "Besondere Elite Textur",
CustomRareTexture = "Besondere Rare Textur",
CustomSettingsLoaded = "Besondere Einstellungen geladen.",
CustomTooltip = "Besonderer Tooltip",
Dead = "Tot",
DebuffFrame = "Debuff Frame",
DebuffsShown = "Max angezeigte Debuffs",
DefaultSettingsLoaded = "Voreinstellungen geladen.",
Delete = "L\195\182SCHEN",
Demon = "D\195\164mon",
DisableMouse = "Deaktiviere Mouse",
DisableTooltip = "Deaktiviere Tooltip",
Dragonkin = "Drachkin",
Druid = "Druide",
Dwarf = "Zwerg",
Elemental = "Elementar",
Elite = "Elite",
EliteTexture = "Elite Textur",
Energy = "Energie",
EnergyColor = "Energie Farbe",
FacesLeft = "Gesichter Links",
Fade = "Verlorene Menge verblassen lassen",
Female = "Weiblich",
Fill = "F\195\188llen statt leeren",
FlashForLowHealth = "Blinken wenn Gesundheit niedrig",
FlashWhenActive = "Blinken wenn aktiv",
Focus = "Fokus",
FocusColor = "Fokus Farbe",
Font = "Schriftart",
FontHeight = "Schriftart H\195\182he",
FrameOptions = "Frame Options",
Friendly = "Freundlich",
FriendlyNPC = "Freundlicher NPC",
FriendlyPlayer = "Freunlicher Spieler",
Ghost = "Geist",
Giant = "Riese",
Gnome = "Gnom",
HappinessIcon = "Zufriedenheits Icon",
HealthBar = "Gesundheits Balken",
HealthThreshold = "Gesundheit % weniger als ",
Height = "H\195\182he",
Hide = "Verstecken",
HideBackground = "Verstecke Hintergrund",
HideIfNoMana = "Verstecken wenn Einheit kein Mana nutzt",
HidePartyInRaid = "Verstecke Gruppen Frames in Raids",
HideTargetTarget = "Verstecke Ziel vom Ziel wenn Solo",
HonorBar = "Ehre Balken",
Horde = "Horde",
Hostile = "Feindlich",
Human = "Mensch",
Humanoid = "Humanoid",
Hunter = "J\195\164ger",
JustifyH = "Horizontale Ausrichtung",
JustifyV = "Vertical Ausrichtung",
LeaderIcon = "Anf\195\188hrer Icon",
LeftClick = "Links-Klick",
LevelDifference1 = "Sehr leicht",
LevelDifference2 = "Leicht",
LevelDifference3 = "Ausgeglichen",
LevelDifference4 = "Schwer",
LevelDifference5 = "Sehr schwer",
LevelDifference6 = "Selbstmord",
Load = "LADEN",
LoadCustomSettings = "Lade besondere Einstellungen",
LoadDefaultSettings = "Lade Voreinstellungen",
LoadSettings = "Lade Einstellungen:",
LockElements = "Fixiere Elemente",
LockFrames = "Fixiere Frames",
LootIcon = "Loot Icon",
LowHealthThreshold = "Niedrige Gesundheit Grenze",
Mage = "Magier",
Main = "Haupt",
Male = "M\195\164nnlich",
Mana = "Mana",
ManaBar = "Mana Balken",
ManaColor = "Mana Farbe",
ManaThreshold = "Mana % weniger als ",
MaxCharacters = "Maximale Anzahl an Zeichen",
Method = "Methode",
MiddleClick = "Mittel-Klick",
MiscOptions = "Verschiedene Optionen",
Mouseover = "Zeige bei Mouseber\195\188hrung",
MouseoverColor = "Mouseber\195\188hrung Farbe",
MouseoverGroup = "Mouseber\195\188hrung Gruppe",
Neuter = "Neutrum",
Neutral = "Neutral",
NightElf = "Nachtelf",
NoCustomSettings = "Keine besonderen Einstellungen gefunden.",
NoDefaultSettings = "Keine Voreinstellungen gefunden.",
NoSettingsFound = "Keine Einstellungen gefunden.",
NoTarget = "Kein Ziel",
NotSpecified = "Nicht spezifiziert",
Offline = "Offline",
OptionsScale = "Optionen Fenster Gr\195\182\195\159e",
Orc = "Orc",
Paladin = "Paladin",
Party = "GRUPPE",
PartyPets = "GRUPPEN PETS",
Pet = "PET",
Portrait = "Portr\195\164t",
Priest = "Priester",
PVP = "PvP",
PVPFree = "PvP Free For All",
PVPFriendly = "PVP-aktiver Player",
PVPIcon = "PvP Icon",
QuickLoad = "Quick Load",
QuickSave = "Quick Save",
RaceIcon = "Rassen Icon",
Rage = "Wut",
RageColor = "Wut Farbe",
RankIcon = "Rang Icon",
Rare = "Rare",
RareElite = "Rare Elite",
ReverseFill = "F\195\188llrichtung umkehren",
RightClick = "Rechts-Klick",
Rogue = "Schurke",
Save = "SPEICHERN",
SaveSettings = "Speichere Einstellungen: ",
Scale = "Gr\195\182\195\159enanpassung",
SecondaryBarColor = "Sekund\195\164re Balken Farbe",
Self = "SELBST",
SettingsDeleted = "Einstellungen gel\195\182scht.",
SettingsLoaded = "Neue Einstellungen geladen.",
SettingsSaved = "Deine Einstellungen wurden gespeichert.",
Shaman = "Schamane",
ShowDefault = "Zeige normale(n) Frame(s)",
Size = "Gr\195\182\195\159e",
Spacing = "Spacing",
Special = "Spezial",
StatusIcon = "Status Icon",
Summoned = "Beschworen",
Tapped = "Markiert",
Target = "ZIEL",
TargetHealthBar = "Ziel Gesundheit Balken",
TargetManaBar = "Ziel Mana Balken",
TargetOfTarget = "TARGET OF TARGET",
TargetTapped = "Tapped",
Tauren = "Tauren",
Text = "Text",
TextBox1 = "TextBox 1",
TextBox2 = "TextBox 2",
TextBox3 = "TextBox 3",
TextBox4 = "TextBox 4",
TextBox5 = "TextBox 5",
TextBox6 = "TextBox 6",
TextBox7 = "TextBox 7",
TextBox8 = "TextBox 8",
TextBox9 = "TextBox 9",
TextBox10 = "TextBox 10",
TextColor = "Text Farbe",
TextVariables = "Text Variablen",
Troll = "Troll",
TwoRows = "Zwei Reihen/Spalten",
Undead = "Untoter",
UnlockElements = "L\195\182se Elemente",
UnlockFrames = "L\195\182se Frames",
UpdateSpeed = "Updates pro Sekunde",
VariablesTitle = "DISCORD UNIT FRAMES TEXT VARIABLEN",
VerticalLayout = "Vertikales Layout",
Warlock = "Hexenmeister",
Warrior = "Krieger",
Width = "Breite",
XPBar = "XP Balken",
You = "* DU *",
YourTarget = "* DEIN ZIEL *",
AutoLock = "Fixiere Frames & Elemente beim Schlie\195\159en dieses Fensters",
CustomTexture = "Besondere Textur",
CustomTexture2 = "Besondere Textur f\195\188r Sekund\195\164re Leiste",
FrameStrata = "Frame Schicht",
FrameLevelOffset = "Frame Level Offset ",
UseClassTexture = "Nutze Klassen Textur f\195\188r Spieler",
UseRaceTexture = "Nutze Rassen Textur f\195\188r Spieler NPCs",
Label = "Bezeichnung",
ShowCircularBorder = "Zeige kreisf\195\182rmigen Rand",
ResizeBasedOnMax = "Gr\195\182\195\159e an Maximalwert anpassen",
ShowDuration = "Zeige Dauer",
DurationHeight = "Dauer Schriftart H\195\182he",
DurationAlpha = "Dauer Alpha",
DurationColor = "Dauer Farbe",
DurationFont = "Dauer Schriftart",
DurationXOffset = "Dauer X Position",
DurationYOffset = "Dauer Y Position",
OutOfRange = "AUSSER REICHWEITE",
HideIfNoText = "Verstecke wenn kein Text",
HideOnMouseover = "Verstecke bei Mouseber\195\188hrung",
BackgroundTexture = "BG Textur",
HideBuffFrame = "Verstecke normalen Buff Frame",
HSpacing = "Horizontale Abst\195\164nde",
VSpacing = "Vertikale Abst\195\164nde",

	DurationFormat = "Use mm:ss Format",
	SafeCopy = "SAFE COPY",
	SafeLoad = "SAFE LOAD",
	Default = "Default",
	NewProfile = "New Profile",
	LoadProfile = "Load Profile",
	Create = "CREATE",
	ProfileCreated = "New profile created for Discord Unit Frames.",
	CurrentProfile = "Current Profile",
	FillDirection = "Fill Direction",
	ShowInCombat = "Show In Combat",
	HealthUpdating = "Show When Health Is Less Than Max",
	ManaUpdating = "Show When Mana Is Less Than Max",
	VerticalText = "Vertical Text",
	Outline = "Outline:",
	TrackReputation = "Track Reputation Instead",
	ShowTargetIcon = "Show Target Icon Instead",
	FrameToMove = "Frame To Move",
};

DUF_TEXTVARIABLES = {
"Zivilist - $cv",
"Klasse, Abk\195\188rzung - $ca",
"Klasse, Mob - $cy",
"Klasse, Player - $cl",
"Klassifikation ('Elite', etc.) - $cc",
"Klassification, Abk\195\188rzung - $cx",
"Farben Code - $co",
"Farben Kontext, Klasse - $cw",
"Farben Kontext, Schwierigkeit - $cq",
"Farben Kontext, Gesundheit - $ch",
"Farben Kontext, Mana - $cm",
"Farben Kontext, Power Type - $cz",
"Farben Kontext, Reaktion - $cr",
"Kombo Punkte - $cp",
"Kreatur Schwierigkeit ('Leicht', etc.) - $cd",
"Kreatur Familie ('Katze', etc.) - $cf",
"Kreatur Type ('Wildtier', etc.) - $ct",
"Todes Status - $ds",
"Fraktion - $fa",
"Geschlecht - $sx",
"Geschlecht, Abk\195\188rzung - $sa",
"Gilde - $gu",
"Gesundheit, momentan - $hc",
"Gesundheit, momentan Prozent - $hp",
"Gesundheit, verloren - $dt",
"Gesundheit, verloren Prozent - $dp",
"Gesundheit, Max - $hm",
"Gesundheit, Regen pro Sek - $hr",
"Gesundheit, Regen pro Tick - $ht",
"Ehre Prozent - $hn",
"Im Kampf - $ic",
"Tastenbindung - $kb",
"Level - $lv",
"Mana, momentan - $mc",
"Mana, momentan Prozent - $mp",
"Mana, verloren - $mx",
"Mana, verloren Prozent - $my",
"Mana, Max - $mm",
"Mana, Regen pro Sek - $mr",
"Mana, Regen pro Tick - $mt",
"Mana, Typ - $ml",
"Name - $nm",
"Next Level - $xn",
"Neeue Zeile - $nl",
"NPC - $np",
"Offline - $of",
"Au\195\159er Erkennungsreichweiche - $iv",
"Pet's momentane XP - $px",
"Pet's Zufriedenheit - $ph",
"Pet's XP ben\195\182tigt zum Level - $py",
"Pet's aktuelle XP Prozent - $pc",
"Pet's netto XP ben\195\182tigt zum Level - $pg",
"Pet's XP Prozent ben\195\182tigt zum Level - $pp",
"PvP aktiv - $pt",
"PvP Rang - $pr",
"PvP Rang Nummer - $pn",
"Rasse - $rc",
"Rasse, Abk\195\188rzung - $ra",
"Raid Gruppe - $rg",
"Reaktion ('Feindlich', etc.) - $re",
"Aktueller Schaden - $rd",
"Aktuelle Heilungen - $rh",
"Markiert - $do",
"Ziel: Kreatur Typ - $tt",
"Ziel: Gesundheit - $th",
"Ziel: Gesundheit Prozent - $ta",
"Ziel: Level - $tl",
"Ziel: Mana - $tm",
"Ziel: Mana Prozent - $tb",
"Ziel: Max Gesundheit - $tx",
"Ziel: Max Mana - $ty",
"Ziel: Name - $tn",
"Watched Faction - $wf",
	 "Watched Faction Current Rep - $wc",
	 "Watched Faction Max Rep - $wm",
	 "Watched Faction Reaction - $wr",
	 "Watched Faction Rep Percent - $wp",
"XP, Aktuell - $xc",
"XP, Aktuell Prozent - $xy",
"XP, Max ben\195\182tigt zum Level - $xl",
"XP, ben\195\182tigt zum Level - $xd",
"XP, ben\195\182tigt zum Level Prozent - $xx",
"XP, Ausgeruht Bonus - $xr",
"XP, Ausgeruht Prozent - $xb"
}

DUF_CLASSABBREV = {
[DUF_TEXT.Warrior] = "Kr",
[DUF_TEXT.Priest] = "Pr",
[DUF_TEXT.Rogue] = "Srk",
[DUF_TEXT.Shaman] = "Sma",
[DUF_TEXT.Mage] = "Ma",
[DUF_TEXT.Paladin] = "Pal",
[DUF_TEXT.Hunter] = "J\195\164",
[DUF_TEXT.Warlock] = "Hex",
[DUF_TEXT.Druid] = "Drd"
};

DUF_RACEABBREV = {
[DUF_TEXT.Undead] = "Un",
[DUF_TEXT.Tauren] = "Ta",
[DUF_TEXT.NightElf] = "NE",
[DUF_TEXT.Gnome] = "Gnm",
[DUF_TEXT.Dwarf] = "Zw",
[DUF_TEXT.Human] = "Men",
[DUF_TEXT.Troll] = "Trl",
[DUF_TEXT.Orc] = "Orc"
};

DUF_SEXABBREV = {
["Male"] = "M",
["Female"] = "W",
["Neuter"] = "N"
};

DUF_BORDER_STYLES = {
{ text="Gerade", value=1 },
{ text="Tooltip", value=2 },
{ text="Dialog", value=3 },
{ text="Schieber", value=4 }
}

DUF_COLOR_CONTEXTS = {
{ text="Keine", value=nil },
{ text="Schwierigkeit", value=1 },
{ text="Reaktion", value=2 },
{ text="Klasse", value=3 },
{ text="Gesundheit", value=4 },
{ text="Mana", value=5 }
}

DUF_CLICK_OPTIONS = {
{ text="Tu Nichts", value=nil },
{ text="Einheit anvisieren", value=1 },
{ text="Einheit assisten", value=2 },
{ text="Zeige Popup", value=3 }
}

DUF_CONNECT_OPTIONS = {
{ text="Oben bis Unten", value=1 },
{ text="Unten bis Oben", value=2 },
{ text="Links bis Rechts", value=3 },
{ text="Rechts bis Links", value=4 }
}

DUF_ANCHORS = {
{ text = "OBEN LINKS", value = "TOPLEFT" },
{ text = "OBEN", value = "TOP" },
{ text = "OBEN RECHTS", value = "TOPRIGHT" },
{ text = "LINKS", value = "LEFT" },
{ text = "MITTE", value = "CENTER" },
{ text = "RECHTS", value = "RIGHT" },
{ text = "UNTEN LINKS", value = "BOTTOMLEFT" },
{ text = "UNTEN", value = "BOTTOM" },
{ text = "UNTEN RECHTS", value = "BOTTOMRIGHT" }
};

DUF_ATTACH_FRAMES = {
{ text="UIParent", value="UIParent" },
{ text="Unit Frame", value="Unit Frame" },
{ text="Buff Frame", value="_Buffs" },
{ text="Klassen Icon", value="_ClassIcon" },
{ text="Debuff Frame", value="_Debuffs" },
{ text="Gesundheits Balken", value="_HealthBar" },
{ text="Anf\195\188hrer Icon", value="_LeaderIcon" },
{ text="Loot Icon", value="_LootIcon" },
{ text="Mana Balken", value="_ManaBar" },
{ text="Portr\195\164t", value="_Portrait" },
{ text="PvP Icon", value="_PVPIcon" },
{ text="Rassen Icon", value="_RaceIcon" },
{ text="Rang Icon", value="_RankIcon" },
{ text="Status Icon", value="_StatusIcon" },
{ text="Ziel Gesundheits Balken", value="_TargetHealthBar" },
{ text="Ziel Mana Balken", value="_TargetManaBar" },
{ text="TextBox 1", value="_TextBox_1" },
{ text="TextBox 2", value="_TextBox_2" },
{ text="TextBox 3", value="_TextBox_3" },
{ text="TextBox 4", value="_TextBox_4" },
{ text="TextBox 5", value="_TextBox_5" },
{ text="TextBox 6", value="_TextBox_6" },
{ text="TextBox 7", value="_TextBox_7" },
{ text="TextBox 8", value="_TextBox_8" },
{ text="TextBox 9", value="_TextBox_9" },
{ text="TextBox 10", value="_TextBox_10" }
};

DUF_COPY_FRAMES = {
{ text=DUF_TEXT.Self, value="player" },
{ text=DUF_TEXT.Party, value="party" },
{ text=DUF_TEXT.Target, value="target" },
{ text=DUF_TEXT.Pet, value="pet" },
{ text=DUF_TEXT.PartyPets, value="partypet" },
{ text=DUF_TEXT.TargetOfTarget, value="targettarget" }
}

DUF_JUSTIFICATION_HORIZONTAL = {
{ text="LINKS", value="LEFT" },
{ text="RECHTS", value="RIGHT" },
{ text="MITTE", value="CENTER" }
}

DUF_JUSTIFICATION_VERTICAL = {
{ text="OBEN", value="TOP" },
{ text="UNTEN", value="BOTTOM" },
{ text="MITTE", value="CENTER" }
}

DUF_MOUSEOVER_GROUPS = {
{ text="Keine", value=nil },
{ text="1", value=1 },
{ text="2", value=2 },
{ text="3", value=3 },
{ text="4", value=4 },
{ text="5", value=5 },
{ text="6", value=6 },
{ text="7", value=7 },
{ text="8", value=8 },
{ text="9", value=9 },
{ text="10", value=10 }
}
end

-- END OF GERMAN TRANSLATIONS


-- French translations courtesy of Miro.

if (GetLocale() == "frFR") then

DUF_ARROW_RIGHT = ">";
DUF_ARROW_LEFT = "<";
DUF_CLASSLABEL = "Classe:";
DUF_CONTEXTLABEL = "Couleurs Contextuelles:";
DUF_DIFFICULTYLABEL = "Difficult\195\169:";
DUF_HEALTHLABEL = "Vie:";
DUF_MANALABEL = "Mana:";
DUF_NUDGE = "D\195\169placer";
DUF_REACTIONLABEL = "R\195\169action:";

BINDING_NAME_DUF_OPTIONS = "Ouvre/Ferme Fen\195\170tre d\'Options";
BINDING_NAME_DUF_TOGGLE_ELEMENTS_LOCK = "Verrouille/D\195\169verrouille El\195\169ments";
BINDING_NAME_DUF_TOGGLE_FRAMES_LOCK = "Verrouille/D\195\169verrouille Fen\195\170tre";

DUF_TEXT = {
		Alliance = "Alliance",
		Alpha = "Transparence",
		AttachFrame = "Attacher Fen\195\170tre",
		AttachPoint = "Attacher Point",
		AttachTo = "Attacher \195\160",
		Background = "Fond",
		BackgroundAlpha = "Transparence Fond",
		BackgroundColor = "Couleur Fond",
		BackgroundPadding = "Remplissage du Fond",
		BarColor = "Couleur Barre",
		Base = "Base",
		Beast = "B\195\170te",
		Border = "Bord",
		BorderAlpha = "Transparence Bordure",
		BorderColor = "Couleur Bordure",
		BorderStyle = "Style de Bordure",
		Boss = "Boss",
		BuffFrame = "Fen\195\170tre Buff",
		BuffsShown = "Am\195\169liorations maximum affich\195\169es",
		ClassIcon = "Icone de Classe",
		Color = "Couleur",
		Combat = "En Combat",
		ComboPoints = "Points de Combo",
		ConnectFrames = "Connecter Fen\195\170tre",
		ContextColors = "Couleurs Contextuelles",
		Copy = "COPIER",
		CopyFrame = "Copier param\195\170tres depuis",
		Crit = "*CRITIQUE*",
		Critter = "Bestiole",
		CustomEliteTexture = "Texture Elite Perso",
		CustomRareTexture = "Texture Rare Perso",
		CustomSettingsLoaded = "Param\195\170tres personnalis\195\169s charg\195\169s.",
		CustomTooltip = "Tooltip Perso.",
		Dead = "Mort",
		DebuffFrame = "Fen\195\170tre Mal\195\169dictions",
		DebuffsShown = "Nb Mal\195\169dictions affich\195\169es",
		DefaultSettingsLoaded = "Param\195\170tres par d\195\169faut charg\195\169s.",
		Delete = "EFFACE",
		Demon = "D\195\169mon",
		DisableMouse = "D\195\169sactiver Souris",
		DisableTooltip = "D\195\169sactiver Tooltip",
		Dragonkin = "Dragonkin",
		Druid = "Druide",
		Dwarf = "Nain",
		Elemental = "El\195\169mentaire",
		Elite = "Elite",
		EliteTexture = "Texture Elite",
		Energy = "En\195\169rgie",
		EnergyColor = "Couleur \195\169n\195\169rgie",
		FacesLeft = "Regarde \195\160 gauche",
		Fade = "Descend progressivement",
		Female = "Femelle",
		Fill = "Remplis \195\160 la place de vider",
		FlashForLowHealth = "Clignotte quand la vie est basse",
		FlashWhenActive = "Clignotte quand Actif",
		Focus = "Focus",
		FocusColor = "Couleur Focus",
		Font = "Texte",
		FontHeight = "Hauteur Texte",
		FrameOptions = "Options Fen\195\170tre",
		Friendly = "Amical",
		FriendlyNPC = "PNJ Amical",
		FriendlyPlayer = "Joueur Alli\195\169",
		Ghost = "Fant\195\180me",
		Giant = "G\195\169ant",
		Gnome = "Gnome",
		HappinessIcon = "Icone Humeur",
		HealthBar = "Barre de Vie",
		HealthThreshold = "% de vie inf\195\169rieur \195\160 ",
		Height = "Hauteur",
		Hide = "Cacher",
		HideBackground = "Cacher Fond",
		HideIfNoMana = "Cache pour les unit\195\169s sans Mana",
		HidePartyInRaid = "Cache les fen\195\170tre de Groupe en Raid",
		HideTargetTarget = "Cache la cible de la cible en Solo",
		HonorBar = "Barre d\'honneur",
		Horde = "Horde",
		Hostile = "Hostile",
		Human = "Humain",
		Humanoid = "Humanoide",
		Hunter = "Chasseur",
		JustifyH = "Justification Horizontale",
		JustifyV = "Justification Verticale",
		LeaderIcon = "Icone Chef",
		LeftClick = "Click-Gauche",
		LevelDifference1 = "Triviale",
		LevelDifference2 = "Mineure",
		LevelDifference3 = "Identique",
		LevelDifference4 = "Dure",
		LevelDifference5 = "Tr\195\168s Dure",
		LevelDifference6 = "Suicidaire",
		Load = "CHARGE",
		LoadCustomSettings = "Charger param\195\170tres perso",
		LoadDefaultSettings = "Charger param\195\170tres d\195\169fauts",
		LoadSettings = "Charger param\195\170tres:",
		LockElements = "Verrouiller El\195\169ments",
		LockFrames = "Verrouiller Fen\195\170tres",
		LootIcon = "Icone Butin",
		LowHealthThreshold = "Limite de 'vie basse'",
		Mage = "Mage",
		Main = "Principal",
		Male = "Mâle",
		Mana = "Mana",
		ManaBar = "Barre de Mana",
		ManaColor = "Couleur Mana",
		ManaThreshold = "% de Mana inf\195\169rieur \195\160 ",
		MaxCharacters = "Nombre de Characteres Max",
		Method = "Methode",
		MiddleClick = "Click-Milieu",
		MiscOptions = "Options diverses",
		Mouseover = "Montrer au passage souris",
		MouseoverColor = "Couleur au passage souris",
		MouseoverGroup = "Groupe Passage Souris",
		Neuter = "Assexu\195\169",
		Neutral = "Neutre",
		NightElf = "Elfe de la nuit",
		NoCustomSettings = "Pas de param\195\170tres perso trouv\195\169s.",
		NoDefaultSettings = "Pas de param\195\170tres d\195\169fauts trouv\195\169s.",
		NoSettingsFound = "Pas de param\195\170tres trouv\195\169s.",
		NoTarget = "Pas de Cible",
		NotSpecified = "Non sp\195\169cifi\195\169",
		Offline = "D\195\169connect\195\169",
		OptionsScale = "Taille de la fen\195\170tre d\'options",
		Orc = "Orc",
		Paladin = "Paladin",
		Party = "GROUPE",
		PartyPets = "PETS Groupe",
		Pet = "PET",
		Portrait = "Portrait",
		Priest = "Pr\195\170tre",
		PVP = "JcJ",
		PVPFree = "JcJ Free For All",
		PVPFriendly = "Joueur JcJ-activ\195\169",
		PVPIcon = "Icone JcJ",
		QuickLoad = "Chargement rapide",
		QuickSave = "Sauvegarde rapide",
		RaceIcon = "Icone Race",
		Rage = "Rage",
		RageColor = "Couleur Rage",
		RankIcon = "Icone Rang",
		Rare = "Rare",
		RareElite = "Elite Rare",
		ReverseFill = "Inverser sens de remplissage",
		RightClick = "Click-Droit",
		Rogue = "Voleur",
		Save = "SAUVE",
		SaveSettings = "Sauve param\195\170tres: ",
		Scale = "Agrandir",
		SecondaryBarColor = "Couleur Barre Secondaire",
		Self = "MOI",
		SettingsDeleted = "Param\195\170tres effac\195\169s.",
		SettingsLoaded = "Nouveaux param\195\170tres charg\195\169s.",
		SettingsSaved = "Vos param\195\170tres ont \195\169t\195\169 sauvegard\195\169s.",
		Shaman = "Chaman",
		ShowDefault = "Montrer les fen\195\170tres d\'origine",
		Size = "Taille",
		Spacing = "Espacement",
		Special = "Sp\195\169cial",
		StatusIcon = "Icone Status",
		Summoned = "Invoqu\195\169",
		Tapped = "Engag\195\169",
		Target = "CIBLE",
		TargetHealthBar = "Barre de vie Cible",
		TargetManaBar = "Barre de Mana Cible",
		TargetOfTarget = "CIBLE de la CIBLE",
		TargetTapped = "Engag\195\169",
		Tauren = "Tauren",
		Text = "Texte",
		TextBox1 = "TextBox 1",
		TextBox2 = "TextBox 2",
		TextBox3 = "TextBox 3",
		TextBox4 = "TextBox 4",
		TextBox5 = "TextBox 5",
		TextBox6 = "TextBox 6",
		TextBox7 = "TextBox 7",
		TextBox8 = "TextBox 8",
		TextBox9 = "TextBox 9",
		TextBox10 = "TextBox 10",
		TextColor = "Couleur Texte",
		TextVariables = "Variables texte",
		Troll = "Troll",
		TwoRows = "2 Lignes/Colonnes",
		Undead = "Mort-Vivant",
		UnlockElements = "D\195\169verrouiller El\195\169ments",
		UnlockFrames = "D\195\169verrouiller Fen\195\170tres",
		UpdateSpeed = "MaJ par Seconde",
		VariablesTitle = "VARIABLES TEXTE DE DISCORD UNIT FRAME",
		VerticalLayout = "Disposition Verticale",
		Warlock = "D\195\169moniste",
		Warrior = "Guerrier",
		Width = "Largeur",
		XPBar = "Barre d\'XP",
		You = "* VOUS *",
		YourTarget = "* VOTRE CIBLE *",
		AutoLock = "Verrouiller fen\195\170tres et \195\169l\195\169ments quand cette fen\195\170tre est ferm\195\169e",
		CustomTexture = "Texture perso",
        CustomTexture2 = "Texture perso de la barre secondaire",
        FrameStrata = "Strate",
        FrameLevelOffset = "Ajuster strate       ",
        UseClassTexture = "Utiliser Texture de classe pour le joueur",
        UseRaceTexture = "Utiliser Texture de race pour les PnJ",
        Label = "Titre",
        ShowCircularBorder = "Affiche un bord circulaire",
        ResizeBasedOnMax = "Redimensionner selon la valeur max",
        ShowDuration = "Afficher les Dur\195\169es",
        DurationHeight = "Dur\195\169es - Hauteur de texte",
        DurationAlpha = "Dur\195\169es - Transparence",
        DurationColor = "Dur\195\169es - Couleur",
        DurationFont = "Dur\195\169es - Font",
        DurationXOffset = "Dur\195\169es - D\195\169calage en X",
        DurationYOffset = "Dur\195\169es - D\195\169calage en Y",
        OutOfRange = "Hors de port\195\169e",
        HideIfNoText = "Cacher Si pas de Texte",
        HideOnMouseover = "Cacher au passage souris",
        BackgroundTexture = "Texture du Fond",

		HideBuffFrame = "Hide Default Buff Frame",
		HSpacing = "Horizontal Spacing",
		VSpacing = "Vertical Spacing",
		DurationFormat = "Use mm:ss Format",
		SafeCopy = "SAFE COPY",
		SafeLoad = "SAFE LOAD",
		Default = "Default",
		NewProfile = "New Profile",
		LoadProfile = "Load Profile",
		Create = "CREATE",
		ProfileCreated = "New profile created for Discord Unit Frames.",
		CurrentProfile = "Current Profile",
		FillDirection = "Fill Direction",
		ShowInCombat = "Show In Combat",
		HealthUpdating = "Show When Health Is Less Than Max",
		ManaUpdating = "Show When Mana Is Less Than Max",
		VerticalText = "Vertical Text",
		Outline = "Outline:",
		TrackReputation = "Track Reputation Instead",
		ShowTargetIcon = "Show Target Icon Instead",
		FrameToMove = "Frame To Move",
	};

DUF_TEXTVARIABLES = {
	 "Civil - $cv",
	 "Classe, Abbr\195\169viation - $ca",
	 "Classe, Monstre - $cy",
	 "Classe, Joueur - $cl",
	 "Classification ('Elite', etc.) - $cc",
	 "Classification, Abbr\195\169viation - $cx",
	 "Code couleur- $co",
	 "Color Context, Class - $cw",
	 "Color Context, Difficulty - $cq",
	 "Color Context, Health - $ch",
	 "Color Context, Mana - $cm",
	 "Color Context, Power Type - $cz",
	 "Color Context, Reaction - $cr",
	 "Points de combo - $cp",
	 "Difficult\195\169 de la cr\195\169ature ('Triviale', etc.) - $cd",
	 "Famille de la cr\195\169ature ('Chat', etc.) - $cf",
	 "Type de cr\195\169ature ('B\195\170te', etc.) - $ct",
	 "Status Mort - $ds",
	 "Faction - $fa",
	 "Sexe - $sx",
	 "Sexe, Abbr\195\169viation - $sa",
	 "Guilde - $gu",
	 "Vie, Actuelle - $hc",
	 "Vie, % Actuelle - $hp",
	 "Vie, perdue - $dt",
	 "Vie, % perdue - $dp",
	 "Vie, Maximum - $hm",
	 "Vie, Gain par seconde - $hr",
	 "Vie, Gain par Cycle - $ht",
	 "Pourcentage d\'honneur - $hn",
	 "En combat - $ic",
	 "Keybinding - $kb",
	 "Niveau - $lv",
	 "Mana, Actuel - $mc",
	 "Mana, % Actuel - $mp",
	 "Mana, Perdu - $mx",
	 "Mana, % Perdu - $my",
	 "Mana, Maximum - $mm",
	 "Mana, Gain par seconde - $mr",
	 "Mana, Gain par cycle - $mt",
	 "Mana, Type - $ml",
	 "Nom - $nm",
	 "Next Level - $xn",
	 "Retour \195\160 la ligne - $nl",
	 "PNJ - $np",
	 "D\195\169connect\195\169 - $of",
	 "Out of Detect Range - $iv",
	 "XP actuelle du Pet - $px",
	 "Humeur du PET - $ph",
	 "XP n\195\169cessaire au PET pour niveau sup - $py",
	 "PET, XP actuelle en % - $pc", 
      "PET, XP N\195\169cessaire pour niveau sup. - $pg",
      "PET, % d'XP restant pour niveau sup. - $pp",
	 "JcJ Activ\195\169 - $pt",
	 "Rang JcJ - $pr",
	 "Nombre Rang JcJ - $pn",
	 "Race - $rc",
	 "Race, Abbr\195\169viation - $ra",
	 "Raid Group - $rg",
	 "R\195\169action ('Hostile', etc.) - $re",
	 "Dommages r\195\169cents - $rd",
	 "Soins r\195\169cents - $rh",
	 "Engag\195\169 - $do",
	 "Cible, Type de cr\195\169ature - $tt",
	 "Cible, Vie - $th",
	 "Cible, Vie en % - $ta",
	 "Cible, Niveau - $tl",
	 "Cible, Mana - $tm",
	 "Cible, Mana en % - $tb",
	 "Cible, Vie Maximum - $tx",
	 "Cible, Mana Maximum - $ty",
	 "Cible, Nom - $tn",
	 "Watched Faction - $wf",
	 "Watched Faction Current Rep - $wc",
	 "Watched Faction Max Rep - $wm",
	 "Watched Faction Reaction - $wr",
	 "Watched Faction Rep Percent - $wp",
	 "XP, Actuelle - $xc",
	 "XP, % Actuelle - $xy",
	 "XP, Totale du niveau - $xl",
	 "XP, N\195\169cessaire pour passer le niveau - $xd",
	 "XP, % restant avant le prochain niveau - $xx",
	 "XP, Bonus de repos - $xr",
	 "XP, Bonus de repos en Pourcent - $xb"
}

DUF_CLASSABBREV = {
		[DUF_TEXT.Warrior] = "Gue",
		[DUF_TEXT.Priest] = "Pre",
		[DUF_TEXT.Rogue] = "Vol",
		[DUF_TEXT.Shaman] = "Sha",
		[DUF_TEXT.Mage] = "Ma",
		[DUF_TEXT.Paladin] = "Pal",
		[DUF_TEXT.Hunter] = "Cha",
		[DUF_TEXT.Warlock] = "D\195\169mo",
		[DUF_TEXT.Druid] = "Dru"
	};

DUF_RACEABBREV = {
		[DUF_TEXT.Undead] = "MV",
		[DUF_TEXT.Tauren] = "Ta",
		[DUF_TEXT.NightElf] = "Elf",
		[DUF_TEXT.Gnome] = "Gnm",
		[DUF_TEXT.Dwarf] = "Na",
		[DUF_TEXT.Human] = "Hum",
		[DUF_TEXT.Troll] = "Trl",
		[DUF_TEXT.Orc] = "Orc"
	};

DUF_SEXABBREV = {
		["Male"] = "M",
		["Female"] = "F",
		["Neuter"] = "N"
	};

DUF_BORDER_STYLES = {
	{ text="Plein", value=1 },
	{ text="Tooltip", value=2 },
	{ text="Dialogue", value=3 },
	{ text="Ascenseur", value=4 }
}

DUF_COLOR_CONTEXTS = {
	{ text="Aucune", value=nil },
	{ text="Difficult\195\169", value=1 },
	{ text="R\195\169action", value=2 },
	{ text="Classe", value=3 },
	{ text="Vie", value=4 },
	{ text="Mana", value=5 }
}

DUF_CLICK_OPTIONS = {
	{ text="Ne fait rien", value=nil },
	{ text="Cible Unit\195\169", value=1 },
	{ text="Aide Unit\195\169", value=2 },
	{ text="Ouvre Menu", value=3 }
}

DUF_CONNECT_OPTIONS = {
	{ text="Haut avec Bas", value=1 },
	{ text="Bas avec Haut", value=2 },
	{ text="Gauche avec Droite", value=3 },
	{ text="Droite avec Gauche", value=4 }
}

DUF_ANCHORS = {
		{ text = "HAUTgauche", value = "TOPLEFT" },
		{ text = "HAUT", value = "TOP" },
		{ text = "HAUTdroite", value = "TOPRIGHT" },
		{ text = "GAUCHE", value = "LEFT" },
		{ text = "CENTRE", value = "CENTER" },
		{ text = "DROITE", value = "RIGHT" },
		{ text = "BASgauche", value = "BOTTOMLEFT" },
		{ text = "BAS", value = "BOTTOM" },
		{ text = "BASdroite", value = "BOTTOMRIGHT" }
	 };

DUF_ATTACH_FRAMES = {
	{ text="UIParent", value="UIParent" },
	{ text="Fen\195\170tre Unit\195\169", value="Unit Frame" },
	{ text="Fen\195\170tre Am\195\169lioration", value="_Buffs" },
	{ text="Icone Classe", value="_ClassIcon" },
	{ text="Fen\195\170tre Mal\195\169diction", value="_Debuffs" },
	{ text="Barre de Vie", value="_HealthBar" },
	{ text="Icone Chef", value="_LeaderIcon" },
	{ text="Icone Butin", value="_LootIcon" },
	{ text="Barre de Mana", value="_ManaBar" },
	{ text="Portrait", value="_Portrait" },
	{ text="Icone JcJ", value="_PVPIcon" },
	{ text="Icone Race", value="_RaceIcon" },
	{ text="Icone Rang", value="_RankIcon" },
	{ text="Icone Status", value="_StatusIcon" },
	{ text="Barre de Vie Cible", value="_TargetHealthBar" },
	{ text="Barre de Mana Cible", value="_TargetManaBar" },
	{ text="TextBox 1", value="_TextBox_1" },
	{ text="TextBox 2", value="_TextBox_2" },
	{ text="TextBox 3", value="_TextBox_3" },
	{ text="TextBox 4", value="_TextBox_4" },
	{ text="TextBox 5", value="_TextBox_5" },
	{ text="TextBox 6", value="_TextBox_6" },
	{ text="TextBox 7", value="_TextBox_7" },
	{ text="TextBox 8", value="_TextBox_8" },
	{ text="TextBox 9", value="_TextBox_9" },
	{ text="TextBox 10", value="_TextBox_10" }
};

DUF_JUSTIFICATION_HORIZONTAL = {
	{ text="GAUCHE", value="LEFT" },
	{ text="DROITE", value="RIGHT" },
	{ text="CENTRE", value="CENTER" }
}

DUF_JUSTIFICATION_VERTICAL = {
	{ text="HAUT", value="TOP" },
	{ text="BAS", value="BOTTOM" },
	{ text="CENTRE", value="CENTER" }
}

DUF_MOUSEOVER_GROUPS = {
	{ text="Aucun", value=nil },
	{ text="1", value=1 },
	{ text="2", value=2 },
	{ text="3", value=3 },
	{ text="4", value=4 },
	{ text="5", value=5 },
	{ text="6", value=6 },
	{ text="7", value=7 },
	{ text="8", value=8 },
	{ text="9", value=9 },
	{ text="10", value=10 }
}

end

-- END OF FRENCH TRANSLATIONS

DUF_OPTIONS_SCALES = {
	{ text="100", value=1 },
	{ text="90", value=.9 },
	{ text="80", value=.8 },
	{ text="70", value=.7 },
	{ text="60", value=.6 },
	{ text="50", value=.5 },
}

DUF_COPY_FRAMES = {
	{ text=DUF_TEXT.Self, value="player" },
	{ text=DUF_TEXT.Party, value="party" },
	{ text=DUF_TEXT.Target, value="target" },
	{ text=DUF_TEXT.Pet, value="pet" },
	{ text=DUF_TEXT.PartyPets, value="partypet" },
	{ text=DUF_TEXT.TargetOfTarget, value="targettarget" }
}

DUF_DEFAULT_SETTINGS = {};
DUF_ELEMENT_INDEX = nil;
DUF_ELEMENTS_UNLOCKED = nil;
DUF_FRAME_INDEX = nil;
DUF_FRAMES_UNLOCKED = nil;
DUF_INITIALIZED = nil;

DUF_FRAME_DATA = {
	player = { frame="DUF_PlayerFrame", index="player", elements= {"XPBar", "HonorBar"} },
	party1 = { frame="DUF_PartyFrame1", index="party", elements={} },
	party2 = { frame="DUF_PartyFrame2", index="party", elements={} },
	party3 = { frame="DUF_PartyFrame3", index="party", elements={} },
	party4 = { frame="DUF_PartyFrame4", index="party", elements={} },
	target = { frame="DUF_TargetFrame", index="target", elements={"ComboPoints"} },
	pet = { frame="DUF_PetFrame", index="pet", elements={"HappinessIcon", "PetXPBar"} },
	partypet1 = { frame="DUF_PartyPetFrame1", index="partypet", elements={} },
	partypet2 = { frame="DUF_PartyPetFrame2", index="partypet", elements={} },
	partypet3 = { frame="DUF_PartyPetFrame3", index="partypet", elements={} },
	partypet4 = { frame="DUF_PartyPetFrame4", index="partypet", elements={} },
	targettarget = { frame="DUF_TargetOfTargetFrame", index="targettarget", elements={} }
};

DUF_FRAME_INDICES = { "player", "pet", "party", "target", "partypet", "targettarget" };
DUF_ELEMENT_INDICES = { "TextBox", "StatusBar", "StatusIcon", "PVPIcon", "LootIcon", "LeaderIcon", "Debuffs", "Buffs", "Portrait", "ClassIcon", "RaceIcon", "RankIcon" };
DUF_STATUSBARS = { "_HealthBar", "_ManaBar", "_XPBar", "_TargetHealthBar", "_TargetManaBar", "_HonorBar" };

DUF_UNIT_CHANGED_EVENTS = {
	pet = "UNIT_PET",
	partypet1 = "UNIT_PET",
	partypet2 = "UNIT_PET",
	partypet3 = "UNIT_PET",
	partypet4 = "UNIT_PET",
	party1 = "PARTY_MEMBERS_CHANGED",
	party2 = "PARTY_MEMBERS_CHANGED",
	party3 = "PARTY_MEMBERS_CHANGED",
	party4 = "PARTY_MEMBERS_CHANGED",
	target = "PLAYER_TARGET_CHANGED"
}

DUF_TEXT_OUTLINES = {
	{text="NONE", value=nil},
	{text="NORMAL", value="NORMAL"},
	{text="THICK", value="THICK"}
}

DUF_FRAME_CHOICES = {
	{value = 1, text = 1}
}