
Nurfed_CombatLog_Strings = {
	Heal = {
		{ s = HEALEDCRITOTHEROTHER,	o = { 1, 2, 3, 4, "Heal", true },	t = "Heal" },
		{ s = HEALEDCRITOTHERSELF,	o = { 1, 2, YOU, 3, "Heal", true },	t = "Heal" },
		{ s = HEALEDCRITSELFOTHER,	o = { YOU, 1, 2, 3, "Heal", true },	t = "Heal" },
		{ s = HEALEDOTHEROTHER,		o = { 1, 2, 3, 4, "Heal", false },	t = "Heal" },
		{ s = HEALEDOTHERSELF,		o = { 1, 2, YOU, 3, "Heal", false },	t = "Heal" },
		{ s = HEALEDSELFOTHER,		o = { YOU, 1, 2, 3, "Heal", false },	t = "Heal" },
	},
	Hot = {
		{ s = PERIODICAURAHEALOTHEROTHER,	o = { 3, 4, 1, 2, "Heal", false },	t = "Heal" },
		{ s = PERIODICAURAHEALOTHERSELF,	o = { 2, 3, YOU, 1, "Heal", false },	t = "Heal" },
		{ s = PERIODICAURAHEALSELFOTHER,	o = { YOU, 3, 1, 2, "Heal", false },	t = "Heal" },
		{ s = PERIODICAURAHEALSELFSELF,		o = { YOU, 2, YOU, 1, "Heal", false },	t = "Heal" },
	},
	Hit = {
		{ s = COMBATHITCRITOTHEROTHER,		o = { 1, "Hit", 2, 3, SPELL_SCHOOL0_CAP, true },	t = "Hit" },
		{ s = COMBATHITCRITSCHOOLOTHEROTHER,	o = { 1, "Hit", 2, 3, 4, true },			t = "Hit" },
		{ s = COMBATHITCRITSELFOTHER,		o = { YOU, "Hit", 1, 2, SPELL_SCHOOL0_CAP, true },	t = "Hit" },
		{ s = COMBATHITCRITSCHOOLSELFOTHER,	o = { YOU, "Hit", 1, 2, 3, true },			t = "Hit" },
		{ s = COMBATHITOTHEROTHER,		o = { 1, "Hit", 2, 3, SPELL_SCHOOL0_CAP, false },	t = "Hit" },
		{ s = COMBATHITSCHOOLOTHEROTHER,	o = { 1, "Hit", 2, 3, 4, false },			t = "Hit" },
		{ s = COMBATHITSELFOTHER,		o = { YOU, "Hit", 1, 2, SPELL_SCHOOL0_CAP, false },	t = "Hit" },
		{ s = COMBATHITSCHOOLSELFOTHER,		o = { YOU, "Hit", 1, 2, 3, false },			t = "Hit" },
	},
	Spell = {
		{ s = SPELLLOGCRITOTHEROTHER,		o = { 1, 2, 3, 4, SPELL_SCHOOL0_CAP, true },	t = "Spell" },
		{ s = SPELLLOGCRITSELFOTHER,		o = { YOU, 1, 2, 3, SPELL_SCHOOL0_CAP, true },	t = "Spell" },
		{ s = SPELLLOGCRITSCHOOLOTHEROTHER,	o = { 1, 2, 3, 4, 5, true },			t = "Spell" },
		{ s = SPELLLOGCRITSCHOOLSELFOTHER,	o = { YOU, 1, 2, 3, 4, true },			t = "Spell" },
		{ s = SPELLLOGOTHEROTHER,		o = { 1, 2, 3, 4, SPELL_SCHOOL0_CAP, false },	t = "Spell" },
		{ s = SPELLLOGSELFOTHER,		o = { YOU, 1, 2, 3, SPELL_SCHOOL0_CAP, false },	t = "Spell" },
		{ s = SPELLLOGSCHOOLOTHEROTHER,		o = { 1, 2, 3, 4, 5, false },			t = "Spell" },
		{ s = SPELLLOGSCHOOLSELFOTHER,		o = { YOU, 1, 2, 3, 4, false },			t = "Spell" },
		{ s = DAMAGESHIELDOTHEROTHER,		o = { 1, REFLECT, 4, 2, 3, false },		t = "Spell" },
		{ s = DAMAGESHIELDSELFOTHER,		o = { YOU, REFLECT, 3, 1, 2, false },		t = "Spell" },
	},
	Dot = {
		{ s = PERIODICAURADAMAGEOTHEROTHER,	o = { 4, 5, 1, 2, 3, false },		t = "Dot" },
		{ s = PERIODICAURADAMAGEOTHERSELF,	o = { 3, 4, YOU, 1, 2, false },		t = "Dot" },
		{ s = PERIODICAURADAMAGESELFOTHER,	o = { YOU, 4, 1, 2, 3, false },		t = "Dot" },
		{ s = PERIODICAURADAMAGESELFSELF,	o = { YOU, 3, YOU, 1, 2, false },	t = "Dot" },
		{ s = SPELLPOWERLEECHOTHEROTHER,	o = { 1, 2, 5, 3, 4, false },		t = "Dot" },
		{ s = SPELLPOWERDRAINOTHEROTHER,	o = { 1, 2, 5, 3, 4, false },		t = "Dot" },
		{ s = SPELLPOWERLEECHSELFOTHER,		o = { YOU, 1, 4, 2, 3, false },		t = "Dot" },
		{ s = SPELLPOWERDRAINSELFOTHER,		o = { YOU, 1, 4, 2, 3, false },		t = "Dot" },
	},
	SpellMiss = {
		{ s = SPELLMISSOTHEROTHER,	o = { 1, 2, 3, MISS, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLMISSOTHERSELF,	o = { 1, 2, YOU, MISS, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLMISSSELFOTHER,	o = { YOU, 1, 2, MISS, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLPARRIEDOTHEROTHER,	o = { 1, 2, 3, PARRY, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLPARRIEDOTHERSELF,	o = { 1, 2, YOU, PARRY, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLPARRIEDSELFOTHER,	o = { YOU, 1, 2, PARRY, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLBLOCKEDOTHEROTHER,	o = { 1, 2, 3, BLOCK, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLBLOCKEDOTHERSELF,	o = { 1, 2, YOU, BLOCK, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLBLOCKEDSELFOTHER,	o = { YOU, 1, 2, BLOCK, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLDODGEDOTHEROTHER,	o = { 1, 2, 3, DODGE, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLDODGEDOTHERSELF,	o = { 1, 2, YOU, DODGE, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLDODGEDSELFOTHER,	o = { YOU, 1, 2, DODGE, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLIMMUNEOTHEROTHER,	o = { 1, 2, 3, IMMUNE, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLIMMUNEOTHERSELF,	o = { 1, 2, YOU, IMMUNE, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLIMMUNESELFOTHER,	o = { YOU, 1, 2, IMMUNE, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLEVADEDOTHEROTHER,	o = { 1, 2, 3, EVADE, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLEVADEDOTHERSELF,	o = { 1, 2, YOU, EVADE, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLEVADEDSELFOTHER,	o = { YOU, 1, 2, EVADE, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLLOGABSORBOTHEROTHER,	o = { 1, 2, 3, ABSORB, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLLOGABSORBOTHERSELF,	o = { 1, 2, YOU, ABSORB, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
		{ s = SPELLLOGABSORBSELFOTHER,	o = { YOU, 1, 2, ABSORB, SPELL_SCHOOL0_CAP, false },	t = "SpellMiss" },
	},
	Env = {
		{ s = VSENVIRONMENTALDAMAGE_FALLING_OTHER,	o = { 1, "Falls", 2, SPELL_SCHOOL0_CAP },		t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_FALLING_SELF,	o = { YOU, "Fall", 1, SPELL_SCHOOL0_CAP },		t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_FIRE_OTHER,		o = { 1, SPELL_SCHOOL2_CAP, 2, SPELL_SCHOOL2_CAP },	t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_FIRE_SELF,		o = { YOU, SPELL_SCHOOL2_CAP, 1, SPELL_SCHOOL2_CAP },	t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_LAVA_OTHER,		o = { 1, "Lava", 2, SPELL_SCHOOL2_CAP },		t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_LAVA_SELF,		o = { YOU, "Lava", 1, SPELL_SCHOOL2_CAP },		t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_DROWNING_OTHER,	o = { 1, "Drowns", 2, SPELL_SCHOOL4_CAP },		t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_DROWNING_SELF,	o = { YOU, "Drown", 1, SPELL_SCHOOL4_CAP },		t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_FATIGUE_OTHER,	o = { 1, TUTORIAL_TITLE27, 2, SPELL_SCHOOL0_CAP },	t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_FATIGUE_SELF,	o = { YOU, TUTORIAL_TITLE27, 1, SPELL_SCHOOL0_CAP },	t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_SLIME_OTHER,	o = { 1, "Slime", 2, SPELL_SCHOOL3_CAP },		t = "Environment" },
		{ s = VSENVIRONMENTALDAMAGE_SLIME_SELF,		o = { YOU, "Slime", 1, SPELL_SCHOOL3_CAP },		t = "Environment" },
	},
	Death = {
		{ s = PARTYKILLOTHER,		o = { 1, "Dies", 2 },		t = "Death" },
		{ s = SELFKILLOTHER,		o = { 1, "Dies", YOU },		t = "Death" },
		{ s = UNITDIESOTHER,		o = { 1, "Dies", false },	t = "Death" },
		{ s = UNITDIESSELF,		o = { YOU, "Die", false },	t = "Death" },
		{ s = UNITDESTROYEDOTHER,	o = { 1, "Destroyed", false },	t = "Destroyed" },
	},
	Aura = {
		{ s = POWERGAINOTHEROTHER,	o = { 1, 2, 3, 5 },		t = "PowerGain" },
		{ s = POWERGAINOTHERSELF,	o = { YOU, 1, 2, 4 },		t = "PowerGain" },
		{ s = POWERGAINSELFSELF,	o = { YOU, 1, 2, 3 },		t = "PowerGain" },
		{ s = AURAADDEDOTHERHARMFUL,	o = { 1, "Afflicted by", 2 },	t = "Debuff" },
		{ s = AURAADDEDSELFHARMFUL,	o = { YOU, "Afflicted by", 1 },	t = "Debuff" },
		{ s = AURAADDEDOTHERHELPFUL,	o = { 1, "Gains", 2 },		t = "Buff" },
		{ s = AURAADDEDSELFHELPFUL,	o = { YOU, "Gain", 1 },		t = "Buff" },
		{ s = AURAREMOVEDOTHER,		o = { 2, 1, "Fades" },		t = "AuraFade" },
		{ s = AURADISPELOTHER,		o = { 1, 2, "Removed" },	t = "AuraFade" },
		{ s = AURADISPELSELF,		o = { YOU, 1, "Removed" },	t = "AuraFade" },
	},
	Miss = {
		{ s = MISSEDOTHEROTHER,		o = { 1, MISS, 2 },	t = "MeleeMiss" },
		{ s = MISSEDSELFOTHER,		o = { YOU, MISS, 1 },	t = "MeleeMiss" },
		{ s = VSABSORBOTHEROTHER,	o = { 2, ABSORB, 1 },	t = "MeleeMiss" },
		{ s = VSABSORBOTHERSELF,	o = { YOU, ABSORB, 1 },	t = "MeleeMiss" },
		{ s = VSABSORBSELFOTHER,	o = { 1, ABSORB, YOU },	t = "MeleeMiss" },
		{ s = VSBLOCKOTHEROTHER,	o = { 2, BLOCK, 1 },	t = "MeleeMiss" },
		{ s = VSBLOCKOTHERSELF,		o = { YOU, BLOCK, 1 },	t = "MeleeMiss" },
		{ s = VSBLOCKSELFOTHER,		o = { 1, BLOCK, YOU },	t = "MeleeMiss" },
		{ s = VSDEFLECTOTHEROTHER,	o = { 2, DEFLECT, 1 },	t = "MeleeMiss" },
		{ s = VSDEFLECTOTHERSELF,	o = { YOU, DEFLECT, 1 },t = "MeleeMiss" },
		{ s = VSDEFLECTSELFOTHER,	o = { 1, DEFLECT, YOU },t = "MeleeMiss" },
		{ s = VSDODGEOTHEROTHER,	o = { 2, DODGE, 1 },	t = "MeleeMiss" },
		{ s = VSDODGEOTHERSELF,		o = { YOU, DODGE, 1 },	t = "MeleeMiss" },
		{ s = VSDODGESELFOTHER,		o = { 1, DODGE, YOU },	t = "MeleeMiss" },
		{ s = VSEVADEOTHEROTHER,	o = { 2, EVADE, 1 },	t = "MeleeMiss" },
		{ s = VSEVADEOTHERSELF,		o = { YOU, EVADE, 1 },	t = "MeleeMiss" },
		{ s = VSEVADESELFOTHER,		o = { 1, EVADE, YOU },	t = "MeleeMiss" },
		{ s = VSIMMUNEOTHEROTHER,	o = { 2, IMMUNE, 1 },	t = "MeleeMiss" },
		{ s = VSIMMUNEOTHERSELF,	o = { YOU, IMMUNE, 1 },	t = "MeleeMiss" },
		{ s = VSIMMUNESELFOTHER,	o = { 1, IMMUNE, YOU },	t = "MeleeMiss" },
		{ s = VSPARRYOTHEROTHER,	o = { 2, PARRY, 1 },	t = "MeleeMiss" },
		{ s = VSPARRYOTHERSELF,		o = { YOU, PARRY, 1 },	t = "MeleeMiss" },
		{ s = VSPARRYSELFOTHER,		o = { 1, PARRY, YOU },	t = "MeleeMiss" },
		{ s = VSRESISTOTHEROTHER,	o = { 2, RESIST, 1 },	t = "MeleeMiss" },
		{ s = VSRESISTOTHERSELF,	o = { YOU, RESIST, 1 },	t = "MeleeMiss" },
		{ s = VSRESISTSELFOTHER,	o = { 1, RESIST, YOU },	t = "MeleeMiss" },
	},
	Resists = {
		{ s = SPELLRESISTOTHEROTHER,	o = { 1, 2, 3, RESIST },	t = "Resist", },
		{ s = SPELLRESISTOTHERSELF,	o = { 1, 2, YOU, RESIST },	t = "Resist" },
		{ s = SPELLRESISTSELFOTHER,	o = { YOU, 1, 2, RESIST },	t = "Resist" },
		{ s = SPELLRESISTSELFSELF,	o = { YOU, 1, YOU, RESIST},	t = "Resist" },
		{ s = PROCRESISTOTHEROTHER,	o = { 2, 3, 1, RESIST},		t = "Resist" },
		{ s = PROCRESISTOTHERSELF,	o = { 1, 2, YOU, RESIST},	t = "Resist" },
		{ s = PROCRESISTSELFOTHER,	o = { YOU, 2, 1, RESIST},	t = "Resist" },
		{ s = PROCRESISTSELFSELF,	o = { YOU, 1, YOU, RESIST},	t = "Resist" },
	},
	SpellFail = {
		{ s = DISPELFAILEDOTHEROTHER,	o = { 1, 3, 2, REMOVE },	t = "SpellFail" },
		{ s = DISPELFAILEDOTHERSELF,	o = { 1, 2, YOU, REMOVE },	t = "SpellFail" },
		{ s = DISPELFAILEDSELFOTHER,	o = { YOU, 2, 1, REMOVE },	t = "SpellFail" },
		{ s = SPELLREFLECTOTHEROTHER,	o = { 1, 2, 3, REFLECT },	t = "SpellFail" },
		{ s = SPELLREFLECTOTHERSELF,	o = { 1, 2, YOU, REFLECT },	t = "SpellFail" },
		{ s = SPELLREFLECTSELFOTHER,	o = { YOU, 1, 2, REFLECT },	t = "SpellFail" },
		{ s = SPELLINTERRUPTOTHEROTHER,	o = { 1, INTERRUPT, 2, 3 },	t = "SpellFail" },
		{ s = SPELLINTERRUPTOTHERSELF,	o = { 1, INTERRUPT, YOU, 2 },	t = "SpellFail" },
		{ s = SPELLINTERRUPTSELFOTHER,	o = { YOU, INTERRUPT, 1, 2 },	t = "SpellFail" },
	},
	Cast = {
		{ s = SPELLCASTOTHERSTART,	o = { 1, 2, false },	t = "Cast" },
	},
	Perform = {
		{ s = SPELLPERFORMGOOTHERTARGETTED,	o = { 1, 2, 3},		t = "Perform" },
		{ s = SPELLPERFORMGOSELFTARGETTED,	o = { YOU, 1, 2 },	t = "Perform" },
		{ s = SIMPLECASTOTHEROTHER,		o = { 1, 2, 3 },	t = "Perform" },
		{ s = SIMPLECASTSELFOTHER,		o = { YOU, 1, 2 },	t = "Perform" },
		{ s = SPELLPERFORMGOOTHER,		o = { 1, 2, false },	t = "Perform" },
		{ s = SPELLPERFORMOTHERSTART,		o = { 1, 2, false },	t = "Perform" },
		{ s = SPELLPERFORMSELFSTART,		o = { YOU, 1, false },	t = "Perform" },
		{ s = SPELLCASTGOOTHER,			o = { 1, 2, false },	t = "Perform" },
		{ s = SIMPLECASTSELFSELF,		o = { YOU, 1, false },	t = "Perform" },
	},
};

Nurfed_CombatLog_Trailers = {
	{ s = ABSORB_TRAILER,	o = "|cff00ff00A:|r" },
	{ s = BLOCK_TRAILER,	o = "|cff00ff00B:|r" },
	{ s = RESIST_TRAILER,	o = "|cff00ff00R:|r" },
};