TITAN_PETINFO_FORMAT = "%d";
TITAN_PETINFO_BUTTON_LABEL_PETINFO = "Pet: ";
TITAN_PETINFO_BUTTON_LABEL_PETLEVEL = "Level: ";
TITAN_PETINFO_BUTTON_LABEL_TYPE = "Type: ";
TITAN_PETINFO_BUTTON_LABEL_NOPET = "No pet summoned.";
TITAN_PETINFO_BUTTON_LABEL_FOOD = "Eats: ";
TITAN_PETINFO_BUTTON_LABEL_LOYALTY = "Loyalty: ";
TITAN_PETINFO_BUTTON_LABEL_TRAINING_POINTS = "Training Points: ";
TITAN_PETINFO_BUTTON_LABEL_ARMOR_CLASS = "Armor Class: ";
TITAN_PETINFO_BUTTON_LABEL_ATTACK_SPEED = "Attack Speed: ";
TITAN_PETINFO_BUTTON_LABEL_ATTACK_RATE = "Attack Rate: ";
TITAN_PETINFO_BUTTON_LABEL_DPS_ACTUAL = "Actual DPS: ";
TITAN_PETINFO_BUTTON_LABEL_DPS_LISTED = "Listed DPS: ";
TITAN_PETINFO_BUTTON_LABEL_CURRENT_XP = "Current XP: ";
TITAN_PETINFO_BUTTON_LABEL_NEEDED_XP = "Needed XP: ";
TITAN_PETINFO_BUTTON_LABEL_TOTAL_XP = "Required XP: ";
TITAN_PETINFO_BUTTON_LABEL_LEVEL_TIME_LEFT = "Time to Level: ";
TITAN_PETINFO_BUTTON_LABEL_XP_PER_MIN = "XP Per Minute: ";
TITAN_PETINFO_TOOLTIP = "Pet Info";
TITAN_PETINFO_MENU_TEXT = "Pet Info";
TITAN_PETINFO_NOLEVEL1 = "Not gaining XP due";
TITAN_PETINFO_NOLEVEL2 = "to level restriction";
TITAN_PETINFO_MENU_SHOW_PET_NAME = "Show pet's name.";
TITAN_PETINFO_MENU_SHOW_PET_LEVEL = "Show pet's level.";
TITAN_PETINFO_MENU_SHOW_BAR_TEXT = "Show pet's XP info in XP bar.";
TITAN_PETINFO_MENU_SHOW_PET_ATTRIB = "Show pet's attributes.";
TITAN_PETINFO_MENU_RESET_SESSION = "Reset session";
TITAN_PETINFO_MENU_GENDER = "Gender";
TITAN_PETINFO_MENU_MALE = "Male";
TITAN_PETINFO_MENU_FEMALE = "Female";

-- German localization
-- by Scarabeus
if ( GetLocale() == "deDE" ) then

TITAN_PETINFO_FORMAT = "%d";
TITAN_PETINFO_BUTTON_LABEL_PETINFO = "Pet: ";
TITAN_PETINFO_BUTTON_LABEL_PETLEVEL = "Level: ";
TITAN_PETINFO_BUTTON_LABEL_TYPE = "Typ: ";
TITAN_PETINFO_BUTTON_LABEL_NOPET = "Kein Begleiter vorhanden.";
TITAN_PETINFO_BUTTON_LABEL_FOOD = "Frist: ";
TITAN_PETINFO_BUTTON_LABEL_LOYALTY = "Treue: ";
TITAN_PETINFO_BUTTON_LABEL_TRAINING_POINTS = "Ausbildungspunkte: ";
TITAN_PETINFO_BUTTON_LABEL_ARMOR_CLASS = "R\195\188stung: ";
TITAN_PETINFO_BUTTON_LABEL_ATTACK_SPEED = "Angriffs Speed: ";
TITAN_PETINFO_BUTTON_LABEL_ATTACK_RATE = "Angriff: ";
TITAN_PETINFO_BUTTON_LABEL_DPS_ACTUAL = "Actual DPS: ";
TITAN_PETINFO_BUTTON_LABEL_DPS_LISTED = "Listed DPS: ";
TITAN_PETINFO_BUTTON_LABEL_CURRENT_XP = "Erhaltende XP: ";
TITAN_PETINFO_BUTTON_LABEL_NEEDED_XP = "Ben\195\182tigte XP: ";
TITAN_PETINFO_BUTTON_LABEL_TOTAL_XP = "Erforderliche XP: ";
TITAN_PETINFO_BUTTON_LABEL_LEVEL_TIME_LEFT = "Zeit zum Levelup: ";
TITAN_PETINFO_BUTTON_LABEL_XP_PER_MIN = "XP pro Minute: ";
TITAN_PETINFO_TOOLTIP = "Begleiter Info";
TITAN_PETINFO_MENU_TEXT = "Begleiter Info";
TITAN_PETINFO_NOLEVEL1 = "Noch keine XP erhalten";
TITAN_PETINFO_NOLEVEL2 = "zur Level Berechnung";
TITAN_PETINFO_MENU_SHOW_PET_NAME = "Name vom Pet anzeigen.";
TITAN_PETINFO_MENU_SHOW_PET_LEVEL = "Level vom Pet anzeigen.";
TITAN_PETINFO_MENU_SHOW_BAR_TEXT = "Show pet's XP info in XP bar.";
TITAN_PETINFO_MENU_SHOW_PET_ATTRIB = "Show pet's attributes.";
TITAN_PETINFO_MENU_RESET_SESSION = "Reset session";
TITAN_PETINFO_MENU_GENDER = "Gender";
TITAN_PETINFO_MENU_MALE = "Male";
TITAN_PETINFO_MENU_FEMALE = "Female";

end


-- French localization
if ( GetLocale() == "frFR" ) then

TITAN_PETINFO_FORMAT = "%d";
TITAN_PETINFO_BUTTON_LABEL_PETINFO = "Pet: ";
TITAN_PETINFO_BUTTON_LABEL_PETLEVEL = "Level: ";
TITAN_PETINFO_BUTTON_LABEL_TYPE = "Type: ";
TITAN_PETINFO_BUTTON_LABEL_NOPET = "No pet summoned.";
TITAN_PETINFO_BUTTON_LABEL_FOOD = "Eats: ";
TITAN_PETINFO_BUTTON_LABEL_LOYALTY = "Loyalty: ";
TITAN_PETINFO_BUTTON_LABEL_TRAINING_POINTS = "Training Points: ";
TITAN_PETINFO_BUTTON_LABEL_ARMOR_CLASS = "Armor Class: ";
TITAN_PETINFO_BUTTON_LABEL_ATTACK_SPEED = "Attack Speed: ";
TITAN_PETINFO_BUTTON_LABEL_ATTACK_RATE = "Attack Rate: ";
TITAN_PETINFO_BUTTON_LABEL_DPS_ACTUAL = "Actual DPS: ";
TITAN_PETINFO_BUTTON_LABEL_DPS_LISTED = "Listed DPS: ";
TITAN_PETINFO_BUTTON_LABEL_CURRENT_XP = "Current XP: ";
TITAN_PETINFO_BUTTON_LABEL_NEEDED_XP = "Needed XP: ";
TITAN_PETINFO_BUTTON_LABEL_TOTAL_XP = "Required XP: ";
TITAN_PETINFO_BUTTON_LABEL_LEVEL_TIME_LEFT = "Time to Level: ";
TITAN_PETINFO_BUTTON_LABEL_XP_PER_MIN = "XP Per Minute: ";
TITAN_PETINFO_TOOLTIP = "Pet Info";
TITAN_PETINFO_MENU_TEXT = "Pet Info";
TITAN_PETINFO_NOLEVEL1 = "Not gaining XP due";
TITAN_PETINFO_NOLEVEL2 = "to level restriction";
TITAN_PETINFO_MENU_SHOW_PET_NAME = "Show pet's name.";
TITAN_PETINFO_MENU_SHOW_PET_LEVEL = "Show pet's level.";
TITAN_PETINFO_MENU_SHOW_BAR_TEXT = "Show pet's XP info in XP bar.";
TITAN_PETINFO_MENU_SHOW_PET_ATTRIB = "Show pet's attributes.";
TITAN_PETINFO_MENU_RESET_SESSION = "Reset session";
TITAN_PETINFO_MENU_GENDER = "Gender";
TITAN_PETINFO_MENU_MALE = "Male";
TITAN_PETINFO_MENU_FEMALE = "Female";

end

-- Korean localization
if ( GetLocale() == "koKR" ) then

TITAN_PETINFO_FORMAT = "%d";
TITAN_PETINFO_BUTTON_LABEL_PETINFO = "Pet: ";
TITAN_PETINFO_BUTTON_LABEL_PETLEVEL = "Level: ";
TITAN_PETINFO_BUTTON_LABEL_TYPE = "Type: ";
TITAN_PETINFO_BUTTON_LABEL_NOPET = "No pet summoned.";
TITAN_PETINFO_BUTTON_LABEL_FOOD = "Eats: ";
TITAN_PETINFO_BUTTON_LABEL_LOYALTY = "Loyalty: ";
TITAN_PETINFO_BUTTON_LABEL_TRAINING_POINTS = "Training Points: ";
TITAN_PETINFO_BUTTON_LABEL_ARMOR_CLASS = "Armor Class: ";
TITAN_PETINFO_BUTTON_LABEL_ATTACK_SPEED = "Attack Speed: ";
TITAN_PETINFO_BUTTON_LABEL_ATTACK_RATE = "Attack Rate: ";
TITAN_PETINFO_BUTTON_LABEL_DPS_ACTUAL = "Actual DPS: ";
TITAN_PETINFO_BUTTON_LABEL_DPS_LISTED = "Listed DPS: ";
TITAN_PETINFO_BUTTON_LABEL_CURRENT_XP = "Current XP: ";
TITAN_PETINFO_BUTTON_LABEL_NEEDED_XP = "Needed XP: ";
TITAN_PETINFO_BUTTON_LABEL_TOTAL_XP = "Required XP: ";
TITAN_PETINFO_BUTTON_LABEL_LEVEL_TIME_LEFT = "Time to Level: ";
TITAN_PETINFO_BUTTON_LABEL_XP_PER_MIN = "XP Per Minute: ";
TITAN_PETINFO_TOOLTIP = "Pet Info";
TITAN_PETINFO_MENU_TEXT = "Pet Info";
TITAN_PETINFO_NOLEVEL1 = "Not gaining XP due";
TITAN_PETINFO_NOLEVEL2 = "to level restriction";
TITAN_PETINFO_MENU_SHOW_PET_NAME = "Show pet's name.";
TITAN_PETINFO_MENU_SHOW_PET_LEVEL = "Show pet's level.";
TITAN_PETINFO_MENU_SHOW_BAR_TEXT = "Show pet's XP info in XP bar.";
TITAN_PETINFO_MENU_SHOW_PET_ATTRIB = "Show pet's attributes.";
TITAN_PETINFO_MENU_RESET_SESSION = "Reset session";
TITAN_PETINFO_MENU_GENDER = "Gender";
TITAN_PETINFO_MENU_MALE = "Male";
TITAN_PETINFO_MENU_FEMALE = "Female";

end
