if (GetLocale() == "zhTW") then
	-- Class Names
	PERL_LOCALIZED_DRUID = "德魯伊";
	PERL_LOCALIZED_HUNTER = "獵人";
	PERL_LOCALIZED_MAGE = "法師";
	PERL_LOCALIZED_PALADIN = "聖騎士";
	PERL_LOCALIZED_PRIEST = "牧師";
	PERL_LOCALIZED_ROGUE = "盜賊";
	PERL_LOCALIZED_SHAMAN = "薩滿";
	PERL_LOCALIZED_WARLOCK = "術士";
	PERL_LOCALIZED_WARRIOR = "戰士";

	-- Creature Types
	PERL_LOCALIZED_CIVILIAN = "平民";
	PERL_LOCALIZED_CREATURE = "生物";
	PERL_LOCALIZED_NOTSPECIFIED = "非特定的";
end