if (GetLocale() == "zhCN") then
	-- Class Names
	PERL_LOCALIZED_DRUID = "德鲁伊";
	PERL_LOCALIZED_HUNTER = "猎人";
	PERL_LOCALIZED_MAGE = "法师";
	PERL_LOCALIZED_PALADIN = "圣骑士";
	PERL_LOCALIZED_PRIEST = "牧师";
	PERL_LOCALIZED_ROGUE = "盗贼";
	PERL_LOCALIZED_SHAMAN = "萨满祭司";
	PERL_LOCALIZED_WARLOCK = "术士";
	PERL_LOCALIZED_WARRIOR = "战士";

	-- Creature Types
	PERL_LOCALIZED_CIVILIAN = "平民";
	PERL_LOCALIZED_CREATURE = "生物";
	PERL_LOCALIZED_NOTSPECIFIED = "非特定的";
end