if (GetLocale() == "esES") then
	-- Class Names
	PERL_LOCALIZED_DRUID = "Druida";
	PERL_LOCALIZED_HUNTER = "Cazador";
	PERL_LOCALIZED_MAGE = "Mago";
	PERL_LOCALIZED_PALADIN = "Paladín";
	PERL_LOCALIZED_PRIEST = "Sacerdote";
	PERL_LOCALIZED_ROGUE = "Pícaro";
	PERL_LOCALIZED_SHAMAN = "Cham\195\161n";
	PERL_LOCALIZED_WARLOCK = "Brujo";
	PERL_LOCALIZED_WARRIOR = "Guerrero";

	-- Creature Types
	PERL_LOCALIZED_CIVILIAN = "Civil";
	PERL_LOCALIZED_CREATURE = "Bestia";
	PERL_LOCALIZED_NOTSPECIFIED = "No Especificado";

	-- Debuff Types
	PERL_LOCALIZED_BUFF_CURSE = "Maldici\195\179n";
	PERL_LOCALIZED_BUFF_DISEASE = "Enfermedad";
	PERL_LOCALIZED_BUFF_MAGIC = "Magia";
	PERL_LOCALIZED_BUFF_POISON = "Veneno";

	-- Status Types
	PERL_LOCALIZED_STATUS_DEAD = "Muerto";
	PERL_LOCALIZED_STATUS_FEIGNDEATH = "Fingir Muerte";
	PERL_LOCALIZED_STATUS_OFFLINE = "Desconectado";
	PERL_LOCALIZED_STATUS_RESURRECTED = "Resucitado";
	PERL_LOCALIZED_STATUS_SS_AVAILABLE = "SS Disponible";

	-- Perl ArcaneBar Strings
	PERL_LOCALIZED_ARCANEBAR_CHANNELING = "Channeling";

	-- Perl Config Strings
	PERL_LOCALIZED_CONFIG_MINIMAP_LOCK = "Clic derecho BLOQUEARA todas las ventanas";
	PERL_LOCALIZED_CONFIG_MINIMAP_UNLOCK = "Clic derecho DESBLOQUEARA todas las ventanas";

	-- Perl Player Strings
	PERL_LOCALIZED_PLAYER_GROUP = "Grupo ";
	PERL_LOCALIZED_PLAYER_LEVEL_SEVENTY = "Nivel 70";
	PERL_LOCALIZED_PLAYER_NOMORE_EXPERIENCE = "¡No puedes ganar m\195\161s experiencia!";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_ONE = "Odiado";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_TWO = "Hostil";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_THREE = "Enemistoso";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FOUR = "Neutral";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FIVE = "Amistoso";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SIX = "Honorado";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SEVEN = "Venerado";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_EIGHT = "Exaltado";
	PERL_LOCALIZED_PLAYER_NO_REPUTATION = "No se est\195\161 monitorizando ninguna reputaci\195\179n.";
	PERL_LOCALIZED_PLAYER_SELECT_REPUTATION = "Selecciona una Reputaci\195\179n";
	PERL_LOCALIZED_PLAYER_UNRANKED = "No tienes Rango.";

	-- Perl Target Strings
	PERL_LOCALIZED_TARGET_BOSS = "Jefe";
	PERL_LOCALIZED_TARGET_ELITE = "\195\137lite";
	PERL_LOCALIZED_TARGET_RARE = "Raro";
	PERL_LOCALIZED_TARGET_RAREELITE = "Raro+";
	PERL_LOCALIZED_TARGET_FIRE_VULNERABILITY = "Vulnerable al Fuego";
	PERL_LOCALIZED_TARGET_SHADOW_VULNERABILITY = "Vulnerable a la Sombra";
	PERL_LOCALIZED_TARGET_SUNDER_ARMOR = "Separar Armadura";

	-- Perl Target Target Strings
	PERL_LOCALIZED_TARGET_TARGET_CHANGED_TO_YOU = " va ahora a por ti!";

	-- Perl Config Key Binging Strings
	BINDING_HEADER_PERLCONFIG = PERL_LOCALIZED_NAME;
	BINDING_NAME_TOGGLEOPTIONS = "Alternar Men\195\186 de Opciones";

	-- Perl Raid Key Binging Strings
	BINDING_HEADER_PERLRAID = "Perl Raid";
	BINDING_NAME_SHOWHIDE = "Mostrar Ventanas de Banda";
	BINDING_NAME_TOGGLECLASS = "Ordenar por Grupos/Clases";
end