--[[
	WARNING: This file is automatically generated from those in the
	locales directory. Do not edit it directly.


	$Id: buildLocales.pl 280 2005-09-22 14:14:27Z norganna $
	Version: 3.1.0.0445
]]






-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================

-- ============= AUTOMATICALLY GENERATED FILE =============
-- ================= DON'T EDIT THIS FILE =================






_AUCT = {};

AUCT_VALID_LOCALES = {["deDE"] = true, ["enUS"] = true, ["esES"] = true, ["frFR"] = true};

function Auctioneer_SetLocaleStrings(locale)
-- Default locale strings are defined in English
	
	
	_AUCT['AdditAlcohol'] = "Alcohol";
	_AUCT['AdditBuff'] = "Buff";
	_AUCT['AdditDrink'] = "Drink";
	_AUCT['AdditFirework'] = "Firework";
	_AUCT['AdditFood'] = "Food";
	_AUCT['AdditGiftwrap'] = "Giftwrap";
	_AUCT['AdditLure'] = "Lure";
	_AUCT['AdditPoison'] = "Poison";
	_AUCT['AdditPotion'] = "Potion";
	_AUCT['AdditRestorative'] = "Restorative";
	_AUCT['AdditScroll'] = "Scroll";
	
	_AUCT['SkillAlchemy'] = "Alchemy";
	_AUCT['SkillBlacksmithing'] = "Smithing";
	_AUCT['SkillCooking'] = "Cooking";
	_AUCT['SkillEnchanting'] = "Enchanting";
	_AUCT['SkillEngineering'] = "Engineering";
	_AUCT['SkillFirstaid'] = "First Aid";
	_AUCT['SkillLeatherworking'] = "Leatherworking";
	_AUCT['SkillMining'] = "Mining";
	_AUCT['SkillTailoring'] = "Tailoring";
	_AUCT['SkillDruid'] = "Druid spells";
	_AUCT['SkillMage'] = "Mage spells";
	_AUCT['SkillPaladin'] = "Paladin spells";
	_AUCT['SkillPriest'] = "Priest spells";
	_AUCT['SkillRogue'] = "Rogue skills";
	_AUCT['SkillShaman'] = "Shaman spells";
	_AUCT['SkillWarlock'] = "Warlock spells";
	
	_AUCT['TimeShort'] = "Short";
	_AUCT['TimeMed'] = "Medium";
	_AUCT['TimeLong'] = "Long";
	_AUCT['TimeVlong'] = "Very Long";
	
	_AUCT['FrmtWelcome'] = "Auctioneer v%s loaded";
	
	_AUCT['FrmtBrokerHeader'] = "Minimum profit: %s, HSP = 'Highest Sellable Price'";
	_AUCT['FrmtBrokerLine'] = "%s, Last %s seen, HSP: %s, BO: %s, Prof: %s";
	_AUCT['FrmtBrokerDone'] = "Brokering done";
	_AUCT['FrmtBidbrokerHeader'] = "Minimum profit: %s, HSP = 'Highest Sellable Price'";
	_AUCT['FrmtBidbrokerMinbid'] = "minBid"
	_AUCT['FrmtBidbrokerCurbid'] = "curBid"
	_AUCT['FrmtBidbrokerLine'] = "%s, Last %s seen, HSP: %s, %s: %s, Prof: %s, Time: %s";
	_AUCT['FrmtBidbrokerDone'] = "Bid brokering done";
	_AUCT['FrmtPctlessHeader'] = "Percent Less than Highest Sellable Price (HSP): %d%%";
	_AUCT['FrmtPctlessLine'] = "%s, Last %d seen, HSP: %s, BO: %s, Prof: %s, Less %s";
	_AUCT['FrmtPctlessDone'] = "Percent less done.";
	_AUCT['FrmtCompeteHeader'] = "Competing auctions at least %s less per item.";
	_AUCT['FrmtCompeteLine'] = "%s, Bid: %s, BO %s vs %s, %s less";
	_AUCT['FrmtCompeteDone'] = "Competing auctions done.";
	_AUCT['FrmtNoauct'] = "No auctions found for the item: %s";
	_AUCT['FrmtMedianLine'] = "Of last %d seen, median BO for 1 %s is: %s";
	_AUCT['FrmtLowLine'] = "%s, BO: %s, Seller: %s, For one: %s, Less than median: %s";
	_AUCT['FrmtHspLine'] = "Highest Sellable Price for one %s is: %s";
	
	_AUCT['FrmtInfoSeen'] = "Seen %d times at auction total";
	_AUCT['FrmtInfoForone'] = "For 1: %s min/%s BO (%s bid) [in %d's]";
	_AUCT['FrmtInfoAverage'] = "%s min/%s BO (%s bid)"
	_AUCT['FrmtInfoHistmed'] = "Last %d, median BO (ea)";
	_AUCT['FrmtInfoSnapmed'] = "Scanned %d, median BO (ea)";
	_AUCT['FrmtInfoSgststx'] = "Suggested price for your %d stack: %s min/%s BO";
	_AUCT['FrmtInfoSgst'] = "Suggested price: %s min/%s BO";
	
	_AUCT['FrmtInfoBidrate'] = "%d%% have bid, %d%% have BO";
	_AUCT['FrmtInfoNever'] = "Never seen at %s";
	_AUCT['FrmtInfoAlsoseen'] = "Seen %d times at %s";
	_AUCT['FrmtInfoClassuse'] = "Class: %s used for %s";
	_AUCT['FrmtInfoClass'] = "Class: %s";
	_AUCT['FrmtInfoUse'] = "Used for: %s";
	_AUCT['FrmtInfoBuy'] = "Buy from vendor";
	_AUCT['FrmtInfoSell'] = "Sell to vendor";
	_AUCT['FrmtInfoBuymult'] = "Buy %d (%s each)";
	_AUCT['FrmtInfoSellmult'] = "Sell %d (%s each)";
	_AUCT['FrmtInfoStx'] = "Stacks in lots of %d";
	
	_AUCT['FrmtInfoHeadMulti'] = "Averages for %d items:";
	_AUCT['FrmtInfoMinMulti'] = "  Starting bid (%s ea)";
	_AUCT['FrmtInfoBidMulti'] = "  Bidded (%s%s ea)";
	_AUCT['FrmtInfoBuyMulti'] = "  Buyout (%s%s ea)";
	
	_AUCT['FrmtInfoHeadOne'] = "Averages for this item:";
	_AUCT['FrmtInfoMinOne'] = "  Starting bid";
	_AUCT['FrmtInfoBidOne'] = "  Bidded%s";
	_AUCT['FrmtInfoBuyOne'] = "  Buyout%s";
	
	_AUCT['FrmtInfoBuymedian'] = "  Buyout median";
	
	_AUCT['FrmtInfoStacksize'] = "  Average stack size: %d items";
	
	_AUCT['FrmtUnknownLocale'] = "The locale you specified ('%s') is unknown. Valid locales are:";
	_AUCT['FrmtUnknownRf']     = "Invalid parameter ('%s'). The parameter must be formated like: [realm]-[faction]. For example: Al'Akir-Horde";
	_AUCT['FrmtUnknownArg']    = "'%s' is no valid argument for '%s'";
	
	_AUCT['FrmtActRemove'] = "Removing auction signature %s from current AH snapshot.";
	
	_AUCT['FrmtAuctinfoHist'] = "%d historical";
	_AUCT['FrmtAuctinfoSnap'] = "%d last scan";
	_AUCT['FrmtAuctinfoLow'] = "Snapshot low";
	_AUCT['FrmtAuctinfoNolow'] = "Item not seen last snapshot";
	_AUCT['FrmtAuctinfoOrig'] = "Original bid";
	_AUCT['FrmtAuctinfoSugbuy'] = "Suggested buyout";
	_AUCT['FrmtAuctinfoSugbid'] = "Suggested bid";
	_AUCT['FrmtAuctinfoMktprice'] = "Market price";
	
	_AUCT['FrmtWarnMarkup'] = "Marking up vendor by %s%%";
	_AUCT['FrmtWarnUndercut'] = "Undercutting by %s%%";
	_AUCT['FrmtWarnNocomp'] = "No competition";
	_AUCT['FrmtWarnAbovemkt'] = "Competiton above market";
	_AUCT['FrmtWarnToolow'] = "Cannot match lowest price";
	_AUCT['FrmtWarnMyprice'] = "Using my current price";
	_AUCT['FrmtWarnNodata'] = "No data for HSP";
	
	_AUCT['CmdOff'] = "off";
	_AUCT['CmdOn'] = "on";
	_AUCT['CmdAlt'] = "alt";
	_AUCT['CmdCtrl'] = "ctrl";
	_AUCT['CmdShift'] = "shift";
	_AUCT['CmdToggle'] = "toggle";
	_AUCT['CmdDisable'] = "disable";
	_AUCT['CmdClear'] = "clear";
	_AUCT['CmdClearAll'] = "all";
	_AUCT['CmdClearSnapshot'] = "snapshot";
	_AUCT['CmdAlso'] = "also";
	_AUCT['CmdAlsoOpposite'] = "opposite";
	_AUCT['CmdLocale'] = "locale";
	_AUCT['CmdDefault'] = "default";
	_AUCT['CmdPrintin'] = "print-in";
	
	_AUCT['CmdBroker'] = "broker";
	_AUCT['CmdBidbroker'] = "bidbroker";
	_AUCT['CmdBidbrokerShort'] = "bb";
	_AUCT['CmdEmbed'] = "embed";
	_AUCT['CmdPercentless'] = "percentless";
	_AUCT['CmdPercentlessShort'] = "pl";
	_AUCT['CmdCompete'] = "compete";
	_AUCT['CmdScan'] = "scan";
	_AUCT['CmdAutofill'] = "autofill";
	
	_AUCT['CmdPctBidmarkdown'] = "pct-bidmarkdown";
	_AUCT['CmdPctMarkup']      = "pct-markup";
	_AUCT['CmdPctMaxless']     = "pct-maxless";
	_AUCT['CmdPctNocomp']      = "pct-nocomp";
	_AUCT['CmdPctUnderlow']    = "pct-underlow";
	_AUCT['CmdPctUndermkt']    = "pct-undermkt";
	
	_AUCT['OptClear'] = "([Item]|".._AUCT['CmdClearAll'].."|".._AUCT['CmdClearSnapshot']..")";
	_AUCT['OptAlso'] = "(realm-faction|".._AUCT['CmdAlsoOpposite']..")"
	_AUCT['OptLocale'] = "<locale>";
	_AUCT['OptBroker'] = "<silver_profit>";
	_AUCT['OptBidbroker'] = "<silver_profit>";
	_AUCT['OptPercentless'] = "<percent>";
	_AUCT['OptCompete'] = "<silver_less>";
	_AUCT['OptScan'] = "";
	_AUCT['OptScale'] = "<scale_factor>";
	_AUCT['OptScaleDefault'] = 1.0;
	_AUCT['OptDefault'] = "(<option>|".._AUCT['CmdClearAll']..")";
	_AUCT['OptPrintin'] = "(<frameIndex>[Number]|<frameName>[String])";
	
	_AUCT['OptPctBidmarkdown'] = "<percent>";
	_AUCT['OptPctMarkup'] = "<percent>";
	_AUCT['OptPctMaxless'] = "<percent>";
	_AUCT['OptPctNocomp'] = "<percent>";
	_AUCT['OptPctUnderlow'] = "<percent>";
	_AUCT['OptPctUndermkt'] = "<percent>";
	
	_AUCT['OptPctBidmarkdownDefault'] = 20;
	_AUCT['OptPctMarkupDefault'] = 300;
	_AUCT['OptPctMaxlessDefault'] = 30;
	_AUCT['OptPctNocompDefault'] = 2;
	_AUCT['OptPctUnderlowDefault'] = 5;
	_AUCT['OptPctUndermktDefault'] = 20;
	
	_AUCT['ShowVerbose'] = "show-verbose";
	_AUCT['ShowAverage'] = "show-average";
	_AUCT['ShowLink'] = "show-link";
	_AUCT['ShowMedian'] = "show-median";
	_AUCT['ShowStats'] = "show-stats";
	_AUCT['ShowSuggest'] = "show-suggest";
	_AUCT['ShowEmbedBlank'] = "show-embed-blankline";
	_AUCT['ShowRedo'] = "show-warning";
	
	_AUCT['HelpOnoff'] = "Turns the auction data display on and off";
	_AUCT['HelpDisable'] = "Stops Auctioneer from automatically loading next time you log in";
	_AUCT['HelpVerbose'] = "Select whether to show averages and suggestions verbosely (or off to show them on a single line)";
	_AUCT['HelpAverage'] = "Select whether to show item's average auction price";
	_AUCT['HelpLink'] = "Select whether to show the link id in the tooltip";
	_AUCT['HelpMedian'] = "Select whether to show item's median buyout price";
	_AUCT['HelpSuggest'] = "Select whether to show item's suggested auction price";
	_AUCT['HelpStats'] = "Select whether to show item's bidded/buyout percentages";
	_AUCT['HelpEmbedBlank'] = "Select whether to show a blank line between the tooltip info and the auction info when embedded mode is on";
	_AUCT['HelpClear'] = "Clear the specified item's data (you must shift click insert the item(s) into the command) You may also specify the special keywords \"all\" or \"snapshot\"";
	_AUCT['HelpAlso'] = "Also display another server's values in the tooltip. For realm, insert the realmname and for faction the faction's name. For example: \"/auctioneer also Al'Akir-Horde\". The special keyword \"opposite\" means the opposite faction, \"off\" disables the functionality.";
	_AUCT['HelpLocale'] = "Change the locale that is used to display Auctioneer messages";
	_AUCT['HelpBroker'] = "Show any auctions from the most recent scan that may be bid on and then resold for profit";
	_AUCT['HelpBidbroker'] = "Show short or medium term auctions from the recent scan that may be bid on for profit";
	_AUCT['HelpEmbed'] = "Embed the text in the original game tooltip (note: certain features are disabled when this is selected)";
	_AUCT['HelpPercentless'] = "Show any recently scanned auctions whose buyout is a certain percent less than the highest sellable price";
	_AUCT['HelpCompete'] = "Show any recently scanned auctions whose buyout is less than one of your items";
	_AUCT['HelpScan'] = "Perform a scan of the auction house at the next visit, or while you are there (there is also a button in the auction pane). Choose which categories you want to scan with the checkboxes.";
	_AUCT['HelpAutofill'] = "Set whether to autofill prices when dropping new auction items into the auction house window";
	_AUCT['HelpPctBidmarkdown'] = "Set the percentage that Auctioneer will mark down bids from the buyout price";
	_AUCT['HelpPctMarkup'] = "The percentage that vendor prices will be marked up when no other values are available";
	_AUCT['HelpPctMaxless'] = "Set the maximum percentage that Auctioneer will undercut market value before it gives up";
	_AUCT['HelpPctNocomp'] = "The percentage that Auctioneer will undercut market value when there is no competition";
	_AUCT['HelpPctUnderlow'] = "Set the percentage that Auctioneer will undercut the lowest auction price";
	_AUCT['HelpPctUndermkt'] = "Percentage to cut market value by when unable to beat competition (due to maxless)";
	_AUCT['HelpRedo'] = "Select whether to show a warning when the currently scanned AH page has taken too long to scan due to server lag.";
	_AUCT['HelpDefault'] = "Set an Auctioneer option to it's default value. You may also specify the special keyword \"all\" to set all Auctioneer options to their default values."
	_AUCT['HelpPrintin'] = "Select which frame Auctioneer will print out it's messages. You can either specify the frame's name or the frame's index.";
	
	_AUCT['DisableMsg'] = "Disabling automatic loading of Auctioneer";
	
	_AUCT['StatOn'] = "Displaying configured auction data";
	_AUCT['StatOff'] = "Not displaying any auction data";
	
	_AUCT['FrmtActClearall'] = "Clearing all auction data for %s";
	_AUCT['FrmtActClearsnap'] = "Clearing current Auction House snapshot.";
	_AUCT['FrmtActClearOk'] = "Cleared data for item: %s";
	_AUCT['FrmtActClearFail'] = "Unable to find item: %s";
	_AUCT['FrmtActEnable'] = "Displaying item's %s data";
	_AUCT['FrmtActDisable'] = "Not displaying item's %s data";
	_AUCT['FrmtActEnabledOn'] = "Displaying item's %s on %s";
	_AUCT['FrmtActSet'] = "Set %s to '%s'";
	_AUCT['FrmtActUnknown'] = "Unknown command keyword: '%s'";
	_AUCT['FrmtActDefaultall'] = "All Auctioneer options have been reset to default settings.";
	_AUCT['FrmtActDefault'] = "Auctioneer's %s option has been reset to its default setting";
	_AUCT['FrmtPrintin'] = "Auctioneer's messages will now print on the \"%s\" chat frame";
	
	_AUCT['TextScan'] = "Scan";
	_AUCT['TextAuction'] = "auction";
	_AUCT['TextNone'] = "none";
	_AUCT['TextUsage'] = "Usage:";
	
	
	
	_AUCT['AuctionScanStart'] = "Auctioneer: scanning %s page 1...";
	_AUCT['AuctionPageN'] = "Auctioneer: scanning %s page %d of %d\nAuctions per second: %s\nEstimated time left: %s";
	_AUCT['AuctionScanDone'] = "Auctioneer: auction scanning finished";
	_AUCT['AuctionScanNexttime'] = "Auctioneer will perform a full auction scan the next time you talk to an auctioneer.";
	_AUCT['AuctionScanNocat'] = "You must have at least one category selected to scan.";
	_AUCT['AuctionScanRedo'] = "Current page took more than %d seconds to complete, retrying page.";
	
	_AUCT['MesgConvert'] = "Auctioneer Database Conversion. Please backup your SavedVariables\\Auctioneer.lua first.%s%s";
	_AUCT['MesgNotconverting'] = "Auctioneer is not converting your database, but will not function until you do.";
	_AUCT['MesgConvertYes'] = "Convert";
	_AUCT['MesgConvertNo'] = "Disable Auctioneer";
	
	_AUCT['MesgNotLoaded'] = "Auctioneer is not loaded. Type /auctioneer for more info.";
	
	_AUCT['AuctionTotalAucts'] = "Total auctions scanned: %s";
	_AUCT['AuctionNewAucts'] = "New auctions scanned: %s";
	_AUCT['AuctionOldAucts'] = "Previously scanned: %s";
	_AUCT['AuctionDefunctAucts'] = "Defunct auctions removed: %s";
	_AUCT['AuctionDiscrepancies'] = "Discrepancies: %s";
	
	
	
	_AUCT['GuiMainHelp'] = "Contains settings for Auctioneer \nan AddOn that displays item info and analyzes auction data. \nClick the \"Scan\" button at the AH to collect auction data.";
	_AUCT['GuiMainEnable'] = "Enable Auctioneer";
	_AUCT['GuiLocale'] = "Set locale to";
	_AUCT['GuiVerbose'] = "Verbose Mode";
	_AUCT['GuiStatsEnable'] = "Show Stats";
	_AUCT['GuiStatsHeader'] = "Item Price Statistics";
	_AUCT['GuiStatsHelp'] = "Show the following statistics in the tooltip.";
	_AUCT['GuiAverages'] = "Show Averages";
	_AUCT['GuiMedian'] = "Show Medians";
	_AUCT['GuiSuggest'] = "Show Suggested Prices";
	_AUCT['GuiVendorHeader'] = "Vendor Prices";
	_AUCT['GuiVendorHelp'] = "Options related to NPC buy/sell prices.";
	_AUCT['GuiVendor'] = "Show Vendor Prices";
	_AUCT['GuiVendorBuy'] = "Show Vendor Buy Prices";
	_AUCT['GuiVendorSell'] = "Show Vendor Sell Prices";
	_AUCT['GuiEmbedHeader'] = "Embed";
	_AUCT['GuiEmbed'] = "Embed info in in-game tooltip";
	_AUCT['GuiEmbedBlankline'] = "Show blankline in in-game tooltip";
	_AUCT['GuiClearHeader'] = "Clear Data";
	_AUCT['GuiClearHelp'] = "Clears Auctioneer data. \nSelect either all data or the current snapshot.\nWARNING: These actions are NOT undoable.";
	_AUCT['GuiClearall'] = "Clear All Auctioneer Data";
	_AUCT['GuiClearallHelp'] = "Click here to clear all of Auctioneer data for the current server-realm.";
	_AUCT['GuiClearallNote'] = "for the current server-faction";
	_AUCT['GuiClearallButton'] = "Clear All";
	_AUCT['GuiClearsnap'] = "Clear Snapshot data";
	_AUCT['GuiClearsnapHelp'] = "Click here to clear the last Auctioneer snapshot data.";
	_AUCT['GuiClearsnapButton'] = "Clear Snapshot";
	_AUCT['GuiPercentsHeader'] = "Auctioneer Threshold Percents";
	_AUCT['GuiPercentsHelp'] = "WARNING: The following setting are for Power Users ONLY.\nAdjust the following values to change how aggresive Auctioneer will be when deciding profitable levels.";
	_AUCT['GuiBidmarkdown'] = "Bid Markdown Percent";
	_AUCT['GuiMarkup'] = "Vendor Price Markup Percent";
	_AUCT['GuiMaxless'] = "Max Market Undercut Percent";
	_AUCT['GuiNocomp'] = "No Competition Undercut Percent";
	_AUCT['GuiUnderlow'] = "Lowest Auction Undercut";
	_AUCT['GuiUndermkt'] = "Undercut Market When Maxless";
	_AUCT['GuiOtherHeader'] = "Other Options";
	_AUCT['GuiOtherHelp'] = "Miscellaneous Auctioneer Options";
	_AUCT['GuiAutofill'] = "Autofill prices in the AH";
	_AUCT['GuiAlso'] = "Also display data for";
	_AUCT['GuiAlsoOpposite'] = "Now also displaying data for opposite faction.";
	_AUCT['GuiAlsoOff'] = "No longer displaying other realm-faction data.";
	_AUCT['GuiAlsoDisplay'] = "Displaying data for %s";
	_AUCT['GuiLink'] = "Show LinkID";
	_AUCT['GuiReloadui'] = "Reload User Interface";
	_AUCT['GuiReloaduiHelp'] = "Click here to reload the WoW User Interface after changing the locale so that the language in this configuration screen matches the one you selected.\nNote: This operation may take a few minutes.";
	_AUCT['GuiReloaduiButton'] = "ReloadUI";
	_AUCT['GuiReloaduiFeedback'] = "Now Reloading the WoW UI";
	_AUCT['GuiRedo'] = "Show Long Scan Warning";
	_AUCT['GuiDefaultAllButton'] = "Reset All";
	_AUCT['GuiDefaultAll'] = "Reset All Auctioneer Options";
	_AUCT['GuiDefaultAllHelp'] = "Click here to set all Auctioneer options to their default values.\nWARNING: This action is NOT undoable.";
	_AUCT['GuiDefaultOption'] = "Reset this setting";
	_AUCT['GuiPrintin'] = "Select the desired message frame";
-- Locale strings for the deDE locale
if locale == "deDE" then
		-- Encoded in UTF8
		
		_AUCT['AdditAlcohol']     = "Alkohol";
		_AUCT['AdditBuff']        = "Buff";
		_AUCT['AdditDrink']       = "Getr\195\164nk";
		_AUCT['AdditFirework']    = "Feuerwerk";
		_AUCT['AdditFood']        = "Nahrung";
		_AUCT['AdditGiftwrap']    = "Geschenkpapier";
		_AUCT['AdditLure']        = "K\195\182der";
		_AUCT['AdditPoison']      = "Gift";
		_AUCT['AdditPotion']      = "Trank";
		_AUCT['AdditRestorative'] = "St\195\164rkungstrank";
		_AUCT['AdditScroll']      = "Zauberspruchrolle";
		
		_AUCT['SkillAlchemy']        = "Alchimie";
		_AUCT['SkillBlacksmithing']  = "Schmieden";
		_AUCT['SkillCooking']        = "Kochen";
		_AUCT['SkillEnchanting']     = "Verzauberungen";
		_AUCT['SkillEngineering']    = "Ingenieurskunst";
		_AUCT['SkillFirstaid']       = "Erste Hilfe";
		_AUCT['SkillLeatherworking'] = "Lederverarbeitung";
		_AUCT['SkillMining']         = "Bergbau";
		_AUCT['SkillTailoring']      = "Schneiderei";
		_AUCT['SkillDruid']          = "Druidenzauber";
		_AUCT['SkillMage']           = "Magierzauber";
		_AUCT['SkillPaladin']        = "Paladinzauber";
		_AUCT['SkillPriest']         = "Priesterzauber";
		_AUCT['SkillRogue']          = "Diebeszubeh\195\182r";
		_AUCT['SkillShaman']         = "Schamanenzauber";
		_AUCT['SkillWarlock']        = "Hexerzauber";
		
		_AUCT['TimeShort'] = "Kurz";
		_AUCT['TimeMed']   = "Mittel";
		_AUCT['TimeLong']  = "Lang";
		_AUCT['TimeVlong'] = "Sehr lang";
		
		_AUCT['FrmtWelcome'] = "Auctioneer v%s geladen";
		
		_AUCT['FrmtBrokerHeader']    = "Mindestprofit: %s, HVP = 'H\195\182chster verk\195\164uflicher Preis'";
		_AUCT['FrmtBrokerLine']      = "%s, zuletzt %s gesehen, HVP: %s, Sofortkauf: %s, Profit: %s";
		_AUCT['FrmtBrokerDone']      = "Brokern fertig";
		_AUCT['FrmtBidbrokerHeader'] = "Mindest Profit: %s, HVP = 'H\195\182chster verk\195\164uflicher Preis'";
		_AUCT['FrmtBidbrokerMinbid'] = "min. Gebot"
		_AUCT['FrmtBidbrokerCurbid'] = "akt. Gebot"
		_AUCT['FrmtBidbrokerLine']   = "%s, zuletzt %s gesehen, HVP: %s, %s: %s, Profit: %s, Restzeit: %s";
		_AUCT['FrmtBidbrokerDone']   = "Gebotbrokern fertig";
		_AUCT['FrmtPctlessHeader']   = "Prozent billiger als der 'H\195\182chster verk\195\164uflicher Preis (HVP)': %d%%";
		_AUCT['FrmtPctlessLine']     = "%s, zuletzt %d gesehen, HSP: %s, Sofortkauf: %s, Prof: %s, Billiger %s";
		_AUCT['FrmtPctlessDone']     = "Prozent unter HSP fertig.";
		_AUCT['FrmtCompeteHeader']   = "Konkurrierende Auktionen mindestens %s billiger pro St\195\188ck.";
		_AUCT['FrmtCompeteLine']     = "%s, Gebot: %s, Sofortkauf %s vs %s, %s billiger";
		_AUCT['FrmtCompeteDone']     = "Konkurrierende Auktionen fertig.";
		_AUCT['FrmtNoauct']          = "Keine Aktionen f\195\188r %s gefunden.";
		_AUCT['FrmtMedianLine']      = "Der Median der %d zuletzt gesehenen %s liegt bei %s/St\195\188ck.";
		_AUCT['FrmtLowLine']         = "%s, Sofortkauf: %s, Verk\195\164ufer: %s, %s/St\195\188ck, %s unter dem Median";
		_AUCT['FrmtHspLine']         = "H\195\182chster verk\195\164uflicher Preis pro %s ist: %s";
		
		_AUCT['FrmtInfoSeen']        = "Insgesamt %d mal in Auktionen gesehen";
		_AUCT['FrmtInfoForone']      = "Pro St\195\188ck: %s min/%s Sofortkauf (%s geboten) [in %d]";
		_AUCT['FrmtInfoAverage']     = "%s min/%s Sofortkauf (%s geboten)"
		_AUCT['FrmtInfoHistmed']     = "Sofortkauf-Median (pro St\195\188ck) der %d letzten Auktionen:";
		_AUCT['FrmtInfoSnapmed']     = "Sofortkauf-Median (pro St\195\188ck) aus %d gescannten Auktionen:";
		_AUCT['FrmtInfoSgststx']     = "Empfohlener Preis f\195\188r diesen %der Stapel: %s min/%s Sofortkauf";
		_AUCT['FrmtInfoSgst']        = "Empfohlener Preis: %s min/%s Sofortkauf";
		
		_AUCT['FrmtInfoBidrate']  = "%d%% haben Gebote, %d%% haben Sofortkauf";
		_AUCT['FrmtInfoNever']    = "Noch in keiner %s gesehen";
		_AUCT['FrmtInfoAlsoseen'] = "%d mal in einer %s gesehen";
		_AUCT['FrmtInfoClassuse'] = "Klasse: %s - Benutzt f\195\188r %s";
		_AUCT['FrmtInfoClass']    = "Klasse: %s";
		_AUCT['FrmtInfoUse']      = "Benutzt f\195\188r: %s";
		_AUCT['FrmtInfoBuy']      = "Einkauf beim H\195\164ndler";
		_AUCT['FrmtInfoSell']     = "Verkauf beim H\195\164ndler";
		_AUCT['FrmtInfoBuymult']  = "Einkauf f\195\188r %d (%s pro St\195\188ck)";
		_AUCT['FrmtInfoSellmult'] = "Verkauf f\195\188r %d (%s pro St\195\188ck)";
		_AUCT['FrmtInfoStx']      = "%d pro Stapel";
		
		_AUCT['FrmtInfoHeadMulti'] = "Durchschnitt f\195\188r %d St\195\188ck:";
		_AUCT['FrmtInfoMinMulti']  = "  Min. Startgebot (%s pro St\195\188ck)";
		_AUCT['FrmtInfoBidMulti']  = "  Geboten (%s%s pro St\195\188ck)";
		_AUCT['FrmtInfoBuyMulti']  = "  Sofortkauf (%s%s pro St\195\188ck)";
		
		_AUCT['FrmtInfoHeadOne'] = "Durchschnitt f\195\188r diesen Gegenstand:";
		_AUCT['FrmtInfoMinOne']  = "  Min. Startgebot";
		_AUCT['FrmtInfoBidOne']  = "  Geboten%s";
		_AUCT['FrmtInfoBuyOne']  = "  Sofortkauf%s";
		
		_AUCT['FrmtInfoBuymedian'] = "  Sofortkauf-Median";
		
		_AUCT['FrmtInfoStacksize'] = "  Durchschnittliche Stapelgr\195\182\195\159e: %d St\195\188ck";
		
		_AUCT['FrmtUnknownLocale'] = "Die angegebene Sprache ('%s') ist unbekannt. Folgende Sprachen sind g\195\188ltig:";
		_AUCT['FrmtUnknownRf']     = "Der angegebene Parameter ('%s') ist ung\195\188ltig. Der Parameter muss das Format: [Realm]-[Fraktion] haben. Zum Beispiel: Kil'Jaeden-Alliance";
		_AUCT['FrmtUnknownArg']    = "'%s' ist kein g\195\188ltiges Argument f\195\188r '%s'";
		
		_AUCT['FrmtActRemove'] = "Entferne Aktionssignatur %s von dem derzeitigen AH-Abbild.";
		
		_AUCT['FrmtAuctinfoHist']     = "%d historisch";
		_AUCT['FrmtAuctinfoSnap']     = "%d aus letztem Scan";
		_AUCT['FrmtAuctinfoLow']      = "billigster Snapshot";
		_AUCT['FrmtAuctinfoNolow']    = "Nicht im letzten Snapshot gesehn";
		_AUCT['FrmtAuctinfoOrig']     = "Original-Gebot";
		_AUCT['FrmtAuctinfoSugbuy']   = "Empf. Sofortkauf";
		_AUCT['FrmtAuctinfoSugbid']   = "Empf. Gebot";
		_AUCT['FrmtAuctinfoMktprice'] = "Marktpreis";
		
		_AUCT['FrmtWarnMarkup']   = "%s%% erh\195\182hter H\195\164ndlerpreis";
		_AUCT['FrmtWarnUndercut'] = "Unterbiete um %s%%";
		_AUCT['FrmtWarnNocomp']   = "Monopol";
		_AUCT['FrmtWarnAbovemkt'] = "Konkurrenz keine Gefahr";
		_AUCT['FrmtWarnToolow']   = "Konkurrenz zu g\195\188nstig";
		_AUCT['FrmtWarnMyprice']  = "Verwende eigenen Preis";
		_AUCT['FrmtWarnNodata']   = "Keine HVP-Daten";
		
		_AUCT['CmdOff']           = "off";
		_AUCT['CmdOn']            = "on";
		_AUCT['CmdAlt']           = "alt";
		_AUCT['CmdCtrl']          = "ctrl";
		_AUCT['CmdShift']         = "shift";
		_AUCT['CmdToggle']        = "toggle";
		_AUCT['CmdClear']         = "clear";
		_AUCT['CmdClearAll']      = "all";
		_AUCT['CmdClearSnapshot'] = "snapshot";
		_AUCT['CmdAlso']          = "also";
		_AUCT['CmdAlsoOpposite']  = "opposite";
		_AUCT['CmdLocale']        = "locale";
		_AUCT['CmdDefault']       = "default";
		
		_AUCT['CmdBroker']           = "broker";
		_AUCT['CmdBidbroker']        = "bidbroker";
		_AUCT['CmdBidbrokerShort']   = "bb";
		_AUCT['CmdEmbed']            = "embed";
		_AUCT['CmdPercentless']      = "percentless";
		_AUCT['CmdPercentlessShort'] = "pl";
		_AUCT['CmdCompete']          = "compete";
		_AUCT['CmdScan']             = "scan";
		_AUCT['CmdAutofill']         = "autofill";
		
		_AUCT['CmdPctBidmarkdown'] = "pct-bidmarkdown";
		_AUCT['CmdPctMarkup']      = "pct-markup";
		_AUCT['CmdPctMaxless']     = "pct-maxless";
		_AUCT['CmdPctNocomp']      = "pct-nocomp";
		_AUCT['CmdPctUnderlow']    = "pct-underlow";
		_AUCT['CmdPctUndermkt']    = "pct-undermkt";
		
		_AUCT['OptClear']        = "([Gegenstand]|".._AUCT['CmdClearAll'].."|".._AUCT['CmdClearSnapshot']..")";
		_AUCT['OptAlso']         = "(Realm-Fraktion|".._AUCT['CmdAlsoOpposite']..")"
		_AUCT['OptLocale']       = "<Sprache>";
		_AUCT['OptBroker']       = "<Gewinn in Silber>";
		_AUCT['OptBidbroker']    = "<Gewinn in Silber>";
		_AUCT['OptPercentless']  = "<Prozent>";
		_AUCT['OptCompete']      = "<Preisnachlass in Silber>";
		_AUCT['OptScan']         = "";
		_AUCT['OptScale']        = "<Skalierungsfaktor>";
		_AUCT['OptScaleDefault'] = 1.0;
		
		_AUCT['OptPctBidmarkdown'] = "<Prozent>";
		_AUCT['OptPctMarkup']      = "<Prozent>";
		_AUCT['OptPctMaxless']     = "<Prozent>";
		_AUCT['OptPctNocomp']      = "<Prozent>";
		_AUCT['OptPctUnderlow']    = "<Prozent>";
		_AUCT['OptPctUndermkt']    = "<Prozent>";
		
		_AUCT['OptPctBidmarkdownDefault'] = 20;
		_AUCT['OptPctMarkupDefault']      = 300;
		_AUCT['OptPctMaxlessDefault']     = 30;
		_AUCT['OptPctNocompDefault']      = 2;
		_AUCT['OptPctUnderlowDefault']    = 5;
		_AUCT['OptPctUndermktDefault']    = 20;
		
		_AUCT['ShowVerbose']    = "show-verbose";
		_AUCT['ShowAverage']    = "show-average";
		_AUCT['ShowLink']       = "show-link";
		_AUCT['ShowMedian']     = "show-median";
		_AUCT['ShowStats']      = "show-stats";
		_AUCT['ShowSuggest']    = "show-suggest";
		_AUCT['ShowEmbedBlank'] = "show-embed-blankline";
		_AUCT['ShowRedo']       = "show-warning";
		
		_AUCT['HelpOnoff']          = "Schaltet die Anzeige der Auktionsdaten ein/aus.";
		_AUCT['HelpVerbose']        = "Schaltet die detaillierte Anzeige der Durchschnittswerte und Preisempfehlungen ein/aus. Deaktivieren reduziert die Datenanzeige auf eine Zeile.";
		_AUCT['HelpAverage']        = "Schaltet die Anzeige des durchschnittlichen Auktionspreises ein/aus.";
		_AUCT['HelpLink']           = "Schaltet die Anzeige der Link-ID im Tooltip ein/aus.";
		_AUCT['HelpMedian']         = "Schaltet die Anzeige des Median-Sofortkaufpreises ein/aus.";
		_AUCT['HelpSuggest']        = "Schaltet die Anzeige des empfohlenen Auktionspreises ein/aus.";
		_AUCT['HelpStats']          = "Schaltet die Prozentanzeige der/des Gebote/Sofortkaufes ein/aus.";
		_AUCT['HelpEmbedBlank']     = "Schaltet die Anzeige einer Leerzeile zwischen der Tooltipinfo und der Auktionsinfo im Embedded-Mode ein/aus.";
		_AUCT['HelpClear']          = "L\195\182scht die Daten der angegebene Gegenst\195\164nde (Gegenst\195\164nde durch Shift+Linksklick dem Befehl hinzuf\195\188gen) Es k\195\182nnen auch die speziellen Keywords \"all\" und \"snapshot\" hinzugef\195\188gt werden.";
		_AUCT['HelpAlso']           = "Zeigt ebenfalls die Werte anderer Server im Tooltip an. Setze den Namen des Realms f\195\188r Realm und den Namen der Faktion f\195\188r Fraktion ein. Zum Beispiel: \"/auctioneer also Kil'Jaeden-Alliance\". Das spezielle Keywort \"opposite\" bedeutet die gegnerische Franktion, \"off\" deaktiviert die Funktionalit\195\164t.";
		_AUCT['HelpLocale']         = "\195\132ndert die f\195\188r die Ausgabe der Auctioneer-Meldungen verwendete Sprache.";
		_AUCT['HelpBroker']         = "Zeigt alle Auktionen des zuletzt durchgef\195\188hrten Scans an, die per Sofortkauf gekauft und mit Gewinn wieder verkauft werden k\195\182nnen.";
		_AUCT['HelpBidbroker']      = "Zeigt alle Auktionen des zuletzt durchgef\195\188hrten Scans mit kurzer oder mittlerer Restlaufzeit an, die per Gebot ersteigert und mit Gewinn wieder verkauft werden k\195\182nnen.";
		_AUCT['HelpEmbed']          = "Bindet den Auktionsinfotext in den WoW-Tooltip ein (Hinweis: Einige Funktionen sind in diesem Modus deaktiviert).";
		_AUCT['HelpPercentless']    = "Zeigt alle Auktionen des zuletzt durchgef\195\188hrten Scans an, deren Sofortkaufpreis einen gewissen Prozentsatz unter dem h\195\182chstm\195\182glichen Verkaufspreis liegt.";
		_AUCT['HelpCompete']        = "Zeigt alle Auktionen des zuletzt durchgef\195\188hrten Scans an, deren Sofortkaufpreis geringer ist als der eines eigenen im AH angebotenen Gegenstandes.";
		_AUCT['HelpScan']           = "F\195\188hrt einen Scan des Auktionshauses beim n\195\164chsten Besuch durch bzw. sofort, wenn man schon dort ist (es gibt ebenfalls einen Knopf im Auktionshausfenster). \195\156ber die Auswahlboxen k\195\182nnen die zu scannenden Kategorien gew\195\164hlt werden.";
		_AUCT['HelpAutofill']       = "Gibt an, ob die Preise automatisch ausgef\195\188llt werden sollen, wenn ein Gegenstand ins Auktionshaus gelegt wird.";
		_AUCT['HelpPctBidmarkdown'] = "Legt den Prozentsatz fest, um den das Mindestgebot niedriger als der Sofortkaufpreis ist.";
		_AUCT['HelpPctMarkup']      = "Legt den Prozentsatz f\195\188r erh\195\182hte H\195\164ndlerpreise fest, der verwendet wird, falls sonst keine anderen Werte verf\195\188gbar sind.";
		_AUCT['HelpPctMaxless']     = "Legt den maximalen Prozentsatz fest, um den der Marktpreis versucht wird zu verringern, bevor aufgegeben wird";
		_AUCT['HelpPctNocomp']      = "Legt den Prozentsatz fest, um den der Marktpreis gesenkt wird, wenn kein konkurierendes Angebot existiert.";
		_AUCT['HelpPctUnderlow']    = "Legt den Prozentsatz fest, um den das g\195\188nstigste konkurierende Angebot unterboten wird.";
		_AUCT['HelpPctUndermkt']    = "Legt den Prozentsatz fest, um den der Marktpreis gesenkt wird, wenn durch den gew\195\164hlten Preozentsatz f\195\188r maxless ein konkurierendes Angebot nicht unterboten werden kann.";
		_AUCT['HelpRedo']           = "Legt fest, ob eine Warnung angezeigt werden soll, wenn die zuletzt gescannte Seite im AH wegen Serverlag zu lange braucht."
		
		_AUCT['StatOn']  = "Auktionsdaten werden angezeigt.";
		_AUCT['StatOff'] = "Auktionsdaten werden nicht angezeigt.";
		
		_AUCT['FrmtActClearall']   = "L\195\182sche alle Auktionsdaten f\195\188r %s";
		_AUCT['FrmtActClearsnap']  = "L\195\182sche aktuelles Auktionshaus-Abbild.";
		_AUCT['FrmtActClearOk']    = "Daten f\195\188r %s wurden gel\195\182scht";
		_AUCT['FrmtActClearFail']  = "Kann %s nicht finden";
		_AUCT['FrmtActEnable']     = "%s wird angezeigt";
		_AUCT['FrmtActDisable']    = "%s wird nicht angezeigt";
		_AUCT['FrmtActEnabledOn']  = "Zeige %s auf %s";
		_AUCT['FrmtActSet']        = "Setze %s auf '%s'";
		_AUCT['FrmtActUnknown']    = "Unbekannter Befehl: '%s'";
		_AUCT['FrmtActDefaultall'] = "Alle Einstellungen wurden auf Standardwerte zur\195\188ckgesetzt.";
		_AUCT['FrmtActDefault']    = "%s wurde auf den Standardwert zur\195\188ckgesetzt.";
		
		_AUCT['TextScan']    = "Scannen";
		_AUCT['TextAuction'] = "Auktion";
		_AUCT['TextNone']    = "nichts";
		_AUCT['TextUsage']   = "Syntax:";
		
		-- AH Scanning localizations
		
		_AUCT['AuctionScanStart']    = "Auctioneer: Scanne %s Seite 1...";
		_AUCT['AuctionPageN']        = "Auctioneer: Scanne %s Seite %d von %d";
		_AUCT['AuctionScanDone']     = "Auctioneer: Scanvorgang abgeschlossen";
		_AUCT['AuctionScanNexttime'] = "Auctioneer wird einen kompletten Auktionsscan durchf\195\188hren, wenn das n\195\164chste mal mit einem Auktionator gesprochen wird.";
		_AUCT['AuctionScanNocat']    = "Es muss mindestens eine Kategorie ausgew\195\164hlt sein, um den Scanvorgang zu starten.";
		_AUCT['AuctionScanRedo']     = "Aktuelle Seite braucht l\195\164nger als %d Sekunden. Fahre mit n\195\164chster Seite fort.";
		
		_AUCT['MesgConvert']       = "Auctioneer Datenbankkonvertierung. Bitte zuerst ein Backup von SavedVariables\\Auctioneer.lua anlegen!%s%s";
		_AUCT['MesgNotconverting'] = "Auctioneers Datenbank wird nicht konvertiert. Auctioneer bleibt deaktiviert, solange die Datenbank nicht konvertiert wurde.";
		_AUCT['MesgConvertYes']    = "Konvertieren";
		_AUCT['MesgConvertNo']     = "Auctioneer deaktivieren";
		
		_AUCT['AuctionTotalAucts']    = "Insgesammt gescannte Auktionen: %s";
		_AUCT['AuctionNewAucts']      = "Davon neu: %s";
		_AUCT['AuctionOldAucts']      = "Davon alt: %s";
		_AUCT['AuctionDefunctAucts']  = "Abgelaufene Auktionen: %s";
		_AUCT['AuctionDiscrepancies'] = "Unstimmigkeiten: %s";
		
		-- GUI localizations
		
		_AUCT['GuiMainHelp']         = "Enth\195\164lt Einstellungen f\195\188r Auctioneer\nein Addon, welches zus\195\164tzliche Informationen zu Gegenst\195\164nden anzeigt und Auktionsdaten analysiert.\nDr\195\188cke den \"Scannen\"-Knopf im Auktionshaus, um Auktionsdaten zu sammeln.";
		_AUCT['GuiMainEnable']       = "Aktiviert Auctioneer";
		_AUCT['GuiLocale']           = "Sprache";
		_AUCT['GuiVerbose']          = "Detaillierte Informationen";
		_AUCT['GuiStatsEnable']      = "Statistiken anzeigen";
		_AUCT['GuiStatsHeader']      = "Preisstatistiken anzeigen";
		_AUCT['GuiStatsHelp']        = "Zeigt die folgenden Statistiken im Tooltip an.";
		_AUCT['GuiAverages']         = "Zeige den Durchschnitt an.";
		_AUCT['GuiMedian']           = "Zeige den Median an.";
		_AUCT['GuiSuggest']          = "Zeige empfohlene Preise an.";
		_AUCT['GuiVendorHeader']     = "Zeige H\195\164ndlerpreise an.";
		_AUCT['GuiVendorHelp']       = "Einstellungen im Zusammenhang mit Verkaufs-/Einkaufspreise von NPCs.";
		_AUCT['GuiVendor']           = "Zeige H\195\164ndlerpreise an.";
		_AUCT['GuiVendorBuy']        = "Zeige H\195\164ndler-Einkaufspreise an";
		_AUCT['GuiVendorSell']       = "Zeige H\195\164ndler-Verkaufspreise an";
		_AUCT['GuiEmbedHeader']      = "Integriert";
		_AUCT['GuiEmbed']            = "Integriere Informationen in den ingame-Tooltip.";
		_AUCT['GuiEmbedBlankline']   = "F\195\188ge leere Zeile in den ingame-Tooltip hinzu.";
		_AUCT['GuiClearHeader']      = "Daten l\195\182schen";
		_AUCT['GuiClearHelp']        = "Auctioneerdaten l\195\182schen.\nW\195\164hle entweder alle Daten oder nur den aktuellen Snapshot aus.\nWARNUNG: Das L\195\182schen kann nicht r\195\188ckg\195\164ngig gemacht werden!"
		_AUCT['GuiClearall']         = "L\195\182sche alle Auctioneerdaten";
		_AUCT['GuiClearallHelp']     = "Hier dr\195\188cken, um die gesamten Auctioneerdaten des aktuellen Realms zu l\195\182schen.";
		_AUCT['GuiClearallNote']     = "der aktuellen Fraktion auf dem aktuellen Realm";
		_AUCT['GuiClearallButton']   = "Alles l\195\182schen";
		_AUCT['GuiClearsnap']        = "Snapshotdaten l\195\182schen";
		_AUCT['GuiClearsnapHelp']    = "Hier dr\195\188cken, um Auctioneers aktuelle Snapshotdaten zu l\195\182schen.";
		_AUCT['GuiClearsnapButton']  = "Snapshot l\195\182schen";
		_AUCT['GuiPercentsHeader']   = "Auctioneer Prozentschwellwerte";
		_AUCT['GuiPercentsHelp']     = "WARNUNG: Die folgenden Einstellungen sind nur f\195\188r erfahrene benutzer.\nDie folgenden Werte k\195\182nnen ge\195\164ndert werden, um festzulegen, wie aggressiv Auctioneer vorgehen soll, um den profitabelsten Preis zu berechnen.";
		_AUCT['GuiBidmarkdown']      = "Gebot um x% unterbieten";
		_AUCT['GuiMarkup']           = "H\195\164ndlerpreis um x% erh\195\182hen";
		_AUCT['GuiMaxless']          = "Marktpreis um max. x% unterbieten.";
		_AUCT['GuiNocomp']           = "Marktpreis um x% im Monopol verringern";
		_AUCT['GuiUnderlow']         = "Marktpreis um x% verringern, wenn Konkurrenz keine Gefahr ist";
		_AUCT['GuiUndermkt']         = "Marktpreis um x% verringern, wenn Konkurrenz zu g\195\188nstig ist";
		_AUCT['GuiOtherHeader']      = "Sonstige Einstellungen";
		_AUCT['GuiOtherHelp']        = "Verschiedene Einstellungen f\195\188r Auctioneer";
		_AUCT['GuiAutofill']         = "Preise im Auktionshaus automatisch eintragen";
		_AUCT['GuiAlso']             = "Zeige zus\195\164tzlich Daten f\195\188r folgendes Realm/Fraktion an";
		_AUCT['GuiAlsoOpposite']     = "Daten der gegnerischen Fraktion werden jetzt ebenfalls angezeigt.";
		_AUCT['GuiAlsoOff']          = "Es werden keine Daten mehr f\195\188r ein anderes Realm / eine andere Fraktion angezeigt.";
		_AUCT['GuiAlsoDisplay']      = "Zeige Daten fpr %s an";
		_AUCT['GuiLink']             = "Zeige LinkID an";
		_AUCT['GuiReloadui']         = "Benutzerinterface neu laden";
		_AUCT['GuiReloaduiHelp']     = "Hier klicken, um das Benutzerinterface neu zu laden, damit die gew\195\164hlte Sprache f\195\188r Auctioneer aktiviert wird, sofern sie ge\195\164ndert wurde.\nHinweis: Dies kann je nach System/Anzahl aktiver Addons \195\188ber eine Minute dauern.";
		_AUCT['GuiReloaduiButton']   = "ReloadUI";
		_AUCT['GuiReloaduiFeedback'] = "Lade jetzt das WoW-UI neu.";
end

-- Locale strings for the esES locale
if locale == "esES" then
		-- Encoded in UTF8
		
		_AUCT['AdditAlcohol'] = "Alcohol";
		_AUCT['AdditBuff'] = "Mejora";
		_AUCT['AdditDrink'] = "Bebida";
		_AUCT['AdditFirework'] = "Fuegos Artificiales";
		_AUCT['AdditFood'] = "Comida";
		_AUCT['AdditGiftwrap'] = "Envoltura";
		_AUCT['AdditLure'] = "Se\195\177uelo";
		_AUCT['AdditPoison'] = "Veneno";
		_AUCT['AdditPotion'] = "Poci\195\179n";
		_AUCT['AdditRestorative'] = "Restaurativo";
		_AUCT['AdditScroll'] = "Voluta";
		
		_AUCT['SkillAlchemy'] = "Alqu\195\173mia";
		_AUCT['SkillBlacksmithing'] = "Herrer\195\173a";
		_AUCT['SkillCooking'] = "Cocinar";
		_AUCT['SkillEnchanting'] = "Encantar";
		_AUCT['SkillEngineering'] = "Ingenier\195\173a";
		_AUCT['SkillFirstaid'] = "Primeros Auxilios";
		_AUCT['SkillLeatherworking'] = "Peleter\195\173a";
		_AUCT['SkillMining'] = "Miner\195\173a";
		_AUCT['SkillTailoring'] = "Sastrer\195\173a";
		_AUCT['SkillDruid'] = "Encantos de Druidas";
		_AUCT['SkillMage'] = "Encantos de Magos";
		_AUCT['SkillPaladin'] = "Encantos de Paladines";
		_AUCT['SkillPriest'] = "Encantos de Sacerdotes";
		_AUCT['SkillRogue'] = "Encantos de P\195\173caros";
		_AUCT['SkillShaman'] = "Encantos de Chamanes";
		_AUCT['SkillWarlock'] = "Encantos de Brujos";
		
		_AUCT['TimeShort'] = "Corto";
		_AUCT['TimeMed'] = "Mediano";
		_AUCT['TimeLong'] = "Largo";
		_AUCT['TimeVlong'] = "Muy Largo";
		
		_AUCT['FrmtWelcome'] = "Auctioneer versi\195\179n %s cargado";
		
		_AUCT['FrmtBrokerHeader'] = "Ganancia Minima: %s, PMV = 'Precio Maximo de Venta'";
		_AUCT['FrmtBrokerLine'] = "%s, Ultimo(s) %s visto(s), PMV: %s, BO: %s, Prof: %s";
		_AUCT['FrmtBrokerDone'] = "Corredor finalizado";
		_AUCT['FrmtBidbrokerHeader'] = "Ganancia Minima: %s, PMV = 'Precio Maximo de Venta'";
		_AUCT['FrmtBidbrokerMinbid'] = "OfertaMinima"
		_AUCT['FrmtBidbrokerCurbid'] = "OfertaCorriente"
		_AUCT['FrmtBidbrokerLine'] = "%s, Ultimo(s) %s visto(s), PMV: %s, %s: %s, Ganancia: %s, Tiempo: %s";
		_AUCT['FrmtBidbrokerDone'] = "Corredor de ofertas finalizado";
		_AUCT['FrmtPctlessHeader'] = "Porcentaje bajo el Precio Maximo de Venta (PMV): %d%%";
		_AUCT['FrmtPctlessLine'] = "%s, Ultimo(s) %d visto(s), PMV: %s, OC: %s, Ganancia: %s, menos %s";
		_AUCT['FrmtPctlessDone'] = "Porcentajes menores finalizado.";
		_AUCT['FrmtCompeteHeader'] = "Subastas compitiendo por al menos %s debajo por art\195\173culo.";
		_AUCT['FrmtCompeteLine'] = "%s, Oferta: %s, OC %s vs %s, %s menos";
		_AUCT['FrmtCompeteDone'] = "Subastas compitiendo finalizado.";
		_AUCT['FrmtNoauct'] = "No se hallaron subastas para el art\195\173culo: %s";
		_AUCT['FrmtMedianLine'] = "De los \195\186ltimos(s) %d vistos, OC mediano por 1 %s es: %s";
		_AUCT['FrmtLowLine'] = "%s, BO: %s, Vendedor: %s, Por uno: %s, Menos que el mediano: %s";
		_AUCT['FrmtHspLine'] = "Precio Maximo de Venta por uno %s es: %s";
		
		_AUCT['FrmtInfoSeen'] = "Visto un total de %d veces en subasta";
		_AUCT['FrmtInfoForone'] = "Por 1: %s min/%s OC (%s oferta) [en %d's]";
		_AUCT['FrmtInfoAverage'] = "%s min/%s OC (%s oferta)"
		_AUCT['FrmtInfoHistmed'] = "\195\154ltimo(s) %d, OC mediano (c/u)";
		_AUCT['FrmtInfoSnapmed'] = "Explorados %d, OC mediano (c/u)";
		_AUCT['FrmtInfoSgststx'] = "Precio sugerido para su lote de %d: %s min/%s OC";
		_AUCT['FrmtInfoSgst'] = "Precio sugerido: %s min/%s OC";
		
		_AUCT['FrmtInfoBidrate'] = "%d%% tienen ofertas, %d%% tienen OC";
		_AUCT['FrmtInfoNever'] = "Nunca visto en %s";
		_AUCT['FrmtInfoAlsoseen'] = "Visto %d veces en %s";
		_AUCT['FrmtInfoClassuse'] = "Clase: %s usado para %s";
		_AUCT['FrmtInfoClass'] = "Clase: %s";
		_AUCT['FrmtInfoUse'] = "Usado para: %s";
		_AUCT['FrmtInfoBuy'] = "Compra del vendedor";
		_AUCT['FrmtInfoSell'] = "Vende al vendedor";
		_AUCT['FrmtInfoBuymult'] = "Compra %d (%s c/u)";
		_AUCT['FrmtInfoSellmult'] = "Vende %d (%s c/u)";
		_AUCT['FrmtInfoStx'] = "Amontonable en lotes de art\195\173culos %d por paquete";
		
		_AUCT['FrmtInfoHeadMulti'] = "Promedios para %d art\195\173culos:";
		_AUCT['FrmtInfoMinMulti'] = "  Oferta a empezar (%s c/u)";
		_AUCT['FrmtInfoBidMulti'] = "  Oferta (%s%s c/u)";
		_AUCT['FrmtInfoBuyMulti'] = "  Opci\195\179n a compra(%s%s c/u)";
		
		_AUCT['FrmtInfoHeadOne'] = "Promedios para este art\195\173culo:";
		_AUCT['FrmtInfoMinOne'] = "  Oferta a empezar";
		_AUCT['FrmtInfoBidOne'] = " %s con propuestas";
		_AUCT['FrmtInfoBuyOne'] = " %s con opci\195\179n a compra";
		
		_AUCT['FrmtInfoBuymedian'] = "  Opci\195\179n a compra mediano";
		
		_AUCT['FrmtInfoStacksize'] = "  Tama\195\177o promedio del paquete: %d art\195\173culos";
		
		_AUCT['FrmtUnknownLocale'] = "La localizaci\195\179n que usted especifico ('%s') no es valida. Locales v\195\161lidos son:"; 
		_AUCT['FrmtUnknownRf']     = "Parametro inv\195\161lido ('%s'). El par\195\161metro debe de estar en la forma de: [reino]-[facci\195\179n]. Por ejemplo: Al'Akir-Horde";
		_AUCT['FrmtUnknownArg']    = "'%s' no es un argumento valido de '%s'";
		
		_AUCT['FrmtActRemove'] = "Eliminando firma %s de la imagen actual de la casa de subastas.";
		
		_AUCT['FrmtAuctinfoHist'] = "%d Hist\195\179ricamente";
		_AUCT['FrmtAuctinfoSnap'] = "%d en la \195\186ltima exploraci\195\179n";
		_AUCT['FrmtAuctinfoLow'] = "M\195\173nimo de la \195\186ltima exploraci\195\179n";
		_AUCT['FrmtAuctinfoNolow'] = "Art\195\173culo no fue visto en ultima imagen";
		_AUCT['FrmtAuctinfoOrig'] = "Oferta Original";
		_AUCT['FrmtAuctinfoSugbuy'] = "Opci\195\179n a compra sugerida";
		_AUCT['FrmtAuctinfoSugbid'] = "Oferta sugerida";
		_AUCT['FrmtAuctinfoMktprice'] = "Precio del mercado";
		
		_AUCT['FrmtWarnMarkup'] = "Superando vendedor por %s%%";
		_AUCT['FrmtWarnUndercut'] = "Socavando por %s%%";
		_AUCT['FrmtWarnNocomp'] = "Sin competencia";
		_AUCT['FrmtWarnAbovemkt'] = "Competencia sobre mercado";
		_AUCT['FrmtWarnToolow'] = "Imposible igualar minimo";
		_AUCT['FrmtWarnMyprice'] = "Usando mi precio actual";
		_AUCT['FrmtWarnNodata'] = "Sin informaci\195\179n para PMV";
		
		_AUCT['CmdOff'] = "apagado";
		_AUCT['CmdOn'] = "prendido";
		_AUCT['CmdAlt'] = "alt";
		_AUCT['CmdCtrl'] = "ctrl";
		_AUCT['CmdShift'] = "shift";
		_AUCT['CmdToggle'] = "invertir";
		_AUCT['CmdDisable'] = "deshabilitar";
		_AUCT['CmdClear'] = "borrar";
		_AUCT['CmdClearAll'] = "todo";
		_AUCT['CmdClearSnapshot'] = "imagen";
		_AUCT['CmdAlso'] = "tambien";
		_AUCT['CmdAlsoOpposite'] = "opuesta";
		_AUCT['CmdLocale'] = "localidad";
		_AUCT['CmdDefault'] = "original";
		_AUCT['CmdPrintin'] = "imprimir-en";
		
		_AUCT['CmdBroker'] = "corredor";
		_AUCT['CmdBidbroker'] = "corredorofertas";
		_AUCT['CmdBidbrokerShort'] = "co";
		_AUCT['CmdEmbed'] = "integrado";
		_AUCT['CmdPercentless'] = "porcientomenos";
		_AUCT['CmdPercentlessShort'] = "pm";
		_AUCT['CmdCompete'] = "competir";
		_AUCT['CmdScan'] = "explorar";
		_AUCT['CmdAutofill'] = "autoinsertar";
		
		_AUCT['CmdPctBidmarkdown'] = "pct-menosoferta";
		_AUCT['CmdPctMarkup']      = "pct-mas";
		_AUCT['CmdPctMaxless']     = "pct-sinmaximo";
		_AUCT['CmdPctNocomp']      = "pct-sincomp";
		_AUCT['CmdPctUnderlow']    = "pct-bajomenor";
		_AUCT['CmdPctUndermkt']    = "pct-bajomercado";
		
		_AUCT['OptClear'] = "([Art\195\173culo]|".._AUCT['CmdClearAll'].."|".._AUCT['CmdClearSnapshot']..")";
		_AUCT['OptAlso'] = "(reino-facci\195\179n|".._AUCT['CmdAlsoOpposite']..")"
		_AUCT['OptLocale'] = "<localidad>";
		_AUCT['OptBroker'] = "<ganancia_plata>";
		_AUCT['OptBidbroker'] = "<ganancia_plata>";
		_AUCT['OptPercentless'] = "<porciento>";
		_AUCT['OptCompete'] = "<plata_menos>";
		_AUCT['OptScan'] = "";
		_AUCT['OptScale'] = "<escala>";
		_AUCT['OptScaleDefault'] = 1.0;
		_AUCT['OptDefault'] = "(<opci\195\179n>|".._AUCT['CmdClearAll']..")";
		_AUCT['OptPrintin'] = "(<indiceVentana>[N\195\186mero]|<nombreVentana>[Serie])";
		
		_AUCT['OptPctBidmarkdown'] = "<porciento>";
		_AUCT['OptPctMarkup'] = "<porciento>";
		_AUCT['OptPctMaxless'] = "<porciento>";
		_AUCT['OptPctNocomp'] = "<porciento>";
		_AUCT['OptPctUnderlow'] = "<porciento>";
		_AUCT['OptPctUndermkt'] = "<porciento>";
		
		_AUCT['OptPctBidmarkdownDefault'] = 20;
		_AUCT['OptPctMarkupDefault'] = 300;
		_AUCT['OptPctMaxlessDefault'] = 30;
		_AUCT['OptPctNocompDefault'] = 2;
		_AUCT['OptPctUnderlowDefault'] = 5;
		_AUCT['OptPctUndermktDefault'] = 20;
		
		_AUCT['ShowVerbose'] = "ver-literal";
		_AUCT['ShowAverage'] = "ver-promedio";
		_AUCT['ShowLink'] = "ver-enlace";
		_AUCT['ShowMedian'] = "ver-mediano";
		_AUCT['ShowStats'] = "ver-estadisticas";
		_AUCT['ShowSuggest'] = "ver-sugerencia";
		_AUCT['ShowEmbedBlank'] = "ver-integrado-lineavacia";
		_AUCT['ShowRedo'] = "ver-advertencia";
		
		_AUCT['HelpOnoff'] = "Enciende o apaga la informacion sobre las subastas";
		_AUCT['HelpDisable'] = "Impide que Auctioneer se carge automaticamente la proxima vez que usted entre al juego";
		_AUCT['HelpVerbose'] = "Selecciona para mostrar promedios literales (O apaga para que aparezcan en una sola linea)";
		_AUCT['HelpAverage'] = "Selecciona para mostrar precio promedio de la subasta para el art\195\173culo";
		_AUCT['HelpLink'] = "Selecciona para mostrar el numero de enlace del art\195\173culo en la caja de ayuda";
		_AUCT['HelpMedian'] = "Selecciona para mostrar el precio promedio para la opci\195\179n a compra";
		_AUCT['HelpSuggest'] = "Selecciona para mostrar el precio sugerido de subasta para el art\195\173culo";
		_AUCT['HelpStats'] = "Selecciona para mostrar porcentajes para ofertas/opci\195\179n a compra del art\195\173culo";
		_AUCT['HelpEmbedBlank'] = "Selecciona para mostrar una linea en blanco entre informacion de la caja de ayuda y la informacion de subasta cuando el modo integrado esta seleccionado";
		_AUCT['HelpClear'] = "Eliminar la informacion existente sobre el art\195\173culo(se debe usar shift-click para insertar el/los articulo(s) en el comando) Tambien se pueden especificar las palabras claves \"todo\" or \"imagen\"";
		_AUCT['HelpAlso'] = "Mostrar tambi\195\169n los valores de otros servidores en la caja de ayuda. Para el reino escribe el nombre del reino y para facci\195\179n escribe el nombre de la facci\195\179n. Por ejemplo: \"/auctioneer tambien Al'Akir-Horde\". La palabra clave \"opuesta\" significa facci\195\179n opuesta, \"apagar\" desabilita la funci\195\179n.";
		_AUCT['HelpLocale'] = "Cambiar la localidad que Auctioneer usa para sus mensajes";
		_AUCT['HelpBroker'] = "Muestra las subastas de la exploraci\195\179n mas reciente en las cuales se puede poner una oferta para luego revenderlas para ganancia";
		_AUCT['HelpBidbroker'] = "Muestra subastas de corto o medio termino de la exploraci\195\179n mas reciente a las cuales se puede poner una oferta y obtener ganancia";
		_AUCT['HelpEmbed'] = "Insertar el texto en la caja de ayuda original del juego (nota: algunas capacidades se desabilitan cuando esta opci\195\179n es seleccionada)";
		_AUCT['HelpPercentless'] = "Muestra cualquier subasta recientemente explorada en la que la compra de participaciones es un porcentaje menor del precio de venta mas alto.";
		_AUCT['HelpCompete'] = "Muestra cualquier subasta explorada recientemente cuya opci\195\179n a compra es menor que alguno de tus art\195\173culos";
		_AUCT['HelpScan'] = "Realiza una exploracion de la casa de subastas en la proxima visita, o mientras este alli (tambien existe un bot\195\179n en el panel de la casa de subastas). Seleccione alli las categorias a explorar.";
		_AUCT['HelpAutofill'] = "Auto-completar precios cuando se a\195\177adan art\195\173culos a subastar en el panel de la casa de subastas";
		_AUCT['HelpPctBidmarkdown'] = "Ajusta el porcentaje del precio de compra por debajo del cual Auctioneer marcara las ofertas";
		_AUCT['HelpPctMarkup'] = "El porcentaje que sera incrementado el precio de venta del vendedor cuando no existan otros valores disponibles.";
		_AUCT['HelpPctMaxless'] = "Ajusta el maximo porcentaje por debajo del valor de mercado que Auctioneer tratara de igualar antes de darse por vencido.";
		_AUCT['HelpPctNocomp'] = "El porcentaje bajo el precio del mercado que Auctioneer usar\195\161 cuando no hay competencia";
		_AUCT['HelpPctUnderlow'] = "Ajusta el porcentaje bajo el menor precio m\195\173nimo de subasta que Auctioneer aplicar\195\161";
		_AUCT['HelpPctUndermkt'] = "Porcentaje a usar cuando sea imposible vencer a la competencia (debido al sinmaximo)";
		_AUCT['HelpRedo'] = "Selecciona para mostrat una advertencia cuando la p\195\161gina corriente en la casa de subastas ha tomado demasiado tiempo para explorar debido a problemas con el servidor.";
		_AUCT['HelpDefault'] = "Revertir una opci\195\179n de Auctioneer a su configuraci\195\179n de f\195\161brica. Tambi\195\169n puede especificar la palabra clave \"todo\" pata revertir todas las opciones de Auctioneer a sus configuraciones de f\195\161brica."
		_AUCT['HelpPrintin'] = "Selecciona cual ventana de mensajes va a usar Auctioneer para imprimir su informacion. Puede especificar el nombre o el \195\173ndice de la ventana.";
		
		_AUCT['DisableMsg'] = "Deshabilitando la auto-carga de Auctioneer";
		
		_AUCT['StatOn'] = "Mostrando la configuracion corriente para la informacion de subastas";
		_AUCT['StatOff'] = "Ocultando toda informaci\195\179n de subastas";
		
		_AUCT['FrmtActClearall'] = "Eliminando toda la informaci\195\179n de subastas para %s";
		_AUCT['FrmtActClearsnap'] = "Eliminando la imagen actual de la casa de subastas.";
		_AUCT['FrmtActClearOk'] = "Informacion eliminada para el art\195\173culo: %s";
		_AUCT['FrmtActClearFail'] = "Imposible encontrar art\195\173culo: %s";
		_AUCT['FrmtActEnable'] = "Mostrando informacion del art\195\173culo: %s ";
		_AUCT['FrmtActDisable'] = "Ocultando informacion de articulo: %s ";
		_AUCT['FrmtActEnabledOn'] = "Mostrando %s de los art\195\173culos usando %s";
		_AUCT['FrmtActSet'] = "%s ajustado(a) a '%s'";
		_AUCT['FrmtActUnknown'] = "Comando o palabra clave desconocida: '%s'";
		_AUCT['FrmtActDefaultall'] = "Todas las opciones de Auctioneer han sido revertidas a sus configuraciones de f\195\161brica.";
		_AUCT['FrmtActDefault'] = "La opci\195\179n %s de Auctioneer ha sido revertida a su configuraci\195\179n de f\195\161brica.";
		_AUCT['FrmtPrintin'] = "Los mensajes de Auctioneer se imprimir\195\161n en la ventana de comunicaci\195\179n \"%s\"";
		
		_AUCT['TextScan'] = "Explorar";
		_AUCT['TextAuction'] = "Subasta";
		_AUCT['TextNone'] = "ningun";
		_AUCT['TextUsage'] = "Uso:";
		
		-- AH Scanning localizations
		
		_AUCT['AuctionScanStart'] = "Auctioneer: Explorando \"%s\" p\195\161gina 1...";
		_AUCT['AuctionPageN'] = "Auctioneer: Explorando \"%s\" p\195\161gina %d de %d\nSubastas por segundo: %s\nTiempo estimado para completar: %s";
		_AUCT['AuctionScanDone'] = "Auctioneer: La exploraci\195\179n de las subastas ha finalizado";
		_AUCT['AuctionScanNexttime'] = "Auctioneer ejecutara una exploracion de las subastas la proxima vez que usted hable con un subastador.";
		_AUCT['AuctionScanNocat'] = "Usted debe tener al menos una categoria seleccionada para poder explorar.";
		_AUCT['AuctionScanRedo'] = "La p\195\161gina corriente ha tomado mas de %d segundos para completar. Tratando p\195\161gina otra vez.";
		
		_AUCT['MesgConvert'] = "Conversi\195\179n de base de datos de Auctioneer. Favor de hacer una copia del SavedVariables\\Auctioneer.lua para la reserva primero.%s%s";
		_AUCT['MesgNotconverting'] = "Auctioneer no convertir\195\161 su base de datos, pero no funcionar\195\161 hasta que la base de datos sea convertida.";
		_AUCT['MesgConvertYes'] = "Convertir";
		_AUCT['MesgConvertNo'] = "Deshabilitar Auctioneer";
		
		_AUCT['MesgNotLoaded'] = "Auctioneer no esta cargado. Escriba /auctioneer para mas informaci\195\179n.";
		
		_AUCT['AuctionTotalAucts'] = "Total de subastas exploradas: %s";
		_AUCT['AuctionNewAucts'] = "Nuevas subastas exploradas: %s";
		_AUCT['AuctionOldAucts'] = "Subastas exploradas previamente: %s";
		_AUCT['AuctionDefunctAucts'] = "Subastas viejas removidas: %s";
		_AUCT['AuctionDiscrepancies'] = "Discrepancias: %s";
		
		-- GUI localizations
		
		_AUCT['GuiMainHelp'] = "Contiene ajustes para Auctioneer \nun aditamento que muestra informacion sobre art\195\173culos y analiza informaci\195\179n de subastas. \nSeleccione \"Explorar\" en la casa de subastas para coleccionar informacion sobre las subastas.";
		_AUCT['GuiMainEnable'] = "Encender Auctioneer";
		_AUCT['GuiLocale'] = "Ajustar localidad a";
		_AUCT['GuiVerbose'] = "Modo literal";
		_AUCT['GuiStatsEnable'] = "Ver estad\195\173sticas";
		_AUCT['GuiStatsHeader'] = "Estad\195\173sticas de precios de art\195\173culos";
		_AUCT['GuiStatsHelp'] = "Mostrar las siguientes estad\195\173sticas en la caja de ayuda.";
		_AUCT['GuiAverages'] = "Mostrar Promedios";
		_AUCT['GuiMedian'] = "Mostrar Medianos";
		_AUCT['GuiSuggest'] = "Mostrar Precios Sugeridos";
		_AUCT['GuiVendorHeader'] = "Precios de Vendedor";
		_AUCT['GuiVendorHelp'] = "Opciones relacionadas a precios de compra/venta a vendedores";
		_AUCT['GuiVendor'] = "Mostrar Precios a Vendedores";
		_AUCT['GuiVendorBuy'] = "Mostrar precios de compra a vendedores";
		_AUCT['GuiVendorSell'] = "Mostrar precios de venta a vendedores";
		_AUCT['GuiEmbedHeader'] = "Integraci\195\179n";
		_AUCT['GuiEmbed'] = "Integrar informaci\195\179n en la caja de ayuda";
		_AUCT['GuiEmbedBlankline'] = "Mostrar linea en blanco.";
		_AUCT['GuiClearHeader'] = "Eliminar Informaci\195\179n";
		_AUCT['GuiClearHelp'] = "Elimina la informacion de Auctioneer. \nSelecciona si eliminar toda la informaci\195\179n o solamente la im\195\161gen corriente.\nADVERTENCIA: Estas acciones NO son reversibles.";
		_AUCT['GuiClearall'] = "Eliminar toda la informaci\195\179n";
		_AUCT['GuiClearallHelp'] = "Seleccione aqui para eliminar toda la informaci\195\179n de Auctioneer para el reino-facci\195\179n corriente.";
		_AUCT['GuiClearallNote'] = "el reino-facci\195\179n corriente.";
		_AUCT['GuiClearallButton'] = "Eliminar Todo";
		_AUCT['GuiClearsnap'] = "Eliminar imagen corriente";
		_AUCT['GuiClearsnapHelp'] = "Presione aqui para eliminar la ultima imagen de informacion de Auctioneer.";
		_AUCT['GuiClearsnapButton'] = "Eliminar Imagen";
		_AUCT['GuiPercentsHeader'] = "Limites de Porcentajes de Auctioneer";
		_AUCT['GuiPercentsHelp'] = "ADVERTENCIA: Las siguientes opciones son para usuarios expertos SOLAMENTE.\nAjuste los siguientes valores para cambiar cuan agresivo es Auctioneer al determinar niveles provechosos.";
		_AUCT['GuiBidmarkdown'] = "Porciento menos oferta";
		_AUCT['GuiMarkup'] = "Porciento sobre vendedor";
		_AUCT['GuiMaxless'] = "Porciento m\195\161ximo bajo mercado";
		_AUCT['GuiNocomp'] = "Porciento sin competencia.";
		_AUCT['GuiUnderlow'] = "Porciento bajo menor subasta";
		_AUCT['GuiUndermkt'] = "Porciento bajo mercado";
		_AUCT['GuiOtherHeader'] = "Otras Opciones";
		_AUCT['GuiOtherHelp'] = "Opciones miscel\195\161neas de Auctioneer";
		_AUCT['GuiAutofill'] = "Autocompletar precios en la casa de subastas";
		_AUCT['GuiAlso'] = "Tambi\195\169n mostrar valores para";
		_AUCT['GuiAlsoOpposite'] = "Mostrando informaci\195\179n para la facci\195\179n opuesta.";
		_AUCT['GuiAlsoOff'] = "No mostrando informaci\195\179n para otro reino-facci\195\179n";
		_AUCT['GuiAlsoDisplay'] = "Mostrando informaci\195\179n para %s";
		_AUCT['GuiLink'] = "Ver numero de enlace";
		_AUCT['GuiReloadui'] = "Recargar Interf\195\161z";
		_AUCT['GuiReloaduiHelp'] = "Presione aqui para recargar el interf\195\161z de WoW luego de haber seleccionado una localidad diferente. Esto es para que el lenguaje de configuraci\195\179n sea el mismo que el de Auctioneer.\nNota: Esta operaci\195\179n puede tomar unos minutos.";
		_AUCT['GuiReloaduiButton'] = "Recargar";
		_AUCT['GuiReloaduiFeedback'] = "Recargando el Interf\195\161z de WoW";
		_AUCT['GuiRedo'] = "Mostrar Advertencia de Exploraci\195\179n";
		_AUCT['GuiDefaultAllButton'] = "Revertir Todo";
		_AUCT['GuiDefaultAll'] = "Revertir todas las opciones de Auctioneer";
		_AUCT['GuiDefaultAllHelp'] = "Seleccione aqui para revertir todas las opciones de Auctioneer a sus configuraciones de f\195\161brica.\nADVERTENCIA: Esta acci\195\179n NO es reversible.";
		_AUCT['GuiDefaultOption'] = "Revertir esta opci\195\179n";
		_AUCT['GuiPrintin'] = "Seleccione la ventana deseada";
end

-- Locale strings for the frFR locale
if locale == "frFR" then
		-- Encoded in UTF8
		_AUCT['AdditBuff']        = "Buff";
		_AUCT['AdditDrink']       = "Boisson";
		_AUCT['AdditFood']        = "Nourriture";
		_AUCT['AdditPoison']      = "Poison";
		_AUCT['AdditPotion']      = "Potion";
		
		_AUCT['SkillAlchemy']        = "Alchimie";
		_AUCT['SkillBlacksmithing']  = "Forgeron";
		_AUCT['SkillCooking']        = "Cuisine";
		_AUCT['SkillEnchanting']     = "Enchantement";
		_AUCT['SkillEngineering']    = "Ing\195\169nieur";
		_AUCT['SkillFirstaid']       = "Premiers Soins";
		_AUCT['SkillLeatherworking'] = "Travail du Cuir";
		_AUCT['SkillMining']         = "Minage";
		_AUCT['SkillTailoring']      = "Tailleur";
		
		_AUCT['FrmtBrokerHeader'] = "Profit Minimum: %s, HSP = 'Prix de vente maximum', AI = 'Achat Imm\195\169diat'";
		_AUCT['FrmtBrokerLine'] = "%s, Derniers %s vus, HSP: %s, AI: %s, Prof: %s";
		_AUCT['FrmtBrokerDone'] = "Brokering termin\195\169";
		_AUCT['FrmtBidbrokerHeader'] = "Profit minimum: %s, HSP = 'Prix de vente maximum'";
		_AUCT['FrmtBidbrokerMinbid'] = "EnchMin"
		_AUCT['FrmtBidbrokerCurbid'] = "EnchAct"
		_AUCT['FrmtBidbrokerLine'] = "%s, Derniers %s vus, HSP: %s, %s: %s, Prof: %s, Temps: %s";
		_AUCT['FrmtBidbrokerDone'] = "Bid brokering termin\195\169";
		_AUCT['FrmtPctlessHeader'] = "Percentage inf\195\169rieur au HSP: %d%%";
		_AUCT['FrmtPctlessLine'] = "%s, Derniers %d vus, HSP: %s, AI: %s, Prof: %s, Moins %s";
		_AUCT['FrmtPctlessDone'] = "Percentage inf\195\169rieur termin\195\169.";
		_AUCT['FrmtCompeteHeader'] = "Encheres comp\195\169titives au moins %s de moins par objet.";
		_AUCT['FrmtCompeteLine'] = "%s, Ench: %s, BO %s vs %s, %s de moins";
		_AUCT['FrmtCompeteDone'] = "Ench\195\168res comp\195\169titives termin\195\169es.";
		_AUCT['FrmtNoauct'] = "Pas d'ench\195\168re trouv\195\169e pour l'objet: %s";
		_AUCT['FrmtMedianLine'] = "Des derniers %d vus, l'achat moyen pour 1 %s est de: %s";
		_AUCT['FrmtLowLine'] = "%s, BO: %s, Vendeur: %s, L'unit\195\169: %s, Moins de la moyenne: %s";
		_AUCT['FrmtHspLine'] = "Prix de vente maximum pour un %s est de: %s";
		_AUCT['FrmtInfoSeen'] = "Vu %d fois aux ench\195\168res";
		_AUCT['FrmtInfoForone'] = "Pour 1: %s min/%s achat (%s ench\195\168re) [par %d]";
		_AUCT['FrmtInfoAverage'] = "%s min/%s achat (%s ench\195\168re)"
		_AUCT['FrmtInfoHistmed'] = "Derniers %d vus, achat moyen:";
		_AUCT['FrmtInfoSnapmed'] = "Vu %d fois au dernier scan, achat moyen:";
		_AUCT['FrmtInfoBidrate'] = "%d%% avec ench\195\168re, %d%% avec achat imm\195\169diat";
		_AUCT['FrmtInfoNever'] = "Jamais vu aux ench\195\168res";
		_AUCT['FrmtInfoAlsoseen'] = "Vu %d fois aux %s";
		_AUCT['FrmtInfoClassuse'] = "Classe: %s utilis\195\169 pour %s";
		_AUCT['FrmtInfoClass'] = "Classe: %s";
		_AUCT['FrmtInfoUse'] = "Utilis\195\169 pour: %s";
		_AUCT['FrmtInfoBuy'] = "Achat%s au marchand";
		_AUCT['FrmtInfoSell'] = "Vente%s au marchand";
		_AUCT['FrmtInfoBuymult'] = "Achat%s %d (%s chacun)";
		_AUCT['FrmtInfoSellmult'] = "Vente%s %d (%s chacun)";
		_AUCT['FrmtInfoStx'] = "Pile par lots de %d";
		
		-- AH Scanning localizations
		_AUCT['AuctionScanStart'] = "Auctioneer: Scan de la cat\195\169gorie '%s': page 1...";
		_AUCT['AuctionPageN'] = "Auctioneer: Scan de la cat\195\169gorie '%s': page %d sur %d";
		_AUCT['AuctionScanDone'] = "Auctioneer: Scan termin\195\169";
		_AUCT['AuctionScanNexttime'] = "Auctioneer fera un scan complet de la maison des ventes la prochaine fois que vous parlerez \195\160 un commisaire-priseur.";
		

end

end

Auctioneer_SetLocaleStrings(GetLocale);

