--
--	$LastChangedBy: karlkfi $
--	$Rev: 3767 $
--	$Date: 2006-07-09 23:22:55 -0700 (Sun, 09 Jul 2006) $
--
SEA_HERB_LIST = {
		"Peacebloom",
		"Silverleaf",
		"Earthroot",
		-- Tuatara: removed as I can't find any reference to this in my research
		--"Snakeroot",
		"Mageroyal",
		"Briarthorn",
		"Swiftthistle",
		"Stranglekelp",
		"Bruiseweed",
		"Wild Steelbloom",
		"Grave Moss",
		"Kingsblood",
		"Liferoot",
		"Fadeleaf",
		"Khadgar's Whisker",
		"Wintersbite",
		"Firebloom",
		"Purple Lotus",
		"Sungrass",
		"Blindweed",
		"Ghost Mushroom",
		"Gromsblood",
		"Goldthorn"
	};

SEA_ORE_LIST =	{
		"Copper Ore",
		"Tin Ore",
		"Silver Ore",
		"Iron Ore",
		"Gold Ore",
		"Mithril Ore",
		"Truesilver Ore",
		"Thorium Ore"
	};

SEA_GEM_LIST = {
		"Malachite",
		"Moss Agate",
		"Tigerseye",
		"Citrine",
		"Jade",
		"Shadowgem",
		"Aquamarine",
		"Blue Pearl",
		"Black Pearl",
		"Golden Pearl",
		"Star Ruby"
	};

SEA_POTION_LIST = {
		"Potion",
		"Elixir",
		"Oil",
		"Holy Spring Water"
	};

SEA_CLOTH_LIST = {
		"Cloth",
		"Wool",
		"Silk",
		"Mageweave",
		"Runecloth",
		"Felcloth",
		"Mooncloth"
	};
SEA_LEATHER_LIST =  {
		"Black Dragonscale",
		"Black Whelp Scale",
		"Blue Dragonscale",
		"Chimera Leather",
		"Deviate Scale",
		"Frostsaber Leather",
		"Green Dragonscale",
		"Green Whelp Scale",
		"Heavy Leather",
		"Heavy Hide",
		"Heavy Scorpid Scale",
		"Light Leather",
		"Light Hide",
		"Medium Leather",
		"Medium Hide",
		"Perfect Deviate Scale",
		"Red Dragonscale",
		"Red Whelp Scale",
		"Rugged Leather",
		"Rugged Hide",
		"Ruined Leather Scraps",
		"Scorpid Scale",
		"Shadowcat Hide",
		"Thick Yeti Hide",
		"Thick Leather",
		"Thick Hide",
		"Thick Wolfhide",
		"Turtle Scale",
		"Warbear Leather",
		"Worn Dragonscale",
	};

SEA_LEATHERWORKING_LIST = {
		"Cured Light Hide",
		"Cured Medium Hide",
		"Cured Heavy Hide",
		"Cured Thick Hide",
		"Cured Rugged Hide"
	};

SEA_FISHING_LIST = {
		"Shiny Bauble",
		"Bright Baubles",
		"Nightcrawlers",
		"Fishing Pole",
		"Aquadynamic Fish Attractor"
	};

SEA_WARLOCK_LIST = {
		"Soul Shard",
		"Healthstone",
		"Spellstone",
		"Soulstone"
	};

SEA_SHAMAN_LIST = {
		"Earth Totem",
		"Fire Totem",
		"Water Totem",
		"Air Totem",
		"Sapta"
	};

SEA_MAGE_LIST =  {
		"Mana Agate",
		"Mana Jade",
		"Mana Citrine",
		"Mana Ruby"
	};

SEA_FOOD_LIST =  {
		"Freshly Baked Bread",
		"Mulgore Spice Bread",
		"Soft Banana Bread",
		"Tough Hunk of Bread",
		"Moist Cornbread",
		"Haunch of Meat",
		"Mutton Chop",
		"Wild Hog Shank",
		"Tough Jerky",
		"Stormwind Brie",
		"Fine Aged Cheddar",
		"Alterac Swiss",
		"Goldenbark Apple",
		"Ripe Watermelon",
		"Snapvine Watermelon",
		"Tel'Abim Banana",
		"Cured Ham Steak",
		"Dalaran Sharp",
		"Darnassian Bleu",
		"Dwarven Mild",
		"Charred Wolf Meat",
		"Spiced Wolf Meat",
		"Roasted Boar Meat",
		"Hot Wolf Ribs",
		"Slitherskin Mackerel",
		"Brilliant Smallfish",
		-- Tuatara: Item doesn't exist from my research
		--"Kaldorei Caviar",
		"Scorpid Surprise",
		"Beer Basted Boar Ribs",
		"Smoked Bear Meat",
		"Roasted Kodo Meat",
		"Longjaw Mud Snapper",
		"Rainbow Fin Albacore",
		"Spinefin Halibut",
		"Strider Stew",
		"Fillet of Frenzy",
		"Boiled Clams",
		"Goretusk Liver Pie",
		"Loch Frenzy Delight",
		"Coyote Steak",
		"Blood Sausage",
		"Westfall Stew",
		"Crab Cake",
		"Crispy Lizard Tail",
		"Succulent Pork Ribs",
		"Crocolisk Steak",
		"Savory Deviate Delight",
		"Scorpid Surprise",
		"Cooked Crab Claw",
		"Dig Rat Stew",
		"Murloc Fin Soup",
		"Clam Chowder",
		"Seasoned Wolf Kabob",
		"Gooey Spider Cake",
		"Big Bear Steak",
		"Lean Venison",
		"Dry Pork Ribs",
		"Crocolisk Gumbo",
		"Hot Lion Chops",
		"Goblin Deviled Clams",
		"Curiously Tasty Omelet",
		"Monster Omelet",
		"Tasty Lion Steak",
		"Barbecued Buzzard Wing",
		"Giant Clam Scorcho",
		"Soothing Turtle Bisque",
		"Rockscale Cod",
		"Delicious Cave Mold",
		"Red-speckled Mushroom",
		"Forest Mushroom Cap",
		"Dried King Bolete",
		"Spongy Morel",
		"Raw Black Truffle",
		"Strider Stew",
		"Mystery Stew",
		"Roast Raptor",
		"Carrion Surprise",
		"Dragonbreath Chilli",
		"Spiced Chilli Crab",
		"Goldthorn Tea",
		"Grilled Squid",
		"Moon Harvest Pumpkin",
		"Small Pumpkin",
		"Tigule and Foror's Strawberry Ice Cream",
		"Blood Sausage",
		"Spider Sausage",
		"Gingerbread Cookie",
		"Clamlette Surprise",
		"Egg Nog",
		"Deep Fried Plantains",
		"Roasted Quail",
		"Homemade Cherry Pie",
		-- conjured stuff
		"Conjured Bread",
		"Conjured Muffin",
		"Conjured Pumpernickel",
		"Conjured Rye",
		"Conjured Sourdough",
		"Conjured Sweet Roll"
	};

SEA_DRINK_LIST = {
		"Refreshing Spring Water",
		"Cherry Grog",
		"Moonberry Juice",
		"Ice Cold Milk",
		"Melon Juice",
		"Sweet Nectar",
		"Morning Glory Dew",
		"Bubbling Water",
		-- conjured stuff
		"Conjured Crystal Water",
		"Conjured Fresh Water",
		"Conjured Mineral Water",
		"Conjured Purified Water",
		"Conjured Sparkling Water",
		"Conjured Spring Water",
		"Conjured Water"
	};

SEA_REAGENT_ALCHEMY ={
			"Arcane Crystal",
			"Arthas' Tears",
			"Black Lotus",
			"Black Vitriol",
			"Blackmouth Oil",
			"Blindweed",
			"Briarthorn",
			"Bruiseweed",
			"Crystal Vial",
			--"Delicate Feather",
			"Deviate Fish",
			"Discolored Worg Heart",
			"Dream Dust",
			"Dreamfoil",
			"Earthroot",
			"Elemental Air",
			"Elemental Earth",
			"Elemental Fire",
			"Elemental Water",
			"Empty Vial",
			"Essence of Air",
			"Essence of Earth",
			"Essence of Fire",
			"Essence of Undeath",
			"Essence of Water",
			"Fadeleaf",
			"Fire Oil",
			"Firebloom",
			"Firefin Snapper",
			"Ghost Mushroom",
			"Golden Sansam",
			"Goldthorn",
			"Grave Moss",
			"Gromsblood",
			"Heart of the Wild",
			"Icecap",
			"Ichor of Undeath",
			"Iron Bar",
			"Khadgar's Whisker",
			"Kingsblood",
			"Large Fang",
			"Large Venom Sac",
			"Leaded Vial",
			"Liferoot",
			"Living Essence",
			"Mageroyal",
			"Minor Healing Potion",
			"Mithril Bar",
			"Mithril Ore",
			"Mountain Silversage",
			"Oily Blackmouth",
			"Peacebloom",
			"Plaguebloom",
			"Purple Dye",
			"Purple Lotus",
			"Shadow Oil",
			"Sharp Claw",
			"Silverleaf",
			"Small Flame Sac",
			"Stonescale Eel",
			"Stonescale Oil",
			"Stranglekelp",
			"Sungrass",
			"Swiftthistle",
			"Thorium Bar",
			"Thorium Ore",
			"Volatile Rum",
			"Wild Steelbloom",
			"Wildvine",
			"Wintersbite"
		};

SEA_REAGENT_BLACKSMITHING = {
		"Aquamarine",
		"Arcanite Bar",
		"Azerothian Diamond",
		"Black Pearl",
		"Blood of the Mountain",
		"Blue Power Crystal",
		"Blue Sapphire",
		"Breath of Wind",
		"Bronze Bar",
		"Citrine",
		"Coarse Grinding Stone",
		"Coarse Stone",
		"Copper Bar",
		"Core of Earth",
		"Dark Iron Bar",
		"Demonic Rune",
		"Dense Grinding Stone",
		"Dense Stone",
		"Elemental Air",
		"Elemental Earth",
		"Elemental Fire",
		"Elemental Water",
		"Elixir of Ogre's Strength",
		"Enchanted Leather",
		"Enchanted Thorium Bar",
		"Essence of Earth",
		"Essence of Fire",
		"Essence of Undeath",
		"Essence of Water",
		"Fine Thread",
		"Frost Oil",
		"Gold Bar",
		"Green Dye",
		"Green Leather Armor",
		"Green Power Crystal",
		"Guardian Gloves",
		"Guardian Stone",
		"Heart of Fire",
		"Heavy Grinding Stone",
		"Heavy Leather",
		"Heavy Stone",
		"Huge Emerald",
		"Ichor of Undeath",
		"Iridescent Pearl",
		"Iron Bar",
		"Jade",
		"Jet Black Feather",
		"Large Fang",
		"Large Opal",
		"Lesser Invisibility Potion",
		"Lesser Moonstone",
		"Light Leather",
		"Linen Cloth",
		"Living Essence",
		"Mageweave Cloth",
		"Malachite",
		"Medium Leather",
		"Mithril Bar",
		"Moss Agate",
		"Powerful Mojo",
		"Red Power Crystal",
		"Righteous Orb",
		"Rough Grinding Stone",
		"Rough Stone",
		"Rugged Leather",
		"Runecloth",
		"Shadow Oil",
		"Shadowgem",
		"Sharp Claw",
		"Silk Cloth",
		"Silver Bar",
		"Small Lustrous Pearl",
		"Solid Grinding Stone",
		"Solid Stone",
		"Star Ruby",
		"Steel Bar",
		"Strong Flux",
		"Swiftness Potion",
		"Thick Leather",
		"Thorium Bar",
		"Tigerseye",
		"Truesilver Bar",
		"Weak Flux",
		"Wicked Claw",
		"Wildvine",
		"Wool Cloth",
		"Yellow Power Crystal"
		 };

		 SEA_REAGENT_ENCHANTING = {
 	"Aquamarine",
	"Arcanite Rod",
	"Black Pearl",
	"Blackmouth Oil",
	"Blood of the Mountain",
	"Breath of Wind",
	"Copper Rod",
	"Core of Earth",
	"Dream Dust",
	"Elemental Earth",
	"Elemental Fire",
	"Elixir of Demonslaying",
	"Essence of Air",
	"Essence of Fire",
	"Essence of Undeath",
	"Essence of Water",
	"Fire Oil",
	"Frost Oil",
	"Globe of Water",
	"Golden Pearl",
	"Golden Rod",
	"Greater Astral Essence",
	"Greater Eternal Essence",
	"Greater Magic Essence",
	"Greater Mystic Essence",
	"Greater Nether Essence",
	"Green Whelp Scale",
	"Heart of Fire",
	"Icecap",
	"Ichor of Undeath",
	"Illusion Dust",
	"Iridescent Pearl",
	"Iron Ore",
	"Kingsblood",
	"Large Brilliant Shard",
	"Large Fang",
	"Large Glimmering Shard",
	"Large Glowing Shard",
	"Large Radiant Shard",
	"Lesser Astral Essence",
	"Lesser Eternal Essence",
	"Lesser Magic Essence",
	"Lesser Mystic Essence",
	"Lesser Nether Essence",
	"Living Essence",
	"Righteous Orb",
	"Rugged Leather",
	"Shadow Protection Potion",
	"Shadowgem",
	"Silver Rod",
	"Simple Wood",
	"Simple Wood",
	"Small Brilliant Shard",
	"Small Glimmering Shard",
	"Small Glowing Shard",
	"Small Radiant Shard",
	"Soul Dust",
	"Star Wood",
	"Strange Dust",
	"Sungrass",
	"Thorium Bar",
	"Truesilver Bar",
	"Truesilver Rod",
	"Vision Dust",
	"Wildvine",
	"Wintersbite"
 };

SEA_REAGENT_ENGINEERING =
{
	"Accurate Scope",
	"Aquamarine",
	"Arcanite Bar",
	"Azerothian Diamond",
	"Big Iron Bomb",
	"Black Mageweave Boots",
	"Blank Parchment",
	"Blue Pearl",
	"Blue Sapphire",
	"Bolt of Mageweave",
	"Bronze Bar",
	"Bronze Framework",
	"Bronze Tube",
	"Catseye Elixir",
	"Citrine",
	"Coarse Blasting Powder",
	"Coarse Stone",
	"Copper Bar",
	"Copper Modulator",
	"Copper Tube",
	"Core of Earth",
	"Dark Iron Bar",
	"Deadly Scope",
	"Dense Blasting Powder",
	"Dense Stone",
	"Dusky Belt",
	"Elemental Earth",
	"Elemental Fire",
	"Enchanted Leather",
	"Enchanted Thorium Bar",
	"Engineer's Ink",
	"Essence of Earth",
	"Essence of Fire",
	"Essence of Undeath",
	"Fire Goggles",
	"Flask of Mojo",
	"Flask of Oil",
	"Flying Tiger Goggles",
	"Frost Oil",
	"Fused Wiring",
	"Goblin Construction Helmet",
	"Goblin Rocket Fuel",
	"Gold Bar",
	"Gold Power Core",
	"Green Tinted Goggles",
	"Gyrochronatom",
	"Handful of Copper Bolts",
	"Heart of Fire",
	"Heart of the Wild",
	"Heavy Blasting Powder",
	"Heavy Leather",
	"Heavy Stock",
	"Heavy Stone",
	"Huge Emerald",
	"Ichor of Undeath",
	"Inlaid Mithril Cylinder",
	"Iron Bar",
	"Iron Strut",
	"Ironweb Spider Silk",
	"Jade",
	"Large Opal",
	"Lesser Moonstone",
	"Light Leather",
	"Linen Cloth",
	"Living Essence",
	"Mageweave Cloth",
	"Malachite",
	"Medium Leather",
	"Minor Soulstone",
	"Mithril Bar",
	"Mithril Casing",
	"Mithril Mechanical Dragonling",
	"Mithril Tube",
	"Moss Agate",
	"Nightcrawlers",
	"Razor Arrow",
	"Refreshing Spring Water",
	"Rough Blasting Powder",
	"Rough Stone",
	"Rugged Leather",
	"Runecloth",
	"Shadow Silk",
	"Shadowgem",
	"Silk Cloth",
	"Silver Bar",
	"Silver Bar",
	"Silver Contact",
	"Small Flame Sac",
	"Snowball",
	"Solid Blasting Powder",
	"Solid Dynamite",
	"Solid Stone",
	"Spellpower Goggles Xtreme",
	"Star Ruby",
	"Steel Bar",
	"Thick Leather",
	"Thick Spider's Silk",
	"Thorium Bar",
	"Thorium Tube",
	"Thorium Widget",
	"Tigerseye",
	"Truesilver Bar",
	"Unstable Trigger",
	"Weak Flux",
	"Whirring Bronze Gizmo",
	"Wildvine",
	"Wooden Stock",
	"Wool Cloth",
};

SEA_REAGENT_LEATHERWORKING = {
	"Black Dragonscale",
	"Black Dye",
	"Black Pearl",
	"Black Whelp Scale",
	"Bleach",
	"Blue Dragonscale",
	"Bolt of Silk Cloth",
	"Bolt of Woolen Cloth",
	"Chimera Leather",
	"Citrine",
	"Coarse Gorilla Hair",
	"Coarse Thread",
	"Core of Earth",
	"Cured Heavy Hide",
	"Cured Light Hide",
	"Cured Medium Hide",
	"Cured Rugged Hide",
	"Cured Thick Hide",
	"Deeprock Salt",
	"Deviate Scale",
	"Devilsaur Leather",
	"Elemental Earth",
	"Elemental Water",
	"Elixir of Agility",
	"Elixir of Defense",
	"Elixir of Greater Defense",
	"Elixir of Lesser Agility",
	"Elixir of Minor Agility",
	"Elixir of Wisdom",
	"Enchanted Leather",
	"Essence of Air",
	"Essence of Earth",
	"Essence of Fire",
	"Essence of Water",
	"Fine Thread",
	"Felcloth",
	"Fine Leather Belt",
	"Fine Leather Gloves",
	"Fine Leather Tunic",
	"Fine Thread",
	"Flask of Big Mojo",
	"Flask of Mojo",
	"Frostsaber Leather",
	"Globe of Water",
	"Gray Dye",
	"Great Rage Potion",
	"Green Dragonscale",
	"Green Dye",
	"Green Whelp Scale",
	"Heart of Fire",
	"Heavy Hide",
	"Heavy Leather",
	"Heavy Scorpid Scale",
	"Heavy Silken Thread",
	"Iridescent Pearl",
	"Iron Buckle",
	"Ironfeather",
	"Jade",
	"Jet Black Feather",
	"Kingsblood",
	"Large Fang",
	"Light Hide",
	"Light Leather",
	"Living Essence",
	"Long Tail Feather",
	"Lucky Charm",
	"Mageweave Cloth",
	"Medium Hide",
	"Medium Leather",
	"Mooncloth",
	"Moss Agate",
	"Perfect Deviate Scale",
	"Raptor Hide",
	"Red Dragonscale",
	"Red Whelp Scale",
	"Refined Deeprock Salt",
	"Rugged Hide",
	"Rugged Leather",
	"Ruined Leather Scraps",
	"Rune Thread",
	"Runecloth",
	"Salt",
	"Scorpid Scale",
	"Shadow Oil",
	"Shadowcat Hide",
	"Silken Thread",
	"Slimy Murloc Scale",
	"Small Lustrous Pearl",
	"Spider's Silk",
	"Swiftness Potion",
	"Thick Hide",
	"Thick Leather",
	"Thick Murloc Scale",
	"Thick Spider's Silk",
	"Thick Wolfhide",
	"Thin Kodo Leather",
	"Turtle Scale",
	"Warbear Leather",
	"Wicked Claw",
	"Wildvine",
	"Worn Dragonscale",
};

SEA_REAGENT_MINING = {
	"Coal",
	"Copper Ore",
	"Dark Iron Ore",
	"Gold Ore",
	"Iron Ore",
	"Mithril Ore",
	"Silver Ore",
	"Thorium Ore",
	"Tin Ore",
	"Truesilver Ore"
};

SEA_REAGENT_FIRSTAID = {
	"Large Venom Sac",
	"Linen Cloth",
	"Mageweave Cloth",
	"Runecloth",
	"Silk Cloth",
	"Small Venom Sac",
	"Wool Cloth"
};

SEA_REAGENT_COOKING = {
	"Bear Meat",
	"Big Bear Meat",
	"Boar Intestines",
	"Boar Ribs",
	"Buzzard Wing",
	"Chunk of Boar Meat",
	"Clam Meat",
	"Coyote Meat",
	"Crag Boar Rib",
	"Crawler Claw",
	"Crawler Meat",
	"Crisp Spider Meat",
	"Crocolisk Meat",
	"Darkclaw Lobster",
	"Deviate Fish",
	"Dig Rat",
	"Giant Clam Meat",
	"Giant Egg",
	"Goldthorn",
	"Gooey Spider Leg",
	"Goretusk Liver",
	"Goretusk Snout",
	"Heavy Kodo Meat",
	"Holiday Spices",
	"Holiday Spirits",
	"Hot Spices",
	"Ice Cold Milk",
	"Kodo Meat",
	"Large Raw Mightfish",
	"Lean Wolf Flank",
	"Lion Meat",
	"Meaty Bat Wing",
	"Mild Spices",
	"Murloc Eye",
	"Murloc Fin",
	"Mystery Meat",
	"Raptor Egg",
	"Raptor Flesh",
	"Raw Brilliant Smallfish",
	"Raw Bristle Whisker Catfish",
	"Raw Glossy Mightfish",
	"Raw Loch Frenzy",
	"Raw Longjaw Mud Snapper",
	"Raw Mithril Head Trout",
	"Raw Nightfin Snapper",
	"Raw Rainbow Fin Albacore",
	"Raw Redgill",
	"Raw Rockscale Cod",
	"Raw Slitherskin Mackerel",
	"Raw Spotted Yellowtail",
	"Raw Summer Bass",
	"Raw Sunscale Salmon",
	"Raw Whitescale Salmon",
	"Raw Spinefin Halibut",
	"Red Wolf Meat",
	"Refreshing Spring Water",
	"Rhapsody Malt",
	"Scorpid Stinger",
	"Shiny Red Apple",
	"Skin of Dwarven Stout",
	"Small Egg",
	"Small Flame Sac",
	"Small Spider Leg",
	"Soft Frenzy Flesh",
	"Soothing Spices",
	"Spider Ichor",
	"Stag Meat",
	"Stormwind Seasoning Herbs",
	"Strider Meat",
	"Stringy Vulture Meat",
	"Stringy Wolf Meat",
	"Swiftthistle",
	"Tangy Clam Meat",
	"Tender Crab Meat",
	"Tender Crocolisk Meat",
	"Tender Wolf Meat",
	"Thunder Lizard Tail",
	"Tiger Meat",
	"Tough Condor Meat",
	"Turtle Meat",
	"White Spider Meat",
	"Winter Squid",
	"Zesty Clam Meat"
};

SEA_REAGENT_ROGUE = {
	  "Blue Hakkari Bijou",
	  "Gold Hakkari Bijou",
	  "Purple Hakkari Bijou",
	  "Flash Powder",
	  "Dust of Deterioration",
	  "Essence of Agony",
	  "Deathweed",
	  "Dust of Decay",
	  "Essence of Pain",
	  "Lethargy Root",
	  "Blinding Powder",
	  "Primal Hakkari Aegis",
	  "Primal Hakkari Armsplint",
	  "Primal Hakkari Girdle",
	  "Primal Hakkari Kossack"
	  };

SEA_REAGENT_POISON =  {
	"Crystal Vial",
	"Deathweed",
	"Dust of Decay",
	"Dust of Deterioration",
	"Empty Vial",
	"Fadeleaf",
	"Empty Vial",
	"Essence of Agony",
	"Essence of Pain",
	"Leaded Vial"
	};

SEA_POISON = {
	  "Instant Poison",
	  "Crippling Poison",
	  "Mind-numbing Poison",
	  "Wound Poison",
	  "Deadly Poison",
	  };
SEA_REAGENT_TAILORING = {
	"Azerothian Diamond",
	"Black Dye",
	"Black Pearl",
	"Bleach",
	"Blue Dye",
	"Bolt of Linen Cloth",
	"Bolt of Mageweave",
	"Bolt of Runecloth",
	"Bolt of Silk Cloth",
	"Bolt of Woolen Cloth",
	"Citrine",
	"Coarse Thread",
	"Demonic Rune",
	"Dream Dust",
	"Elemental Air",
	"Elemental Earth",
	"Elemental Fire",
	"Elemental Water",
	"Elixir of Wisdom",
	"Enchanted Leather",
	-- Tuatara removed as I don't think their is such a thing from my research
	--"Enchanted Thread",
	"Essence of Air",
	"Essence of Earth",
	"Essence of Fire",
	"Essence of Undeath",
	"Essence of Water",
	"Felcloth",
	"Fine Thread",
	"Fire Oil",
	"Frost Oil",
	"Ghost Dye",
	"Globe of Water",
	"Gold Bar",
	"Golden Pearl",
	"Gray Dye",
	"Green Dye",
	"Healing Potion",
	"Heart of Fire",
	"Heart of the Wild",
	"Heavy Leather",
	"Heavy Silken Thread",
	"Huge Emerald",
	"Iridescent Pearl",
	"Iron Buckle",
	"Ironweb Spider Silk",
	"Jade",
	"Large Brilliant Shard",
	"Lesser Moonstone",
	"Light Leather",
	"Linen Cloth",
	"Long Elegant Feather",
	"Mageweave Cloth",
	"Mana Potion",
	"Medium Leather",
	"Mooncloth",
	"Naga Scale",
	"Orange Dye",
	"Pink Dye",
	"Purple Dye",
	"Red Dye",
	"Righteous Orb",
	"Rugged Leather",
	"Rune Thread",
	"Runecloth",
	"Shadow Oil",
	"Shadow Protection Potion",
	"Shadow Silk",
	"Silk Cloth",
	"Silken Thread",
	"Small Lustrous Pearl",
	"Spider's Silk",
	"Star Ruby",
	"Thick Leather",
	"Thick Spider's Silk",
	"Truesilver Bar",
	"Wildvine",
	"Wool Cloth",
	"Yellow Dye",
};

SEA_REAGENT_PALADIN = {
	  "Symbol of Divinity"
	  };

SEA_REAGENT_MAGE = {
	"Light Feather",
	"Rune of Portals",
	"Rune of Teleportation"
	};

SEA_REAGENT_PRIEST = {
	"Light Feather"
	};

SEA_REAGENT_SHAMAN = {
	"Shiny Fish Scales",
	"Fish Oil",
	"Ankh"
	};

SEA_REAGENT_WARLOCK = {
	"Infernal Stone",
	"Demonic Figurine",
	"Soul Shard"
	};

SEA_REAGENT_DRUID = {
	"Maple Seed",
	"Stranglethorn Seed",
	"Ashwood Seed",
	"Hornbeam Seed",
	"Ironwood Seed",
	"Wild Berries",
	"Wild Thornroot"
	};

SEA_REAGENT_HUNTER = {
	};

SEA_REAGENT_WARRIOR = {
	};

SEA_SELF_CAST_LIST = {
		-- Druid
		["Abolish Poison"] = 1;
		["Cure Poison"] = 1;
		["Healing Touch"] = 1;
		["Mark of the Wild"] = 1;
		["Regrowth"] = 1;
		["Rejuvenation"] = 1;
		["Remove Curse"] = 1;
		["Thorns"] = 1;
		["Innervate"] = 1;
		-- Mage
		["Amplify Magic"] = 1;
		["Arcane Intellect"] = 1;
		["Dampen Magic"] = 1;
		["Remove Lesser Curse"] = 1;
		-- Paladin
		["Cleanse"] = 1;
		["Flash of Light"] = 1;
		["Holy Light"] = 1;
		["Purify"] = 1;
		["Lay on Hands"] = 1;
		["Blessing of Freedom"] = 1;
		["Blessing of Kings"] = 1;
		["Blessing of Light"] = 1;
		["Blessing of Might"] = 1;
		["Blessing of Protection"] = 1;
		["Blessing of Sacrifice"] = 1;
		["Blessing of Salvation"] = 1;
		["Blessing of Sanctuary"] = 1;
		["Blessing of Wisdom"] = 1;
		-- Priest
		["Abolish Disease"] = 1;
		["Cure Disease"] = 1;
		["Dispel Magic"] = 1;
		["Divine Spirit"] = 1;
		["Flash Heal"] = 1;
		["Greater Heal"] = 1;
		["Lesser Heal"] = 1;
		["Heal"] = 1;
		["Holy Word: Fortitude"] = 1; --Leaving this here incase they change the name back
		["Holy Word: Shield"] = 1; --Leaving this here incase they change the name back
		["Power Word: Fortitude"] = 1;
		["Power Word: Shield"] = 1;
		["Renew"] = 1;
		["Shadow Protection"] = 1;
		-- Shaman
		["Chain Heal"] = 1;
		["Cure Disease"] = 1;
		["Cure Poison"] = 1;
		["Healing Wave"] = 1;
		["Lesser Healing Wave"] = 1;
		["Water Breathing"] = 1;
		["Water Walking"] = 1;
		-- Warlock
		["Detect Greater Invisibility"] = 1;
		["Detect Invisibility"] = 1;
		["Detect Lesser Invisibility"] = 1;
		["Unending Breath"] = 1;
		-- First Aid
		["Linen Bandage"] = 1;
		["Heavy Linen Bandage"] = 1;
		["Wool Bandage"] = 1;
		["Heavy Wool Bandage"] = 1;
		["Silk Bandage"] = 1;
		["Heavy Silk Bandage"] = 1;
		["Mageweave Bandage"] = 1;
		["Heavy Mageweave Bandage"] = 1;
		["Runecloth Bandage"] = 1;
		["Heavy Runecloth Bandage"] = 1;
		["Anti-Venom"] = 1;
		["Strong Anti-Venom"] = 1
	};
